:PROPERTIES:
:ID:       ddc21510-6693-4c1e-9070-db0dd2a8160b
:header-args+: :wrap
:END:
#+title: Rust
* 概要
RustはC言語、C++の置換を目指した[[id:868ac56a-2d42-48d7-ab7f-7047c85a8f39][Programming Language]]。

- 性能
- メモリ安全性
- 安全な並行性

を特徴とする。

[[id:4270d99a-d2b5-429e-b33c-c2e097b20730][Zig]]と方向性が同じ。
* Memo
** 変更を検知して自動ビルド
変更したら自動でcargo runしてほしいときがある。

#+caption: cargo-watchを使う
#+begin_src shell
cargo install cargo-watch
cargo watch -x run
#+end_src
** print
#+begin_src rust
  println!("hello world!");
  println!("{} days", 31);
  println!("{0}, this is {1}, {1}, this is {0}", "Alice", "Bob");
  println!("{} of {:b} people know binary, the other half doesn't", 1, 2);
  println!("{number:>0width$}", number=1, width=6);
  println!("{subject} {verb} {object}", object="the lazy dog", subject="the quick brown fox", verb="jumps over");
#+end_src

#+RESULTS:
#+begin_results
hello world!
31 days
Alice, this is Bob, Bob, this is Alice
1 of 10 people know binary, the other half doesn't
000001
the quick brown fox jumps over the lazy dog
#+end_results

引数チェックもしてくれる。
#+begin_src rust
  println!("My name is {0}, {1} {0}", "Bond");
#+end_src

#+RESULTS:
#+begin_results
error: invalid reference to positional argument 1 (there is 1 argument)
 --> /tmp/babel-wnDbpn/rust-W98kSP:2:27
  |
2 | println!("My name is {0}, {1} {0}", "Bond");
  |                           ^^^
  |
  = note: positional arguments are zero-based

error: aborting due to previous error
#+end_results

マーカーの変更。
#+begin_src rust
  println!("This struct `{}` won't print...", Structure(3));
#+end_src

#+RESULTS:
#+begin_results
error[E0425]: cannot find function, tuple struct or tuple variant `Structure` in this scope
 --> /tmp/babel-wnDbpn/rust-If17CF:2:45
  |
2 | println!("This struct `{}` won't print...", Structure(3));
  |                                             ^^^^^^^^^ not found in this scope

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
#+end_results

#+begin_src rust
  #[derive(Debug)]
  struct Structure(i32);
  println!("This struct `{:?}` won't print...", Structure(3));
#+end_src

#+RESULTS:
#+begin_results
This struct `Structure(3)` won't print...
#+end_results

* パッケージ
** [[id:1ad8c3d5-97ba-4905-be11-e6f2626127ad][Emacs]]をRustで書き直すプロジェクト
EmacsのC言語で書かれた部分をRustに書き直すリポジトリがある。
[[https://github.com/remacs/remacs][remacs/remacs: Rust Emacs]]
** 超高速なripgrep
高速検索するripgrepは、ほかのどのgrepツールより早いらしい。

- repository :: [[https://github.com/BurntSushi/ripgrep][BurntSushi/ripgrep]]
** 新世代の[[id:585d3b5e-989d-4363-bcc3-894402fcfcf9][Shell]]nushell
[[id:fa497359-ae3f-494a-b24a-9822eefe67ad][System Crafters]]の動画[[https://www.youtube.com/watch?v=IHeKUeO7bpo][Integrating Nushell with Emacs]]のコラボ回で出たパッケージ。
リッチな出力形式、便利コマンドがすごい。
- repository :: [[https://github.com/nushell/nushell][nushell/nushell: A new type of shell]]
* Tasks
** TODO [[https://doc.rust-jp.rs/rust-by-example-ja/][Introduction - Rust By Example 日本語版]]
** TODO [[https://doc.rust-jp.rs/book-ja/title-page.html][The Rust Programming Language 日本語版]]
** WIP [[https://bfnightly.bracketproductions.com/][Introduction - Roguelike Tutorial - In Rust]]
:LOGBOOK:
CLOCK: [2022-03-22 Tue 23:37]--[2022-03-23 Wed 00:02] =>  0:25
CLOCK: [2022-03-22 Tue 22:27]--[2022-03-22 Tue 22:52] =>  0:25
CLOCK: [2022-03-21 Mon 23:31]--[2022-03-21 Mon 23:57] =>  0:26
CLOCK: [2022-03-21 Mon 22:34]--[2022-03-21 Mon 22:59] =>  0:25
CLOCK: [2022-03-21 Mon 21:18]--[2022-03-21 Mon 21:43] =>  0:25
CLOCK: [2022-03-21 Mon 20:39]--[2022-03-21 Mon 21:04] =>  0:25
CLOCK: [2022-03-21 Mon 20:01]--[2022-03-21 Mon 20:26] =>  0:25
CLOCK: [2022-03-21 Mon 18:59]--[2022-03-21 Mon 19:24] =>  0:25
CLOCK: [2022-03-21 Mon 17:17]--[2022-03-21 Mon 17:42] =>  0:25
CLOCK: [2022-03-21 Mon 16:26]--[2022-03-21 Mon 16:51] =>  0:25
CLOCK: [2022-03-21 Mon 15:48]--[2022-03-21 Mon 16:13] =>  0:25
CLOCK: [2022-03-21 Mon 14:58]--[2022-03-21 Mon 15:23] =>  0:25
CLOCK: [2022-03-21 Mon 14:27]--[2022-03-21 Mon 14:52] =>  0:25
CLOCK: [2022-03-21 Mon 13:53]--[2022-03-21 Mon 14:18] =>  0:25
CLOCK: [2022-03-21 Mon 13:11]--[2022-03-21 Mon 13:36] =>  0:25
CLOCK: [2022-03-21 Mon 00:10]--[2022-03-21 Mon 00:35] =>  0:25
CLOCK: [2022-03-20 Sun 22:33]--[2022-03-20 Sun 22:58] =>  0:25
CLOCK: [2022-03-20 Sun 21:28]--[2022-03-20 Sun 21:53] =>  0:25
CLOCK: [2022-03-20 Sun 20:55]--[2022-03-20 Sun 21:20] =>  0:25
CLOCK: [2022-03-20 Sun 20:20]--[2022-03-20 Sun 20:45] =>  0:25
CLOCK: [2022-03-20 Sun 18:30]--[2022-03-20 Sun 18:55] =>  0:25
CLOCK: [2022-03-20 Sun 17:56]--[2022-03-20 Sun 18:21] =>  0:25
CLOCK: [2022-03-20 Sun 15:53]--[2022-03-20 Sun 16:18] =>  0:25
CLOCK: [2022-03-20 Sun 15:20]--[2022-03-20 Sun 15:45] =>  0:25
CLOCK: [2022-03-20 Sun 14:49]--[2022-03-20 Sun 15:14] =>  0:25
CLOCK: [2022-03-20 Sun 10:34]--[2022-03-20 Sun 10:59] =>  0:25
CLOCK: [2022-03-20 Sun 00:28]--[2022-03-20 Sun 00:54] =>  0:26
CLOCK: [2022-03-19 Sat 22:17]--[2022-03-19 Sat 22:42] =>  0:25
CLOCK: [2022-03-19 Sat 21:45]--[2022-03-19 Sat 22:10] =>  0:25
CLOCK: [2022-03-19 Sat 19:56]--[2022-03-19 Sat 20:21] =>  0:25
CLOCK: [2022-03-19 Sat 18:40]--[2022-03-19 Sat 19:05] =>  0:25
CLOCK: [2022-03-19 Sat 17:12]--[2022-03-19 Sat 17:37] =>  0:25
CLOCK: [2022-03-19 Sat 16:33]--[2022-03-19 Sat 16:58] =>  0:25
CLOCK: [2022-03-19 Sat 15:56]--[2022-03-19 Sat 16:21] =>  0:25
CLOCK: [2022-03-19 Sat 15:13]--[2022-03-19 Sat 15:38] =>  0:25
:END:

[[id:50ac66da-89f2-42dc-a746-d20b041d06ae][roguelike]]を作る長大なチュートリアル。
* Reference
- [[https://ja.wikipedia.org/wiki/Rust_(%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0%E8%A8%80%E8%AA%9E)][Rust (プログラミング言語) - Wikipedia]]
* Archives
