:PROPERTIES:
:ID:       b78984cc-0e02-413d-ae20-2cb2b046038f
:END:
#+title: career
* 概要
プログラマーのキャリアに関することをまとめる。

キャリアのことについて考えるのはあまり面白くない。が、同じ努力で結果が大きく変わる要素のために無視してもいられない。たとえば[[id:868ac56a-2d42-48d7-ab7f-7047c85a8f39][Programming Language]]の選択で未来は変わる。業界や領域が死ねば、精通していてもアドバンテージを失う。たまには考えないと。

よく考える疑問: 働くとしたら大企業がいいのか、[[id:9c5f9bfa-dc41-40b6-94cd-0791ab9d40c1][startup]]がいいのか。あるいはフリーランス、会社を立ち上げるのがいいのか。
望むものや状況によって最善の手は変わりそうなので、よく周りと自分を理解するために書く。
* Memo
** やりたいことをやりきる
たとえば前職のレガシーなシステムに不満がありました、という理由は採用側から見るとクソに見える。じゃあなんで改修しないの、しようとしたの、と。結局のところ、すごい人は環境ごと変えるので、説得感のある理由にならない。環境を変えられない人は価値がない。そしてモダンな開発にも対応してないんじゃ話しにならない。
やることは2つ。
- 何かしらのレガシーの根本的な脱却をすること。モダン化すること。バージョンを上げる、ライブラリ置き換えや削除、データベースリファクタリング。
- モダンな技術スタック開発に精通すること

どうせ離れることを考えているなら，何も失うものはないので技術的挑戦を自分から上を説得してやるのがよさそう。何も気にする必要がなくやりたい放題。それによって結局のところ会社は長期的なメリットを得る。個人も実績を積むことができるので、もはや常時離れるつもりで仕事をやったほうがいいか。少なくとも居座るつもりで挑戦しないよりは確実に良い。
** やることを選ぶ
スキル的な面で、やりたい仕事の種類を優先づけしていくことが重要に見える。
与えられた仕事をやるだと、ジャンルがバラけて技術が蓄積しない。
割り振るのにもコストがかかる。

自分から取っていくこと、言い方を変えると選べる範囲で仕事を選ぶことが重要そうだ。選ぶというとアレな感じがするが、我慢しても見返りは来ない。やりたいことを明確に伝えないと。
** 仕事の探し方
まず自分の要件を明確にする。それから探す。カジュアル面談して掘り下げ。応募する。

- 業種
  - toB, toC
- 使用技術
  - プログラミング言語
- 理想のキャリア
- 会社の規模
- 幅広くか、掘り下げか
- リモートワーク
- 給料
- 自分がよいと思えるサービスがいい
  とくに開発やプログラマーとして使える、使っているものだとよい。極端な例は[[id:6b889822-21f1-4a3e-9755-e3ca52fa0bc4][GitHub]]、CircleCIとか。
  自分がユーザとしてイメージできないものは作れない。
- 利用ユーザ数
  多いほど要件がシビアで、知見や良い知見がある可能性は高い。例: 1000万ユーザのサービスで遅いクエリを作ると完全に止まるので、ノウハウが蓄積する。1万ユーザでは致命的に遅いクエリでないかぎり問題にならない。
- ユーザとの距離感
** 仕事内容を数字で示す
アピールしよう、ってなったときでは思い出せないので重要な手柄については日頃メモしておく。
リンクだけでも思い出しやすい。

期間やラベルを指定して検索した結果の(クエリがくっついた)URLを貼ると、数字として示しやすい。

- PR数
- Review数
- 解決Issue数(必ずやるときはAssignしておくことが重要)
- OSS活動へのリンク
** 聞くこと
- 開発人員の数。チームの数、チームの人数
- チームは何の単位で分割されてるのか
- チームごとの違いは何か
- どのチームに採用される可能性があるのか
- 期待されてるポジション。技術レベル/スタック
- カバレッジ率はどれくらいか
- 技術負債はどうしているか
- OSSにコントリビュートしてる人はいるか
- 会社やチームの課題は何か
- フルリモートワークは可能か
- ドキュメント管理はどうやっているか
- 技術選定の理由
- GitHubやりとり見せて(review, PRコメントの感じ)
- プロジェクト管理見せて(タスクの切り方、進めかた)
- プロダクト見せて
- 専門領域の知識を必要とするか(例: 法律)
** 効果的なコミュニケーションを行えているか
リモートワークでは[[id:d68263db-a8c5-478e-b456-8a753eb34416][communication]]についての共通理解が、より重要になる。
リアルの仕事環境と異なる点。
高コンテキストでのリモートワークはやりにくい。
仕事の行いやすさに直結するだろう。

だから、集団としてどのような取り組みを行っているか、そこを整備している人間はいるか確認するとよいだろう。
** デフォルトの条件
- リモートワークOK
- フルフレックス
- 人が多くない(仕事全体に自分の占める割合が多い方がいいから。結果が見えるのがいい) かつ 技術力がある
  規模というより、文化による違いの可能性が高いので再考。
* Tasks
* Reference
** [[https://openviewpartners.com/blog/the-product-led-growth-market-map/#.YVB533UzbyL][The Product Led Growth Market Map - OpenView]]
プロダクトを成長させる市場。こういう企業を狙うとよさそう。
** [[https://www.docswell.com/s/shu223/YZ98P5-enjoy?utm_source=twitter&utm_medium=social&utm_campaign=singlepage#p1][エンジニアという仕事を楽しみ続けるためには | ドクセル]]
技術の選択、プログラマとしてのブランディング、キャリア論。
** [[https://github.com/kdn251/interviews][kdn251/interviews: Everything you need to know to get the job.]]
interview対策。
** TODO [[http://media.steampowered.com/apps/valve/Valve_NewEmployeeHandbook.pdf][VALVE handbook for new employees]]
VALVEの新入社員ガイド。
** [[https://tkybpp.hatenablog.com/entry/2018/05/16/073000][【翻訳】「シリコンバレーから生まれた最高の文書」と絶賛されたNetflixのカルチャーガイド全文 - BppLOG]]
Netflixのカルチャーガイドの翻訳。
** [[https://jobs.netflix.com/culture][Netflix Jobs]]
Netflixのカルチャーガイド。日本語訳もある。
** [[https://www.slideshare.net/reed2001/culture-1798664][Netflix Culture]]
スライドバージョン。
** [[https://dropbox.github.io/dbx-career-framework/overview.html][Overview - Dropbox Engineering Career Framework]]
Dropboxのキャリアの文書化。
* Archives
