:PROPERTIES:
:ID:       e3b48a23-21bc-4cdf-8395-052fab9fecb5
:END:
#+title: Computer Science
* 概要
Computer Scienceは学問としての領域。
* Memo
* Tasks
** TODO [[https://zenn.dev/yukiyada/articles/23c9fde740744d][Nand2tetrisをGoで実装する ~ コンパイラ(コンパイラ・フロントエンド)編(10,11章) ~]]
やる。
** TODO [[https://www.oreilly.co.jp/books/9784873116976/][O'Reilly Japan - アンダースタンディング コンピュテーション]]     :Read:
:LOGBOOK:
CLOCK: [2022-09-25 Sun 08:41]--[2022-09-25 Sun 09:06] =>  0:25
:END:
計算の仕組みを理解する本。
** TODO [[https://drive.google.com/file/d/1Hdh-K3gyttzf-74j3B9EfOl_dScswHEF/view][ods-cpp.pdf - Google Drive]]
:LOGBOOK:
CLOCK: [2022-12-10 Sat 16:15]--[2022-12-10 Sat 16:40] =>  0:25
CLOCK: [2022-12-10 Sat 09:56]--[2022-12-10 Sat 10:21] =>  0:25
:END:
無料のコンピュータサイエンスの教科書。
** WIP [[https://www.oreilly.co.jp/books/9784873117126/][O'Reilly Japan - コンピュータシステムの理論と実装]]               :Read:
:PROPERTIES:
:Effort:   50:00
:END:
:LOGBOOK:
CLOCK: [2023-04-06 Thu 23:32]--[2023-04-06 Thu 23:57] =>  0:25
CLOCK: [2023-04-06 Thu 23:03]--[2023-04-06 Thu 23:28] =>  0:25
CLOCK: [2023-04-06 Thu 22:27]--[2023-04-06 Thu 22:52] =>  0:25
CLOCK: [2023-04-06 Thu 22:02]--[2023-04-06 Thu 22:27] =>  0:25
CLOCK: [2023-04-06 Thu 21:10]--[2023-04-06 Thu 21:35] =>  0:25
CLOCK: [2023-04-06 Thu 00:37]--[2023-04-06 Thu 01:02] =>  0:25
CLOCK: [2023-04-04 Tue 20:45]--[2023-04-04 Tue 21:10] =>  0:25
CLOCK: [2023-04-04 Tue 20:01]--[2023-04-04 Tue 20:26] =>  0:25
CLOCK: [2023-04-04 Tue 19:35]--[2023-04-04 Tue 20:00] =>  0:25
CLOCK: [2023-04-04 Tue 00:35]--[2023-04-04 Tue 01:00] =>  0:25
CLOCK: [2023-04-03 Mon 00:45]--[2023-04-03 Mon 01:10] =>  0:25
CLOCK: [2023-04-02 Sun 22:34]--[2023-04-02 Sun 22:59] =>  0:25
CLOCK: [2023-04-02 Sun 22:08]--[2023-04-02 Sun 22:33] =>  0:25
CLOCK: [2023-04-02 Sun 19:56]--[2023-04-02 Sun 20:01] =>  0:05
CLOCK: [2023-03-28 Tue 22:00]--[2023-03-28 Tue 22:25] =>  0:25
CLOCK: [2023-03-28 Tue 21:26]--[2023-03-28 Tue 21:51] =>  0:25
CLOCK: [2023-03-18 Sat 15:54]--[2023-03-18 Sat 16:19] =>  0:25
CLOCK: [2023-03-18 Sat 15:27]--[2023-03-18 Sat 15:52] =>  0:25
:END:
実装して理解する本。

- 97, 128

メモ。

- @value はAレジスタにvalueを格納することを示す
  - 例. @17 はAレジスタに17を格納する
- A命令 :: 操作を行いたいアドレスを指定する命令
- C命令 :: 計算命令
- デバイスはメモリマップを通じて、ほかのメモリと全く同じようにCPUから扱うことができる
  - キーボードを押している間、メモリのどこかの値が変わっている
* Words
- インタフェース :: そのデータ構造が何をするか表現する。データ構造がサポートしている操作一式と、セマンティクスを定義する
- 実装 :: そのデータ構造をどのようにやるかを表現する
- セマンティクス :: 操作の意味
* Reference
** [[https://w.atwiki.jp/gbspec/pages/35.html][CPU/命令セット - GB Spec - atwiki（アットウィキ）]]
命令セットの一覧。
** [[https://www.oreilly.co.jp/books/9784873118819/][O'Reilly Japan - Python計算機科学新教本]]
計算機科学を動くコードで学ぶ本。
** [[https://www.memorymanagement.org/][Home — Memory Management Reference 4.0 documentation]]
メモリ管理のリファレンス。
** [[https://cs50.jp/][CS50 for Japanese: コンピュータサイエンスの入門 – 当ウェブサイトは、Creative Commons ライセンスに基づいて管理されています。]]
ハーバード大学のコンピュータサイエンス講座の日本語訳。
** [[https://github.com/Developer-Y/cs-video-courses][Developer-Y/cs-video-courses: List of Computer Science courses with video lectures.]]
コンピュータ・サイエンスの動画集。
* Archives
