:PROPERTIES:
:ID:       02b46258-7650-4a02-9f0e-c422555b29d0
:END:
#+title: Archive
* 概要
単発の発表などを置く。
* Memo
** 知っておきたかったこと
すごく好きな文章なので、保存用にコピーしておく。

#+begin_quote
知っておきたかったこと
--- What You'll Wish You'd Known
Paul Graham, January 2005
Copyright 2005 by Paul Graham.
これは、Paul Graham：What You'll Wish You'd Known を、原著者の許可を得て翻訳・公開するものです。

<版権表示>
本和訳テキストの複製、変更、再配布は、この版権表示を残す限り、自由に行って結構です。
(「この版権表示」には上の文も含まれます。すなわち、再配布を禁止してはいけません)。
Copyright 2005 by Paul Graham
原文: http://www.paulgraham.com/hs.html
日本語訳：Shiro Kawai (shiro ＠ acm.org)
<版権表示終り>

Paul Graham氏のエッセイをまとめた『ハッカーと画家』の 邦訳版が出版されました。
出版社の案内ページ Amazon.co.jp サポートページ

2005/01/22 翻訳公開
2005/01/24 水落毅様より誤記の訂正を反映
このエッセイは、ある高校の講演依頼を受けて準備したものである。 その高校のお偉いさん方が反対して、結局私の講演はキャンセルされたのだが。

こんど高校で講演することになったと言ったら、ぼくの友達はみんな 興味を持って尋ねてきた。高校生に向かってどんな話をするんだい。 だからぼくは逆に聞き返したんだ。君が高校生の時に、誰かがこのことを 教えていてくれたらなぁ、と思うことってあるかい。 そう聞くと、みんな自分のことを語りはじめたんだけれど、 だいたい誰も同じようなことを思っていたんだ。 そこで今日は、ぼくらがみんな、 誰かに教えてもらいたかったなあと思っていることを話そうと思う。

まず、高校にいるうちは知らなくてもいいことから始めよう。 人生で何を為すかってことだ。大人はいつも、君は人生において 何を成し遂げたいかって聞くものだから、答えを考えておかなくちゃ いけないなんて思っているんじゃないかな。 実は大人がこの質問をするのは、単に会話を始めるためなんだ。 君がどんな人間かを知りたくて、そしてこの質問をすればとにかく 君は何かを話し出すだろう。潮溜りのヤドカリを突っついて どんな反応をするか見てみるのと同じさ。

ぼくが高校生に戻ってこの質問を受けたとしたら、 まず何が可能かを学ぶことだと答えるだろう。 人生を賭ける仕事を選ぶのに急ぐ必要なんてない。 必要なのは、自分は何が好きなのかを発見することだ。 上手くできるようになりたいなら、そのことが好きじゃなくちゃだめだからね。

何が好きかを決めるのなんて一番簡単なことだと思うかもしれない。 でもやってみると、それはとても難しい。理由のひとつは、 仕事で実際にどういうことをしているかっていうはっきりしたイメージを 持つことが、多くの仕事では難しいからだ。例えば医者という仕事の実際は、 テレビで描かれるようなものじゃない。もっとも医者の場合は、病院で ボランティアをすれば本物の医者を見る機会が得られるけれどね [1]。

それどころか、今決して学ぶことが出来ない仕事っていうのもある。 今はまだ誰もやっていないような仕事だ。ぼくがこれまでの10年間でやってきた 仕事のほとんどは、ぼくが高校生の時には存在していなかった。 世界はどんどん変化しているし、変化のスピードも速くなってる。 こんな世界では、決まった計画を持つことはあまりうまくない。

それでも毎年5月になると、全国津々浦々の卒業式で決まりきった演説が 聞かれることになる。テーマはこうだ。「夢をあきらめるな。」 ぼくはその真意を知っているけれど、この表現は良いものじゃない。 だって、早いうちに計画を立ててそれに縛られることを暗示しているからね。 コンピュータの世界では、これに名前までついている。 「早すぎる最適化」というんだ。別の言葉で言い替えると「大失敗」ということだ。 演説ではもっと単純にこう言うべきだろうね。「あきらめるな。」

この言葉の真意は、士気を失うなってことだ。 他の人に出来ることを自分は出来ないと思っちゃだめだ。 それに、自分の可能性を過小評価してもいけない。 すごいことを成し遂げた人を見て、自分とは人種が違うと思うかもしれない。 しかも伝記ではそういう幻想はますます誇張される。伝記を書く人っていうのは 対象となる人物にどうしても畏敬の念を抱くものだし、物語の結末がわかっているから そこに至るまでの人生のできごとをまるで運命に導かれたように、 内なる天才が徐々に現れて来るように描きたくなるんだ。 実際のところ、もし16歳のシェークスピアやアインシュタインが君と同級生 だったとしたら、たぶん彼らは才能を現しているだろうけれど、それ以外は 君の他の友達とさほど変わらないはずだとぼくは思う。

こう考えるのは、おっかないことだ。彼らがぼくらと同じなんだとしたら、 彼らはすごいことを成し遂げるためにものすごい努力をしたってことになる。 そう思うのはこわいから、ぼくらは天才というものを信じたがるんだ。 ぼくらが怠けている言い訳ができるからね。 もし彼らが、魔法のシェークスピア属性やアインシュタイン属性のせいで 素晴らしいことを成し遂げたんだとすれば、ぼくらが同じくらい すごいことをできなくてもぼくらのせいじゃないことになる。

天才なんてない、って言ってるわけじゃないよ。 でも、二つの理論を選ぶときに、一方は怠惰であることを正当化するものだと したら、たぶんもう一方の理論が正しい。

ここまでで、卒業演説の「夢をあきらめるな」から、 「他の誰かに出来たなら、きみにも出来る」が彫り出せた。 でもこれはもっと彫り進めることができる。 生まれついての能力の差というものは多少はある。 過大評価されがちだけど、無くは無い。 例えば背が120cmしかない人がいつかNBAでプレーしたいんだと言った時に、 本当に頑張れば何でも出来るよというのは空々しく聞こえるだろう。 [2]

だから、卒業演説はこんなふうになるだろう。 「きみと同じ能力を持つ誰かができることなら、きみにもできる。 そして自分の能力を過小評価しちゃいけない。」 でも、よくあることだけれど、真実に近付こうとするほど 多くの言葉を費さなくちゃならなくなる。 かっこよく決まっている、でも正しくないスローガンを、 泥をかき混ぜるみたいにいじってみたわけだが、 これじゃあまり良いスピーチにはならなさそうだ。 それに、これじゃ何をすべきかってこともよくわからない。 「きみと同じ能力」って? 自分の能力って何だろう?

風上
この問題の解法は、反対側からやってみることだ。 ゴールを最初に決めてそこから逆算するんじゃなく、 より良さそうな状況に向けて少しづつ前に進んでゆくんだ。 成功した人の多くは実際にはそうやって成功したんだ。

卒業演説方式では、きみはまず20年後にどうなりたいかを決めて、 次にそこに至るには今何をすればいい、と考える。 ぼくが提案するのは逆に、将来のことは一切決めないでおいて、 今ある選択肢を見て、良さそうな選択肢がより増えるものを選ぶってことだ。

時間を無駄にしてない限り、実際に何をするかってことはあまり問題じゃない。 面白いと思えて、選択肢が増えるものなら何でもいい。増えた選択肢のどれを 選ぶかなんて後で考えればいいんだ。

たとえば、君が大学の1年生で、数学と経済学のどっちを専攻しようかと 迷っているとする。この場合はね、数学の方が選択肢がひろがるんだ。 数学からはほとんどどの分野へも進むことができる。数学を専攻していたら、 経済学の大学院へ進むのは簡単だろう。でも経済学を専攻して、 数学の大学院へ進むのは難しい。

グライダーを考えてみるといい。グライダーはエンジンを持っていないから、 風上に向かって進もうとすると高度を大きく失うことになる。 着陸に適した地点よりずっと風下に行っちゃったら、打てる手はひどく 限られるものになるだろう。風上にいるべきなんだ。 だからぼくは「夢をあきらめるな」のかわりにこう言おう。「風上をめざせ」。

でも、どうすればいい? 数学が経済学の風上だったとして、 高校生はそんなことを知っていなくちゃならないんだろうか。

もちろん知らないだろう。だから、風上を自分で見つけ出さなくちゃならない。 風上を知る方法のヒントをいくつかあげよう。 賢い人々と、難しい問題を探すことだ。賢い人々は自分達で固まりがちだ。 そういう集団を見つけたら、たぶんそれに参加する価値はある。 但し、そういう集団を見つけることは簡単じゃない。 ごまかしがたくさんあるからだ。

大学生になったばかりのときには、大学のどの学部もだいたい似たように見える。 教授たちはみんな手の届かない知性の壇上にいて、凡人には理解不能な論文を 発表している。でもね、確かに難しい考えがいっぱい詰まっているせいで 理解できないような論文もあるけれど、何か重要なことを言っているように 見せかけるためにわざとわかりにくく書いてある論文だっていっぱいあるんだ。 こんなふうに言うと中傷に聞こえるかもしれないけれど、 これは実験的に確かめられている。有名な『ソーシャル・テクスト』事件だ。 ある物理学者が、人文科学者の論文には、 知的に見えるだけの用語を連ねたでたらめにすぎないものがしばしばあると考えた。 そこで彼はわざと知的に見えるだけの用語を連ねたでたらめ論文を書き、 人文科学の学術誌に投稿したら、その論文が採択されたんだ。

一番良い防御は、常に難しい問題に取り組むようにすることだ。 小説を書くことは難しい。小説を読むことは簡単だ。 難しいということは、不安を感じるということだ。 自分が作っているものが上手くいかないかもしれないとか、 自分が勉強していることが理解出来ないんじゃないかという不安を 感じていないなら、それは難しくない問題だ。 ドキドキするスリルがなくちゃ。

ちょっと厳しすぎる見方じゃないかって思うかい。 不安を感じなくちゃダメだなんて。 そうだね。でもこれはそんなに悪いことじゃない。 不安を乗り越えれば歓喜が待っている。 金メダルを勝ち取った人の顔は幸福に満ちているだろう。 どうしてそんなに幸福なのかわかるかい。安心したからさ。

幸福になる方法がこれしかないと言っているんじゃないよ。 ただ、不安の中にも、そんなに悪くないものがあるって言いたいんだ。

野望
「風上をめざせ」というのは、現実には「難しい問題に取り組め」という ことだった。そして、君は今日からそれを始めることができる。 ぼくも、このことに高校にいる時に気付いていたらなと思うよ。

たいていの人は、自分がやってることを上手くできるようになりたいと 思う。いわゆる現実社会では、この要求はとても強い力なんだ。 しかし高校では、上手くできたからっていいことはあまりない。 やらされていることが偽物だからだ。 ぼくが高校生だった時は、高校生であることが自分の仕事なんだって思ってた。 だから、上手くやれるようになる必要があることっていうのは、 学校でいい成績をあげることだと思ってた。

その時のぼくに、高校生と大人の違いは何かと聞いたなら、 たぶん大人は生活のために稼がなくちゃならない、と答えていただろう。 間違いだ。ほんとうの違いは、大人は自分自身に責任を持つということだ。 生活費を稼ぐのはそのほんの小さな一部にすぎない。 もっと大事なのは、自分自身に対して知的な責任を取ることだ。

もしもう一回高校をやりなおさせられるとしたら、ぼくは学校を 昼間の仕事のようにあしらうだろう。学校でなまけるということじゃないよ。 昼間の仕事のようにやる、っていうのは、それを下手にやるってことじゃない。 その意味は、それによって自分を規定されないようにするってことだ。 たとえば昼間の仕事としてウェイターをやっているミュージシャンは、 自分をウェイターだとは思わないだろう [3]。 同じように、ぼくも、自分を高校生だとは思わないだろうね。 そして昼間の仕事が済めば、本当の仕事を始めるだろう。

高校時代を思い出して一番後悔することは何かって尋ねると、 たいていみんな同じ答えを返す。時間を大いに無駄にしたってね。 君が、今こんなことをしてて将来後悔することになるだろうなと 思っているなら、きっと後悔することになるよ[4]。

これは仕方ないと言う人もいる。高校生はまだ何もきちんと出来ないからってね。 ぼくはそうは思わない。高校生が退屈しているというのがその証拠だ。 8歳の子供は退屈しない。8歳の時には「ぶらつく」かわりに「遊んで」いたはずだ。 やってることは同じなのにね。そして8歳の時、ぼくは退屈することがほとんど 無かった。裏庭と数人の友達がいれば、一日中遊んでいることができた。

今振り返ってみれば、中学高校でこれがつまらなくなった理由は、 ぼくが他の何かをする準備が出来たからだった。 子供であることに飽きてきたんだ。

友達とぶらついちゃだめだなんて言ってないよ。 誰ともつき合わなかったら、仕事しかしないむっつりした小さなロボットに なるしかない。友達と出かけるのは、チョコレートケーキみたいなもんだ。 時々食べるからおいしい。毎食チョコレートケーキを食べていたら、 たとえどんなに好きだとしても、3食目には吐き気がしてくるだろう。 高校で感じる不安感はまさにそれ、精神的な吐き気なんだ [5]。

良い成績を取る以上に何かしなくちゃならないと聞いたら、 『課外活動』のことだと思うかもしれない。 でも君はもう、ほとんどの『課外活動』がどんなにばかげたものかを知っているよね。 チャリティの寄付集めは称賛されるべきことかもしれないが、 それは難しいことじゃない。 何かを成し遂げるってことじゃないからだ。 何かを成し遂げるっていうのは、たとえば上手く文章を書けるようになるとか、 コンピュータをプログラムできるようになるとか、 工業化以前の社会の生活が実際どんなものだったかを知るとか、 モデルを使って人間の顔を書くことを学ぶとか、そういうことだ。 この手の活動は、大学入試願書に一行で書けるようなものにはなかなかならない。

堕落
大学に入ることを人生の目標にするのは危険なことだ。 大学に入るために自分の能力を見せなくちゃならない相手っていうのは、 概して鋭いセンスを欠いている。多くの大学では、 きみの合否を決めるのは教授じゃなくて入学管理者[訳註1]で、 彼らは全然賢くない。知的社会の中では彼らは下士官だ。 きみがどれだけ賢いかなんて彼らに分かりはしない。 私立の進学校が存在することが、その証明になっている。

入試に受かる見込みが上がらないのに多額の金を学校に払う親はほとんどいない。 私立の進学校は、入試に受かるための学校であることを明示している。 でも立ち止まって考えてみたまえ。同じくらいの子供が、 ただ地域の公立高校だけに行くより私立の進学校に行った方が入試に受かりやすくなるってことは、 私立の進学校は入試のプロセスをハックできるってことだ [6]。

君達の多くは、今人生でやるべきことは大学入試に受かるように なることだと思っているだろうね。でもそれは、自分の人生を空っぽの プロセス、それを堕落させるためだけで一つの業界が存在しているほどの プロセスに押し込めていることになる。 シニカルになるのも無理ないよ。 君が感じている不快感は、リアリティTVのプロデューサーや タバコ会社の重役が感じているものと同種のものだ。 君の場合は給料をもらっているわけでもないのにね。

じゃあどうしようかね。 ひとつ、やっちゃいけないのは反抗だ。 ぼくは反抗した。それは間違いだった。 ぼくは、自分達の置かれた状況をはっきり認識していなかったけど、 なにか臭いものを感じていた。だから全部投げ出したんだ。 世界がクソなら、どうなろうと知ったことか、ってね。

教師の一人が試験対策のアンチョコを使っているのを見つけた時に、 ぼくはこれでおあいこだと思った。そんな授業でいい点数をもらって どんな意味があるっていうんだ。

今、振り返ってみれば、ぼくは馬鹿だったと思うよ。 これはまるで、サッカーで相手にファウルされて、おまえ反則しただろ、 ルール違反だ！と怒ってグランドから立ち去るようなものだ。 反則はどうしたって起きる。そうなった時に、冷静さを失わないことが重要だ。 ただゲームを続けるんだ。

きみをこんな状況に押し込めたのは、社会がきみに反則したからだ。 そう、きみが思っているように、授業で習うほとんどのことはクソだ。 そう、きみが思っているように、大学入試は茶番だ。 でも、反則の多くと同じように、悪意があってそうなったわけじゃない [7]。 だから、ただゲームを続けるんだ。

反抗は服従と同じくらいばかげたことだ。 どちらにしてもきみは他人に言われたことに縛られている。 一番良いのは、直角の方向に足を踏み出すことだ。 言われたからただやる、でもなく、言われたからやらない、でもない。 かわりに、学校を昼間の仕事にするんだ。昼間の仕事だと考えれば 学校なんて楽勝だよ。3時には終わるんだし、なんなら自分のやりたいことを 内職しててもいい。

好奇心
じゃあ、本当の仕事は何になるんだろう。 きみがモーツァルトでない限り、やるべきことはまずそれを探し出すことだ。 やりがいのあることって何だろう。すごい発想をする人達はどこにいるだろう。 そして一番重要なこと：自分は何に興味があるだろう。 「適性」という単語はちょっと誤解を招きやすい。 元から備わった性質のように思われるからね。 最も強い種類の適性とは、ある種の問題に対するどん欲な興味だけれど、 そういう興味は後天的に獲得するものが多い。

この考えの変化したものは、現代の文化においては「熱意」という言葉で 呼ばれている。最近、ウェイター募集の広告で「サービスに対する熱意」を 持った人を求めている、というのを見た。 本物の熱意は、ウェイターくらいじゃおさまらないものだ。 それに熱意という単語も良くない。むしろそれは好奇心と呼ぶのがいい。

子供は好奇心旺盛だ。ただ、ぼくがここで言っている好奇心は 子供のとはちょっと違う。子供の好奇心は広くて浅い。 ランダムに色々なことについて「どうして?」と尋ねる。 多くの人は、大人になるまでにこの好奇心が全部渇いてしまう。 これは仕方無いことだ。だって何についても「なぜ?」と尋ねていたら 何もできないからね。でも野心を持つ大人では、 好奇心は全部渇いてしまうのではなく、狭く深くなってゆくんだ。 泥の庭が井戸になるんだ。

好奇心を持っていると、努力が遊びになる。 アインシュタインにとっては、相対性理論は試験のために勉強しなくちゃならない 難しい式の詰まった本ではなかったはずだ。 それは解き明かしたい神秘に見えていただろう。 だからたぶん、彼にとって相対性理論を見出すことは、 今の学生が授業でそれを学ぶことほど、努力とは感じられなかったんじゃないかな。

学校で植え付けられる幻想の一番危険なものは、 素晴らしいことを為すには自分に厳しくなければならないというものだ。 多くの科目はあまりに退屈に教えられるから、 自律心が無いと全部に出席することなんてできやしない。 大学に入ってすぐに、ぼくはヴィドゲンシュタインの言葉を読んで びっくりした。彼は自律心が無くて、たかが一杯のコーヒーであろうと 欲しくなったら我慢することができなかったというんだ。

今、ぼくは素晴らしい仕事をした人を何人も知っているけれど、 みんな同じなんだ。自分を律するということをほとんどしない。 延ばせることはぐずぐず先に延ばすし、興味のないことをやらせようと しても全くの無駄だ。そのうちの一人ときたら、自分の結婚式に 出席してくれた人へのお礼の手紙を出してない。 結婚して4年経つのに。もう一人は、メールボックスに26000通のメールをため込んでる。

自律心が全くのゼロだったら困るよ。走りに行こうかなと思うくらいの 自律心は必要だ。ぼくも時々、走るのが面倒だなあと思うけれど、 一度走り出せばあとは楽しめる。そして何日か走らないと具合が悪くなる。 素晴らしい仕事をする人にとっても同じことなんだ。 仕事をしてないと具合が悪くなるし、仕事を始めるだけの自律心は 持っている。ひとたび仕事を始めれば、興味の方に圧倒されて、 自律心は必要なくなるんだ。

シェークスピアは偉大な文学を産み出そうと歯を食いしばって 勤勉に努力したって思うかい。そんなわけないさ。 きっと楽しんでいたはずだ。だから素晴らしい作品が書けたんだ。

いい仕事をしたいなら、必要なのは見込みのある問題に対する 大きな好奇心だ。アインシュタインにとっての一番大事な瞬間は、 マクスウェルの方程式を眺めて、これはどうなっているんだろうと 自問したところにあった。

生産的な問題に照準を合わせるのには長い時間がかかる。 本当の問題は何なのかを見つけるだけで何年もかかるかもしれないからね。 極端な例を言えば、たとえば数学だ。数学を嫌う人は多い。 でも学校で「数学」の名前でやらされていたことは、 実際に数学者がやっていることとはほど遠いんだ。

偉大な数学者のG. H. ハーディは、高校の時は数学が嫌いだったと 言っている。ただ他の生徒より高い点数をとれたから選択しただけだったと。 後になって、彼は数学が面白いということに気づいた。 質問に正しく答えることのかわりに、自分で問題を見つけるようになってからね。

ぼくの友達の一人は、学校で提出するレポートに苦しんでいると 母親が「それを楽しむ方法を見付ければいいのよ」っていうんだとぼやいていた。 でもそれが、やるべきことなんだ。世界を面白くする問いを見つけ出すんだ。 素晴らしい仕事をした人は、ぼくらと違った世界を見ていたわけじゃない。 ただこの世界の中の、ほんのちょっとした、でも不思議なことがらに気づいただけなんだ。

これは学問だけの話じゃない。「車はどうして贅沢品じゃなきゃいけないんだ? 車が日用品になったらどうなるだろう?」これがヘンリー・フォードの発した 偉大な問いだった。フランツ・ベッケンバウアー[訳註2]の問いはこうだった。 「どうしてみんな自分のポジションに留まってなくちゃならないんだ? ディフェンダーがシュートしたっていいじゃないか。」

現在
偉大な問いを発するのに何年もかかるとしたら、 いま、16歳の君は何をしたらいいだろう。 質問を見つける準備をするんだ。 偉大な問いは突然現れるんじゃない。徐々に頭の中に結晶してくるんだ。 それを結晶させるのは経験だ。だから、偉大な問いを見つけるのに 探し回ってもだめだ。「ぼくができる偉大な発見は何だろう」なんて ぼんやり考えててもだめだ。そんな質問に答えはない。答えがあるなら 既に見つけてるはずだからね。

大きなアイディアが頭に浮かぶようになるには、大きなアイディアを 追い求めるんじゃなく、自分が興味を持つことにたくさんの時間を費すことだ。 そして頭を柔軟に開いておいて、いつでも大きなアイディアが巣を作れるように しておくんだ。アインシュタイン、フォード、ベッケンバウアー、 みんなこのレシピを使ったんだ。彼らはみな、ピアニストがピアノの鍵盤を 知りつくしているのと同じように、自分の仕事を知りつくしていた。 だから何かひっかかりがあれば、すぐにそれに気づけるという自信を持っていたんだ。

今、何を、どうやってすればいいかって? まず興味の持てるプロジェクトを選ぶことだ。ある分量の資料を研究するとか、 何かを作ってみるとか、何かの問題の答えを見つけてみるとか。 ひと月以内で終わらせられるようなプロジェクトがいい。 そして、ちゃんと終わらせられる手段があるようなものにする。 少しは頑張らなくちゃならないようなものがいいけれど、ほんとうに少しだけでいい。 特に最初はね。もし二つのプロジェクトのどっちを選ぶか迷ったら、 面白そうな方を選ぼう。失敗したら、もう一方を始めればいいんだ。 これを繰り返す。そうすると次第に、ちょうど内燃機関みたいに、 このプロセスが自分で走り出すようになる。一つのプロジェクトが次の プロジェクトを生み出すようになるんだ。(そうなるまでには何年もかかるけれどね。)

学校に受けがよさそうというだけでプロジェクトを選ぶのは良くない。 特にそれで制約を受けたり、それが課題のように感じられるならね。 友達を巻き込みたかったら声をかけてもいいだろう。 でもあまりたくさんでない方がいいし、ただ群れたがるだけの人は避けたほうがいい。 友達は士気を保つのにいい (一人だけで始められるベンチャー企業はほとんどない)。 でも秘密にやることにも利点はある。秘密のプロジェクトというだけで 何かわくわくするものがあるし、失敗したって誰にもばれないんだから、 大胆な挑戦ができる。

プロジェクトが君の将来目指すものにあまり関係なさそうだったとしても、 心配することはない。目指すものに到達する道っていうのは、君が思うより ずっと大きく曲がりくねるものなんだ。プロジェクトをやることで、道は伸びてゆくんだ。 一番大事なのは、わくわくして取り組むことだ。そうすれば経験から学ぶことができるからだ。

人に言えないような動機だからって、それを抑えないようにしよう。 欲望の中で最も強いもののひとつは、他人よりうまくやりたいということだ。 ハーディはその気持ちで数学を始めたと言ったが、 それは別に珍しいことじゃないと思う。それを公に認める人は少ないけれど。 他の強い動機としては、知らなくてよいとされていることを知りたいとか、 やっちゃいけないとされていることをやりたいという欲望がある。 大胆な行動をしたいというのも、これに近い欲望だ。 16歳の生徒が小説を書けるなんて多くの人は思っていない。 そういうことに挑戦すれば、どんな結果であっても、プラス点になるはずだ。 本当に大失敗したところで、周囲の期待より悪いってことはないわけだからね [8]。

悪いモデルに気をつけよう。特に怠けることを肯定するようなものにね。 ぼくは高校生の時に、有名作家がやっているような「実存主義的」短篇小説を いくつか書いたことがある。そういうものっていうのは、 読んで面白い小説を書くよりも、たぶん簡単だ。 これは危険信号なんだ。そのことを知っているべきだった。 実際、ぼくが書いたものはどれも退屈だった。 ただ、有名作家みたいに知的で厳粛なものを書くっていうことがすごいことに 思えてただけだったんだ。

今はもう十分に経験を積んだから、そういう有名作家が本当は全然たいしたこと ないってことがわかる。実は有名人のほとんどはそうなんだ。 短期的に見ると、ある仕事の質っていうのは有名度とはほとんど関係がない。 今思えば、ぼくは何かカッコいいことをしたいなんて焦らないで、 ただやりたいことをやってればよかったはずなんだ。 それが実は、カッコいい仕事への道なんだ。

多くのプロジェクトで大事な要素は、もうほとんどそれ自体が一つの プロジェクトになるようなものなんだが、良い本を見つけることだ。 ほとんど全ての教科書はダメだ[9]。 だからたまたま手近にあった本を見て、それがその分野の全てだとは 思わないほうがいい。ごくわずかの良い本を積極的に探さないとならない。

大事なことは、外に出てなにかを為すことだ。黙って座って教えられるのを 待つんじゃなく、自分から踏み出して学ぶんだ。

入試の試験官に自分の人生を合わせる必要なんてない。 自分の好奇心に合わせて人生を作っていけばいい。 野心的な大人はみんなそうしてる。それに、君は待つ必要はないんだ。 大人になるまで待たなくてもいい。だって、ある年齢になったり、 どこかの学校を卒業した時にぱちんと大人になるようなスイッチなんて ないんだからね。自分の人生に責任を持つことを決心したその時に、 君は大人になるんだ。何歳だってできることだ [10]。

ばかげだ話だと思うかい。君はこう思うかもしれないね。 「ぼくは未成年だし、金もないし、親と一緒に住まなくちゃならないし、 一日中大人に言われたことをやらなくちゃならないのに！」ってね。 でもね、大人になって仕事をしていたって、やっぱり似たような 面倒な制限がいろいろあるものさ。でもやる人はちゃんとやり遂げる。 子供であることが制限の多いことだって思ってるなら、子供を持ったら どんなことになるか考えてごらん。

大人と高校生の唯一の違いは、大人はものを成し遂げる必要があることを 知っていて、高校生はそうでないということだ。 多くの人々は、それをだいたい23歳くらいの時に知る。 でも、こっそりいまから始めることを、ぼくは君達に勧めたい。 さあ、始めよう。そうすれば、君達は史上初めて、高校の時に時間を無駄にしなかったと 言える世代になるかもしれない。

原註
[1] ぼくの友人の医者は、 これでも医者の仕事が本当はどんなものかを知ることはできないだろうと言っている。 「どれだけ時間を費して、ほとんど自分の時間を持てない何年もの訓練を受けて、 そしていつだってポケベルで呼び出されることがどんなに煩わしいかなんて、 わかるわけないよ。」

[2] 彼が出来る一番の方法は、 おそらく独裁者になってNBAを脅して自分をプレイさせることだ。 現実的に、それに一番近い立場は労働長官になることだ。

[3] 昼間の仕事というのは、 本当の仕事(バンドで演奏したり、相対性理論を発明したり)に時間を費せるように、 生活費を稼ぐためにやるような仕事のことだ。

高校を昼間の仕事だと思うことは、生徒の何人かにとっては むしろ良い成績をとるのに役立つかもしれない。 授業をゲームだと思えば、内容自体に意味が無くてもがっかりすることはないだろう。

授業がどんなにひどくても、それなりの大学に入るには良い成績は 取っとかないとならない。そのこと自体は、やる価値のあることだ。 近年では、賢い人々の集団を見つけるのに大学は良い場所だからだ。

[4] 二番目に大きな後悔は、重要でないことを気にしすぎていたことだ。 特に、他の人にどう思われているかってことだね。

より正確に言えば、ランダムな人々にどう思われているかを気にするってことだ。 大人だって人にどう思われるかを気にするけれど、誰に思われるかって 点ではより選別していることが多い。

ぼくはだいたい30人くらい、意見を気にする友人がいる。 残りの世界の意見はぼくにとってはどうでもいい。 高校の問題は、まわりに居る人間が、自分の判断ではなくて 年齢と地域がたまたま一緒だったというだけで決まることだ。

[5] 時間を無駄にする 一番の要因は、気を散らすものだ。気を散らすものが無ければ、 自分が何もしていないということにすぐ気づいて、落ち着かなくなるはずだ。 どれだけ余分なことに気を取られてるかを知るには、こういう実験をしてみるといい。 週末にある程度の時間をとって、一人で座ってただ考えるんだ。 ノートを持っていてそれにメモを取るのはいい。けれど、他のものは 全て絶つ。友達も、テレビも、音楽も、電話も、インスタントメッセンジャーも、 メールも、ウェブも、ゲームも、本も、新聞も、雑誌も無しだ。 1時間もすれば、ほとんどの人は何か気を散らすものが欲しくてどうしようもなく なるはずだ。

[6] 私立の進学校が 入学審査官をだますためだけのものだって言うつもりはないよ。 普通は、より良い教育もしてくれる。でもこういう思考実験をしてみたまえ。 私立の進学校が、今と同じ質の教育をしてくれるんだが、そこに行くと ごくわずか (.001) の確率で入試に受かりにくくなるとする。 そしたらどれだけの親が子供を私立の進学校に行かせようとするだろうね。

もちろん、私立の進学校に行った子供はより多くのことを学んだのだから、 より大学の合格者としてふさわしいという議論はできる。 でもそれは経験的には誤りだ。 一番素晴らしい高校だって、そこで教えてくれることなんて 大学で学ぶことに比べたら誤差の範囲だからだ。 公立高校を卒業した子供は入学直後には多少の不利はあるかもしれないが、 2年生になればむしろリードするようになる。

(公立高校の生徒の方が賢いって言っているんじゃなくて、 どんな大学にも公立高校出身の学生がいるってことを言っている。 私立の進学校の方が入試に受かりやすいという前提を認めれば、 公立高校出身で試験に受かった生徒の方が平均的に高い能力を持っているということになる)

[7] どうして社会が君に ファウルするんだろう。その主な原因は、無関心だ。 高校を良くするという外圧が全く無いからだ。 航空管制システムは優れたシステムだが、それは そうでなくちゃ飛行機が落ちてしまうからだ。 企業は製品を作らないとライバルに客を取られてしまう。 でも学校がダメになっても飛行機は落ちないし、競争相手もいない。 高校は邪悪なのではなく、ただランダムなんだ。 でもランダムであることは、かなり悪いことだ。

[8] それに、もちろんお金という動機もある。 高校ではこれはあまり関係無いだろう。人が欲しがるようなものを 作れることは少ないからね。でも多くの偉大なものごとというのは、 お金を稼ぐために為された。 サミュエル・ジョンソンは、「金のため以外にものを書くやつなんて馬鹿だ」と 言っている。(多くの人は、彼は誇張してるんだと思いたがるけどね)。

[9] 大学の教科書だってひどいものだ。 大学に入ってみれば、教科書の多くは(いくつかの輝ける例外を除いては) その分野の第一人者が書いたものじゃないことがわかるだろう。 大学の教科書を書くのはあまり面白い仕事じゃないし、 お金のために書かれることが多い。面白くない仕事なのは、 出版社が色々注文をつけて来るからで、自分がやってることを 理解できない人間に注文をつけられるのは最悪なことだからだ。 高校の教科書では状況は もっと悪いらしい。

[10] 教師はいつも「大人のように振る舞いなさい」と君達に言っているかもしれない。 でも、本当に君達がそうすることを望んでいるかは怪しいものだ。 君達は騒がしくてまとまりが無いかもしれないけれど、 大人に比べたらずっと素直だ。 君達が本当に大人のように振る舞い出したら、それは例えば 大人達を君達の体に移し変えたようなものになるだろう。 FBIエージェントやタクシーの運転手や記者達が、 トイレに行くのにいちいち許可を得る必要があって、しかも一度に一人しか いけないなんて聞いてどういう反応をするか想像してごらん。 君達が教えられたことなんてひとつも守られないはずだ。 もし本当に大人達が高校に入ることになったら、最初にやることはきっと 組合を作って校則の改正を教師達と談判することだろうね。

このエッセイの下書きに目を通してくれた、Ingrid Bassett、Trevor Blackwell、 Rich Draves、Dan Giffin、Sarah Harlin、 Jessica Livingston、Jackie McDonough、Robert Morris、Mark Nitzberg、 Lisa Randall、Aaron Swartz、 それに、高校時代について私に語ってくれた他の多くの人々に感謝します。

訳註
訳註1：
入学管理者：原文admission officer。 米国の大学は入試一発ではなく、大学ごとのAdmission Officeが 志願者の高校での活動や成績、統一テストの結果などを勘案して合否を決定する。
訳註2：
フランツ・ベッケンバウアー Franz Beckenbauer：サッカー選手、監督。 「リベロ」のポジションを確立した。
#+end_quote
** textlint-plugin-orgプラグイン発表用スライド<2021-07-02 金>
[[id:d3394774-aba5-4167-bd18-f194eb2bd9ed][TextLint]]
[[https://github.com/kijimaD/textlint-plugin-org][GitHub - kijimaD/textlint-plugin-org]]
[[https://github.com/textlint/textlint#supported-file-formats][GitHub - textlint/textlint]]

textlintのプラグインを作成しました。
npmに登録＋公式のREADMEにリンクしました。
~npm install textlint-plugin-org~

orgファイル(Emacs独自のアウトライン形式)で使えるようにしました。
(orgデモ)
*** TextLintの説明
TextLintはその名の通り自然言語用のLintです。
単純な間違いや、わかりづらい言い回し、語数制限などを検知してくれます。たくさんルールがあって面白いです。

Markdownは標準、ほかにもHTMLなどは対応してます。

対応してないフォーマットの場合、たとえば見出しで ~。~ がないとか、コードブロックに対して検知をしてまともに使用できません。

*どうしても* orgで使いたかったので作成することにしました。
*** Lintについて学ぶ
https://azu.github.io/JavaScript-Plugin-Architecture/

中段の動作イメージがとてもわかりやすい。

AST変換というのが重要だということがわかります。

#+begin_quote
ESLintはコードをパースしてASTにして、そのASTをJavaScriptで書いたルールを使いチェックするという大まかな仕組みは分かりました。
#+end_quote

textlint-plugin-org/test/OrgProcessor-test.ts
テストから実際にASTオブジェクトの中身を見てみます。
#+begin_src javascript
    it('heading should Header', () => {
      const result = parse(`
,** Heading
      `);
      const section = result.children[0];
      const header = section.children[0];
      assert.equal(header.type, Syntax.headline);
    });
#+end_src

~console.log(section)~ ↓
#+begin_src javascript
  {
      type: 'UNKNOWN',
      level: 2,
      properties: {},
      children: [
          {
              type: 'Header',
              actionable: false,
              content: 'Heading',
              children: [Array],
              level: 2,
              loc: [Object],
              range: [Array],
              raw: '** Heading\n'
          },
          type: 'UNKNOWN'
      ],
      loc: { start: { line: 2, column: 0 }, end: { line: 3, column: 0 } },
      range: [ 1, 12 ],
      raw: '** Heading\n'
  }
#+end_src

~console.log(header)~ ↓
#+begin_src javascript
  {
      type: 'Header',
      actionable: false,
      content: 'Heading',
      children: [
          {
              type: 'UNKNOWN',
              level: 2,
              loc: [Object],
              range: [Array],
              raw: '**'
          },
          {
              type: 'Str',
              value: 'Heading',
              loc: [Object],
              range: [Array],
              raw: 'Heading'
          },
          { type: 'UNKNOWN', loc: [Object], range: [Array], raw: '\n' },
          type: 'UNKNOWN'
      ],
      level: 2,
      loc: { start: { line: 2, column: 0 }, end: { line: 3, column: 0 } },
      range: [ 1, 12 ],
      raw: '** Heading\n'
  }
#+end_src

Lintは、このASTオブジェクトのTypeに基づいてそれぞれのルールを適用してます。
なので見出しの星は対象外にできます。
*** AST変換器を調べる
- ファイル形式の文字列 → (ここが必要) → AST → Lint

やる必要があるのは、オブジェクトの形式を揃えることです。
typeの名前がtextlintに対応したシンボルへマッピングします。

変換器はすでにあります。
- orgajs :: https://github.com/orgapp/orgajs

なので、本質的に必要なことはこのマッピングです(ほかにも位置や範囲を付加する必要がありますが、HTMLとかとほぼ同じ)。
#+begin_src javascript
export const nodeTypes = {
  document: ASTNodeTypes.Document,
  paragraph: ASTNodeTypes.Paragraph,
  list: ASTNodeTypes.List,
  'list.item': ASTNodeTypes.ListItem,
  headline: ASTNodeTypes.Header,
  block: ASTNodeTypes.CodeBlock,
  hr: ASTNodeTypes.HorizontalRule,
  // inline block
  'text.plain': ASTNodeTypes.Str,
  'text.code': ASTNodeTypes.Code,
  'text.bold': ASTNodeTypes.Emphasis,
  link: ASTNodeTypes.Link,
  footnote: 'FootnoteReference',
};
#+end_src
*** テストを書く
orgajsがどんな名前で出力するかは実行しないとわからなかったので、ちゃんとすべてテストを書いて調べました。上流の不慮の変更も検知できます。

ということで使えるようになりました🎉。

便利です。
*** まとめ
Emacsエコシステムを少し広げることができました。
** digger発表用スライド<2021-07-02 金>
[[id:70f249a8-f8c8-4a7e-978c-8ff04ffd09c0][digger]]
*** やっていること(途中)
[[https://github.com/kijimaD/digger][GitHub - kijimaD/digger]]
CLIのゲームを作っています(WIP)。

(デモ)

まだ移動しかできない。
*** 前回の反省を踏まえた要件
- *画像表示はあきらめる or 見下ろし*
- ターン制にする。リアルタイムではなく。
- テストを書く(*テストが書ける構造にする*)
*** 利点
時代に逆行した開発ですが、よいところもあります。

- 真のRubyだけに集中できる(ライブラリすら必要ではない。CLI用のCursesくらい)
- オブジェクト指向をやらなければならない状況。ゲームそのものがゲームオブジェクトの相互作用なので、オブジェクト指向でないと条件ありすぎて死ぬ。フツーに命令的に書けるプログラムが二者間だとしたら、ゲームは三者間。

+ 例 :: 壁に当たるのは自キャラだけでない。敵キャラや銃弾も当たる。各オブジェクトに判断してもらわないといけない。
+ 例 :: 弾がヒットしたら、誰のスコアになるのか => その銃弾オブジェクトを生成したキャラクターオブジェクト。みたいな。
+ 例 :: 毎ターンフィールドにあるすべてのオブジェクトを更新＋新描画したい => すべて入れ物オブジェクトに入れておいて、mapですべてを一括処理しよう、とか。
*** まとめ
1ヶ月くらい頑張ってみます(宣言)。
*** ボツ
ローグライクになる予定です。↓みたいなゲーム。超好きなジャンルです。

- [[https://github.com/CleverRaven/Cataclysm-DDA][Cataclysm-DDA]] :: ゾンビサバイバル
  [[https://www.google.com/search?q=cataclysm+dark+days+ahead+&tbm=isch&ved=2ahUKEwir1caPhcLxAhVBxosBHUPJCfwQ2-cCegQIABAA&oq=cataclysm+dark+days+ahead+&gs_lcp=CgNpbWcQAzICCAAyAggAMgIIADICCAAyAggAMgIIADICCAAyAggAMgIIADICCAA6BAgAEBhQtsMFWPDFBWCxxwVoAHAAeACAAbUBiAHHApIBAzIuMZgBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=eMvdYKu5B8GMr7wPw5Kn4A8&bih=733&biw=1451#imgrc=NRZZLClw8123FM][参考]]

- [[http://www.bay12games.com/dwarves/][Dwarf Fortress]] :: サバイバル/シミュレーション
  [[https://www.google.com/search?q=dwarf+fortress+gif&tbm=isch&ved=2ahUKEwi3lIiphMLxAhVvzYsBHQ5zAiUQ2-cCegQIABAA&oq=dwarf+fortress+gif&gs_lcp=CgNpbWcQAzICCAA6BAgAEEM6BAgAEBhQ_ZkDWLqcA2CgngNoAHAAeACAAXeIAY4DkgEDMi4ymAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=ocrdYPe_C--ar7wPjuaJqAI&bih=733&biw=1451#imgrc=pWyEfsGw-tobeM&imgdii=LjqvyOp9B09twM][参考]]

- Elona :: RPG風
  [[https://www.google.com/search?q=elona&tbm=isch&ved=2ahUKEwjR1oDUhcLxAhXNDN4KHVI7CTEQ2-cCegQIABAA&oq=elona&gs_lcp=CgNpbWcQAzICCAAyBAgAEEMyBAgAEEMyAggAMgIIADIECAAQQzICCAAyAggAMgQIABBDMgIIAFCP9gFYk_0BYJH-AWgAcAB4AIABXogB1gKSAQE0mAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=B8zdYJG3Kc2Z-AbS9qSIAw&bih=733&biw=1451#imgrc=pLVXzgxlaxCVDM][参考]]

これらは商業的な作品ではなく、貧弱なグラフィックですが、超濃密なゲーム世界を作り上げています。
個人がめざす(めざせる)のはこういう方向性だと考えてます。
*** 前回の反省
仕事につく前、何度か作りはじめては挫折してきました。

直近だと去年開発してましたが、開発が進まなくなってやめました↓。
- [[https://github.com/kijimaD/ban-ban-don][GitHub - kijimaD/ban-ban-don]] :: rubyのゲームライブラリGosuを使った、シューティングゲーム。
(本に載ってたコードをベースに開発しました。根本部分のコード構造はほとんどオリジナル性ないです)


これの問題点、挫折した理由...。

- 要件を高望みしすぎた。
  - 疑似3Dにした。座標に、ひし形の画像を敷き詰めると疑似3Dができます…画面確認が大変だった。特に重なりとか、接触判定が…。
  - アニメーションする画像の用意が大変すぎた。方向分の画像を作る必要がある。
  - リアルタイムなので再現しにくい。
  - パフォーマンスを考えないとまともに動かなくなる。黒魔術がある(四分木とか)。

- つらい目視確認開発。
  - 新機能を作るときも、いちいち起動して該当箇所までいって開発していた。
  - テストがない、lintがない(まだ知らなかった)
  - いつのまにかどこかが壊れて動かなくなること多数

=> ムリ ~＼(^o^)／~
