:PROPERTIES:
:ID:       49971784-7850-4d24-92f2-9c6f29bd332e
:END:
#+title: system
* 概要
Linuxマシンでいろんな設定をしている。
別のマシンへ移るときに再現できるよう、システムに関する情報をまとめる。

リポジトリにdotfilesとしてまとまっている。[[https://github.com/kijimaD/dotfiles][kijimaD/dotfiles: System settings]]
* 好みのOSを作る
カスタマイズ性の高いソフトを組み合わせて、再現性の高い最高のシステムを作る。
Guixは土台になる。
だいたい[[id:fa497359-ae3f-494a-b24a-9822eefe67ad][System Crafters]]の情報がベースになってる。

- プレーンテキストでの設定
- 柔軟な設定
- コードがオープン
- キーボード指向

** [[id:d694ecaa-6a8b-4669-a95c-f76de6dcbd2c][GNU Guix]]
パッケージ管理システム。
** GNU [[id:1ad8c3d5-97ba-4905-be11-e6f2626127ad][Emacs]]
環境。
** GNU Stow
設定ファイル管理ツール。
シンボリックリンクを管理してくれる。
** GNU Shepherd
サービス管理ツール。
** GNU Make
古代からのビルド用ツール。タスク定義をドキュメント化するのに使う。
** nyxt
完全キーボードでのインターネットブラウジングを可能にする。
** i3-wm
どうしてもEmacsで日本語入力ができない。
ibusが特定アプリで動作しない不具合にあたっている。
gnomeでは完全にできるので、自動でやってくれてるところがあるよう。
Emacs上ではskkを使うようにして解決。Emacs以外では普通に入力すればいい。

ドキュメント
https://i3wm.org/docs/userguide.html#_hiding_vertical_borders

- close window: ~Mod + Shift + q~
** polybar
柔軟に設定できるメニューバー。
** compton
Emacs側で透過設定しても字が薄くなって微妙だが、ウィンドウ側でやると綺麗にできる。
また、ほかのアプリケーションを透過できて統一感がある。かっこいい。
** feh
背景を設定する。
#+begin_src shell
  feh --bg-fill -Zr ~/dotfiles/backgrounds/4k-Ultra-HD_00330.jpg
#+end_src
** dunst
[[https://github.com/dunst-project/dunst][dunst-project/dunst: Lightweight and customizable notification daemon]]
通知機能が入ってないウィンドウシステムでは([[id:eb196529-bdbd-48c5-9d5b-a156fe5c2f41][EXWM]]とか)、これを組み合わせて通知する。
* [[id:d694ecaa-6a8b-4669-a95c-f76de6dcbd2c][GNU Guix]]への移行
Linux Mintに、Guixを後でインストールして使っている。
Guixオンリーにしたい。

好ましく思える理由。
- 設定がシンプルになる
- 再現性が高い

移行できない理由。
- 日本語入力
- 設定類に不明なところが多い。例えば音声切り替えはどうするのか、シャットダウンはどうするのか
* QEMU
新しい[[id:7a81eb7c-8e2b-400a-b01a-8fa597ea527a][Linux]] ディストリビューションを試すときや、設定を変更するときは仮想マシン上で行った方がいい。
気軽に試せるし、再現性が高い。緊密なフィードバックループがあるとき開発は効率的になる。

逆にマシン本体へのインストールだと、設定変更や壊れたときの対応が面倒。
マシン本体へのインストールは本番環境みたいなもので、すばやく試すのには向いてないし、壊れたときがさらに面倒。
** DONE polybarにネットワーク表示を追加する
CLOSED: [2022-02-11 Fri 17:45]
:LOGBOOK:
CLOCK: [2022-02-11 Fri 14:26]--[2022-02-11 Fri 14:51] =>  0:25
CLOCK: [2022-02-11 Fri 13:33]--[2022-02-11 Fri 13:58] =>  0:25
:END:
** TODO guix system reconfigureできない問題
仮想環境内でsystem reconfigureすると次回起動時に起動できなくなる。パーティションの問題らしいのだが全くわからない。
system reconfigureができないと、キーボードレイアウトをいじれないのでまともに使えない。
** イメージ内でやったことをリセットする
イメージ内でやったことはイメージに書き込まれるので、[[id:90c6b715-9324-46ce-a354-63d09403b066][Git]]管理に入れておいてresetすれば戻る。
#+begin_src shell
git checkout -- .
#+end_s
** [[id:d694ecaa-6a8b-4669-a95c-f76de6dcbd2c][GNU Guix]]を仮想マシンで起動する
[[id:d694ecaa-6a8b-4669-a95c-f76de6dcbd2c][GNU Guix ]][[https://www.youtube.com/watch?v=7ZdMRLPZhFs][5 Reasons to Try Guix in 2022 - YouTube]]
#+begin_src shell
  sudo apt install qemu-kvm
  qemu-system-x86_64 \
      -nic user,model=virtio-net-pci \
      -enable-kvm -m 2048 \
      -device virtio-blk,drive=guix-demo \
      -drive if=none,file=$HOME/Downloads/guix-vm.qcow2,id=guix-demo \
#+end_src
** Windowsを仮想マシンで起動する
[[https://qiita.com/Hiroki_Kawakami/items/b18f6c50df4ce215e40d][無料のWindows仮想マシンをQEMUで動かす - Qiita]]

#+caption: Hyper-V用のイメージWin10.vhdxを用意して起動する
#+begin_src shell
qemu-system-x86_64 -m 4096 -smp 2 -hda MSEdge\ -\ Win10.vhdx -enable-kvm
#+end_src

[[https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/][配布サイト]]に記載のように、パスワードは ~Passw0rd!~ 。
仮想マシンのフォーカスを抜けるにはCtrl + Alt + g。
* Tasks
** TODO dotfilesと内容がかぶっているので、統一する
** TODO [[id:1658782a-d331-464b-9fd7-1f8233b8b7f8][Docker]]で動作チェックできるようにする
クリーンな環境でうまくいっているかチェックしたい。
Guix関連が難しく、詰まっている。
* Reference
** DONE polybarとpomodoroを連携させる
CLOSED: [2022-01-16 Sun 17:13]
:LOGBOOK:
CLOCK: [2022-01-16 Sun 22:41]--[2022-01-16 Sun 23:06] =>  0:25
CLOCK: [2022-01-16 Sun 20:39]--[2022-01-16 Sun 21:04] =>  0:25
CLOCK: [2022-01-16 Sun 20:01]--[2022-01-16 Sun 20:26] =>  0:25
CLOCK: [2022-01-16 Sun 16:33]--[2022-01-16 Sun 16:58] =>  0:25
CLOCK: [2022-01-16 Sun 16:02]--[2022-01-16 Sun 16:27] =>  0:25
:END:
- [[https://colekillian.com/posts/org-pomodoro-and-polybar/][Org Pomodoro and Polybar - Cole Killian Adventure]]

改良してゲージ型にした。
全体カウント機能を追加した。一日ごとにリセットする。
* Archives
