:PROPERTIES:
:ID:       1658782a-d331-464b-9fd7-1f8233b8b7f8
:END:
#+title: Docker

* 概要
Dockerはパフォーマンスに優れた仮想環境を作るプログラム。
* 各種コマンド
** dockerfile/runでbundle installするのは何が違うか
runは新しいコンテナを作成するため永続しない。
** dockerfile
Dockrfileはイメージを作る。(image build)

docker-composeは↑で作られたコンテナを作り操作する(不正確な可能性がある)。
コンテナには2種類ある。
- 自作する必要があるものは↑Dockerfileで作られたイメージを使う
- 既存コンテナ([[id:7dab097c-60ba-43b9-949f-c58bf3151aa8][MySQL]]とか)はコンテナをダウンロードする
** アタッチ
** コマンド実行
コンテナ内部で実行する。
#+begin_src shell
  docker-compose run {コンテナ} {shellコマンド}
#+end_src
** キャッシュを使わずにbuild
#+begin_src shell
  docker-compose build --no-cache
#+end_src
** 立ち上げと停止
#+begin_src shell
docker-compose up --build -d
docker-compose down
#+end_src
** docker外に公開
[[id:e04aa1a3-509c-45b2-ac64-53d69c961214][Rails]]
Dockerfileで。
#+begin_src shell
  CMD bundle exec rails server -b 0.0.0.0
#+end_src

などと書いておくと、外部(Docker外)からアクセスできるようになる。
左が公開、右がコンテナ内。だからブラウザでポート8000アクセスできるようになる。
#+begin_src shell
  docker run -p 8000:3000 -it bdd92ace66ec
#+end_src
** ログ確認
#+begin_src shell
docker ps -a # id確認
docker logs 1111... # idを入れる
#+end_src
** [[id:7dab097c-60ba-43b9-949f-c58bf3151aa8][MySQL]]エラー
- copyしてくるdocker-compose.ymlファイルが間違っていた。なので変更が反映されていなかった。
- docker-compose ps で見ると、mysqlがfailしていた。つまり起動後すぐMysqlがシャットダウンしてるのでアクセスできない。ログを見てみるとたくさんエラーが出ていたがよくわからない。バージョンを変えると起動できた。
** トークンエラー無視
docker内のrailsでtoken errorになった。dockerが1層はさまって、直に公開するわけでないので何かアドレスが異なるために起こるのだろう。
lvh.meからアクセスすると直った。

逐一対応するなら↓だが現実的でない。
#+begin_src ruby
skip_before_action :verify_authenticity_token
#+end_src
** 周辺コンテナとの疎通
エラー内容を確認する。
コンテナ間で通信したいのに、127.0.0.1になっていたらローカルのやつと通信しようとしている。

- redisエラーになった。確かに立ち上がってはいるのだが、railsからはアクセスできていない。
URLを環境変数でコンテナを指定した。

- memcachedエラーになった。特にブラウザにエラーは出ないがサーバでエラーが出てる。
127.0.0.1を見ているよう。ホストが指定できてないんだな。同様に環境変数を設定して接続できるようになった。
** 削除
使ってないイメージを削除する。
#+begin_src shell
  docker images prone
#+end_src

一気に全部削除する。
#+begin_src shell
docker stop $(docker ps -q)
docker rm $(docker ps -aq)
docker rmi $(docker images -q)
#+end_src
** LinuxのDockerで rails new したときの権限がrootになる問題
[[https://docs.docker.com/samples/rails/][If you are running Docker on Linux, the files rails new created are owned by root.]]
* Tasks
** day jobのdocker環境化[2/6]
Day JobもLinuxに統一する。
*** [ ] テストの実行
アタッチ…コンテナ内部でシェルコマンドを実行する必要がある。
*** [X] サーバ立ち上げ
サーバ部分も完全にdocker化した。表示はまったく問題なさそう
できたと思ってたが、完全にdockerにすると反映が死ぬほど面倒なのでアタッチしないといけない。
アタッチするとうまくいかない。
*** [ ] volumes
うまくできない。docker-compose内でもbundle installしないとgem not foundになる。
かといってdocker-compose内でやるとまずい権限で作られるらしく、後のコンテナが起動に失敗する。
*** [X] DBのGUIツールとの接続
Linux用のsqlectronがよさそう。が、上手く[[id:7dab097c-60ba-43b9-949f-c58bf3151aa8][MySQL]]と接続できない
~MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'~ を追加して入れるように。指定してるとログインできなかった。
*** [ ] メール関係の動作確認
redisが本当に動いてるかわからない。
*** [ ] yarnができてない
どうやってwatchして反映できるんだろう。確かにコマンドはできてるけど、nodeサーバと通信ができてない感じだ。
*** [ ] コンソールに入れるように
~docker exec -it {container} /bin/bash~ に入れない。
containerIDを入れたらいけたが、不便。
* Archive
* References
**  [[https://docs.docker.jp/pdf-download.html][Docker ドキュメント日本語版 PDF ダウンロード — Docker-docs-ja 19.03 ドキュメント]]
Dockerのドキュメント。
