:PROPERTIES:
:ID:       a6980e15-ecee-466e-9ea7-2c0210243c0d
:END:
#+title: JavaScript

* JavaScript
JavaScriptはブラウザ上で動作するのを特徴とする[[id:868ac56a-2d42-48d7-ab7f-7047c85a8f39][Programming Language]]。
WEB開発に多用される。多くの実装、フレームワーク、パッケージが存在する。

進歩が早いため、古い本だと書き方が古くなってたり最悪動かなかったりする。
最新のコードを読んでもよくわからない、ということも多い。
書籍を買うときは発行年度を確かめることが必要。

以前JSやってたので[[id:dc50d818-d7d1-48a8-ad76-62ead617c670][React]],[[id:ad1527ee-63b3-4a9b-a553-10899f57c234][TypeScript]]にいって大丈夫だろう、は罠。
学ぶ前に最新のJSをキャッチアップしておかないと、理解しにくい。
* Memo
新しく追加された構文などもあって、ややこしい。
** promise method
非同期のアクセス処理を行う関数。
アクセスに時間がかかる間待ってるのは無駄なので、平行処理させる。
#+begin_src javascript
  fetch("https://google.com") // promiseオブジェクトが返ってくるだけ

  fetch("https://google.com").then(res =>
      res.json() // 非同期処理した結果が返ってくる
  )
#+end_src

#+begin_src javascript
  fetch("https://google.com")
    .then(res => res.json())
    .then(json => json.results)
    .then(console.log)
    .catch(console.error);
#+end_src
** spread syntax
~...~ : スプレッド構文。いくつかの用途がある。

- 配列の連結に使用される。
#+begin_src javascript
  const peaks = ["Tallac", "Ralston", "Rose"];
  const canyons = ["Ward", "Blackwood"];
  const tahoe = [...peaks, ...canyons];

  console.log(tahoe.join(", ")); // Tallac, Ralston, Rose, Ward, Blackwood
#+end_src

- 配列のコピー作成
#+begin_src javascript
  const peaks = ["Tallac", "Ralton", "Rose"];
  const [last] = [...peaks].reverse(); // peaksがreverse()で破壊するのを防ぐため、コピーを作成する。そして配列の最初の要素をlastに代入する。

  console.log(last); // Rose
  console.log(peaks.join(", ")); // Tallac, Ralston, Rose => 破壊してない
#+end_src

- 配列の「残り全部」を表現する
#+begin_src javascript
  const num = [1, 2, 3]
  const [first, ...others] = nums;
  console.log(others.join(", ")); // 2, 3
#+end_src

- 関数の引数を配列として受け取る
#+begin_src javascript
  funciton directions(...args) {
      let [start, ...remaining] = args;
      let [finish, ...stops] = remaining.reverse();

      args.length
      start
      finish
      stops.length
  }

  directions("Truckee", "Tahoe City", "Sunnyside") // 任意の引数を受け取れる
#+end_src

- オブジェクトの連結

  #+begin_src javascript
    const morning = {
      breakfast: "oatmeal",
      lunch: "peanut butter and jelly"
    };

    const dinner = "mac and cheese";
    const backpackingMeals = {
      ...morning,
      dinner
    };

    console.log(backpackingMeals);

    // {
    //     breakfast: "oatmeals",
    //     lunch: "peanut butter and jelly",
    //     dinner: "mac and cheese"
    // }
  #+end_src
** object literal
変数をオブジェクトのプロパティ名として記述する場合、プロパティ名を省略できる。
#+begin_src javascript
  const name = "Alice";
  const age = 9;

  const person = { name, age };
  console.log(person); // { name: "Alice", age: 9 }
#+end_src

関数もオブジェクトリテラル内に記述することが可能。
#+begin_src javascript
  const name = "Alice";
  const age = 9;
  const print = function() {
    console.log(`${this.name}` is `${this.age} years old.`)
  }

  const person = { name, age, print };
  person.print(); // "Alice is 9 years old."
#+end_src

オブジェクトリテラル内に関数を記述する際に、functionキーワードを省略できる。
#+begin_src javascript
  const skier = {
      name,
      sound,
      powderYell() {
          let yell = this.sound.toUpperCase();
          console.log(`${yell} ${yell} ${yell}`);
      },
      speed(mph) {
          this.speed = mph;
          console.log("speed:", mph);
      }
  }
#+end_src
** destructuring
必要なプロパティのみを取捨選択して、代入できる機能。
#+begin_src javascript
  const aaa = {
      bread: "aaa",
      meat: "bbb",
      cheese: "ccc"
  };

  const { bread, meat } = sandwitch // オブジェクトから必要なプロパティのみを取捨選択する
  sandwitch // => aaa, bbb
#+end_src

読み飛ばすことも可能。必要な要素のみを取得することをリストマッチングという。
#+begin_src javascript
  const [, , thirdAnimal] = ["Horse", "Mouse", "Cat"];

  console.log(thirdAnimal); // Cat
#+end_src
** arrow function
#+begin_src javascript
  const aaa = (arg) => `return_value: ${arg}`;
#+end_src

戻り値のオブジェクトを括弧で囲む必要がある。
#+begin_src javascript
  const aaa = (firstName) => ({
      first: firstName,
      last: lastName
  })
#+end_src

アロー関数は独自のスコープを持たないので、アロー関数の外側と内側でスコープが保持される。
** 巻き上げ
関数式は変数宣言の前で呼び出せない。
#+begin_src javascript
  aaa() // これは呼び出せない

  const = aaa = function() {
    "aaa"
  }
#+end_src

関数宣言は宣言の前で呼び出すことができる。(巻き上げ)
#+begin_src javascript
  bbb() // これは呼び出せる

  function bbb() {
    "bbb"
    }
#+end_src
** node
フルスタックアプリケーションを構築するために設計されたJavaScript実行環境。
** npm
Node.jsのパッケージ管理システム。
** yarn
Node.jsのパッケージ管理システム。
当時npmではできなかった依存パッケージのバージョン固定化のために実装された。
** バージョンを無視してインストール
#+begin_src shell
  yarn install --ignore-engines
#+end_src
** スプレッド演算子
~...state~ といった記法。中身を展開するスプレッド演算子。
[[https://stackoverflow.com/questions/31048953/what-does-the-three-dots-notation-do-in-javascript][reactjs - What does the three dots notation do in Javascript? - Stack Overflow]]

↓2つは同じ意味。
#+begin_src javascript
<Modal {...this.props} title='Modal heading' animation={false}>
<Modal a={this.props.a} b={this.props.b} title='Modal heading' animation={false}>
#+end_src
** 特徴
[[https://book.yyts.org/revisiting-javascript/objects-and-classes][JavaScriptのオブジェクトとクラス - サバイバルTypeScript-TypeScript入門]]

#+begin_quote
JavaScriptの特徴はオブジェクトリテラル{}という記法を用いて、簡単にオブジェクトを生成できる点です。

JavaやPHPなどの言語では、オブジェクトを生成するにはまずクラスを定義し、そのクラスを元にインスタンスを作るのが普通ですが、JavaScriptはクラス定義がなくてもこのようにオブジェクトリテラルを書くと、オブジェクトをインラインで作れます。
オブジェクトリテラルがあるおかげで、JavaScriptでは自由度の高いコードが書けるようになっています。
#+end_quote

#+begin_src javascript
// 空っぽのオブジェクトを生成
const object = {};

// プロパティを指定しながらオブジェクトを生成
const person = { name: "Bob", age: 25 };
#+end_src

- メソッド :: オブジェクトに関連づいた関数のことです。

#+begin_src javascript
const object = {
  // キーと値に分けて書いたメソッド定義
  printHello1: function () {
    console.log("Hello");
  },
  // 短い構文を用いたメソッド定義
  printHello2() {
    console.log("Hello");
  },
};
#+end_src

#+begin_quote
JavaやPHPでは、オブジェクトのフィールドとメソッドははっきり区別されます。
一方、JavaScriptではその区別はきっちりしていません。Javaで言うところの
メソッドとフィールドは、JavaScriptでは同じように扱われます。たとえば、
メソッドにnullを代入することで、フィールドに変えてしまうこともできます。
#+end_quote

#+begin_quote
このようにclassでクラスを定義し、newでインスタンスを生成するスタイルは、
JavaやPHP、Rubyなどと使用感がよく似ています。

JavaScriptのクラスの特徴は、クラスもオブジェクトの一種というところです。
オブジェクトとは、プロパティの集合体だと前述しましたが、クラスもオブジェ
クトなのでプロパティの集合体としての性質を持ちます。したがって、定義し
たクラスはプロパティを追加したり、変更したりできます。
#+end_quote

#+begin_src javascript
const myObject = {};
myObject.key = "value"; // プロパティを追加
​class MyClass {}
MyClass.key = "value"; // プロパティを追加
#+end_src

ほかの言語ではクラスを後から変更できない。
#+begin_src typescript
  interface Person {
    name: string;
    age: number;
  }
#+end_src

インターフェースでの型ガードを自前で実装する必要がある。
#+begin_src typescript
  type UnKnownObject<T extends object> = {
    [P in keyof T]: unknown;
  };

  function isStudent(obj: unknown): obj is Student {
    if (typeof obj !== 'object') {
      return false;
    }
    if (obj === null) {
      return false;
    }
    const {
      name,
      age,
      grade
    } = obj as UnKnownObject<Student>;
    if (typeof name !== 'string') {
      return false;
    }
    if (typeof age !== 'number') {
      return false;
    }
    if (typeof grade !== 'number') {
      return false;
    }
    return true;
  }
#+end_src
** 配列
- 配列を処理するときはやりたいことに応じて関数を選択します。するとやりたいことが明確になるのでわかりやすくもなります。除去したときは`filter()`、新しい配列を作るときは`map()`という感じです。
** コールバック関数
- コールバック関数: 他の関数に引数として渡す関数のことです。
[[https://sbfl.net/blog/2019/02/08/javascript-callback-func/][JavaScriptの「コールバック関数」とは一体なんなのか]]
** Eslint無視の方法
#+begin_src json
 "rules": {
     "comma-dangle": "error",
     "require-yield": "error",
     "no-unused-vars": "off",
     "no-undef": "off",
 },
#+end_src

などと書きます。
** クラスを使わずにモジュール分割する
#+begin_src javascript
  var Msg = (function() {
    function test() {
    }
  }
  Msg.test()
#+end_src
** 命名の意味
 - ~_~ で始まるのはプライベートメソッドです。言語によっては未使用変数ということもあります。
** 関数宣言と関数式
2つの関数宣言の方法があります。

#+begin_src javascript
// 関数宣言
function hello() {
  return "hello";
}
#+end_src

#+begin_src javascript
// 関数式で関数を定義
let hello = function () {
    return "hello";
}; //←セミコロン
#+end_src
** 2つの関数式の書き方
関数式には2つの書き方があります。

#+begin_src javascript
// function式を用いた関数式
const hello = function (name) {
  return `Hello, ${name}!`;
};

// アロー関数の関数式
const hello = (name) => {
  return `Hello, ${name}!`;
};
#+end_src

短く書けるのでアロー関数が好まれます。
** NodeList
 - NodeList - https://developer.mozilla.org/ja/docs/Web/API/NodeList
 - text node: タグに囲まれたもの。 ~<p>これ</p>。~
 - element node: ~<p>や、</p>~
 - DOMツリー: ブラウザがアクセスしてHTMLを解析すると文書の内容を表すオブジェクトのツリー構造が構築されます。これがDOMツリーです。DOMツリーを形成する1つ1つのオブジェクトがノードです。さらに子のオブジェクトを持っている可能性があります。
https://qiita.com/KDE_SPACE/items/e21bb31dd4d9c162c4a6
** package.json
パッケージを理解するために不可欠です。
*** scripts
makeのようなもの。
#+begin_src shell
npm run <タスク名>
#+end_src
で実行できる。

#+begin_src json
  "scripts": {
      "build": "NODE_ENV=production babel src --out-dir lib --source-maps",
      "watch": "babel src --out-dir lib --watch --source-maps",
      "prepublish": "npm run --if-present build",
      "test": "mocha --require @babel/register test/*test.js"
  }
#+end_src
*** files
npm installされたときに展開されるファイル、実行されるファイルを指定する。

#+begin_src json
  "main": "lib/index.js",
  "files": [
      "lib",
      "src"
  ],
#+end_src

srcをコンパイルしてlibに格納、パッケージとしてはこちらを使用する、みたいなことを指定する。はず。
*** GitHubリポジトリから読み込むとき
#+begin_src shell
  npm install git@github.com:kijimaD/textlint-plugin-org#develop
#+end_src
** .babelrc
babelの設定。presetは使うbabelと合わせる必要がある。
#+begin_src json
{
  "presets": [
      "@babel/preset-env"
  ],
  "env": {
    "development": {
      "presets": [
          "jsdoc-to-assert",
          "power-assert"
      ]
    }
  }
}
#+end_src
** .eslintrc
*** extends

事前にnode i airbnb-baseしておいて
.eslintrcに追加するとルールセットを追加できる。
#+begin_src json
"extends": "airbnb-base",
#+end_src
** パッケージ関連の言葉
ややこしい。
*** npm パッケージマネージャ

package.jsonに書かれた設定でいろいろ実行。
パッケージインストール、アップデート、タスク実行、などいろいろ。
パッケージをインストールするときには、これが実行されてコンパイルされて使える状態になってたりする。

#+begin_src shell
  npm i
#+end_src

パッケージ内のコマンドを実行する。おそらくbundle execとかと同じ。

#+begin_src shell
  npx lint
#+end_src
*** node 実行環境

#+begin_src shell
  node # repl起動
#+end_src

#+begin_src shell
  node -v
#+end_src

本体をバージョンアップしても反映されないときは実行場所を確認する。
nでバージョンしても、読んでるのはnvmだったりする。.bash_profileなどを確認。
** 便利コマンド
ファイルに更新があったらテスト実行する。超便利。
#+begin_src shell
npm test -- --watch
#+end_src
** npm publishのやりかた
- npm publishはローカルのファイルをアップロードして公開するので、ブランチ、 ~git status~ に気をつける。

#+begin_src javascript
  # タグ付けとコミットを行う。package.jsonも更新される。
  npm version [ major | minor | patch ]
  npm publish
  git push --follow-tags
#+end_src

- [[https://qiita.com/akameco/items/de7718c6e10dc22be5b0][npm publishの流れとそれを1コマンド行うnp - Qiita]]
- [[https://ja.wikipedia.org/wiki/%E3%82%BB%E3%83%9E%E3%83%B3%E3%83%86%E3%82%A3%E3%83%83%E3%82%AF%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%8B%E3%83%B3%E3%82%B0][セマンティックバージョニング - Wikipedia]]
- [[https://semver.org/lang/ja/][セマンティック バージョニング 2.0.0 | Semantic Versioning]]
- [[https://github.com/semver/semver][semver/semver: Semantic Versioning Specification]]
* Tasks
** TODO 実際にinstallしてCIで確かめる
プラグイン本体でテストしてるが、実際にnpm installするわけではないので依存パッケージ検知できないことがある。
ローカルでクリーンインストールでもglobalにインストールしてたりしてるので検知できないのだろう。
* References
- [[https://www.oreilly.co.jp/books/9784873119380/][O'Reilly Japan - Reactハンズオンラーニング 第2版]]
- https://book.yyts.org/
- http://typescript.ninja/typescript-in-definitelyland/index.html
- https://future-architect.github.io/typescript-guide/index.html
