:PROPERTIES:
:ID:       ed146d63-0e55-4008-98e8-2a2f1f7329b5
:END:
#+title: Novel Game
#+filetags: Project

* 概要
ノベルゲームを作成する。

[[id:da7ec7fb-e585-4699-85dc-172c5060499a][Phaser]]がとてもよい。
ブラウザでプレイできるようにする。
* Memo
* Tasks
** TODO 文字をアニメーション表示する
** TODO プロンプトをアニメーション表示する
** TODO bundleするとパスが変わって読み込めない問題
開発時と本番環境での、ファイルパスのズレが生じる。
* Reference
** [[https://qiita.com/non_cal/items/622108030aa2e516260c][TypeScriptを使ってノベルゲームを作ろう - Qiita]]
最低限のノベルゲームが作成できる。非常に参考になる。
* Archives
* Prot
** キャラ
*** 田島
過去の記憶があまりない。

友人が死んだところから。それでいて自分の記憶が曖昧なところで、よく思い出せないが、仲が悪かったことを思い出す。
その友人との思い出、というところで語る。
ストーリーでは思い出すことができるが、年表では思い出すことのできない病気。最初に語っていたのは診療に対するものだった。
** オチ
廃墟で死体を見つける。
次に見たとき、死体はなくなっていた。
実は殺したのは自分で、その記憶をでっち上げていた。
それぞれ無関係そうな無邪気な遊びを、後から見ると恐ろしい行為として思い出す、ということ。

- 夢や個人だけの回想で少しずつ記憶を改変していた。
** ライン
*** オープニング(駅)
どうして忘れていたんだろう。いつも平凡な生活に飽き飽きしていたじゃないか。
あんなことを。
事実だとすれば、俺は一体誰なんだ。考えても、次の瞬間覚えてないんじゃ、俺じゃない誰かだ。
奇妙なことはあった。時間の流れが変だったし、レンズ越しに見ているような、そういう感覚があった。
でも、本当に事実なんだろうか？誰かがそう思わそうとしてるだけなんじゃないのか？
まあ、どうでもいい。あと25秒もすればわかることだ。肉体に劇的な変化が起きて、あらゆる眠った精神を引き起こすだろう。本当の目覚めだ。

柵を乗り越えてそのまま飛び込んだ。
*** 家
テレビを見ていた。ドアベルが鳴った。8時頃だ。宅配を頼んでいない。面倒な感じがした。
開ける？
開けた。ドアの前には見覚えのないスーツの中年の男が立っていた。
ああ、しまった、と思った。厄介な感じがする。

テレビの音量を少し下げて、そのまま無視した。
居留守だと明らかだからか、しばらくドアベルが鳴らされた後、静かになった。その後、この出来事について思い出すことはなかった。
*** 思い出せないこと
え、平川陽一のことについて聞きたい？
俺は昔のことをあまり覚えてないんですが。
昔からそうですよ。
よく幼少期のことを覚えていて、そういう話しをしてくる人いるじゃないですか。
そういう人とはまったく話しが通じなかったですね。
中学生のころっていうと、今から20年以上前のことでしょう。
俺は3年前のことですら怪しいですよ。

とにかくその時期になにを考えてるかってことが思い出せないんです。
本とか映画とかニュースの出来事とかは割合覚えてるけど、個人的な出来事になるとね。
あまり忘れるんで日記をつけてるんだけど、後から見るとまったく自分だって思い出せないんだよ。
何の話しだったっけ。ああ平川のことか。

何か事件でも起こしたんですか。
ああ、自殺。
正直いって昔のことすぎて、何にも実感わかないですね。
もちろん悲しいとは感じますけど。

で、一応裏取りしてると。
そういう調査って中学の関係まで広げるんですね。
あいつも関東だったよな。あ、東京の方出てきてたんだ。
だから俺にも一応来たと。
*** 仲が悪かったこと
どんな人間だったかって？
まず性格的なところをいうと、そんなに善良な人間じゃなかったってことかな。
ちょっと言いづらいけど。
俺らの住んでたところは九州の端の片田舎だったんだけど、大体田舎の人って聞いて想像するのって素朴な人じゃない。
悪い人なんかいないから鍵もかけないような暮らし、みたいなの想像すると思う。
大体それは合ってると思う。でも平川はそうじゃなかったんだな。
ワルってわけでもなかったんだけど、とにかく意地が悪いやつではあったよ。
陰口ばっかりっていうかさ。俺がいないときでは俺の陰口を言ってるだろうな、てのがわかるの。

最初出会ったころは意気投合したというか、仲よく遊んだものだけど、次第に話さなくなっていったね。
ゲームとか漫画の趣味が合ったんだ。
片田舎の学校で人数が少なかったから割とよく顔を合わせてたんだけど、最後の方はほとんど話すことはなかったかな。
卒業してからは会ってないね。中学の連中で集まっても、そいつだけ呼ばれなかったりしてさ。同時に俺が呼ばれてなかっただけかもしれないけどね。

家族の関係？
聞いたことないなあ。家へ遊びに行ったことはあるけど、普通の家庭に見えたかな。たしか家は広かったかなあ。

何か印象的な出来事はあるかって？

いやに細かく質問するけど、ほんとに単なる自殺なの？
こういうふうに警察が来ることもあまりないと思うけど。
まあ、教えてくれないよね。

そうだな、話してるうちに思い出してきたよ。
あいつを家に読んだときに金がなくなってたことがあったな。
中学生だからせいぜい3000円くらいのものだけど。
そのときは考えもしなかったけど、今思うとあいつが盗んでたのかもなあ。
とにかく平和な田舎にまったく合わないくらい、底意地の悪い人間ではあったね。
*** 出来事の回想(承)
あとは…探検のことかな。
当時近くの地区に建物があって、そこに入ってみたことがあるんだ。
廃墟とまではいかないけど、明らかに人は住んでないくらいの建物にさ。
*** 警察(転)
遺書で、出来事の詳細が綴られていた。
だが、詳細な事実を言われると思い出す。深く後悔する。
*** 刑事の所感(解説)
- 社会のつながりがなくなっていたため、外部記憶の欠損
- 明確に認識すると記憶は回復する。たしかに存在するが思い出せないだけ。後悔する
- 気にかけてくれる人は誰もいない、と思ってたけどあいつにもいたはずだ
- 聞き取りをしてみると、けっこう印象深い人物として挙げられていたよ
- 人のネットワークが記憶を維持させる
*** memo
空白の記憶期間がある。
昔の記憶が出てこない。自分自身が誰かわからなくなることがある。
死んだ友人のことを思い出す。
