:PROPERTIES:
:ID:       7e85e3f3-a6b9-447e-9826-307a3618dac8
:END:
#+title: org-mode
* 概要
org-modeは[[id:1ad8c3d5-97ba-4905-be11-e6f2626127ad][Emacs]]の機能の1つ。
独自のマークダウン形式.orgを扱うためのインターフェースを提供する。
Emacsのkiller appの一角で、根強い人気がある。
- プロジェクト管理
- 脚注
- PDFをはじめ各種形式への変換
* Memo
** pdf閲覧
読書をEmacsでしたいときはpdfから変換する。あまりEmacs関係ない。

#+begin_src shell
  sudo apt-get install pdftotext
  pdftotext text.pdf
#+end_src

あるいは、HTMLに変換してewwで閲覧すればいい可能性がある。
** 外観設定
[[id:1ad8c3d5-97ba-4905-be11-e6f2626127ad][Emacs]]はテキストエディタなので、文字表示のほとんどは等幅フォントだ。が、
org-modeでは自然言語の文章なので、幅の違うフォントのほうが読みやすい。

[[https://zzamboni.org/post/beautifying-org-mode-in-emacs/][zzamboni.org | Beautifying Org Mode in Emacs]] の設定がとても良い。

- M-qでインデントの形に文章を整形する
- variable-pitch-modeが可変幅にするmode
- variable-pitch-modeだけだとコードブロックも可変になっちゃうので、コードブロックなどのfaceも変更する
** org-alertで通知する
[[https://github.com/spegoraro/org-alert][spegoraro/org-alert: System notifications of org agenda items]]
org-alertでDEADLINEが近い見出しを通知できる。
期限設定していても、通知されなければ忘れる。
スケジュール管理に使うのであれば必須か。
** babelのヘッダーを挿入する
ヘッダーでbabelの実行結果のオプションを変えることができる。

#+BEGIN_SRC org
,#+BEGIN_SRC emacs-lisp :result outputs
(concat "hello" "world")
,#+END_SRC
#+END_SRC

で実行すると標準出力が挿入される。

手書きは忘れやすいのでコマンドでやる。
コードブロック上で ~C-c C-v j~ :: ~org-babel-insert-header-arg~ 。

わかりやすい説明。
[[http://misohena.jp/blog/2017-10-26-how-to-use-code-block-of-emacs-org-mode.html][org-modeのコードブロック(Babel)の使い方 | Misohena Blog]]
** babelで結果をそのまま表示する
適用させたい見出しレベルのproperty内で、↓追加する。
#+begin_src shell
:header-args+: :results output
#+end_src

動作の違い。

#+begin_src ruby
[1, 2]
#+end_src

#+RESULTS:
| 1 | 2 |

#+begin_src ruby :results output
p [1, 2]
#+end_src

#+RESULTS:
: [1, 2]

** org-protocolの設定
:LOGBOOK:
CLOCK: [2021-09-26 Sun 09:45]--[2021-09-26 Sun 09:55] =>  0:10
:END:

- [[https://github.com/sprig/org-capture-extension][sprig/org-capture-extension: A Chrome and firefox extension facilitating org-capture in emacs]]
Chrome拡張としてある。ここのReadmeに書いてあるコマンドを実行する。

- emacsclientをorg-protocolのハンドラとして登録する。たぶんプロトコルと対応するアプリケーションを選ぶ、という処理だろう。httpのときはブラウザを起動する、みたいな。
#+begin_src shell
cat > "${HOME}/.local/share/applications/org-protocol.desktop" << EOF
[Desktop Entry]
Name=org-protocol
Exec=emacsclient %u
Type=Application
Terminal=false
Categories=System;
MimeType=x-scheme-handler/org-protocol;
EOF
#+end_src

そして↓。Linux MintでもOKだった。

#+begin_src shell
update-desktop-database ~/.local/share/applications/
#+end_src

OSの設定は完了。
Emacsの設定を追加する。
template名をちゃんと設定しないと、起動しない。

#+begin_src emacs-lisp
(setq org-capture-templates `(
    ("p" "Protocol" entry (file+headline ,(concat org-directory "notes.org") "Inbox")
        "* %^{Title}\nSource: %u, %c\n #+BEGIN_QUOTE\n%i\n#+END_QUOTE\n\n\n%?")
    ("L" "Protocol Link" entry (file+headline ,(concat org-directory "notes.org") "Inbox")
        "* %? [[%:link][%:description]] \nCaptured On: %U")
))
#+end_src

Chromeに拡張機能をインストールしてクリックすると、Emacsが立ち上がる。
** メモを取るのにはorg-captureを使う
** エクスポートしないタグ
~C-c C-q~ で ~noexport~ を指定するとその場所はエクスポートされない。
* Tasks
** TODO org-lintをCIで実行する
~org-lint~ をディレクトリに対して行う方法。
** TODO ファイルごとの形式を正規化する
見出しにけっこうズレがある。そういうのを検知するLintがあるはずだ。
** TODO clock table/agenda にリンクをつける
* Example
** チェックリスト
~C-c~ でチェックできる。
- 人としてやるべきこと [1/3]
  - [X] 盆栽に水をやる
  - [ ] 子孫に美田を残す
  - [ ] 借金を返す
** 脚注
これが脚注[fn:1]である。
定義はどこに書いてもいい。
出力時にはFootnotesのアウトラインが作られてそこに挿入される。

[fn:1] The link is: https://orgmode.org
* Reference
** [[https://orgmode.org/manual/Results-of-Evaluation.html][Results of Evaluation (The Org Manual)]]
** [[https://lists.gnu.org/archive/html/emacs-orgmode/2017-10/msg00227.html][Re: [O] Lint multiple files at once]]
**  [[https://blog.jethro.dev/posts/org_mode_workflow_preview/][Org-mode Workflow: A Preview · Jethro Kuan]]
org-mode運用法。
** [[https://github.com/sprig/org-capture-extension][sprig/org-capture-extension: A Chrome and firefox extension facilitating org-capture in emacs]]
org-protocolの設定。
* Archive
** CLOSE exampleを完成させる
CLOSED: [2021-09-26 Sun 09:41]
どういう意味なのか、全く思い出せない。
ああ、org-modeの使用例のページを作るということか。
別にいらないだろう。実際の例で示せばいい。
** DONE org-captureでメモ元リンクを記録しないようにする
CLOSED: [2021-09-26 Sun 09:41]
** CLOSE org-pomodoro完了後メモを残すように設定を復活
CLOSED: [2021-09-26 Sun 09:42]
:LOGBOOK:
CLOCK: [2021-09-19 Sun 15:37]--[2021-09-19 Sun 16:02] =>  0:25
:END:

別に見ないから不要だろう。
