:PROPERTIES:
:ID:       a04ab4c3-a7de-4c73-8570-865b3db61ebb
:END:
#+title: chore
* 概要
再利用できそうな生活のメモをまとめる。
* 自己紹介で使うシリーズ
** 好きなゲーム
- [[id:7c01d791-1479-4727-b076-280034ab6a40][Simutrans]]
  - 鉄道会社経営シミュレーション
- Rimworld
  - コロニー運営シミュレーション
- Cataclysm - Dark Days Ahead
  - ゾンビの世界で生き残るローグライク
- Elona
  - RPGローグライク
- Factorio
  - 工場経営シミュレーション
** 好きな映画
カタカナばっかりだな。外国舞台の映画が好きな傾向。

- アウトブレイク
- ボーンシリーズ
- トランスフォーマー(1, 2)
- ハリーポッター
- インセプション

** 好きなアニメ
- さよなら絶望先生
- 攻殻機動隊
- 交響詩篇エウレカセブン
** 好きな食べ物
- 数の子
- ラーメン
- 油そば
** 嫌いな食べ物
- 脱脂綿
- ティッシュ
- チョコミント
** 好きな作家
- 村上龍
** 好きな芸能人
- 伊集院光
** 好きな歌手
- ミスチル
- 大槻ケンヂ
** 余暇の過ごし方
- コード読み書き
- 環境改善([[id:1ad8c3d5-97ba-4905-be11-e6f2626127ad][Emacs]]、[[id:32295609-a416-4227-9aa9-47aefc42eefc][dotfiles]])
- 映画鑑賞
- ゲーム
** 小学生のとき
GBA/DS/Wii/PS2/PSP。PS3やXBOXも出てたけど、買えなかった。

- 伝説のスタフィー
- 星のカービィ
- ポケモン
  - ルビーサファイア、ダイヤモンドパール。
- ラチェット&クランク1〜4
- 鬼武者3
- サルゲッチュ3
- ボンバーマンランド
- グランドセフトオート サンアンドレアス
- 大乱闘スマッシュブラザーズX
- Wii Fit
- もっと脳を鍛える大人のDSトレーニング
- 漢字検定DS
- 喧嘩番長4
- 箱庭諸島
- HISTNAGE
- ドラゴンクエスト8
- ドラゴンクエスト5
- エクスターミネーション
- Y氏の隣人
- ハウルの動く城
- パワポケ9~12
- デルトラクエスト
- ダレン・シャン
- おいでよどうぶつの森
- セブンスタワー
- 火の鳥
- ブラックジャック

** 中学生のとき
PCにはまり始める。

- モンスターハンター3rd
- バイオハザード4
- ザ・コンビニ3
- 少年ヤンガスと不思議のダンジョン
- ゲーム発展途上国
- らんだむダンジョン
- ウォーロック
- Simutrans
- OpenTTD
- Phun
- Minecraft
- ロマンシングサガ
- Trick
- SPEC
- ケイゾク
- ハリーポッター
- 1週間中国を旅行した

** 高校生のとき

- ひぐらしのなく頃に(PS2)
- Elona
- Linux
- Emacs
- Perl
- Freeciv
- 年1回台湾を旅行した

** 大学生のとき
- Steamでゲームをやるようになる
- スカイリム
- Factorio
- Simutrans
- 三大電波ゲー
- 村上龍
- ひぐらしのなく頃に(原作PC)
- 伊集院光 深夜の馬鹿力
- Cataclysm - Dark Days Ahead
- 中国に留学
- 坂本龍一のアルバム esperanto
- The Prodigy
- さよなら絶望先生
- 大槻ケンヂ
- ひとかた
** 社会人
- 交響詩篇エウレカセブン
- いじめるヤバい奴
* 持ち出しリスト
- 耳栓
- アイマスク
* Best Goods
** _
買って最高だったもの。
何らかの理由で失ったときに元の環境へ戻せるために書く。
** キーボード Realforce * 2
2台置いて、片手ずつで使っている。肩こりがない。
** ディスプレイ 4K モバイルディスプレイ + グラボ
15.6型の4Kモバイルディスプレイ。特定のメーカーが良いというのはない。

フォントの綺麗さを最優先している。 4Kでスケーリング2倍は最高に綺麗(作業領域はHDと変わらなくなる)。同じ解像度だと画面が小さいほどピクセルは小さくなるので、美しくなる。

4K表示はそれなりにマシンパワーを使うようで、ある程度のグラフィックボードがないと動きが遅くなる。
** ノイズキャンセリングヘッドホン
SONY WH-1000XM3 を使っている。

ノイズキャンセリングモードをオンにしたときの静寂がすごい。
部屋ってこんなにうるさかったんだ、とわかる。マシンのファンの回る音、エアコンの音、隣のビルのドアを占める音、夜になると聞こえる謎の重低音、冷蔵庫の音…が消えた。静寂を楽しむために音楽を何も流さずにヘッドホンつけるレベル。

大学から一人暮らしを初めて以降、音に対して神経質な問題が常にあり、いくつかの策を試したがうまくいっていなかった。このノイズキャンセリングヘッドホンにより問題は完全に解決した。間違いなく人生を変えた買い物。

⚠重要なこと: いくつかの挙動はスマートフォンアプリを通じて設定できる。初期設定ではBluetoothに接続してないと5分で電源が切れる挙動は変えられる。これを知らず接続だけして音楽は流さない、という使い方を半年くらいしていた。接続しなくても電源を切らないように設定できる。
** 耳栓
寝るときは耳栓してると安眠できる。最初はいろんなタイプの耳栓が1セットずつ入っているパックがあるのでそれを買ってよさそうなものを試した。サイズや柔らかさが合っているかによって長くつけやすさが変わる。

[[https://www.amazon.co.jp/-/en/gp/product/B00L0507PW/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1][Amazon.co.jp: MOLDEX Disposable Ear Plugs without Cord, : Health & Personal Care]]
** アイマスク
暗くしたいというより、目の疲れが取れやすい。起きたときに目が乾いているのを防げる。特に冬。
** Apple Magic Trackpad
スクロールのために使用。これでないとパソコンで長時間の読書ができない。読書中ずっと触るものであるので、自然な姿勢で使えるようにする必要がある。微調整がかなり効き、大量のスクロールも可能。手触りが良い。

いくつも試してきたが、最終的にApple Magic Trackpadに落ち着いた。互換性を心配したが、[[id:7a81eb7c-8e2b-400a-b01a-8fa597ea527a][Linux]]でも問題なく使える。

- マウスのホイール
  - 指が痛くなる
  - 微調整が効かない
- ボリュームノブ
  - 使いにくい。横方向の回転は自然な動きでない
  - 微調整が効かない
- ワイヤレス片手マウス
  - 結局ホイールで指が痛い
  - 手を机に置かなくていいので姿勢の自由度が高い
  - トリガーボタンをスクロールに割り当てられれば良さげ
- フットペダル
  - 全く微調整が効かない
  - 脚を常に置くのが面倒
  - 間違えて押す
- コントローラ
  - トリガーボタンをページ送りにして使用
  - 押し心地はかなりいい
  - 両手で持たないといけないのが致命的

マウスのスクロールは腱鞘炎になりやすく、スクロールの精度もあまりよくない。何百ページもあるときつい。トラックパッドだと微細な操作と大きな操作が両方できるので、読書に向く。さらに操作の自由度が高いので腱鞘炎になりにくい。
** 加湿器
冬に目が乾くのを防ぐために使う。
** LAN切替器
集中したいときに良い。
* ローカル環境でのマルチプレイ
ローカル環境でPCマルチプレイゲームをするとき(年末とか)毎回困るのでメモ。年末など親戚があつまるときに、同年代の人とやることがない。ゲーム機とかはないので、毎回パソコンでなにかやろうとするのだが、パソコンのゲームにはローカルでできるものが意外となくて困る。

一番良いのは、人数分のマシンを用意して、オンライン対戦にすること。多くの種類のゲームが楽しめる。準備。

- Steamクライアントを準備しておく。
- ゲームもダウンロードしておく。時間がかかるので、前もって準備する。
- コントローラを用意しておく(画面分割できる類のゲームのときは)。キーボード1つでできるのもあるが、多くない。

* 部屋の条件
防音性を重視する。

- 防音性
  - 鉄筋コンクリート造
    - 特に壁式構造は内壁も鉄筋コンクリートである可能性が高くなる。
    - ラーメン構造であった場合、内壁は木造と同等のことがある
  - ドアや窓の重さ。十分に防音性能があるか
  - 大きな道路や線路に面していない
  - 玄関を隔てる空間がある
  - 玄関が道路沿いの方向についていない
  - 窓が小さい
  - 交差点近くでない
    - 逆に対策されていて静かな物件もあるよう
  - 細い道でもバイクの通りが多いことがある
  - 細い道でも距離が近いと、歩行者もうるさい
  - 部屋の中に引き戸がない(部屋を区切るドアがない)
  - 最上階
    - 上からの足音が存在しない、眺望が良い
  - 角部屋(通路の一番奥側)
    - 隣が少ない
  - 単身者向け
    - 人が多いほど騒音は増える。狭いところだと禁止されてるところも多い
  - エアコンの室外機との距離・位置関係。窓と室外機が隣接していると大きな騒音になる
- 便利さ
  - コンビニ/スーパー/飲食店が近い
    - 自炊しないため、近くに必要

よりよい条件。

- 良い景観
- 広い窓
- 川の近く
- 公園の近く

優先しない。

- 安さ
  - 部屋で過ごす時間が多いので、金をかける価値はあると考えている。嫌な思いをするより金で解決したい
- 交通の便
  - だが、結局駅の近くに店が集まっていて便利なので、矛盾はしている
- 広さ
  - 狭くてOK

* リモートワークを好む理由
- プログラミングを妨げないから
  - まともな部屋が用意されていて十分会社まで近いのであれば、毎日出社でも構わない。ただ、大部屋でプログラミングすることはひどく気を散らす。話し声、奥でちらつく人の姿はひどく気を散らす
- 出勤時間が不快だから
* 知りたかったことリスト
誰も教えてくれなかった、子供のうちに知りたかったことのリスト。

- 毎朝7時に家を出るのは小中高の間だけ
- 学校のほとんどの教師は生活のために働いているだけで、科学的な教育技能や、人にアドバイスできる人生経験を持っているわけではない
- 学生の頃からやっていることは非常に大きなアドバンテージであって、学生のうちではじめて遅いことは一切ない
- 大人は子供の思っているよりはるかに多くの金を持っている。遠慮する必要はない
- 何かスイッチがあって子供から大人になっているわけじゃない。成人年齢になる日とその前日で大して変わりがないように、大人と子供は大して変わらない
- 当然だと思っている景色のうちいくつかは永遠に失われるので、思い出せるように写真を撮っておかないといけない
- 最も大きい出費は家賃で、存在してるだけで金がかかる。いい職につかないと贅沢できないだけでなく、のたれ死ぬ

* みうらじゅん『「ない仕事」の作り方』名言
- [[https://www.amazon.co.jp/%E3%80%8C%E3%81%AA%E3%81%84%E4%BB%95%E4%BA%8B%E3%80%8D%E3%81%AE%E4%BD%9C%E3%82%8A%E6%96%B9-%E6%96%87%E6%98%A5%E6%96%87%E5%BA%AB-%E3%81%BF%E3%81%86%E3%82%89-%E3%81%98%E3%82%85%E3%82%93-ebook/dp/B07HWHKXR1/ref=sr_1_1?keywords=%E3%81%AA%E3%81%84%E4%BB%95%E4%BA%8B%E3%81%AE%E4%BD%9C%E3%82%8A%E6%96%B9&qid=1663141940&sprefix=%E3%81%AA%E3%81%84%E4%BB%95%E4%BA%8B%2Caps%2C272&sr=8-1][「ない仕事」の作り方 (文春文庫) | みうら じゅん | ノンフィクション | Kindleストア | Amazon]]

#+begin_quote
そこで必要になってくるのが、無駄な努力です。興味の対象となるものを、大量に集め始めます。好きだから買うのではなく、買って圧倒的な量が集まってきたから好きになるという戦略です。人は「大量なもの」に弱いということが、長年の経験でわかってきました。大量に集まったものを目の前に出されると、こちらのエレクトしている気分が伝わって、「すごい!」と錯覚するのです。
#+end_quote

#+begin_quote
なかったジャンルのものに名前をつけ、それが好きだと自分に思い込ませ、大量に集めたら、次にすることは「発表」です。収集しただけではただのコレクターです。それを書籍やイベントに昇華させて、初めて「仕事」になります。
#+end_quote

#+begin_quote
人はよくわからないものに対して、すぐに「つまらない」と反応しがちです。しかしそれでは「普通」じゃないですか。「ない仕事」を世に送り出すには、「普通」では成立しません。「つまらないかもな」と思ったら「つま……」くらいのタイミングで、「そこがいいんじゃない!」と全肯定し、「普通」な自分を否定していく。そうすることで、より面白く感じられ、自信が湧いてくるのです。
#+end_quote

#+begin_quote
趣味は突き詰めなければ意味がありません。対象そのものが好きだからぐらいでは困るのです。サッカーのあるチームが好きだ、アイドルのあのグループが好きだ、将棋を打つのが好きだ、イタリア料理を作るのが好きだ。すべて「そのまま」では何も生み出すことはできません。
#+end_quote

#+begin_quote
このポップにするための、手っ取り早い方法は、何にでも言葉の終わりに「ブーム」か「プレイ」をつけてしまうことです。たとえば一般的にマイナスだと思われている単語である「童貞」や「失恋」も、「童貞プレイ」「失恋プレイ」と呼んでみるのです。失恋したら、それは誰だってへこみます。食事ものどを通らないと言われます。しかしそのとき、落ち込んでいる自分の状態を「失恋プレイ」と呼んでみたら、どうでしょう? なんだかわざとやっているようで、気持ちが楽にならないでしょうか。
#+end_quote

#+begin_quote
皆さんも会社で仕事がつらいときや、家の家事が大変なときなど、「会議プレイ」「残業ブーム」「ゴミ捨てプレイ」などと心の中でつぶやいてみてください。
#+end_quote

#+begin_quote
映画館で、鑑賞後のエレベーターのあたりですぐに「つまんなかったね」と、一言で片付ける人がいます。それは才能と経験がない人です。映画は、面白いところを自分で見つけるものなのです。
#+end_quote

#+begin_quote
普通の仕事ではどうかわかりませんが、私は仕事をする際、「大人数に受けよう」という気持ちでは動いていません。それどころか、「この雑誌の連載は、あの後輩が笑ってくれるように書こう」「このイベントはいつもきてくれるあのファンにウケたい」と、ほぼ近しい一人や二人に向けてやっています。あるいは、その原稿や絵を最初に受け取る編集者を笑わせたいだけで書いてると言っても過言ではありません。知らない大多数の人に向けて仕事をするのは、無理です。顔が見えない人に向けては何も発信できないし、発信してみたところで、きっと伝えたいことがぼやけてしまいます。私の場合、そんな「喜ばせたい読者」の最高峰は誰かと言えば、それは母親です。
#+end_quote

#+begin_quote
どれだけ面白いことを考えても、人に知られなければ仕事ではありません。
#+end_quote

#+begin_quote
そこで、親に買ってもらった量でなく「好き」である熱量をどう表現するかばかりを考えて、たどり着いたのがスクラップでした。
#+end_quote

#+begin_quote
太郎さんの名言にはもうひとつ「なんだこれは!?」というものもあります。何もないところで発しても意味のない言葉です。しかし、自ら作品を作ってから「なんだこれは!?」と自分で驚く。これが実は、「ない仕事」の本質なのではないかと、私は思います。
#+end_quote

#+begin_quote
こんな仕事をしているので、私自身がさぞ自己主張が強いと思われがちですが、実はそうではありません。私が何かをやるときの主語は、あくまで「私が」ではありません。「海女が」とか「仏像が」という観点から始めるのです。
#+end_quote

#+begin_quote
そもそも何かをプロデュースするという行為は、自分をなくしていくことです。自分のアイデアは対象物のためだけにあると思うべきなのです。
#+end_quote

#+begin_quote
「自分探し」をしても、何にもならないのです。そんなことをしているひまがあるのなら、徐々に自分のボンノウを消していき、「自分なくし」をするほうが大切です。自分をなくして初めて、何かが見つかるのです。
#+end_quote

#+begin_quote
仕事をしているうえで、いちばん心がけていることといえば、無理してでも「不自然体」でいること、「レッツゴー不自然」です。
#+end_quote

#+begin_quote
「キープオン・ロケンロール!」言うは易いですが、やり続けることが大切なのです。何かを好きになるというのは、自分を徐々に洗脳して、長く時間をかけて修行をして、対象のことを深く知ってからでないと、長続きもしないし、人を説得することもできないということです。仏像展で一回仏像を見ただけで「仏像が好き」と感じたとしても、その気持ちはきっとすぐに冷めてしまうでしょう。そこから、コツコツと自分だけの「好き」を極めていかないといけない。奥が深い世界であればあるほど、軽く口にしてはいけないのです。
#+end_quote

#+begin_quote
人生どうなるかなんてわかりませんが、ひとつはっきりしていることは、他人と同じようなことをしていては駄目だということです。なぜかというと、つまらないからです。皆と同じ人気職種を目指し、同じ地位を目指すのは、競争率も高いし、しんどいじゃないですか。それよりも、人がやっていないことを見つけて達成するほうが、楽しいじゃありませんか。
#+end_quote
* 仕事場へのこだわりは能力と逆相関である可能性
:LOGBOOK:
CLOCK: [2022-10-26 Wed 01:37]--[2022-10-26 Wed 02:02] =>  0:25
CLOCK: [2022-10-26 Wed 01:05]--[2022-10-26 Wed 01:30] =>  0:25
CLOCK: [2022-10-25 Tue 22:50]--[2022-10-25 Tue 23:15] =>  0:25
:END:

何かを成し遂げるようなすごい人は、仕事場に無頓着に見える。

最近RedHatの開発者のPCまわりを紹介している動画を見た。多くの開発者は質素なものだった。乱雑な人、片付いている人は半々くらい。片付いているいっても普通の生活のレベルでいう「片付いている」で、モデルルームのようではない。1枚のディスプレイを使う開発者が半分で、残り半分は複数のディスプレイを使う。自分の観測できる範囲のすごい開発者も、ノートパソコン1台という人はけっこういる。使用マシンもそう高性能ではない、年式の経ったものが多い。

以前読んだ本で、偉大な作品を残した芸術家や作家の特徴となる習慣を探る、というのがあった。仕事をする場所(ソファやベッド、冷蔵庫の上で仕事する作家もいた)や、昼型/夜型、乱雑/整然について調査していた。結局人によってバラバラで、「成功要因」みたいなものはない、ということだった。開発者についても、同じ結論がいえるように見えた。

逆に、二流三流ほど要因や方法にこだわりたがるんじゃないかって、自分と重ねて感じている。PC周りを紹介しているブロガーやプログラマーはネットに多くいるので彼らを何人か観察してみる。自分の仕事環境に自信を持っていて、紹介しているように見える。それぞれのこだわりのグッズや家具があって、画像を多く含んだレビューを入れている。彼らは自分と同じように、職業人として大した特徴のない平凡な人々に見える。

- HHKB
- 複数のディスプレイ
- ゲーミングチェア
- Mac
- ディスプレイライト

は、驚くほど出てくる。[fn:1]

デスク周りへのこだわりはプログラマとしての能力と逆相関に見える。本当は好きじゃないから少しでも快適にすることでなんとかしようとしているんじゃないか。だから、もし机周りを買い換えて *生産性* を上げよう、とよく考えるなら注意したほうがいい。コンピュータやソフトウェアそのものに興味がないってことを示している可能性がある。

[fn:1] 単にみんながいいっていう理由で選ばれているように見える。

* Tasks
* Reference
* Archives
