:PROPERTIES:
:ID:       0862ffbd-e509-4731-a80b-ba4d71d2a15a
:END:
#+title: bookmarks
* 概要
各ノートに分類できないブックマーク集。

リンクを辿らずとも内容がわかるようにすること。
* Memo
* Tasks
** TODO [[http://archive.linux.or.jp/JF/JFdocs/Unix-and-Internet-Fundamentals-HOWTO/][The Unix and Internet Fundamentals HOWTO]]                      :Read:
コンピュータやシステムに関する、実用的な基礎知識の解説。
** TODO Dom document
DOMのドキュメント。日本訳もある。
- [[https://dom.spec.whatwg.org/][DOM Standard]]
** TODO Martin Fowlerの和訳
リファクタリング手法で有名な人のブログ記事の、和訳リポジトリがある。

- [[https://bliki-ja.github.io/][Martin Fowler's Bliki (ja)]]
** TODO Practical Scheme
- [[http://practical-scheme.net/index-j.html][Practical Scheme]]
* DONE [[https://www.oreilly.co.jp/books/9784873119656/][O'Reilly Japan - Googleのソフトウェアエンジニアリング]]           :Read:
CLOSED: [2022-02-12 Sat 17:36] DEADLINE: <2022-02-25 Fri>
:LOGBOOK:
CLOCK: [2022-02-12 Sat 17:19]--[2022-02-12 Sat 17:36] =>  0:17
CLOCK: [2022-02-12 Sat 16:33]--[2022-02-12 Sat 16:58] =>  0:25
CLOCK: [2022-02-12 Sat 15:55]--[2022-02-12 Sat 16:20] =>  0:25
CLOCK: [2022-02-12 Sat 14:09]--[2022-02-12 Sat 14:34] =>  0:25
CLOCK: [2022-02-12 Sat 13:27]--[2022-02-12 Sat 13:52] =>  0:25
CLOCK: [2022-02-12 Sat 12:14]--[2022-02-12 Sat 12:39] =>  0:25
CLOCK: [2022-02-12 Sat 11:43]--[2022-02-12 Sat 12:08] =>  0:25
CLOCK: [2022-02-12 Sat 11:01]--[2022-02-12 Sat 11:26] =>  0:25
CLOCK: [2022-02-11 Fri 17:47]--[2022-02-11 Fri 18:12] =>  0:25
CLOCK: [2022-02-11 Fri 16:57]--[2022-02-11 Fri 17:22] =>  0:25
CLOCK: [2022-02-11 Fri 15:28]--[2022-02-11 Fri 15:53] =>  0:25
CLOCK: [2022-02-11 Fri 08:24]--[2022-02-11 Fri 08:49] =>  0:25
CLOCK: [2022-02-11 Fri 07:51]--[2022-02-11 Fri 08:16] =>  0:25
CLOCK: [2022-02-10 Thu 22:35]--[2022-02-10 Thu 23:00] =>  0:25
CLOCK: [2022-02-10 Thu 10:20]--[2022-02-10 Thu 10:45] =>  0:25
CLOCK: [2022-02-10 Thu 09:16]--[2022-02-10 Thu 09:41] =>  0:25
CLOCK: [2022-02-04 Fri 09:37]--[2022-02-04 Fri 10:02] =>  0:25
CLOCK: [2022-02-01 Tue 22:39]--[2022-02-01 Tue 23:04] =>  0:25
CLOCK: [2022-02-01 Tue 22:06]--[2022-02-01 Tue 22:31] =>  0:25
CLOCK: [2022-01-31 Mon 10:40]--[2022-01-31 Mon 11:05] =>  0:25
CLOCK: [2022-01-31 Mon 10:09]--[2022-01-31 Mon 10:34] =>  0:25
CLOCK: [2022-01-30 Sun 11:31]--[2022-01-30 Sun 11:56] =>  0:25
CLOCK: [2022-01-30 Sun 10:53]--[2022-01-30 Sun 11:18] =>  0:25
CLOCK: [2022-01-30 Sun 10:27]--[2022-01-30 Sun 10:52] =>  0:25
CLOCK: [2022-01-29 Sat 14:07]--[2022-01-29 Sat 14:32] =>  0:25
CLOCK: [2022-01-29 Sat 13:24]--[2022-01-29 Sat 13:50] =>  0:26
CLOCK: [2022-01-10 Mon 17:14]--[2022-01-10 Mon 17:39] =>  0:25
CLOCK: [2022-01-10 Mon 13:56]--[2022-01-10 Mon 14:21] =>  0:25
CLOCK: [2022-01-10 Mon 10:42]--[2022-01-10 Mon 11:22] =>  0:40
CLOCK: [2022-01-09 Sun 23:18]--[2022-01-10 Mon 00:22] =>  1:04
CLOCK: [2022-01-09 Sun 19:26]--[2022-01-09 Sun 21:29] =>  2:03
:END:
- (全)101, 117, 171, 188,  213, 225, 235, 240, 261, 363, 401, 500, 559, 595, 633, 685
読書メモ。
** 1. ソフトウェアエンジニアリングとは何か
- 時間と変化
- スケールと発展
- トレードオフとコード

プログラミングエンジニアリングとソフトウェアエンジニアリングは異なる。

ソフトウェアエンジニアリングは、生産したコードを有用性のある稼働期間中は保守するように、プログラミングを拡張する。
稼働期間に合わせた戦略を取ることが必要。
繰り返し実行しなければならない全タスクは、スケーラブルであるべき。
** 2. 文化
天才神話。偉業に対して、1人の人間の結果と考えがちだ。
天才ではないので、自分のキャリアを活かすか殺すかは他者とうまく共同作業を行うかにかかっている。
最初に正しい対象への作業に取り掛かっていること、作業を正しく行っていること、以前に同じ作業が行われていないことを確認しなければならない。早めに気づかないと、無駄な作業になる。

DevOpsのゴール。
- なるべく早期にフィードバックを得よ
- なるべく早期にテストせよ
- なるべく早期にセキュリティと本番環境について考慮せよ

ソフトウェアはチームによって書かれているので、広帯域のフィードバックを得られるように、同じオフィスで働くことが望ましい。個人用オフィスでなく、巨大な1つの部屋でもなく、数人の部屋で作業を進めるのがよい。

自分の秘密の発明を隠れて準備しているようでは、世界を変えたりコンピュータ利用者を歓喜させることはできないだろう。他者とともに仕事をしなければならないのである。ビジョンを共有しよう。苦役を分担しよう。他者から学ぼう。
成功したソフトウェアで、1人で書かれたものは存在しない。

共同作業の三本柱。
- 謙虚
- 尊敬
- 信頼

批判とは個人攻撃のようなものであることは滅多になく、通常はプロジェクトを改善するプロセスの一部分にすぎない。その秘訣は、誰かの創造的成果についての建設的批判と、誰かの人格へのあからさまな攻撃との間の差異について、自分(ならびに周囲の者)の理解を徹底することだ。
たとえばコードレビューを取り入れるとき、いきなり始めるのでなく先に議論するだけでも理解が深まる。巧妙な手段が必要。

建設的批判を礼儀正しく行うことを学ぶ。誰かを真に尊敬するなら、機転の利いた、助けになる言い方を選ぶようになるだろう。
[[id:bb71747d-8599-4aee-b747-13cb44c05773][OSS]]でのやりとりを見ているとよく見る。参考になりそうだ。

ましな言い方の一例。
#+begin_quote
やあ、ここのこの部分の制御フローに混乱しちゃって。xyzzyコードパターンならここをもっと明確にして保守しやすくするかもと思うんだけどどうかな
#+end_quote

相手が間違っているのではなく、自分がコードを理解するのに苦労しているだけなのだ。
議論は、誰かの価値やコーディングスキルではなく、コード自体に的を絞った状態を保つ。

Googleには、モットー「失敗は選択肢の1つである」というものがある。ときどき失敗するようなことがなかったとすれば、十分に革新的ではないか、十分にリスクを取っていないかのどちらかであるということが、広く認められているのだ。
** 3. 知識共有
学びを阻む課題。
- 心理的安全性の欠如
- 情報の孤島群 :: コミュニケーションや共有リソースを利用しない組織の、知識の断片化
- 情報の断片化 :: 各孤島が全体像の不完全版をもつ
- 情報の重複 :: 各孤島が自前の方法を再発明している
- 情報のスキュー :: 各孤島が自前の方法をもつ
- 単一障害点 :: 決定的な情報が1人の人物からのみ得られる場合に生じうるボトルネック。短期的効率に向けて最適化されていて、長期的スケーラビリティが劣化する。
- 全か無かの専門知識 :: 全て知っている者と初心者の2種類に分断され、中間の者がほとんどいないような集団。メンタリングやドキュメンテーションを通じた新たな専門家の育成に時間をかけない場合、この問題が悪化することが多い。
- 猿真似 :: 理解せずに真似すること
- 幽霊の出る墓場 :: 何かがおかしくなるかもと恐れて触れたり変更するのを皆が避ける場所。

ソフトウェアエンジニアリングは、複数バージョンのプログラムの複数人による開発として定義できる。コードは製品開発の一部にすぎない。

ドキュメント化された知識は専門家よりスケーラブルで、チームのみならず全組織にまでスケールする。

解決案。
- 心理的安全性
- メンター制度
- 質問する
  - 行き詰まったときに助けを求める。1人で切り抜けようとしたりしない。
- 書き留める
- まず理解する
  エンジニアは、馴染みのないコード、言語、パラダイムについては特に、短時間でこれは駄目だという結論に飛びつく傾向がある。文脈を探し出して理解しなければならない。ガイドラインの背後にある理論的根拠について、読者の理解を助けるための文脈が明示的に含ませる。根拠を理解することで、それぞれで決定できる。
- 人間の専門家とドキュメント化されたリファレンスの双方から助けを得られるようにする

ドキュメントを更新する最良のタイミングは、学ぶときである。難しいところ、抜けていた部分の記憶が鮮明だからだ。
** 4. 公正のためのエンジニアリング
人種が考慮されておらず、致命的に間違った結果を表示するインシデントが複数件発生している。
** 5. チームリーダー入門
プログラマーがマネージャーになることを恐れる原因の1つは、達成したことが明確でないからだ。コード、ドキュメントの形として残ることがない。

新任のマネージャーが感じる衝動で最大のものは、積極的に従業員を管理するというものだ。これに対処する方法となるのが、「サーヴァントリーダーシップ」である。リーダーとしてできる重要なこと、執事が一家に気を配るのと似た形でチームに仕えることである、ということ。サーバントリーダーが行う管理は、チームの技術的健全性ならびに社会的健全性の両方の管理のみである。

伝統的なマネージャーは物事をやり遂げる方法を気にする一方で、優れたマネージャーはどんな物事がやり遂げられるのかを気にする(方法を見つけるのはチームに任せる)。

リスクを避ける常套手段となるのが、保守的に仕事をこなし小さめの成功事例に専念するという行動だ。

#+begin_quote
不可能なゴールの達成を目指すなら、失敗の可能性が高い。だが、不可能なことを達成しようとして失敗するなら、完遂できるのがわかっていることを試みたにすぎない場合に成し遂げたであろうことよりはるかに多くのことをきっと成し遂げるだろう
#+end_quote

リスクを取ることが許容される文化を育む良い方法は、失敗しても問題ないことをチームに認識させること。
失敗を、多くのことを非常にすばやく学ぶ方法とみなす。失敗を学びの機会として捉え、非難や問責のための機会として捉えない。かかっているものが多くないので、高速に失敗するのは良いことである。

リーダーのアンチパターンの1つ: 全員の友人になる。

受ける質問には感謝するように努めるべきだ。自分の決定や発言に疑問を呈する者がいるとき、たいていは自分のことをもっとよく理解しようとしているだけなのだということを思い出す。

平静を保つ。リーダーは常に舞台にいるようなもので、注目されているため挙動に注意しなければならない。
アドバイスを求めている者は、あなたに問題を解決してほしいわけではなく、問題の解決を手伝ってほしいのだ。それを行うには質問を尋ねることだ。

チームリーダが行う最も一般的なこと。合意形成。
満足度を追跡調査する。「何が必要かな」と尋ねる。
** 6. スケールするリーダー
長く取り組んできた者たちの目隠し(常識)を特定し、新しい戦略を検討する。

現時点で最良の答えのみが存在する。トレードオフを特定し、どうバランスを取るかの決定を補助する。

バス係数: プロジェクトを完全に破滅へ追い込むのに要する、プロジェクト内でバスに轢かれる者の人数。
いつでも立ち去れるようにする。自分が居合わせる必要なしに、曖昧な部類の問題を自動的に解決する組織を構築する。

チームに解ではなく、問題を担当させる。製品とは問題への解で、解の平均存続は短い可能性があるから。しかし問題はいつでも新鮮である。

すべてやろうとすると終わらない。緊急なものばかりやり、重要なものを達成できなくなる。
上位80％のタスクにのみ取り組む。最上位の20％へ厳密に入るボールだけ専念してやる。残り80％を落とすことを自身に明示的に許可する。

エネルギーを管理する方法を学ぶ。
- 「本物」の休暇を取る。メールや何かに確認せずに取れる休み。仕組みを構築しておくことが必須。
- つながりを断つことが大したことではないようにする。スマホにコミュニケーションアプリをインストールしているなら、仕事用プロファイルでいつでも切り替えられるようにする。
- 「本物」の週末休みも過ごす。仕事関係のコミュニケーション手段のつながりを断つとき効果がある。
- 日中に休憩する
- メンタルヘルスの日を取ることを自分に許す
** 7. エンジニアリング生産性の計測
メトリクス作成の指針: GSM。
- Goal :: 望ましい最終結果
- Signal :: 最終的な結果を達成したことを知る方法
- Metrics :: シグナルの代用品で、実際に計測可能なもの

この順に作成する。簡単に入手可能なメトリクスを使うと、それによって目標が決定してしまうため。

生産性の5つの構成要素(QUANTS)。
- コード品質
- エンジニアの注意
- 知的複雑性
- テンポと速度
- 満足

  生産性を計測する前に、結果が行動可能かどうかを問うべき。結果に対して何もできないならば、計測の価値はない。
** 8. スタイルガイドとルール
ルールは他のルールと同程度に有用でなければならない。たとえばgotoの利用を禁止する明示的ルールは必要でない。ほとんどのエンジニアは避けるので。
読者に向けて最適化する。書くのが簡単と、読むのが簡単、の2つの選択肢がある場合後者を選ぶ。読まれることのほうが多いからだ。

一貫性があることはときに拘束がきついように感じられる。しかし一貫性があれば、比較的少ない努力で比較的多くの仕事をやりとげるエンジニアが増える。

ガイダンス。やるべきこと。
** 9. コードレビュー
- 論理的な間違いやバグだけでなく、理解しやすさもテストしている
- 質問によって意図が明確になる。自分のコードをもっと明確に説明する必要がある
- 提出する際に良い変更説明を書く。短くわかりやすい要約
- 提出前に自動で検知できるようにする…たとえば変更行数が多すぎる場合は自動で却下されるなど
- 新しいコードやプロジェクトは、コードレビューとは別の設計レビューを経ることが求められる…グリーンフィールドレビュー。既存コードはブラウンフィールド
- コードレビューは、過去に既に行われた設計上の決定について討議するための時間ではない。そして提案されるAPIの設計を紹介するための時間ではない
** 10. ドキュメント
- ドキュメンテーションの作者は、直に恩恵にあずかれるわけではない。すぐに利益になるテストと違い、ドキュメンテーションは通常、より多くの労力が必要で、後になるまで作者に明確な利益をもたらさない
- テストへの投資と同様に、ドキュメンテーションに行われる投資は、長期的には回収できる。ドキュメントが書かれるのは1度だけだが、読まれることは何百回とある
- ドキュメンテーションはコードのようなものである
- ドキュメンテーションの指針:
  - 従うべき内部的なポリシーかルールを持つ
  - ソースコントロールシステムの管理下に置かれる
  - そのドキュメントを保守する責任を持つ明確なオーナーシップ(管理人)がある
  - 変更についてのレビューを経る(ドキュメント化対象のコードとともに変更される)
  - コード内でバグが追跡されるように、ドキュメントの問題が追跡されるようにする
  - 定期的に評価される(ある点ではテストされる)
  - 可能なら、正確性や鮮度等の面で計測される
- GoogleがWikiからバージョン管理のドキュメントに移行した話。重複、未更新によって貧弱になっていた。ドキュメントをソースコントロール下に移すのは論争の的になった。作成の障壁が高くなるので品質が劣化すると確信していた。しかしそうはならず、ドキュメントの品質は上がった
- ドキュメンテーションの類型
  - コードのコメントが含まれたリファレンスドキュメンテーション
    - APIコメントと、実装コメントの2つを分けて考える
    - ファイルコメント。ヘッダに書かれるコメント
    - チュートリアルドキュメント
  - デザインドキュメント
  - チュートリアル
  - ランディングページ
  - 概念的ドキュメンテーション
    - 概念ドキュメントは一般的な利用法に専念し、稀なり用法や副作用はリファレンスに任せるべき
- 対象読者を意識する
  - 経験レベル
  - ドメイン知識
  - 目的、エンドユーザ
- ドキュメントレビューの三類型
  - 技術的レビュー(正確性)
  - 対象読者レビュー(明確性)
  - 作文法レビュー(一貫性)
- 優れたドキュメンテーションの要素
  - 完全性
  - 正確性
  - 明確性
- まとめ
  - ドキュメンテーションは長期的・スケールの観点から見て重要である
  - ドキュメンテーションの変更は、既存の開発者ワークフローを活用すべき
  - ドキュメンテーションは1つの目的に専念したものにとどめておかなければならない
  - ドキュメンテーションは対象読者に向けて書くべきであり、自分自身のために書くべきではない
** 11. テスト概観
- テストの信頼性を保つことは非常に重要
- テストはできるだけ小さい粒度でやる。早くて確実性が高いから。
- 蓄積するとアイドル時間が増えるため、sleepは使わない
-  テストがまだ規範となっていない時期があった。規範とするために、テストカバレッジやレイテンシーなど、プロジェクトの健全性についてのメトリクスを継続的に収集した。すべてのチームがスコアを自動的につけられた
  - 開発体制について強制しなかった。成功する思想は広まるものであるというのが我々の信念であり、したがって専念すべき点は、成功を実証してみせることだった
- 自動テストは変化を可能とするための基盤となる
- テストがスケールするためには、自動化が必要
- テストも文化であり、変えるのには時間がかかる
** 12. ユニットテスト
- 規模が小さく、理解しやすい
- コード例を示せる
- 80％がユニットテスト、20％がより広範囲となるテスト
- 4つの変更
  - 純粋なリファクタリング
  - 新機能
  - バグ修正
  - 挙動の変更
- 公開API経由のテストは実装詳細のテストより優れている
  - ユーザの使い方に近いから
  - 変更に対して強いから
- まとめ
  - 変化しないテストを目指す
  - 公開API経由でテストする
  - 相互作用でなく、状態をテストする
  - メソッドではなく、挙動をテストする
  - 挙動に重点を置いてテストを構成する
  - 挙動にちなんでテストに命名する
  - テストにロジックを入れない
  - 明確な失敗メッセージを書く
  - テスト用コードを共有する場合、DRYよりDAMPに従う
** 13. テストダブル
- できるだけ本物の実装を使い、テストダブルは使わない。本物の実装と同期が取りにくいから
- 高速性、コスト面で必要な場面に使うのが効果的
- インタラクションテストはテスト対象システムの実装詳細を公開するため、脆いテストになりがち
** 14. 大規模テスト
- ユニットテストで捉えられない種類の問題を発見するのに必要である
- 開発者に対して優しいテスト
  - 信頼性がある
  - 高速である
  - スケーラブルである
- 開発の最初の数日以内にユニットテストを構築してテストピラミッドの形に向けて進み、その後は自動インテグレーションテストの導入と手動のエンドツーエンドテストからの脱却によりテストピラミッドを完成させることが、長期的な健全性のためには決定的に重要である
- 大テストの種類
  - 1つ以上のバイナリの機能テスト
  - ブラウザーとデバイスのテスト
  - パフォーマンス、負荷、ストレスのテスト
  - デプロイ設定のテスト
  - 探索的テスト
  - A/B差分(リグレッション)テスト
  - ユーザー受け入れテスト
  - プローバーとカナリア分析
  - 障害復旧とカオスエンジニアリング
  - ユーザー評価
- sleepとタイムアウトに頼るテストは、動かしてるサーバが高負荷になると失敗が連鎖する。なるべく使わない
** 15. 廃止
- 古いシステムには継続的な保守や専門知識が必要
- 周りのエコシステムから外れていくにつれて必要な作業が増える
- コードは債務であり資産ではない。コードが資産なら、時間を費やして旧来システムを止める必要がないから。正確にいうとコード自体は価値をもたらさないが、コードが提供する機能は価値をもたらす
- 多くのコードは、廃止することを前提にして設計されていない
- ユーザに対して出される非推奨の警告は、2つの属性を持っていなければならない
  - 行動可能性…何らかの関連する行動を実践面で実行できること
  - 関連性…警告に示された行動をユーザが実際に行う際に警告が表示されること
- 廃止プロセスに明確なオーナーが必要
** 16. バージョンコントロールとブランチ管理
** 17. Code Search
あまりにコードベースが巨大でローカルに展開できないので、自前のコードサーチツールを使っている。
もはや1つのサービスですごい。面白そう。
** 18. ビルドシステムとビルド哲学
スケールするビルド。
最初はシェルスクリプトで十分だったが、増える人員、異なる環境ではうまくいかなくなってくる。ビルド時間は伸びる。
原始的なビルドシステムではタスクベースである。依存を暗黙的に表現している。
現代的なビルドシステムは、依存を記述したビルドファイルを使う。並列実行、依存解決が可能になりスケールする。

ビルドシステムは、エンジニアリング組織の最重要部分である。
粒度の細かいモジュールはよくスケールする。
単一バージョンルール、明示的なバージョン管理。
** 19. GoogleのコードレビューツールCritique
システムの説明。あまり参考になるところはなかった。
** 20. 静的解析
成果を計測しないと、問題の修正ができない。
** 21. 依存関係管理
外部の依存にどう対応するか。
ダイヤモンド依存関係。同じライブラリの2つの異なるバージョンへの依存があるとき。
標準となっているセマンティックバージョニングの限界。

変更は分離された単体で見る限りは、破壊的でも、非破壊的でもない。
長期間サポートする計画なしに物をリリースしてはいけない。
** 22. 大規模変更
コード変更が500箇所以上編集を要するなら、手動で実行するより、コード変更生成ツールを学んで実行したほうが効率的である。
動的に型付けされた言語は、メンテナーにとって扱いが難しい。開発者の生産性を重視するとみなされる言語は、保守が比較的難しい傾向をもつ。
リファクタリングの伝統的モデルは、スケールが大きくなると破綻する。
自動化によって、ある技術的決定の不変性を再考することが可能になる。
** 23. 継続的インテグレーション
ビルドからリリースまでの様々な段階でアプリケーションの動作状態を保証でき、それによって、製品の品質と信頼性、ならびにチームの生産性を向上できる。
実際に存在する一般的な設定ファイルは全て、その設定と対応するコードと並んでテストを受けられるように、リリース候補の一部として昇格されるべき。

Googleの継続的デリバリーの定義。
リリース候補の継続的な組み立てと、それに続く、組み立てられたリリース候補に対する、一連の環境群を昇格していく中で終始行われるテスト。本番環境まで到達することもあれば到達しないこともある。

[[id:1658782a-d331-464b-9fd7-1f8233b8b7f8][Docker]]等のコンテナを利用すると、ローカル開発環境以降の各環境におけるRCの一貫性を強制するのに役立つ。同様に、[[id:81b73757-21b3-438c-ab65-680b5ad88a1b][Kubernetes]]等のオーケストレーションツールを利用すれば、各デプロイ間の一貫性を強制するのに役立つ。

品質と安定性のために頼るのは、たった1つの技術やポリシーではなく、テストのアプローチを多数組み合わせたものなのだ。
** 24. 継続的デリバリー
継続的デリバリー・アジャイル方法論は、長期的に変更のパッチを小さくすると、高い品質につながるというもの。
より速い方がより安全、といえる。

最終ゴールの途上でも独立して価値をもたらす様々な特徴。
- アジャイル性
  - 頻繁に、小さなバッチでリリースする
- 自動化
  - 頻繁なリリースで繰り返し生ずるオーバーヘッドを、低減するか除去する
- 分離
  - 変更を分離しトラブルシューティングを容易にするモジュール化アーキテクチャーを目指す
- 信頼性
  - クラッシュやレイテンシー等、健全性の重要指標を計測し、指標の改善を続ける
- データ駆動の意思決定
  - 品質を担保するために、健全性メトリクスにA/Bテストを適用する
- 段階的ロールアウト
  - 変更を、全ユーザーに向けてリリースする前に、少数のユーザーに向けてロールアウトする

信頼性のある継続的なリリースの鍵は、エンジニアが *全変更* を必ず「フラグで保護」することである。

明確な閾値を備えた、重要業績指標のメトリクスがあれば、たとえ完璧でない機能であってもリリースできるようになる。
- 速度はチームスポーツである
- 変更は分離して評価すべきである
- 現実をベンチマークとすべきである。デバイスの多様性とユーザベースの幅に対処するために、段階的ロールアウトを利用すべき。本番環境と似ていない人工的な環境では、後の段階での意外な問題につながる可能性がある
- 利用されるもののみをリリースすべきである。リリース済みのあらゆる機能について、その機能がまだ意味がありユーザにとって十分な価値を届けているか知るために、その機能のコストと価値を監視すべきだ
- 左に移すべきである。CIと継続的デプロイを通じ、すべての変更について、より高速でよりデータ駆動な意思決定を、早期に行えるようにすべきだ
- より速い方がより安全である。各リリースのリスクを低減しつつ、市場に投入するまでの時間を最小化するために、早期かつ頻繁に小さなバッチでリリースすべきだ
** 25. サービスとしてのコンピュート
コードを書いたあとは、実行するためにコンピュータが必要である。そこでハードウェアを買うか借りる。これがサービスとしてのコンピュートである。

組織が拡大し、製品が普及するにつれて、全ての軸が増加する。そのため、自動化が必要。
- 管理すべき別々のアプリケーションの数
- アプリケーションの実行が必要なコピー数
- 最大アプリケーションのサイズ

レプリケーションされたソフトウェア単位を説明する方法としての「  ペット対家畜」の類推。
システム内の何かに対し、その上でプログラムが動作するホストの名前がハードコードされているなら、プログラムのレプリカは家畜ではない。

2種類のジョブ。
- 提供ジョブ。常に起動して待ち受ける必要があるジョブ
- バッチジョブ。実行は一度きりで終了する

Googleは組織全体のために単一のインフラストラクチャーを有する。例: 各リージョンにつき1つ以上の少数の共有[[id:81b73757-21b3-438c-ab65-680b5ad88a1b][Kubernetes]]クラスター。管理コストとリソースコストにおける効率の向上がもたらせる。
- スケールするには、本番環境でワークロードを実行するための共通インフラストラクチャーを要する
- コンピュートソリューションは、ソフトウェアのために標準化され安定した抽象化と環境を提供できる
- ソフトウェアは、分散マネージドコンピュート環境に適応しなければならない
- 組織のためのコンピュートソリューションは、提供される抽象化のレベルが適切なものとなるよう、思慮深く選択されるべきである
** まとめ
- ソフトウェアエンジニアリングの諸原則は、単に組織を効果的に運営する方法にとどまらず、ユーザーと世界全体にとっての責任をさらに果たしていく企業となる方法をめぐる原則となっている。
- 大多数の問題は、現在の問題に効くのみならず、技術的システムにいずれ起こる不可避の変化に耐える解決策を特定するために、一定レベルの決然とした機敏さを要する。機敏さこそが、光栄に浴してきたソフトウェアエンジニアリングチーム群に共通の資質である。
- 変化に対して反応して適応できなければならない。例:
  - 製品の方向性
  - 技術プラットフォーム
  - 基盤のライブラリー
  - オペレーティングシステム
* GitHub
** [[https://github.com/abcdw/rde][abcdw/rde: Tools for managing reproducible development environments. Mirror of https://sr.ht/abcdw/rde/]]
** [[https://github.com/htop-dev/htop][htop-dev/htop: htop - an interactive process viewer]]
* Essay
** [[https://www.amazon.co.jp/exec/obidos/ASIN/4122067375/hatena-blog-22/][Amazon.co.jp: 富士日記(上) 新版 (中公文庫 (た15-10)) : 武田 百合子: Japanese Books]]
リアルな日記。
** [[http://www-comm.cs.shinshu-u.ac.jp/david/papers/stories/japanese/hamming.pdf][あなたとあなたの研究]]
すごい実績を上げる科学者と、それほどでない科学者の違いはなにか。
** 知っておきたかったこと
人生の指針として保存用にコピーしておく。
[[http://practical-scheme.net/trans/hs-j.html][What You'll Wish You'd Known]]

#+begin_src
知っておきたかったこと
--- What You'll Wish You'd Known
Paul Graham, January 2005
Copyright 2005 by Paul Graham.
これは、Paul Graham：What You'll Wish You'd Known を、原著者の許可を得て翻訳・公開するものです。

<版権表示>
本和訳テキストの複製、変更、再配布は、この版権表示を残す限り、自由に行って結構です。
(「この版権表示」には上の文も含まれます。すなわち、再配布を禁止してはいけません)。
Copyright 2005 by Paul Graham
原文: http://www.paulgraham.com/hs.html
日本語訳：Shiro Kawai (shiro ＠ acm.org)
<版権表示終り>

Paul Graham氏のエッセイをまとめた『ハッカーと画家』の 邦訳版が出版されました。
出版社の案内ページ Amazon.co.jp サポートページ

2005/01/22 翻訳公開
2005/01/24 水落毅様より誤記の訂正を反映
このエッセイは、ある高校の講演依頼を受けて準備したものである。 その高校のお偉いさん方が反対して、結局私の講演はキャンセルされたのだが。

こんど高校で講演することになったと言ったら、ぼくの友達はみんな 興味を持って尋ねてきた。高校生に向かってどんな話をするんだい。 だからぼくは逆に聞き返したんだ。君が高校生の時に、誰かがこのことを 教えていてくれたらなぁ、と思うことってあるかい。 そう聞くと、みんな自分のことを語りはじめたんだけれど、 だいたい誰も同じようなことを思っていたんだ。 そこで今日は、ぼくらがみんな、 誰かに教えてもらいたかったなあと思っていることを話そうと思う。

まず、高校にいるうちは知らなくてもいいことから始めよう。 人生で何を為すかってことだ。大人はいつも、君は人生において 何を成し遂げたいかって聞くものだから、答えを考えておかなくちゃ いけないなんて思っているんじゃないかな。 実は大人がこの質問をするのは、単に会話を始めるためなんだ。 君がどんな人間かを知りたくて、そしてこの質問をすればとにかく 君は何かを話し出すだろう。潮溜りのヤドカリを突っついて どんな反応をするか見てみるのと同じさ。

ぼくが高校生に戻ってこの質問を受けたとしたら、 まず何が可能かを学ぶことだと答えるだろう。 人生を賭ける仕事を選ぶのに急ぐ必要なんてない。 必要なのは、自分は何が好きなのかを発見することだ。 上手くできるようになりたいなら、そのことが好きじゃなくちゃだめだからね。

何が好きかを決めるのなんて一番簡単なことだと思うかもしれない。 でもやってみると、それはとても難しい。理由のひとつは、 仕事で実際にどういうことをしているかっていうはっきりしたイメージを 持つことが、多くの仕事では難しいからだ。例えば医者という仕事の実際は、 テレビで描かれるようなものじゃない。もっとも医者の場合は、病院で ボランティアをすれば本物の医者を見る機会が得られるけれどね [1]。

それどころか、今決して学ぶことが出来ない仕事っていうのもある。 今はまだ誰もやっていないような仕事だ。ぼくがこれまでの10年間でやってきた 仕事のほとんどは、ぼくが高校生の時には存在していなかった。 世界はどんどん変化しているし、変化のスピードも速くなってる。 こんな世界では、決まった計画を持つことはあまりうまくない。

それでも毎年5月になると、全国津々浦々の卒業式で決まりきった演説が 聞かれることになる。テーマはこうだ。「夢をあきらめるな。」 ぼくはその真意を知っているけれど、この表現は良いものじゃない。 だって、早いうちに計画を立ててそれに縛られることを暗示しているからね。 コンピュータの世界では、これに名前までついている。 「早すぎる最適化」というんだ。別の言葉で言い替えると「大失敗」ということだ。 演説ではもっと単純にこう言うべきだろうね。「あきらめるな。」

この言葉の真意は、士気を失うなってことだ。 他の人に出来ることを自分は出来ないと思っちゃだめだ。 それに、自分の可能性を過小評価してもいけない。 すごいことを成し遂げた人を見て、自分とは人種が違うと思うかもしれない。 しかも伝記ではそういう幻想はますます誇張される。伝記を書く人っていうのは 対象となる人物にどうしても畏敬の念を抱くものだし、物語の結末がわかっているから そこに至るまでの人生のできごとをまるで運命に導かれたように、 内なる天才が徐々に現れて来るように描きたくなるんだ。 実際のところ、もし16歳のシェークスピアやアインシュタインが君と同級生 だったとしたら、たぶん彼らは才能を現しているだろうけれど、それ以外は 君の他の友達とさほど変わらないはずだとぼくは思う。

こう考えるのは、おっかないことだ。彼らがぼくらと同じなんだとしたら、 彼らはすごいことを成し遂げるためにものすごい努力をしたってことになる。 そう思うのはこわいから、ぼくらは天才というものを信じたがるんだ。 ぼくらが怠けている言い訳ができるからね。 もし彼らが、魔法のシェークスピア属性やアインシュタイン属性のせいで 素晴らしいことを成し遂げたんだとすれば、ぼくらが同じくらい すごいことをできなくてもぼくらのせいじゃないことになる。

天才なんてない、って言ってるわけじゃないよ。 でも、二つの理論を選ぶときに、一方は怠惰であることを正当化するものだと したら、たぶんもう一方の理論が正しい。

ここまでで、卒業演説の「夢をあきらめるな」から、 「他の誰かに出来たなら、きみにも出来る」が彫り出せた。 でもこれはもっと彫り進めることができる。 生まれついての能力の差というものは多少はある。 過大評価されがちだけど、無くは無い。 例えば背が120cmしかない人がいつかNBAでプレーしたいんだと言った時に、 本当に頑張れば何でも出来るよというのは空々しく聞こえるだろう。 [2]

だから、卒業演説はこんなふうになるだろう。 「きみと同じ能力を持つ誰かができることなら、きみにもできる。 そして自分の能力を過小評価しちゃいけない。」 でも、よくあることだけれど、真実に近付こうとするほど 多くの言葉を費さなくちゃならなくなる。 かっこよく決まっている、でも正しくないスローガンを、 泥をかき混ぜるみたいにいじってみたわけだが、 これじゃあまり良いスピーチにはならなさそうだ。 それに、これじゃ何をすべきかってこともよくわからない。 「きみと同じ能力」って? 自分の能力って何だろう?

風上
この問題の解法は、反対側からやってみることだ。 ゴールを最初に決めてそこから逆算するんじゃなく、 より良さそうな状況に向けて少しづつ前に進んでゆくんだ。 成功した人の多くは実際にはそうやって成功したんだ。

卒業演説方式では、きみはまず20年後にどうなりたいかを決めて、 次にそこに至るには今何をすればいい、と考える。 ぼくが提案するのは逆に、将来のことは一切決めないでおいて、 今ある選択肢を見て、良さそうな選択肢がより増えるものを選ぶってことだ。

時間を無駄にしてない限り、実際に何をするかってことはあまり問題じゃない。 面白いと思えて、選択肢が増えるものなら何でもいい。増えた選択肢のどれを 選ぶかなんて後で考えればいいんだ。

たとえば、君が大学の1年生で、数学と経済学のどっちを専攻しようかと 迷っているとする。この場合はね、数学の方が選択肢がひろがるんだ。 数学からはほとんどどの分野へも進むことができる。数学を専攻していたら、 経済学の大学院へ進むのは簡単だろう。でも経済学を専攻して、 数学の大学院へ進むのは難しい。

グライダーを考えてみるといい。グライダーはエンジンを持っていないから、 風上に向かって進もうとすると高度を大きく失うことになる。 着陸に適した地点よりずっと風下に行っちゃったら、打てる手はひどく 限られるものになるだろう。風上にいるべきなんだ。 だからぼくは「夢をあきらめるな」のかわりにこう言おう。「風上をめざせ」。

でも、どうすればいい? 数学が経済学の風上だったとして、 高校生はそんなことを知っていなくちゃならないんだろうか。

もちろん知らないだろう。だから、風上を自分で見つけ出さなくちゃならない。 風上を知る方法のヒントをいくつかあげよう。 賢い人々と、難しい問題を探すことだ。賢い人々は自分達で固まりがちだ。 そういう集団を見つけたら、たぶんそれに参加する価値はある。 但し、そういう集団を見つけることは簡単じゃない。 ごまかしがたくさんあるからだ。

大学生になったばかりのときには、大学のどの学部もだいたい似たように見える。 教授たちはみんな手の届かない知性の壇上にいて、凡人には理解不能な論文を 発表している。でもね、確かに難しい考えがいっぱい詰まっているせいで 理解できないような論文もあるけれど、何か重要なことを言っているように 見せかけるためにわざとわかりにくく書いてある論文だっていっぱいあるんだ。 こんなふうに言うと中傷に聞こえるかもしれないけれど、 これは実験的に確かめられている。有名な『ソーシャル・テクスト』事件だ。 ある物理学者が、人文科学者の論文には、 知的に見えるだけの用語を連ねたでたらめにすぎないものがしばしばあると考えた。 そこで彼はわざと知的に見えるだけの用語を連ねたでたらめ論文を書き、 人文科学の学術誌に投稿したら、その論文が採択されたんだ。

一番良い防御は、常に難しい問題に取り組むようにすることだ。 小説を書くことは難しい。小説を読むことは簡単だ。 難しいということは、不安を感じるということだ。 自分が作っているものが上手くいかないかもしれないとか、 自分が勉強していることが理解出来ないんじゃないかという不安を 感じていないなら、それは難しくない問題だ。 ドキドキするスリルがなくちゃ。

ちょっと厳しすぎる見方じゃないかって思うかい。 不安を感じなくちゃダメだなんて。 そうだね。でもこれはそんなに悪いことじゃない。 不安を乗り越えれば歓喜が待っている。 金メダルを勝ち取った人の顔は幸福に満ちているだろう。 どうしてそんなに幸福なのかわかるかい。安心したからさ。

幸福になる方法がこれしかないと言っているんじゃないよ。 ただ、不安の中にも、そんなに悪くないものがあるって言いたいんだ。

野望
「風上をめざせ」というのは、現実には「難しい問題に取り組め」という ことだった。そして、君は今日からそれを始めることができる。 ぼくも、このことに高校にいる時に気付いていたらなと思うよ。

たいていの人は、自分がやってることを上手くできるようになりたいと 思う。いわゆる現実社会では、この要求はとても強い力なんだ。 しかし高校では、上手くできたからっていいことはあまりない。 やらされていることが偽物だからだ。 ぼくが高校生だった時は、高校生であることが自分の仕事なんだって思ってた。 だから、上手くやれるようになる必要があることっていうのは、 学校でいい成績をあげることだと思ってた。

その時のぼくに、高校生と大人の違いは何かと聞いたなら、 たぶん大人は生活のために稼がなくちゃならない、と答えていただろう。 間違いだ。ほんとうの違いは、大人は自分自身に責任を持つということだ。 生活費を稼ぐのはそのほんの小さな一部にすぎない。 もっと大事なのは、自分自身に対して知的な責任を取ることだ。

もしもう一回高校をやりなおさせられるとしたら、ぼくは学校を 昼間の仕事のようにあしらうだろう。学校でなまけるということじゃないよ。 昼間の仕事のようにやる、っていうのは、それを下手にやるってことじゃない。 その意味は、それによって自分を規定されないようにするってことだ。 たとえば昼間の仕事としてウェイターをやっているミュージシャンは、 自分をウェイターだとは思わないだろう [3]。 同じように、ぼくも、自分を高校生だとは思わないだろうね。 そして昼間の仕事が済めば、本当の仕事を始めるだろう。

高校時代を思い出して一番後悔することは何かって尋ねると、 たいていみんな同じ答えを返す。時間を大いに無駄にしたってね。 君が、今こんなことをしてて将来後悔することになるだろうなと 思っているなら、きっと後悔することになるよ[4]。

これは仕方ないと言う人もいる。高校生はまだ何もきちんと出来ないからってね。 ぼくはそうは思わない。高校生が退屈しているというのがその証拠だ。 8歳の子供は退屈しない。8歳の時には「ぶらつく」かわりに「遊んで」いたはずだ。 やってることは同じなのにね。そして8歳の時、ぼくは退屈することがほとんど 無かった。裏庭と数人の友達がいれば、一日中遊んでいることができた。

今振り返ってみれば、中学高校でこれがつまらなくなった理由は、 ぼくが他の何かをする準備が出来たからだった。 子供であることに飽きてきたんだ。

友達とぶらついちゃだめだなんて言ってないよ。 誰ともつき合わなかったら、仕事しかしないむっつりした小さなロボットに なるしかない。友達と出かけるのは、チョコレートケーキみたいなもんだ。 時々食べるからおいしい。毎食チョコレートケーキを食べていたら、 たとえどんなに好きだとしても、3食目には吐き気がしてくるだろう。 高校で感じる不安感はまさにそれ、精神的な吐き気なんだ [5]。

良い成績を取る以上に何かしなくちゃならないと聞いたら、 『課外活動』のことだと思うかもしれない。 でも君はもう、ほとんどの『課外活動』がどんなにばかげたものかを知っているよね。 チャリティの寄付集めは称賛されるべきことかもしれないが、 それは難しいことじゃない。 何かを成し遂げるってことじゃないからだ。 何かを成し遂げるっていうのは、たとえば上手く文章を書けるようになるとか、 コンピュータをプログラムできるようになるとか、 工業化以前の社会の生活が実際どんなものだったかを知るとか、 モデルを使って人間の顔を書くことを学ぶとか、そういうことだ。 この手の活動は、大学入試願書に一行で書けるようなものにはなかなかならない。

堕落
大学に入ることを人生の目標にするのは危険なことだ。 大学に入るために自分の能力を見せなくちゃならない相手っていうのは、 概して鋭いセンスを欠いている。多くの大学では、 きみの合否を決めるのは教授じゃなくて入学管理者[訳註1]で、 彼らは全然賢くない。知的社会の中では彼らは下士官だ。 きみがどれだけ賢いかなんて彼らに分かりはしない。 私立の進学校が存在することが、その証明になっている。

入試に受かる見込みが上がらないのに多額の金を学校に払う親はほとんどいない。 私立の進学校は、入試に受かるための学校であることを明示している。 でも立ち止まって考えてみたまえ。同じくらいの子供が、 ただ地域の公立高校だけに行くより私立の進学校に行った方が入試に受かりやすくなるってことは、 私立の進学校は入試のプロセスをハックできるってことだ [6]。

君達の多くは、今人生でやるべきことは大学入試に受かるように なることだと思っているだろうね。でもそれは、自分の人生を空っぽの プロセス、それを堕落させるためだけで一つの業界が存在しているほどの プロセスに押し込めていることになる。 シニカルになるのも無理ないよ。 君が感じている不快感は、リアリティTVのプロデューサーや タバコ会社の重役が感じているものと同種のものだ。 君の場合は給料をもらっているわけでもないのにね。

じゃあどうしようかね。 ひとつ、やっちゃいけないのは反抗だ。 ぼくは反抗した。それは間違いだった。 ぼくは、自分達の置かれた状況をはっきり認識していなかったけど、 なにか臭いものを感じていた。だから全部投げ出したんだ。 世界がクソなら、どうなろうと知ったことか、ってね。

教師の一人が試験対策のアンチョコを使っているのを見つけた時に、 ぼくはこれでおあいこだと思った。そんな授業でいい点数をもらって どんな意味があるっていうんだ。

今、振り返ってみれば、ぼくは馬鹿だったと思うよ。 これはまるで、サッカーで相手にファウルされて、おまえ反則しただろ、 ルール違反だ！と怒ってグランドから立ち去るようなものだ。 反則はどうしたって起きる。そうなった時に、冷静さを失わないことが重要だ。 ただゲームを続けるんだ。

きみをこんな状況に押し込めたのは、社会がきみに反則したからだ。 そう、きみが思っているように、授業で習うほとんどのことはクソだ。 そう、きみが思っているように、大学入試は茶番だ。 でも、反則の多くと同じように、悪意があってそうなったわけじゃない [7]。 だから、ただゲームを続けるんだ。

反抗は服従と同じくらいばかげたことだ。 どちらにしてもきみは他人に言われたことに縛られている。 一番良いのは、直角の方向に足を踏み出すことだ。 言われたからただやる、でもなく、言われたからやらない、でもない。 かわりに、学校を昼間の仕事にするんだ。昼間の仕事だと考えれば 学校なんて楽勝だよ。3時には終わるんだし、なんなら自分のやりたいことを 内職しててもいい。

好奇心
じゃあ、本当の仕事は何になるんだろう。 きみがモーツァルトでない限り、やるべきことはまずそれを探し出すことだ。 やりがいのあることって何だろう。すごい発想をする人達はどこにいるだろう。 そして一番重要なこと：自分は何に興味があるだろう。 「適性」という単語はちょっと誤解を招きやすい。 元から備わった性質のように思われるからね。 最も強い種類の適性とは、ある種の問題に対するどん欲な興味だけれど、 そういう興味は後天的に獲得するものが多い。

この考えの変化したものは、現代の文化においては「熱意」という言葉で 呼ばれている。最近、ウェイター募集の広告で「サービスに対する熱意」を 持った人を求めている、というのを見た。 本物の熱意は、ウェイターくらいじゃおさまらないものだ。 それに熱意という単語も良くない。むしろそれは好奇心と呼ぶのがいい。

子供は好奇心旺盛だ。ただ、ぼくがここで言っている好奇心は 子供のとはちょっと違う。子供の好奇心は広くて浅い。 ランダムに色々なことについて「どうして?」と尋ねる。 多くの人は、大人になるまでにこの好奇心が全部渇いてしまう。 これは仕方無いことだ。だって何についても「なぜ?」と尋ねていたら 何もできないからね。でも野心を持つ大人では、 好奇心は全部渇いてしまうのではなく、狭く深くなってゆくんだ。 泥の庭が井戸になるんだ。

好奇心を持っていると、努力が遊びになる。 アインシュタインにとっては、相対性理論は試験のために勉強しなくちゃならない 難しい式の詰まった本ではなかったはずだ。 それは解き明かしたい神秘に見えていただろう。 だからたぶん、彼にとって相対性理論を見出すことは、 今の学生が授業でそれを学ぶことほど、努力とは感じられなかったんじゃないかな。

学校で植え付けられる幻想の一番危険なものは、 素晴らしいことを為すには自分に厳しくなければならないというものだ。 多くの科目はあまりに退屈に教えられるから、 自律心が無いと全部に出席することなんてできやしない。 大学に入ってすぐに、ぼくはヴィドゲンシュタインの言葉を読んで びっくりした。彼は自律心が無くて、たかが一杯のコーヒーであろうと 欲しくなったら我慢することができなかったというんだ。

今、ぼくは素晴らしい仕事をした人を何人も知っているけれど、 みんな同じなんだ。自分を律するということをほとんどしない。 延ばせることはぐずぐず先に延ばすし、興味のないことをやらせようと しても全くの無駄だ。そのうちの一人ときたら、自分の結婚式に 出席してくれた人へのお礼の手紙を出してない。 結婚して4年経つのに。もう一人は、メールボックスに26000通のメールをため込んでる。

自律心が全くのゼロだったら困るよ。走りに行こうかなと思うくらいの 自律心は必要だ。ぼくも時々、走るのが面倒だなあと思うけれど、 一度走り出せばあとは楽しめる。そして何日か走らないと具合が悪くなる。 素晴らしい仕事をする人にとっても同じことなんだ。 仕事をしてないと具合が悪くなるし、仕事を始めるだけの自律心は 持っている。ひとたび仕事を始めれば、興味の方に圧倒されて、 自律心は必要なくなるんだ。

シェークスピアは偉大な文学を産み出そうと歯を食いしばって 勤勉に努力したって思うかい。そんなわけないさ。 きっと楽しんでいたはずだ。だから素晴らしい作品が書けたんだ。

いい仕事をしたいなら、必要なのは見込みのある問題に対する 大きな好奇心だ。アインシュタインにとっての一番大事な瞬間は、 マクスウェルの方程式を眺めて、これはどうなっているんだろうと 自問したところにあった。

生産的な問題に照準を合わせるのには長い時間がかかる。 本当の問題は何なのかを見つけるだけで何年もかかるかもしれないからね。 極端な例を言えば、たとえば数学だ。数学を嫌う人は多い。 でも学校で「数学」の名前でやらされていたことは、 実際に数学者がやっていることとはほど遠いんだ。

偉大な数学者のG. H. ハーディは、高校の時は数学が嫌いだったと 言っている。ただ他の生徒より高い点数をとれたから選択しただけだったと。 後になって、彼は数学が面白いということに気づいた。 質問に正しく答えることのかわりに、自分で問題を見つけるようになってからね。

ぼくの友達の一人は、学校で提出するレポートに苦しんでいると 母親が「それを楽しむ方法を見付ければいいのよ」っていうんだとぼやいていた。 でもそれが、やるべきことなんだ。世界を面白くする問いを見つけ出すんだ。 素晴らしい仕事をした人は、ぼくらと違った世界を見ていたわけじゃない。 ただこの世界の中の、ほんのちょっとした、でも不思議なことがらに気づいただけなんだ。

これは学問だけの話じゃない。「車はどうして贅沢品じゃなきゃいけないんだ? 車が日用品になったらどうなるだろう?」これがヘンリー・フォードの発した 偉大な問いだった。フランツ・ベッケンバウアー[訳註2]の問いはこうだった。 「どうしてみんな自分のポジションに留まってなくちゃならないんだ? ディフェンダーがシュートしたっていいじゃないか。」

現在
偉大な問いを発するのに何年もかかるとしたら、 いま、16歳の君は何をしたらいいだろう。 質問を見つける準備をするんだ。 偉大な問いは突然現れるんじゃない。徐々に頭の中に結晶してくるんだ。 それを結晶させるのは経験だ。だから、偉大な問いを見つけるのに 探し回ってもだめだ。「ぼくができる偉大な発見は何だろう」なんて ぼんやり考えててもだめだ。そんな質問に答えはない。答えがあるなら 既に見つけてるはずだからね。

大きなアイディアが頭に浮かぶようになるには、大きなアイディアを 追い求めるんじゃなく、自分が興味を持つことにたくさんの時間を費すことだ。 そして頭を柔軟に開いておいて、いつでも大きなアイディアが巣を作れるように しておくんだ。アインシュタイン、フォード、ベッケンバウアー、 みんなこのレシピを使ったんだ。彼らはみな、ピアニストがピアノの鍵盤を 知りつくしているのと同じように、自分の仕事を知りつくしていた。 だから何かひっかかりがあれば、すぐにそれに気づけるという自信を持っていたんだ。

今、何を、どうやってすればいいかって? まず興味の持てるプロジェクトを選ぶことだ。ある分量の資料を研究するとか、 何かを作ってみるとか、何かの問題の答えを見つけてみるとか。 ひと月以内で終わらせられるようなプロジェクトがいい。 そして、ちゃんと終わらせられる手段があるようなものにする。 少しは頑張らなくちゃならないようなものがいいけれど、ほんとうに少しだけでいい。 特に最初はね。もし二つのプロジェクトのどっちを選ぶか迷ったら、 面白そうな方を選ぼう。失敗したら、もう一方を始めればいいんだ。 これを繰り返す。そうすると次第に、ちょうど内燃機関みたいに、 このプロセスが自分で走り出すようになる。一つのプロジェクトが次の プロジェクトを生み出すようになるんだ。(そうなるまでには何年もかかるけれどね。)

学校に受けがよさそうというだけでプロジェクトを選ぶのは良くない。 特にそれで制約を受けたり、それが課題のように感じられるならね。 友達を巻き込みたかったら声をかけてもいいだろう。 でもあまりたくさんでない方がいいし、ただ群れたがるだけの人は避けたほうがいい。 友達は士気を保つのにいい (一人だけで始められるベンチャー企業はほとんどない)。 でも秘密にやることにも利点はある。秘密のプロジェクトというだけで 何かわくわくするものがあるし、失敗したって誰にもばれないんだから、 大胆な挑戦ができる。

プロジェクトが君の将来目指すものにあまり関係なさそうだったとしても、 心配することはない。目指すものに到達する道っていうのは、君が思うより ずっと大きく曲がりくねるものなんだ。プロジェクトをやることで、道は伸びてゆくんだ。 一番大事なのは、わくわくして取り組むことだ。そうすれば経験から学ぶことができるからだ。

人に言えないような動機だからって、それを抑えないようにしよう。 欲望の中で最も強いもののひとつは、他人よりうまくやりたいということだ。 ハーディはその気持ちで数学を始めたと言ったが、 それは別に珍しいことじゃないと思う。それを公に認める人は少ないけれど。 他の強い動機としては、知らなくてよいとされていることを知りたいとか、 やっちゃいけないとされていることをやりたいという欲望がある。 大胆な行動をしたいというのも、これに近い欲望だ。 16歳の生徒が小説を書けるなんて多くの人は思っていない。 そういうことに挑戦すれば、どんな結果であっても、プラス点になるはずだ。 本当に大失敗したところで、周囲の期待より悪いってことはないわけだからね [8]。

悪いモデルに気をつけよう。特に怠けることを肯定するようなものにね。 ぼくは高校生の時に、有名作家がやっているような「実存主義的」短篇小説を いくつか書いたことがある。そういうものっていうのは、 読んで面白い小説を書くよりも、たぶん簡単だ。 これは危険信号なんだ。そのことを知っているべきだった。 実際、ぼくが書いたものはどれも退屈だった。 ただ、有名作家みたいに知的で厳粛なものを書くっていうことがすごいことに 思えてただけだったんだ。

今はもう十分に経験を積んだから、そういう有名作家が本当は全然たいしたこと ないってことがわかる。実は有名人のほとんどはそうなんだ。 短期的に見ると、ある仕事の質っていうのは有名度とはほとんど関係がない。 今思えば、ぼくは何かカッコいいことをしたいなんて焦らないで、 ただやりたいことをやってればよかったはずなんだ。 それが実は、カッコいい仕事への道なんだ。

多くのプロジェクトで大事な要素は、もうほとんどそれ自体が一つの プロジェクトになるようなものなんだが、良い本を見つけることだ。 ほとんど全ての教科書はダメだ[9]。 だからたまたま手近にあった本を見て、それがその分野の全てだとは 思わないほうがいい。ごくわずかの良い本を積極的に探さないとならない。

大事なことは、外に出てなにかを為すことだ。黙って座って教えられるのを 待つんじゃなく、自分から踏み出して学ぶんだ。

入試の試験官に自分の人生を合わせる必要なんてない。 自分の好奇心に合わせて人生を作っていけばいい。 野心的な大人はみんなそうしてる。それに、君は待つ必要はないんだ。 大人になるまで待たなくてもいい。だって、ある年齢になったり、 どこかの学校を卒業した時にぱちんと大人になるようなスイッチなんて ないんだからね。自分の人生に責任を持つことを決心したその時に、 君は大人になるんだ。何歳だってできることだ [10]。

ばかげだ話だと思うかい。君はこう思うかもしれないね。 「ぼくは未成年だし、金もないし、親と一緒に住まなくちゃならないし、 一日中大人に言われたことをやらなくちゃならないのに！」ってね。 でもね、大人になって仕事をしていたって、やっぱり似たような 面倒な制限がいろいろあるものさ。でもやる人はちゃんとやり遂げる。 子供であることが制限の多いことだって思ってるなら、子供を持ったら どんなことになるか考えてごらん。

大人と高校生の唯一の違いは、大人はものを成し遂げる必要があることを 知っていて、高校生はそうでないということだ。 多くの人々は、それをだいたい23歳くらいの時に知る。 でも、こっそりいまから始めることを、ぼくは君達に勧めたい。 さあ、始めよう。そうすれば、君達は史上初めて、高校の時に時間を無駄にしなかったと 言える世代になるかもしれない。

原註
[1] ぼくの友人の医者は、 これでも医者の仕事が本当はどんなものかを知ることはできないだろうと言っている。 「どれだけ時間を費して、ほとんど自分の時間を持てない何年もの訓練を受けて、 そしていつだってポケベルで呼び出されることがどんなに煩わしいかなんて、 わかるわけないよ。」

[2] 彼が出来る一番の方法は、 おそらく独裁者になってNBAを脅して自分をプレイさせることだ。 現実的に、それに一番近い立場は労働長官になることだ。

[3] 昼間の仕事というのは、 本当の仕事(バンドで演奏したり、相対性理論を発明したり)に時間を費せるように、 生活費を稼ぐためにやるような仕事のことだ。

高校を昼間の仕事だと思うことは、生徒の何人かにとっては むしろ良い成績をとるのに役立つかもしれない。 授業をゲームだと思えば、内容自体に意味が無くてもがっかりすることはないだろう。

授業がどんなにひどくても、それなりの大学に入るには良い成績は 取っとかないとならない。そのこと自体は、やる価値のあることだ。 近年では、賢い人々の集団を見つけるのに大学は良い場所だからだ。

[4] 二番目に大きな後悔は、重要でないことを気にしすぎていたことだ。 特に、他の人にどう思われているかってことだね。

より正確に言えば、ランダムな人々にどう思われているかを気にするってことだ。 大人だって人にどう思われるかを気にするけれど、誰に思われるかって 点ではより選別していることが多い。

ぼくはだいたい30人くらい、意見を気にする友人がいる。 残りの世界の意見はぼくにとってはどうでもいい。 高校の問題は、まわりに居る人間が、自分の判断ではなくて 年齢と地域がたまたま一緒だったというだけで決まることだ。

[5] 時間を無駄にする 一番の要因は、気を散らすものだ。気を散らすものが無ければ、 自分が何もしていないということにすぐ気づいて、落ち着かなくなるはずだ。 どれだけ余分なことに気を取られてるかを知るには、こういう実験をしてみるといい。 週末にある程度の時間をとって、一人で座ってただ考えるんだ。 ノートを持っていてそれにメモを取るのはいい。けれど、他のものは 全て絶つ。友達も、テレビも、音楽も、電話も、インスタントメッセンジャーも、 メールも、ウェブも、ゲームも、本も、新聞も、雑誌も無しだ。 1時間もすれば、ほとんどの人は何か気を散らすものが欲しくてどうしようもなく なるはずだ。

[6] 私立の進学校が 入学審査官をだますためだけのものだって言うつもりはないよ。 普通は、より良い教育もしてくれる。でもこういう思考実験をしてみたまえ。 私立の進学校が、今と同じ質の教育をしてくれるんだが、そこに行くと ごくわずか (.001) の確率で入試に受かりにくくなるとする。 そしたらどれだけの親が子供を私立の進学校に行かせようとするだろうね。

もちろん、私立の進学校に行った子供はより多くのことを学んだのだから、 より大学の合格者としてふさわしいという議論はできる。 でもそれは経験的には誤りだ。 一番素晴らしい高校だって、そこで教えてくれることなんて 大学で学ぶことに比べたら誤差の範囲だからだ。 公立高校を卒業した子供は入学直後には多少の不利はあるかもしれないが、 2年生になればむしろリードするようになる。

(公立高校の生徒の方が賢いって言っているんじゃなくて、 どんな大学にも公立高校出身の学生がいるってことを言っている。 私立の進学校の方が入試に受かりやすいという前提を認めれば、 公立高校出身で試験に受かった生徒の方が平均的に高い能力を持っているということになる)

[7] どうして社会が君に ファウルするんだろう。その主な原因は、無関心だ。 高校を良くするという外圧が全く無いからだ。 航空管制システムは優れたシステムだが、それは そうでなくちゃ飛行機が落ちてしまうからだ。 企業は製品を作らないとライバルに客を取られてしまう。 でも学校がダメになっても飛行機は落ちないし、競争相手もいない。 高校は邪悪なのではなく、ただランダムなんだ。 でもランダムであることは、かなり悪いことだ。

[8] それに、もちろんお金という動機もある。 高校ではこれはあまり関係無いだろう。人が欲しがるようなものを 作れることは少ないからね。でも多くの偉大なものごとというのは、 お金を稼ぐために為された。 サミュエル・ジョンソンは、「金のため以外にものを書くやつなんて馬鹿だ」と 言っている。(多くの人は、彼は誇張してるんだと思いたがるけどね)。

[9] 大学の教科書だってひどいものだ。 大学に入ってみれば、教科書の多くは(いくつかの輝ける例外を除いては) その分野の第一人者が書いたものじゃないことがわかるだろう。 大学の教科書を書くのはあまり面白い仕事じゃないし、 お金のために書かれることが多い。面白くない仕事なのは、 出版社が色々注文をつけて来るからで、自分がやってることを 理解できない人間に注文をつけられるのは最悪なことだからだ。 高校の教科書では状況は もっと悪いらしい。

[10] 教師はいつも「大人のように振る舞いなさい」と君達に言っているかもしれない。 でも、本当に君達がそうすることを望んでいるかは怪しいものだ。 君達は騒がしくてまとまりが無いかもしれないけれど、 大人に比べたらずっと素直だ。 君達が本当に大人のように振る舞い出したら、それは例えば 大人達を君達の体に移し変えたようなものになるだろう。 FBIエージェントやタクシーの運転手や記者達が、 トイレに行くのにいちいち許可を得る必要があって、しかも一度に一人しか いけないなんて聞いてどういう反応をするか想像してごらん。 君達が教えられたことなんてひとつも守られないはずだ。 もし本当に大人達が高校に入ることになったら、最初にやることはきっと 組合を作って校則の改正を教師達と談判することだろうね。

このエッセイの下書きに目を通してくれた、Ingrid Bassett、Trevor Blackwell、 Rich Draves、Dan Giffin、Sarah Harlin、 Jessica Livingston、Jackie McDonough、Robert Morris、Mark Nitzberg、 Lisa Randall、Aaron Swartz、 それに、高校時代について私に語ってくれた他の多くの人々に感謝します。

訳註
訳註1：
入学管理者：原文admission officer。 米国の大学は入試一発ではなく、大学ごとのAdmission Officeが 志願者の高校での活動や成績、統一テストの結果などを勘案して合否を決定する。
訳註2：
フランツ・ベッケンバウアー Franz Beckenbauer：サッカー選手、監督。 「リベロ」のポジションを確立した。
#+end_src

** [[https://www.aozora.gr.jp/cards/000148/files/1102_14956.html][夏目漱石 創作家の態度]]
#+begin_quote
なぜと云うと文学史で云う何々主義と云うのは理論から出たのでなくして、個人の作物から出たのであって、その作物の大体を鷲攫わしづかみにして、そうしてもっとも顕著に見える特性だけを目懸めがけて名を下したまでであります。
#+end_quote

#+begin_quote
つまりは幾通りとなく成立し得べき歴史のうちで実際に発展した歴史だけに重きを置いて、しかもほとんど偶然に出現した人間の作そのものを全まったき成体で取り崩くずす事のできないものと見傚みなした上でその特色の著るしきものだけに何主義の名をもってする弊であります。
#+end_quote

** [[http://www.foundersatwork.com/steve-wozniak.html][Steve Wozniak - Founders at Work]]
** [[http://www.paulgraham.com/speak.html][Writing and Speaking]]
どうやって書くか、公演するか。
** [[http://www.aoky.net/articles/paul_graham/head.htm][頭の中にプログラムを入れる]]
Paul Grahamのエッセイ。
** DONE 簡潔さは力なり(エッセイ)
CLOSED: [2021-09-11 Sat 16:15]
[[id:18fbe00f-4ec8-4ca0-adfa-2d1381669642][LISP]]プログラマのPaul Grahamのエッセイ。
- [[http://practical-scheme.net/trans/power-j.html][Succinctness is Power]]
* プログラマー
** [[http://dnobori.cs.tsukuba.ac.jp/ja/][http://dnobori.cs.tsukuba.ac.jp/ja/]]
すごい人。ソフトウェア研究者・技術者。深さ、広さがすごい。
** [[https://shimataro.me/][Taro ODASHIMA | A full-stack web engineer, and a close-up magician!]]
伝わるポートフォリオ。
** [[https://www.bracketproductions.com/][Bracket Productions]]
すごいゲーム開発者。
roguelike tutorialの作者。
** [[https://hiroppy.me/][universe]]
Javascriptのすごい人。
** [[https://toshi0607.com/about/][About Me – DoorLog]]
すごいエンジニアの人。
未経験時のログが残っていて、そんな時期が存在していたことを知れる。成長速度えぐい。
** [[https://note.com/simplearchitect][牛尾 剛｜note]]
エンジニア。
*** [[https://note.com/simplearchitect/n/nf50d0418bc5f][才能ない人を観察してどうやったらできるようになるか考えてみた｜牛尾 剛｜note]]
アウトカムを急がない。理解するのには時間がかかる。
アウトプットを考えがちだが、それでコピペしてたら意味がない。

- ブログ書くのが重要
*** [[https://note.com/simplearchitect/n/nbf330ae7770f][技術者には試行錯誤は圧倒的に悪であると腹落ちした話｜牛尾 剛｜note]]
ただ単にいろんなパターンを試して正解を探しても、何も学べていない。
関連技術を理解して、自分のコントロール化に置くことが重要。
*** [[https://note.com/simplearchitect/n/n9bd63cd83c6b][最近の技術イケメン観察日記 Tips 4選｜牛尾 剛｜note]]
4時間ほど予定をブロックしているという。
その時間は返信もせず、自分の仕事に熱中する。
*** [[https://note.com/simplearchitect/n/n1170c5ecfb1a][技術イケメンになれるブログの書き方｜牛尾 剛｜note]]
*** [[https://note.com/simplearchitect/n/n388201603a28][プログラミングというより物事が出来るようになる思考法｜牛尾 剛｜note]]
*** [[https://note.com/simplearchitect/n/n2168b03da314][一流のソフトウェアエンジニアになるための考察｜牛尾 剛｜note]]
*** [[https://note.com/simplearchitect/n/n8cd219056536][コードリーディングのコツは極力コードを読まないこと｜牛尾 剛｜note]]
*** [[https://note.com/simplearchitect/n/n1b0263219060][生産性を上げたければ定時上がりが効率が良い｜牛尾 剛｜note]]
** [[https://www.sanityinc.com/][Sanity, Inc. · sanity, inc.]]
Purcel(パッケージシステムMelpaを作った人)のブログ。
** [[https://www.fosskers.ca/jp/cv][Colin Woodbury]]
OSSのすごい人。幅広い。長崎でALTをしてたことがあるらしく、ちょっと親近感。
** [[https://blog.jiyu.dev/about][About — Jiyu Software]]
かっこいい自己紹介ページ。
** [[https://web.archive.org/web/20070821003652/http:/www.danchan.com/weblog/nestum/][a cuppa nestum]]
若かりし頃のブログ。
** [[https://danielmiessler.com/][Daniel Miessler | Security, Technology, and Society]]
セキュリティで有名な人。
** [[https://www.dodgycoder.net/2012/09/q-with-nine-great-programmers.html][Dodgy Coder: Q&A With Nine Great Programmers]]
偉大なプログラマーへのQ&A集。
** [[https://endlessparentheses.com/about.html][Endless Parentheses · Ramblings on productivity and technical subjects.]](Malabarba)
複数のパッケージ開発者。
https://endlessparentheses.com/about.html
** [[https://oremacs.com/][(or emacs · irrelevant)]]
Emacsの有名人のブログ。
** [[https://liberapay.com/wasamasa/][wasamasa's profile - Liberapay]]
いい感じの自己紹介。Emacs。
** [[https://eed3si9n.com/about/][about me · eed3si9n]]
[[id:b2f63c13-4b30-481c-9c95-8abe388254fd][Scala]]のすごい人。
* プログラム
** [[https://logstalgia.io/][Logstalgia - a website access log visualization tool]]
Webアクセスの美しい可視化ツール。
** [[https://roll20.net/compendium/dnd5e/Weapons#content][Weapons | D&D 5th Edition on Roll20 Compendium]]
D&Dスタイルの武器。
** [[https://qiita.com/yagince/items/546d86588aaa3fdb3c94][[Rust] proc_macro入門 CustomDeriveを書いてみる - Qiita]]
proc_macroの使い方。
** [[https://zenn.dev/saitoyutaka/articles/fe12c982e89a7b][Guixのパッケージを作ってみる]]
パッケージの作り方。
** [[https://qiita.com/oohira/items/63b5ccb2bf1a913659d6][gRPCって何？ - Qiita]]
プロトコルの種類。
** [[http://www.plantuml.com/plantuml/uml/][PlantUML Web Server]]
宣言的な作図ツール。グルーピングができる分mermaidより使いやすい気がする。
** [[https://www.techscore.com/tech/DesignPattern/][デザインパターン | TECHSCORE(テックスコア)]]
デザインパターンのサイト。
** [[https://speakerdeck.com/twada/growing-reliable-code-phperkaigi-2022?slide=133][予防に勝る防御なし - 堅牢なコードを導く様々な設計のヒント / Growing Reliable Code PHPerKaigi 2022 - Speaker Deck]]
Simple と Easy は異なる。混ぜてはいけない。
Easy: 手数の少なさを重視。覚えることが増え、特定の状況に強いが他には弱い設計になる。
Simple: 覚えることの少なさを重視。手数が増えたり、自分で組み合わせたりしなければならない。
** [[https://docs.aws.amazon.com/ja_jp/elasticloadbalancing/latest/network/introduction.html][Network Load Balancer とは? - Elastic Load Balancing]]
ロードバランサーの詳細。
** [[https://stakiran.hatenablog.com/entry/2019/07/01/203651][【第二版】ファイアウォールやネットワークにおける上り、下り、イングレス(Ingress)、エグレス(Egress)、インバウンド(Inbound)、アウトバウンド(Outbound)の違い - stamemo]]
** [[https://qiita.com/NewGyu/items/9597ed2eda763bd504d7][Amazon EC2 Container Service(ECS)の概念整理 - Qiita]]
ECSの概要。
** [[https://tratt.net/laurie/blog/2022/practising_programming.html][Laurence Tratt: Practising Programming]]
:LOGBOOK:
CLOCK: [2022-04-24 Sun 20:53]--[2022-04-24 Sun 21:18] =>  0:25
:END:
実践してきた方法。
メーラーデーモン、asyncなどの現実世界の問題を解くことで上達していったという。
** [[https://programming-place.net/ppp/contents/bookshelf/free.html][無料で読める書籍 | Programming Place Plus]]
プログラミング関係の書籍。
** [[https://www.oreilly.co.jp/books/9784873117874/][O'Reilly Japan - Cooking for Geeks 第2版]]
オライリーの料理本。なぜ。
** [[https://github.com/google/styleguide][google/styleguide: Style guides for Google-originated open-source projects]]
Googleのスタイルガイド。
** [[http://www.happiese.com/system/dataorient.html][データ中心指向とオブジェクト指向]]
指向の違い。
** [[https://openviewpartners.com/blog/the-product-led-growth-market-map/#.YbN9aOozbAS][The Product Led Growth Market Map - OpenView]]
優良IT企業のリスト。あらゆる分野に浸透している。
** [[https://practicingruby.com/articles/patterns-for-building-excellent-examples][Patterns for building excellent examples]]
サンプルコードの書き方。
** [[https://colin-scott.github.io/personal_website/research/interactive_latency.html][Numbers Every Programmer Should Know By Year]]
各速度の表。
** [[https://speakerdeck.com/uzulla/phpbaziyonatupukemofalsedao][PHPバージョンアップけもの道 - Speaker Deck]]
言語のバージョンアップは大変な仕事。どうやって進めるか。
** [[https://www.foragoodstrftime.com/][For a Good Strftime | Easy Skeezy Ruby Date/Time Formatting]]
日付のフォーマット文字列を生成するツール。
** [[https://zenn.dev/ak/articles/c28fa3a9ba7edb][ブラウザレンダリングの仕組み]]
非常にわかりやすいレンダリングの解説。
** [[https://www.oreilly.co.jp/library/][O'Reilly Japan - Library]]
オープンライセンスで公開されているもの。
** [[https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf][Adobe PDF]]
PDFの仕様書。
** [[https://transparentcalifornia.com/][Transparent California]]
オープンな行政。
** [[https://speakerdeck.com/keiya01/burauzafalsezuo-rifang][ブラウザの作り方 - Speaker Deck]]
** [[https://www.hyrumslaw.com/][Hyrum's Law]]
Hyrumの法則。
* 乗り物
** [[https://www.myskc.net/o_150627.php][金券ショップの切符はなぜ安いのか]]
新幹線の回数券はマネーロンダリングに使われるらしい。
** [[https://travel.spot-app.jp/ohtsuki_shimomurayama/][大月駅に終電で寝過ごして来てしまった方へ。始発を待つ方法はコレ！ | SPOT]]
面白い。
** [[https://archive.org/details/navpers][NAVPERS Collection : Free Texts : Free Download, Borrow and Streaming : Internet Archive]]
アメリカ海軍のマニュアル集。
** [[https://travel.spot-app.jp/seisyun18kippu_ekimemo/][青春18きっぷで日本縦断。最南端の鹿児島から稚内まで行ってみた | SPOT]]
すごい。
** [[http://yamaiga.com/][廃道・廃線・未成道・隧道・林鉄・道路趣味～山さ行がねが～]]
面白い。
* 郷土
** [[https://373news.com/_news/storyid/142378/][76年前、自宅前の線路の列車を米軍機が襲った。怖いもの見たさで外に出た。右足に強い痛み。大量の血の中から見つけた銃弾は今も持っている〈証言 語り継ぐ戦争〉 | 鹿児島のニュース | 南日本新聞 | 373news.com]]
折口の、鉄道車両に対する空襲。
** [[https://www3.nhk.or.jp/lnews/kagoshima/20220627/5050019201.html][太平洋戦争末期の阿久根市の列車空襲 米軍撮影の写真見つかる｜NHK 鹿児島県のニュース]]
証言を裏付ける写真が発見される。川の流路が現在と違うことがわかる。
* 趣味
** [[https://drive-ns.hatenablog.com/archive][記事一覧 - 週末大冒険]]
面白いスポット紹介。
** [[https://www.youtube.com/watch?v=txkHN6izK2Y][GameBoy Graphics: Tiles, Palettes, and Encoding - YouTube]]
ゲームボーイの描画システムの解説。
** [[https://media.longnow.org/files/2/soul-of-japan-wb.pdf][Soul of Japan]]
日本文化の説明。
** [[https://www.youtube.com/watch?v=d0yGdNEWdn0][How to learn any language in six months | Chris Lonsdale | TEDxLingnanUniversity - YouTube]]
外国語を学ぶ方法。
- コンテンツに集中する
- コミュニケーションの道具として使う
- 体で学ぶ
- リラックス、好奇心。曖昧さに耐えられる環境
- ボディランゲージから得る
- たくさん聞く
- 組み合わせる
- 表情から学ぶ。発音とか
** [[https://http.cat/][HTTP Cats]]
HTTP Statusの猫画像。
** [[https://milan.cvitkovic.net/writing/rules_for_conferences/][Milan Cvitkovic]]
カンファレンスのルール。
** [[https://ja.wikipedia.org/wiki/%E3%83%9E%E3%83%B3%E3%83%8F%E3%83%83%E3%82%BF%E3%83%B3%E8%B7%9D%E9%9B%A2][マンハッタン距離 - Wikipedia]]
タクシー幾何学。
** [[https://ciechanow.ski/mechanical-watch/][Mechanical Watch – Bartosz Ciechanowski]]
時計の詳細な仕組み。精巧なアニメーションで理解しやすい。
** [[https://nlftp.mlit.go.jp/kokjo/tochimizu/F3/data/pdf/4622t.pdf][土地分類基本調査 阿久根]]
折口川に関する記述がある。
#+begin_quote
阿久根市折口と野田町の一部の折口川をはさむ水田地帯302haを対象に昭和26年~昭和31年にかけて実施した用水改良事業である。折口川は、路線・断面共の不規則で又河口に設けられた樋門(3連)が不備であるため、排水が悪い。そのため本事業においては幹線・排水路及び樋門を改修すると共に取水堰の改修を行った。
#+end_quote

- [[https://mapps.gsi.go.jp/map-lib-api/contentsImageDisplay.do?specificationId=41735&isDetail=true][USA-R50-2-17]] 1948年
- [[https://mapps.gsi.go.jp/map-lib-api/apiContentsView.do?specificationId=18100][USA-M798-A-39]] 1948年
- [[https://purl.stanford.edu/kq741wk9448][1:50,000 chikeizu | 地形図]]
- [[https://www.env.go.jp/water/suiiki/h14/fu04.pdf][平成１４年度公共用水域水質測定結果　付表４]]
  - 河川水質ワースト
- [[https://www.kagoshima-it.go.jp/k-it/pdf/kenkyu_report/i_report_1962_17.pdf][鹿児島県工業試験場(　1962／第9号　)　大隅中部・垂水地域および阿久根・出水地域の地下水の水質について]]
  - 水質調査
  - 折口川、およびその周りの深井戸は各成分が多く水質が悪い。これは折口川周辺の温泉水の混入によるものと思われる。
** [[https://tatsu-zine.com/books/blood-sweat-and-pixels][血と汗とピクセル　大ヒットゲーム開発者たちの激戦記]]
:LOGBOOK:
CLOCK: [2022-05-02 Mon 23:22]--[2022-05-02 Mon 23:47] =>  0:25
CLOCK: [2022-05-02 Mon 22:18]--[2022-05-02 Mon 22:43] =>  0:25
CLOCK: [2022-05-02 Mon 21:39]--[2022-05-02 Mon 22:04] =>  0:25
CLOCK: [2022-05-02 Mon 21:12]--[2022-05-02 Mon 21:37] =>  0:25
CLOCK: [2022-05-02 Mon 20:43]--[2022-05-02 Mon 21:08] =>  0:25
CLOCK: [2022-05-02 Mon 10:22]--[2022-05-02 Mon 10:47] =>  0:25
CLOCK: [2022-05-02 Mon 09:55]--[2022-05-02 Mon 10:20] =>  0:25
CLOCK: [2022-05-02 Mon 09:30]--[2022-05-02 Mon 09:55] =>  0:25
CLOCK: [2022-05-01 Sun 22:17]--[2022-05-01 Sun 22:42] =>  0:25
CLOCK: [2022-05-01 Sun 21:51]--[2022-05-01 Sun 22:17] =>  0:26
CLOCK: [2022-05-01 Sun 21:26]--[2022-05-01 Sun 21:51] =>  0:25
:END:
スターデューバレーの開発者の話。5年間1人で開発して完成させた...。
ディアブロ3の話はすごいな。最初だめだったゲームが、数年かけてその評価を覆す。
** [[https://www.thesaurus.com/][Synonyms and Antonyms of Words | Thesaurus.com]]
類語辞典。
** [[https://futuretage.tumblr.com/][S C A P E S]]
すごい雰囲気のいいGIFを集めたページ。
** [[https://www.sycom.co.jp/custom/model?no=000680][Aqua-Master X570A｜水冷PC｜BTOパソコン｜BTO パソコン(PC)の【@Sycom】(サイコム)]]
なしを選択できるので安くできる。
** [[https://gigazine.net/news/20110909-tepco-report/][福島第一原発に襲来した高さ10メートルの津波写真付き報告書まとめを東電が公開中 - GIGAZINE]]
解説。
** [[https://www.tepco.co.jp/cc/press/betu11_j/images/110909m.pdf][福島第一原子力発電所 東北地方太平洋沖地震に伴う原子炉施設への影響について]]
東電の報告書。
** [[https://www.gizmodo.jp/2019/02/the-best-websites-to-use-one-hour.html][｢有意義に｣時間を潰せるウェブサイト12選 | ギズモード・ジャパン]]
面白いサイトの紹介。
** [[https://www.howstuffworks.com/][HowStuffWorks - Learn How Everything Works!]]
色々な仕組みを教える教育サイト。
** [[https://www.mapcrunch.com/][MapCrunch - Random Street View]]
ランダムな場所のストリートビューを表示する。
** [[https://apod.nasa.gov/apod/astropix.html][Astronomy Picture of the Day]]
毎日NASAの写真を公開している。
** [[https://www.earthcam.com/][EarthCam - Webcam Network]]
世界中のWEBカメラを閲覧できるサイト。
** [[https://www.netinbag.com/ja/internet-page-1.html][インターネット - Netinbag.com]]
さまざまな分野の興味深いFAQが掲載されてる謎のサイト。
** [[https://www.nikkei-science.com/page/magazine/1009/201009_040.html][時間は実在するか？ - 日経サイエンス]]
時間はお金のようなもの、という例えがわかりやすい。
** [[https://old.no/charmap/Unicode/][Unicode 10.0]]
1ページにまとまったUnicode絵文字一覧。
** [[https://manytools.org/hacker-tools/convert-images-to-ascii-art/][ASCII art generator for geeks! - Convert images/pictures to ASCII art online! (HTML/text)]]
画像をアスキーアートに変換する。
** [[http://ccmixter.org/view/media/home][ccMixter - Welcome to ccMixter]]
CCの音源。
** [[https://bonkersworld.net/][Bonkers World]]
おもしろい風刺画サイト。
** [[https://mycolor.space/?hex=%23EFEC88&sub=1][ColorSpace - Color Palettes Generator and Color Gradient Tool]]
カラーテーマを作成してくれる。
** [[https://www.science.org/careers/2016/03/how-seriously-read-scientific-paper][How to (seriously) read a scientific paper | Science | AAAS]]
科学論文の読み方。
** [[https://www.remove.bg/upload][Upload Image – remove.bg]]
画像から背景を消すツール。
** [[https://tanks-encyclopedia.com/][Tank Encyclopedia, the first online tank museum]]
戦車の百科事典。おもしろい。
** [[http://www.securico.co.jp/jbl/image/guns.html][銃の基礎知識]]
面白い。特に ~警察庁長官狙撃事件~ の銃の観点から見た分析が興味深い。
** [[http://www.kagakueizo.org/][科学映像館]]
古い映像が面白い。
** [[https://tiermaker.com/][Tier List Maker for Everything - TierMaker]]
なんでもリスト、ランキングを作るサイト。
** [[https://manjotpahwa.medium.com/10-reading-habits-that-changed-my-life-5c7673bc34bc][10 Reading habits that changed my life | by Manjot Pahwa | Medium]]
読み方。
** [[https://generated.photos/][Generated Photos | Unique, worry-free model photos]]
架空の顔を生成するツール。
** [[https://www.handheldmuseum.com/][Electronic Handheld Game Museum]]
携帯ゲーム機の博物館。
** [[https://www.yumeginga.jp/720_directors_room/monokowashis/index.html][「ものこわし」のすすめ！]]
身近なエンジニアリング。
** [[https://www.wdic.org/w/WDIC/%E8%A9%AD%E5%BC%81%E3%81%AE%E7%89%B9%E5%BE%B4%E3%81%AE%E3%82%AC%E3%82%A4%E3%83%89%E3%83%A9%E3%82%A4%E3%83%B3][詭弁の特徴のガイドライン ‐ 通信用語の基礎知識]]
** [[http://www.toothpastefordinner.com/][Toothpaste For Dinner by @drewtoothpaste - wait for that first beer]]
面白い漫画のサイト。
** [[http://www.jsce.or.jp/committee/hsce/2800/index2(2800).htm][日本の近代土木遺産]]
面白い。
** [[http://osomatsulabo.web.fc2.com/archives.files/archives.html][バイオハザードへのツッコミ]]
面白い。
** [[https://www.arcgis.com/apps/SimpleViewer/index.html?appid=733446cc5a314ddf85c59ecc10321b41][Japan 1:50,000 測量地図 スタンフォード]]
日本の古地図。
** [[http://blog.livedoor.jp/lionfan/archives/52681874.html][らいおんの隠れ家 : 「忍者ハットリくん☆ベスト盤」から抜粋。 - livedoor Blog（ブログ）]]
こういうの大好き。
** [[https://toyokeizai.net/articles/-/450356][父の借金を負わされた男性がやっと掴んだ｢幸せ｣ | ボクらは｢貧困強制社会｣を生きている | 東洋経済オンライン | 社会をよくする経済ニュース]]
逆境でも才能によって抜け出せる人もいる。
** [[https://mdbootstrap.com/docs/standard/content-styles/colors/][Bootstrap 5 Colors - examples & tutorial]]
Bootstrapの色一覧。
** DONE The Tipping Point
CLOSED: [2022-01-26 Wed 10:45]
:LOGBOOK:
CLOCK: [2022-01-26 Wed 09:50]--[2022-01-26 Wed 10:15] =>  0:25
CLOCK: [2022-01-24 Mon 10:17]--[2022-01-24 Mon 10:42] =>  0:25
CLOCK: [2022-01-24 Mon 09:29]--[2022-01-24 Mon 09:54] =>  0:25
CLOCK: [2022-01-23 Sun 22:25]--[2022-01-23 Sun 22:50] =>  0:25
CLOCK: [2022-01-23 Sun 21:42]--[2022-01-23 Sun 22:07] =>  0:25
CLOCK: [2022-01-23 Sun 16:05]--[2022-01-23 Sun 16:30] =>  0:25
CLOCK: [2022-01-26 Wed 10:27]--[2022-01-26 Wed 10:45] =>  0:18
CLOCK: [2022-01-25 Tue 22:42]--[2022-01-25 Tue 23:07] =>  0:25
CLOCK: [2022-01-25 Tue 22:05]--[2022-01-25 Tue 22:30] =>  0:25
CLOCK: [2022-01-10 Mon 11:50]--[2022-01-10 Mon 12:15] =>  0:25
CLOCK: [2022-01-10 Mon 11:48]--[2022-01-10 Mon 11:50] =>  0:02
CLOCK: [2022-01-09 Sun 17:29]--[2022-01-09 Sun 19:08] =>  1:39
CLOCK: [2021-12-19 Sun 18:47]--[2021-12-19 Sun 19:30] =>  0:43
CLOCK: [2021-12-19 Sun 18:27]--[2021-12-19 Sun 18:35] =>  0:08
CLOCK: [2021-12-19 Sun 00:07]--[2021-12-19 Sun 00:55] =>  0:48
CLOCK: [2021-12-18 Sat 22:56]--[2021-12-18 Sat 23:31] =>  0:35
CLOCK: [2021-12-18 Sat 18:11]--[2021-12-18 Sat 18:44] =>  0:33
CLOCK: [2021-11-21 Sun 20:07]--[2021-11-21 Sun 20:26] =>  0:19
CLOCK: [2021-11-20 Sat 20:58]--[2021-11-20 Sat 21:28] =>  0:30
CLOCK: [2021-11-17 Wed 22:15]--[2021-11-17 Wed 22:53] =>  0:38
:END:
- 25, 30, 40, 43, 58, 60, 73, 80, 86, 90, 96, 101, 122, 144, 158, 177, 200, 202, 215, 230, 244, 250, 260

- 6回辿る
  - 任意の人を2人選んで関係を6回辿ればつながる、というがこれは一様でない。一部の人が大きなつながりを持っていてハブになっている。コネクター。その人を元に様々な人がつながりを生んでいるような。
- 知人
  - ほとんどの人にとって、この種の知人関係養成(バースデーカードを送ることとか)にはシャイになる。誰でもやっぱりそうだよな。connectorの一人は、そういうゆるいつながりを維持することに長けていた。
  - 仕事を得る上では、弱いつながりの方が役に立つ。多くの人が紹介で職を得る。友人よりも知人の方が多い。定義的に知人の方が外部の世界の人々であるからだ。
- セサミストリート
  - セサミストリートはもっとも教育的な番組の1つである。どうやって子供に興味をもってもらうか。世界に名前付けをしている段階の子供にとって、1つの名前が異なる2つの物を指すことがあることを理解させるのは難しい。
- 1980年代のニューヨークの犯罪
  - 犯罪は病気のように伝染する。割れ窓。犯罪を防ぐためには巨大な問題を解決する必要はない。落書きなど小さな犯罪を防げばいい。
- 人間は行動を考える時、文脈より人物の性格や備わったものを重視しやすい(FAE)。実際は文脈のほうが大きな影響をおよぼしている。たとえば兄弟構成。よく言われる特質(年上の子は保守的、とか)は、家族外では当てはまらないことが多い。
- 家族より、近所やコミュニティの方が影響が大きい。歩いていてすれ違う人も、どう行動するかを決定するのに大きな影響をもたらす。
- 組織は小さい方がいい。大きいとコミュニケーションコストが大きくなり、コントロールが難しくなるから。
- 1960年のミクロネシアでは自殺はほとんど知られてなかったが、一人の少年の自殺をきっかけに毎年増加していった。率はアメリカの7倍にまで達した。自殺は伝染する。
- ヘビースモーカーの典型的な特徴。当てはまる人が多いな。
  - 外向的
  - 不安症、神経症
  - 飲酒、コーヒーの量が非喫煙者に比べて多い
* 未分類
** [[https://www.youtube.com/channel/UCsLiV4WJfkTEHH0b9PmRklw][Webdriver Torso - YouTube]]
GoogleがYouTubeの本番環境の品質検証で使っていた動画チャンネル。
** [[http://shapecatcher.com/][Shapecatcher: Draw the Unicode character you want!]]
手書きで記号検索する。
** [[https://unicode-table.com/en/search/?q=square][Search - Unicode Character Table]]
絵文字を探すときに便利。
* Archives
** DONE はてなブックマークからroam notesに移動
CLOSED: [2021-09-26 Sun 15:53]
:LOGBOOK:
CLOCK: [2021-09-26 Sun 09:59]--[2021-09-26 Sun 11:49] =>  1:50
:END:
<2021-09-26 Sun> org-protocolを設定したのではてブを使う理由はない。
