#+title: Project
* Project
** よいプロジェクト
- 1ヶ月以内で終わること
- テストしやすいこと
- コードに集中できること
- 新しく学ぶことが絞られていること
** 案
*** Rubyの本
途中までだった。続きをやろう。
*** 一気にcloneスクリプト
*** ゲーム
ゲームの問題点。遊ぶ人が自分だけであること。
ゼロからやるのは楽しいが、結局大きすぎて途中で飽きる。
**** テキストベースのゲーム
- テストしやすいためテキスト主体。
- ローグライク
- アドベンチャーゲーム
**** DBゲーム
話がデカすぎてやる気が持続するとは思えない。

自動生成操作をするプログラムをユーザに見立てて、dbアプリを作成する。出来ていくデータを眺める。とにかく重要なのは、生身のユーザを必要としないことだ。
基本的に眺める楽しさ。

viewは一切開発せず、直にパブリックメソッドを実行するbotを仮想ユーザとして考える。何かイベントを与えると必要なことを行おうとする。経営のダッシュボードだけ可視化できるようにして、あとはルールとして実装する。あとで変更しやすいように、テキストで全管理できるDBにしたいな。
- 株
- 病院
- レンタルビデオ
- 人間関係ネットワーク。お互いに影響を与え合う様子。

パワポケのペナントモードという考え方もできる。チームという入力を入れると、試合データが出てくる。試合やチームによって、所属する選手は変化していく。それってシミュレーションゲーム。値を自由に入れることができないシミュレーション。
うむむ、DBを使う必要はあるんだろうか。
**** SimutransのCUI版
**** 倉庫番
でかいのに取り組むより、これくらいがよい。
- 空間の実装方法が理解できる。
**** プログラムゲーム
最低限の世界のルールを定めておいて、それをプログラムで解決するゲーム。
世界のルール: 物体は質量を持つ、移動には費用がかかる、その枠の中で自由にプログラムできる、というもの。本質的には、ルールセットを記述して戦うロボット的なゲームに似ている。でもそうやって具体的なひとつのケースを見るのではなくて、全体を見るところが違う。
**** サウンドノベル・web
- markdownを拡張してサウンドノベル用の文法を作る。
- webでmdを読み込んで表示できるようにする。
*** パッケージ作る
これが現実的か。
- 小さくていい。
- 他のを見て参考にできる。
- 一度理解すれば横展開がやりやすい。どこかにPR出せばスターがつきやすいのもいい。確実に需要がある。
** ボツ
*** Textlint Web
- もうすでにある。
