:PROPERTIES:
:ID:       eb196529-bdbd-48c5-9d5b-a156fe5c2f41
:END:
#+title: EXWM
* 概要
EXWM([[id:1ad8c3d5-97ba-4905-be11-e6f2626127ad][Emacs]] X Window Manager)は、ウィンドウマネージャの1つ。

Emacs下でX Windowの管理ができる。
つまり、Emacsでブラウザを開く…など、あらゆる操作が可能になり、1つのbufferとして扱える。

- Repository :: [[https://github.com/ch11ng/exwm][ch11ng/exwm: Emacs X Window Manager]]
- Wiki :: [[https://github.com/ch11ng/exwm/wiki#keybindings][Home · ch11ng/exwm Wiki]]
* Memo
** 起動時微妙にフルスクリーンにならないことがある
たまにEmacsのモードラインの下に、微妙に黒いゾーンができる。
最初に ~(toggle-frame-fullscreen)~ してから ~(exwm-init)~ するとよい。
** アプリケーション起動
~S-&~ でウィンドウが立ち上がるコマンドを実行する。
- ~blueman-manager~ :: bluetooth管理
- ~google-chrome~ :: Chrome
- nemo :: Linux Mintのファイルマネージャ
** X Windowとは
* Tasks
** TODO Chromeに切り替えたときフォーカスしない
[[id:b69fe713-7aef-4282-b6e3-f83bc8cb7f6d][qutebrowser]]では起きないのでChromeの問題の可能性。
** TODO 通知ができない
** TODO ブラウザが個別に開く設定にし、各バッファ選択から直に移動できるようにする
どこか[[id:fa497359-ae3f-494a-b24a-9822eefe67ad][System Crafters]]の動画で紹介されていたはずだ。
** TODO 再帰でEmacsを開く方法を調べる
* Reference
* Archive
** DONE chromeバッファなどでpersp移動ができなくて不便
CLOSED: [2021-09-19 Sun 00:25]
いちいちEmacsバッファに移ってからキーを打たないと反応しなかった。
define-keyでmodeに定義してやると共通のキーバインドで使用できるようになった。
こういうのちょっとめんどい。
#+begin_src emacs-lisp
  (global-set-key (kbd "C-M-<right>") 'persp-next) ;; 従来
  (global-set-key (kbd "C-M-<left>") 'persp-prev) ;; 従来
  (define-key exwm-mode-map (kbd "C-M-<right>") 'persp-next) ;; 加える
  (define-key exwm-mode-map (kbd "C-M-<left>") 'persp-prev) ;; 加える
#+end_src
** DONE Setting EXWM
単に ~(start-process-shell-command)~ を使ってコマンドを実行すればいい。
#+begin_src emacs-lisp
(start-process-shell-command
   "compton" nil "compton -b --config $HOME/dotfiles/.config/compton/compton.conf")
#+end_src

CLOSED: [2021-09-19 Sun 00:25]
- background
- transparent background
- polybar
