:PROPERTIES:
:ID:       ed146d63-0e55-4008-98e8-2a2f1f7329b5
:END:
#+title: Novel Game
#+filetags: Project

* 概要
ノベルゲームを作成する。

[[id:da7ec7fb-e585-4699-85dc-172c5060499a][Phaser]]がとてもよい。
ブラウザでプレイできるようにする。
* Memo
* Tasks
** TODO 文字をアニメーション表示する
** TODO プロンプトをアニメーション表示する
** TODO bundleするとパスが変わって読み込めない問題
開発時と本番環境での、ファイルパスのズレが生じる。
* Reference
** [[https://qiita.com/non_cal/items/622108030aa2e516260c][TypeScriptを使ってノベルゲームを作ろう - Qiita]]
最低限のノベルゲームが作成できる。非常に参考になる。
* Archives
* Prot
** キャラ
*** 北島
30代後半。サラリーマン、独身。九州の田舎出身。
恋人、友人なし。
社会とのつながりが切れている。
過去の記憶があまりない。
*** 川平
北島の中学時代の同級生。

病苦で自殺、遺書を残す。
*** 刑事
北島を訪ねてくる刑事。
** オチ
廃墟で死体を見つける。
次に見たとき、死体はなくなっていた。
実は殺したのは自分で、その記憶をでっち上げていた。
それぞれ無関係そうな無邪気な遊びを、後から見ると恐ろしい行為として思い出す、ということ。
- 話す途中で断片的に思い出していき、疑心暗鬼になっていく
- 夢や個人だけの回想で少しずつ記憶を改変していた
- 不思議な出来事の真相が記憶改ざんだけなのは弱い
** オープニング
飛び込み。この動機が弱いんだよな。インパクトは大きいけども。
警察にバレるのではないかという恐怖(実際捜査は進んでる)。
幼少の記憶が戻って良心の呵責で？弱い。何かもうひと押し必要に思える。
記憶がないということへの絶望と、これまでいくつもの手を振り払ってきたことへの後悔。
思い出せないけど確かに存在したというのは希望な気もするな。

ミスリード、という手もある。単に目撃しただけ、みたいな。
でもそうなると回想と合わなくなるしな。錯乱でいいか。
** ライン
*** オープニング(駅)
どうして忘れていたんだろう。
あれは間違いなく事実だ。確かに覚えている。
感触すら浮かぶ。忘れられる？
暴露されるとどうなる？俺は正常だ。
昨日までは、何も問題なかった。そう、何も問題なかった。本当に？

奇妙だと思うことはあった。時間は伸び縮みしたし、常に画面越しに見ているような感じがしていた。
あれは目の前だったんだ。世界は長方形でなくてオレンジのカーブミラーだということを忘れてはいけない。
でもそんなことはどうだっていい。もうすぐわかる。あと16秒もすればわかる。完全に忘れるか、現実に戻してくれる。本当の目覚めだ。
*** 家
テレビを見ていた。ドアベルが鳴った。夜9時頃だ。宅配を頼んでいない。面倒な感じがした。
Q. 開ける？
A1. 開けた。ドアの前には見覚えのない両方スーツの中年の男と若い男が立っていた。
ああ、しまった、と思った。厄介な感じがする。

A2. テレビの音量を少し下げて、そのまま無視した。
居留守だと明らかだからか、しばらくドアベルが鳴らされた後、静かになった。
その後来客が誰だったのかはわからず、来たことを思い出すことすらなかった。
*** 思い出せないこと
どなたですか。
ああ、刑事さん。

え、平川陽一のことについて聞きたい？
俺は昔のことをあまり覚えてないんですが。昔からそうですよ。
よく幼少期のことを覚えていて、そういう話しをしてくる人いるじゃないですか。ああいうのには全然ついていけなかったですね。
自分のことを言われて覚えてることもあったけど、ほとんどは見に覚えのないことで。
中学生のころっていうと、今から20年以上前のことでしょう。
俺は3年前のことですら怪しいですよ。

とにかくその時期になにを考えてるかってことが思い出せないんです。
本とか映画とかニュースの出来事とかは割合覚えてるけど、個人的な出来事になるとね。
あまり忘れるんで日記をつけてるんだけど、後から見るとまったく自分だって思い出せないんだよ。
何の話しだったっけ。ああ平川のことか。

何か事件でも起こしたんですか。
ああ、自殺。
正直いって昔のことすぎて、何にも実感わかないですね。
もちろん悲しいとは感じますけど。

そういう調査って中学の関係まで広げるんですね。
あいつも関東だったよな。あ、東京の方出てきてたんですね。
なるほど、不自然な部分があるから詳しくいろんな人に聞いてると。
うん、あまり関係が多いタイプではない、から、難航している、と。

どんな人間だったかっていうと、うーん。
まず性格的なところをいうと、ちょっと言いづらいけど、そんなに善良な人間じゃなかったと思いますね。
少なくとも中学の時点ではですが。

実家は九州の端の海と山に囲まれた田舎なんですが、大体田舎の人って聞いて想像するのって素朴な人じゃないですか。
悪い人なんかいないから鍵もかけない善良な人、みたいなの想像すると思います。
で、実際のところそれは合ってるわけですね。周りの大人や同級生はみんなのほほんとしてました。
でも平川はそのイメージに当てはまらない感じだったんですね。
ワルとは違ったんですが、とにかく意地が悪かったんですね。
陰口ばっかりって感じですね。自分がいないときでは自分の陰口を言ってるだろうな、てのがわかるような。

最初出会ったころは意気投合したというか、仲よく遊んだものだけど、でも次第に話さなくなっていきました。ゲームとか漫画の趣味が合ったんですけど。
田舎の学校で人数が少なかったから、割とよく顔を合わせてたんだけど、最後の方はほとんど話すことはなかったですかね。
卒業してからは会ってないですね。中学の連中で集まっても、そいつだけ呼ばれてなかったように思います。俺が呼ばれてなかっただけかもしれないですが。

家族関係ですか。
聞いたことないですね。家へ遊びに行ったことはあります、比較的裕福な、普通の家庭に見えましたね。家は広かったですね。

何か印象的な出来事ですか。
僕の話、参考になってます？昔だし個人的すぎて僕の思い出話になっちゃってますけど。
あ、じゃあ続けます。

そうだな、話してるうちに少し思い出してきました。うん、やっぱりあまりいい話しじゃないですが。
川平を家に呼んだときに金がなくなってたことがありました。
財布とかじゃなくて、おもむろに机の上に置いてあったお金ですね。
どこか外に遊びに行くときに親にせびる金、みたいなやつがあったんです。親は外聞を気にする人だったから、外で遊ぶときはよくその金がリビングの机に置いてあったんですね。その金がなくなってたことがありました。
別に当時はなんとも深く考えることもなく、別に疑ってもいなかったですけど。今考えると盗まれてたのかな、って思うんですね。
中学生だからせいぜい2000円くらいですかね。それが何回かあったんです。
それまで牧歌的な人たちばかりと接してきましたので、ある意味で一番衝撃的な人物だったかもしれません。
*** 出来事の回想(承)
ほかに？あとは…探検のことかな。ちょっと長くなるけど大丈夫？
うん。
そうだな、近所にコンビニくらいの大きさのコンクリの壁の建物があって、平川とそこに入ってみたことがあるんだ。
たまにそういうちょっと危ないことをした。
周りは田んぼが延々と広がる中に、ぽつんと1軒だけ木に囲まれた建物だった。
あまり日当たりがよくなくてコンクリの外壁は湿気で黒ずんでて汚なかった。
明らかに人は住んでない雰囲気で周囲は雑草が生え放題だった。
鍵がかかっていたけど、どこか閉まってない窓から入って開けた気がする。中は倉庫だった。何か工業関係の企業の倉庫だったのか、埃をかぶった大量の工具や、作業台があった。最初のころは腐敗臭、かびの臭いもひどかったもんだけど、窓を開け放してちょっと掃除したりしてましになった。秘密基地って感じで、川平とは休日そこで遊ぶことがあった。

そうそこで、今でも奇妙に思うことがあった。
そこに一人で夜行ったときのことだ。
たぶん忘れ物でもしたか何かだったと思うんだけど、ライト片手に行ったわけ。
夜に行く倉庫は恐ろしかった。昼間でも不気味だからさ。
忘れもの…ゲーム機か何かだったかな、は入り口に近い、いつも座っていた事務椅子の近くにはなかった。
びくびくしながら奥へ進んでいって、一番奥のほうのソファにあるのを見つけた。
それから体とライトの向きを変えたとき、何か見覚えのないモノが転がっていたような気がして、ライトをそれにあてた。

人っぽいモノが転がっていた。うつぶせの黒い髪と、作業服が見えたと思う。完全に動転してそのまま走って飛び出したから、後から冷静になって考えるとアレがなんだったのかはわからない。あるいは単なる毛布の塊だったのかもわからない。
何もなかったことは確かだと思う。忌々しくなり、その後全く寄り付かなくなった。1ヶ月後くらいに落ち着いてから昼間見に行ったけど、やっぱりその位置には何もなかった。見間違いになりそうなものも何もない空間で、ただの床と壁だった。

元々一人で行くことはなかったから、川平と遊ぶこともなくなって、それっきり行かなくなった。
あれは何だったんだろうな、と今でも思う。
あまり異質で、出来事自体が夢だった気もする。
*** 警察(転)
遺書で、出来事の詳細が綴られていた。
刑事は完全に事情を把握して、真相を話す。
詳細な事実を言われると思い出す。衝撃を受ける。
*** 刑事の所感(解説)
知らずに生きてたのを埋めた。

- 社会のつながりがなくなっていたため、外部記憶の欠損
- 話そうとしたり、聞いたりで記憶は回復する。たしかに存在するが思い出せないだけ。後悔する
- 気にかけてくれる人は誰もいない、と思ってたけどあいつにもいたはずだ
- 聞き取りをしてみると、けっこう印象深い人物として挙げられていたよ
- 人のネットワークが記憶を維持させる
*** memo
空白の記憶期間がある。
昔の記憶が出てこない。自分自身が誰かわからなくなることがある。
死んだ友人のことを思い出す。
