:PROPERTIES:
:ID:       585d3b5e-989d-4363-bcc3-894402fcfcf9
:END:
#+title: Shell

* 概要
シェルスクリプトはUnixシェルで使われる[[id:868ac56a-2d42-48d7-ab7f-7047c85a8f39][Programming Language]]。
* Memo
** 一括削除
TODO: xargsシリーズどこかにまとめたい。
#+begin_src shell
find . -name "*.log" | xargs rm -fv
#+end_src

findでファイルのリストを作成して、xargsに渡す。
xargsはファイルを1つずつrmに渡す。

xargsにはdry-runモードがある。
#+caption: pオプションがついてると生成コマンドを確認するだけで実行しない
#+begin_src shell
find . -name "*.log" | xargs -p rm -fv
#+end_src

[[https://techblog.kyamanak.com/entry/2018/02/12/202256][【Linux】xargs コマンドの使い方がよく分からない - きゃまなかのブログ]]
** リポジトリ内一括置換
git grep、xargs、sedを組み合わせる。

#+caption: リポジトリの2.6.5という文字列を2.7.1に置換する例
#+begin_src shell
git grep -l '2\.6\.5' | xargs sed -i 's/2\.6\.5/2.7.1/g'
#+end_src

- git grepの ~l~ オプションはヒットしたファイル名を出力する。
- xargsは標準出力からリストを読み込み、出力を次のコマンドの引数に渡すコマンド。
- sedは置換。 ~i~ オプションは結果を画面出力しないオプション。 本来は ~sed -i "s/aaa/bbb/s" Gemfile~ みたいな順だが、xargsで自動で渡されている。
** 一括git clone
[[id:6b889822-21f1-4a3e-9755-e3ca52fa0bc4][GitHub]]から、
個人 or 組織のリポジトリをすべてダウンロードする方法。
#+begin_src shell
curl https://api.github.com/users/{USER}/repos?per_page=100 | jq .[].ssh_url | xargs -n 1 git clone
#+end_src

#+begin_src shell
curl https://api.github.com/orgs/{ORG}/repos?per_page=100  | jq .[].ssh_url | xargs -n 1 git clone
#+end_src

~?per_page=100~ をつけないとデフォルトの30件しか取ってこないので注意。
100を超えるとページを指定する必要がある。

- https://tic40.hatenablog.com/entry/2018/03/26/073000

参考に読む用リポジトリは、organizationにまとめておく。
ローカルですぐ閲覧できて便利。
** Cinnamonのコントロールパネルを出す
これが起動できればサウンドやディスプレイ設定もできる。
#+begin_src shell
cinnamon-settings
#+end_src
** 失敗時例外を出す
#+begin_src shell
  #!/bin/bash

  set -e

  # ...
#+end_src
というように、しておくと、実行時できなかったときにエラーメッセージを出す。
何も指定しないと、どこで失敗したのか把握するのが困難。
ローカル環境だといいのだが、CIだと確認コストがかかるので必ず指定しておくとよい。
** デバッグメッセージ出力
#+begin_src shell
  #!/bin/bash -x

  # ...
#+end_src
-xをつけると評価結果を逐一出力する。
** GNOMEの音量調整
#+begin_src shell
  pactl set-sink-volume @DEFAULT_SINK@ +5%
  pactl set-sink-volume @DEFAULT_SINK@ -5%
#+end_src
**  カレントディレクトリ行数カウント
#+begin_src shell
  wc -l `find ./ -name '*.el'`
#+end_src

別解。
#+begin_src shell
  git ls-files *.org | xargs wc -c | sort -n
#+end_src
** ディレクトリの全ファイルで実行する
#+begin_src shell
  for file in `\find ./src -name '*.py'`;
  do
  echo $file
  python $file | sed -e s/.*[0-9]m// >> ./docs/query.org
  done
#+end_src
** port検索
port already in used. が出たとき。

プロセスを探す。
#+begin_src shell
  sudo lsof -i:5432
#+end_src

ポートを使ってるプロセスを削除する。
#+begin_src shell
sudo lsof -t -i tcp:5432 | sudo xargs kill -9
#+end_src
** LinuxでWindowsのブートメディアを作成する
woeusbというパッケージをインストールして行う。
#+begin_src shell
  sudo add-apt-repository ppa:tomtomtom/woeusb
  sudo apt update && sudo apt install woeusb-frontend-wxgtk
#+end_src
https://www.omgubuntu.co.uk/2017/06/create-bootable-windows-10-usb-ubuntu
** apt
aptはdebian系ディストリビューションで用いられるパッケージマネージャ。
- パッケージ検索
#+begin_src shell
  apt search libffi
#+end_src
** suspend
コマンドでサスペンドする方法。

Ubuntuのとき。
#+begin_src shell
  sudo pm-suspend
#+end_src

GNU Guixのとき。
#+begin_src shell
  loginctl suspend
#+end_src
** pgrep, pkill
簡単に検索、killできる。
#+begin_src shell
  pgrep firefox
  pkill firefox
#+end_src
* References
* Tasks
** TODO [[https://www.itmedia.co.jp/enterprise/articles/0811/20/news019.html][インストール済みUbuntuのクローンを新しいハードディスクに作成する：Linux Hacks（1/2 ページ） - ITmedia エンタープライズ]]
まとめておく。
