:PROPERTIES:
:ID:       ddc21510-6693-4c1e-9070-db0dd2a8160b
:header-args+: :wrap
:END:
#+title: Rust
* 概要
RustはC言語、C++の置換を目指した[[id:868ac56a-2d42-48d7-ab7f-7047c85a8f39][Programming Language]]。

- 性能
- メモリ安全性
- 安全な並行性

を特徴とする。

[[id:4270d99a-d2b5-429e-b33c-c2e097b20730][Zig]]と方向性が同じ。
* Memo
** print
#+begin_src rust
  println!("hello world!");
  println!("{} days", 31);
  println!("{0}, this is {1}, {1}, this is {0}", "Alice", "Bob");
  println!("{} of {:b} people know binary, the other half doesn't", 1, 2);
  println!("{number:>0width$}", number=1, width=6);
  println!("{subject} {verb} {object}", object="the lazy dog", subject="the quick brown fox", verb="jumps over");
#+end_src

#+RESULTS:
#+begin_results
hello world!
31 days
Alice, this is Bob, Bob, this is Alice
1 of 10 people know binary, the other half doesn't
000001
the quick brown fox jumps over the lazy dog
#+end_results

引数チェックもしてくれる。
#+begin_src rust
  println!("My name is {0}, {1} {0}", "Bond");
#+end_src

#+RESULTS:
#+begin_results
error: invalid reference to positional argument 1 (there is 1 argument)
 --> /tmp/babel-wnDbpn/rust-W98kSP:2:27
  |
2 | println!("My name is {0}, {1} {0}", "Bond");
  |                           ^^^
  |
  = note: positional arguments are zero-based

error: aborting due to previous error
#+end_results

マーカーの変更。
#+begin_src rust
  println!("This struct `{}` won't print...", Structure(3));
#+end_src

#+RESULTS:
#+begin_results
error[E0425]: cannot find function, tuple struct or tuple variant `Structure` in this scope
 --> /tmp/babel-wnDbpn/rust-If17CF:2:45
  |
2 | println!("This struct `{}` won't print...", Structure(3));
  |                                             ^^^^^^^^^ not found in this scope

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
#+end_results

#+begin_src rust
  #[derive(Debug)]
  struct Structure(i32);
  println!("This struct `{:?}` won't print...", Structure(3));
#+end_src

#+RESULTS:
#+begin_results
This struct `Structure(3)` won't print...
#+end_results

* パッケージ
** [[id:1ad8c3d5-97ba-4905-be11-e6f2626127ad][Emacs]]をRustで書き直すプロジェクト
EmacsのC言語で書かれた部分をRustに書き直すリポジトリがある。
[[https://github.com/remacs/remacs][remacs/remacs: Rust Emacs]]
** 超高速なripgrep
高速検索するripgrepは、ほかのどのgrepツールより早いらしい。

- repository :: [[https://github.com/BurntSushi/ripgrep][BurntSushi/ripgrep]]
** 新世代の[[id:585d3b5e-989d-4363-bcc3-894402fcfcf9][Shell]]nushell
[[id:fa497359-ae3f-494a-b24a-9822eefe67ad][System Crafters]]の動画[[https://www.youtube.com/watch?v=IHeKUeO7bpo][Integrating Nushell with Emacs]]のコラボ回で出たパッケージ。
リッチな出力形式、便利コマンドがすごい。
- repository :: [[https://github.com/nushell/nushell][nushell/nushell: A new type of shell]]
* Tasks
** TODO [[https://doc.rust-jp.rs/rust-by-example-ja/][Introduction - Rust By Example 日本語版]]
** TODO [[https://doc.rust-jp.rs/book-ja/title-page.html][The Rust Programming Language 日本語版]]
* Reference
- [[https://ja.wikipedia.org/wiki/Rust_(%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0%E8%A8%80%E8%AA%9E)][Rust (プログラミング言語) - Wikipedia]]
* Archives
