:PROPERTIES:
:ID:       ed146d63-0e55-4008-98e8-2a2f1f7329b5
:END:
#+title: Novel Game
#+filetags: Project

* 概要
ノベルゲームを作成する。

[[id:da7ec7fb-e585-4699-85dc-172c5060499a][Phaser]]がとてもよい。
ブラウザでプレイできるようにする。
* Tasks
** TODO シーン遷移をアニメーションさせる
** TODO 文字をアニメーション表示する
一気にパッと出すのではなく、アニメーションで出したい。
** TODO プロンプトをアニメーション表示する
次がクリックできますよ、ということを示すために。
固定位置だとできるんだが、微妙だな。
一番ベストなのは、文末で▽を表示してゆっくりと点滅させることだ。
* Memo
** WEB上で作成まで
今jsonで書いてるところをWEB上でできるようにすれば、WEBビルダーが作れる。
* Reference
** [[https://qiita.com/non_cal/items/622108030aa2e516260c][TypeScriptを使ってノベルゲームを作ろう - Qiita]]
最低限のノベルゲームが作成できる。非常に参考になる。
* Archives
** DONE bundleするとパスが変わって読み込めない問題
CLOSED: [2021-10-31 Sun 17:32]
開発時と本番環境での、ファイルパスのズレが生じる。

カレントディレクトリはsrcディレクトリになってるようなので、そこからの相対指定でできた。
* Prot
クソだが、とりあえず完成させてみる。
** キャラ
*** 北島
30代後半。サラリーマン、独身。九州の田舎出身。
恋人、友人なし。
社会とのつながりが切れている。
過去の記憶があまりない。
*** 川平
北島の中学時代の同級生。

病気で死亡、遺書を残す。
*** 刑事
北島を訪ねてくる刑事。
** オチ
廃墟で死体を見つける。
次に見たとき、死体はなくなっていた。
実は殺したのは自分で、その記憶をでっち上げていた。
それぞれ無関係そうな無邪気な遊びを、後から見ると恐ろしい行為として思い出す、ということ。
- 話す途中で断片的に思い出していき、疑心暗鬼になっていく
- 夢や個人だけの回想で少しずつ記憶を改変していた
- 不思議な出来事の真相が記憶改ざんだけなのは弱い
** オープニング
飛び込み。この動機が弱いんだよな。インパクトは大きいけども。
警察にバレるのではないかという恐怖(実際捜査は進んでる)。
幼少の記憶が戻って良心の呵責で？弱い。何かもうひと押し必要に思える。
記憶がないということへの絶望と、これまでいくつもの手を振り払ってきたことへの後悔。
思い出せないけど確かに存在したというのは希望な気もするな。

ミスリード、という手もある。単に目撃しただけ、みたいな。
でもそうなると回想と合わなくなるしな。錯乱でいいか。
** ライン
*** オープニング(駅)
どうして忘れていたんだろう。
あれは間違いなく事実だ。確かに覚えている。
感触すら浮かぶ。忘れられる？
暴露されるとどうなる？俺は正常だ。
昨日までは、何も問題なかった。そう、何も問題なかった。本当に？

奇妙だと思うことはあった。時間は伸び縮みしたし、常に画面越しに見ているような感じがしていた。
あれは目の前だったんだ。世界は長方形でなくてオレンジのカーブミラーだということを忘れてはいけない。
でもそんなことはどうだっていい。もうすぐわかる。あと16秒もすればわかる。完全に忘れるか、現実に戻してくれる。本当の目覚めだ。
*** 家
夜仕事を終えてテレビを見ていると、ドアベルが鳴った。来客などない時間帯なので、出るか出ないか逡巡する。
Q. 開ける？
A1. 開けた。ドアの前には見覚えのない両方スーツの中年の男と若い男が立っていた。
ああ、しまった、と思った。厄介な感じがする。

A2. テレビの音量を少し下げて、そのまま無視した。
居留守だと明らかだからか、しばらくドアベルが鳴らされた後、静かになった。
その後来客が誰だったのかはわからず、来たことを思い出すことすらなかった。
*** 思い出せないこと
どなたですか。
ああ、刑事さん。

え、平川陽一のことについて聞きたい？
俺は昔のことをあまり覚えてないんですが。昔からそうですよ。
よく幼少期のことを覚えていて、そういう話しをしてくる人いるじゃないですか。ああいうのには全然ついていけなかったですね。
自分のことを言われて覚えてることもあったけど、ほとんどは見に覚えのないことで。
中学生のころっていうと、今から20年以上前のことでしょう。
俺は3年前のことですら怪しいですよ。

とにかくその時期になにを考えてるかってことが思い出せないんです。
本とか映画とかニュースの出来事とかは割合覚えてるけど、個人的な出来事になるとね。
あまり忘れるんで日記をつけてるんだけど、後から見るとまったく自分だって思い出せないんだよ。
何の話しだったっけ。ああ平川のことか。

何か事件でも起こしたんですか
病死して、遺書でいくつか捜査が必要なことを書いていた？懺悔的なやつですかね。
内容については伏せてる、なるほど。まずは人となり的なことを取り調べしてると。

どんな人間だった、か。
まず性格的なところをいうと、ちょっと言いづらいけど、そんなに善良な人間じゃなかったと思いますね。
少なくとも中学の時点ではですが。

実家は九州の端にある田舎なんですが、大体田舎の人って聞いて想像するのって素朴な人じゃないですか。
悪い人なんかいないから鍵もかけない善良な人、みたいなの想像すると思います。
で、実際のところそれは合ってるわけですね。周りの大人や同級生はみんなのほほんとしてました。
でも平川はそのイメージに当てはまらない感じだったんですね。
ワルとは違ったんですが、とにかく意地が悪かったんですね。
陰口ばっかりって感じですね。自分がいないときでは自分の陰口を言ってるだろうな、てのがわかるような。

最初出会ったころは意気投合したというか、仲よく遊んだものだけど、でも次第に話さなくなっていきました。ゲームとか漫画の趣味が合ったんですけど。
田舎の学校で人数が少なかったから、割とよく顔を合わせてたんだけど、最後の方はほとんど話すことはなかったですかね。
卒業してからは会ってないですね。中学の連中で集まっても、そいつだけ呼ばれてなかったように思います。俺が呼ばれてなかっただけかもしれないですが。

家族関係ですか。
聞いたことないですね。家へ遊びに行ったことはあります、比較的裕福な、普通の家庭に見えましたね。家は広かったですね。

何か印象的な出来事ですか。
僕の話、参考になってます？昔だし個人的すぎて僕の思い出話になっちゃってますけど。
あ、じゃあ続けます。

そうだな、話してるうちに少し思い出してきました。
うん、やっぱりあまりいい話しじゃないですが。とにかく彼にはよくない印象があるんです。
川平を家に呼んだときに金がなくなってたことがありました。
財布とかじゃなくて、おもむろに机の上に置いてあったお金ですね。
どこか外に遊びに行くときに親にせびる金、みたいなやつがあったんです。親は外聞を気にする人だったから、外で遊ぶときはよくその金がリビングの机に置いてあったんですね。その金がなくなってたことがありました。
別に当時はなんとも深く考えることもなく、別に疑ってもいなかったですけど。今考えると盗まれてたのかな、って思うんですね。
中学生だからせいぜい2000円くらいですかね。それが何回かあったんです。
それまで牧歌的な人たちばかりと接してきましたので、ある意味で一番衝撃的な人物だったかもしれません。
*** 廃墟探検(承)
あとは廃墟探検のことですかね。
近所にコンビニくらいの大きさのコンクリの建物があって、平川とそこで遊んでた時期があるんですね。
周りは田んぼが延々と広がる中に、ぽつんと1軒だけ木に囲まれた建物でした。周囲は雑草が生え放題でした。
あまり日当たりがよくなくてコンクリの外壁は湿気で黒ずんでて汚なかったですね。
外観から明らかに居住用というよりは何かの倉庫みたいな感じでした。
鍵がかかっていたけど、どこか閉まってない窓から入って開けた気がします。やっぱり中は倉庫でした。
企業か何かの倉庫だったのか、埃をかぶった大量の工具や、大型の作業機械がありました。
最初のころは腐敗臭、かびの臭いもひどく、窓を開け放してちょっと掃除したりもしました。
秘密基地って感じで、川平とは休日そこで遊ぶことがありました。
まだ遊んでた頃は、たまにそういうちょっと危ないことをしてた仲、と言えるかもしれません。

ああ、そういえば今でも奇妙に思うことがありました。川平はあまり関係ないですけど。
夜一人で倉庫に行ったことがあります。
昼間に川平と倉庫で遊んだあと、夜忘れ物を取りに行きました。
ライト片手に行きました。昼間でも薄暗くて不気味ですが、夜に行く倉庫はさらに怖かったです。
忘れものは携帯ゲーム機でした。まず入り口に近い、いつも座っていた事務椅子の近くを探してもありませんでした。
あとありそうなのは一番入り口から遠いところにあるソファ付近でした。左右を照らしながら慎重に進みました。
目的のものはソファの脇にある低い背の棚の上にありました。いつも本や飲み物を置いているところです。
ポケットにゲームを入れて体とライトの向きを変えました。そこで見覚えのないモノが一瞬照らされた気がして、ライトをそれに向けました。

確かに人っぽいモノが転がっていたんですね。うつぶせの黒い髪と、作業服が見えました。
動転していて、そのあとどうやって帰ったかは…覚えてないです。後から冷静になって考えるとアレがなんだったのかはわからないです。あるいは単なる壁のシミや毛布の塊だったのかもしれません。
翌日明るいうちに確かめに行きましたが、目撃した位置には何もなく、僕の見間違えだったようです。

川平と遊ぶこともなくなって、元々一人で行くことはなかったから、それっきり倉庫にも行くことはなくなりました。
あれは何だったんだろうな、と今でも思います。
あまりに異質で、出来事自体が夢だった気もする。夜行ったこともそうだし、目撃したときどう帰ったかも独立して記憶にあります。夢ってこんな感じじゃないですか。突然そのシチュエーションになっていて、何も違和感を覚えない、みたいな。

長くなりましたが、こんな感じですかね。
すいません、長々と関係ない話しを。つい思い出してしまって。今まで誰にも話したことがありませんでした。

あ、いえいえ。
意外に覚えてるものですね。あまりいい話しじゃなかったけど、お役に立てば。
はい、遅くまでご苦労さまでした。それではまた。

扉を閉めて、立ち尽した。
*** 刑事の会話
二人の刑事は停めていた車に乗り込んだ。
「ピンポイントで遺書の出来事を話してくれるとは思いませんでしたね。20年前の関係を辿るのは大変かと思ってましたが、幸先いいですね」
「そうだな。内容とも辻褄は合っているしな。新証言ではあるけど、これ以上捜査しようもない。内容の裏取りだけで十分だろ。まあ内容が一致しすぎて不自然すぎる感じはある。でもだとしたら、北島が自分から遺書の内容を言うことはないだろう。」
*** 思い出す
今に刑事が引き返してくるのではないかと思って、ドアスコープを覗いていた。汗で服が皮膚にへばりついている。
オレは、話している途中からぼんやりと感触が蘇ってくるのを感じていた。
冷たく、ずっしりとした鉄筋の棒で柔らかいものを殴りつけて潰したとき、手に伝わってくる感覚。血の臭い。土にめり込むシャベル。重たい土。土と草の臭い。

ぐったりとしたそれが動き出したとき、恐怖と不法侵入している自覚で反射的に殴りつけた。動かなくなったとき、二度と戻らないことに気づいた。明かりをつけると窓から丸見えなのに気づいて、ライトを消した。真っ暗な闇の中で、すべてを行った。視覚のかわりに鋭くなった感覚だけが、行為を覚えていた。

刑事は、川平の遺書にあった倉庫の事件を調査しに来たんだろう。
*** 刑事の所感(解説)
知らずに生きてたのを埋めた。

- 社会のつながりがなくなっていたため、外部記憶の欠損
- 話そうとしたり、聞いたりで記憶は回復する。たしかに存在するが思い出せないだけ。後悔する
- 気にかけてくれる人は誰もいない、と思ってたけどあいつにもいたはずだ
- 聞き取りをしてみると、けっこう印象深い人物として挙げていた
- 人のネットワークが記憶を維持させる
*** memo
空白の記憶期間がある。
昔の記憶が出てこない。自分自身が誰かわからなくなることがある。
死んだ友人のことを思い出す。
