:PROPERTIES:
:ID:       a04ab4c3-a7de-4c73-8570-865b3db61ebb
:END:
#+title: chore
* 概要
再利用できそうな生活のメモをまとめる。
* 自己紹介で使うシリーズ
** 好きなゲーム
- [[id:7c01d791-1479-4727-b076-280034ab6a40][Simutrans]]
- Rimworld
- Cataclysm - Dark Days Ahead
- Elona
- Factorio
** 好きな映画
カタカナばっかりだな。

- アウトブレイク
- ボーンシリーズ
- トランスフォーマー(1, 2)
- ハリーポッター
- インセプション
** 好きなアニメ
- さよなら絶望先生
- 攻殻機動隊
- 交響詩篇エウレカセブン
** 好きな食べ物
- 数の子
- ラーメン
- 油そば
** 嫌いな食べ物
- 脱脂綿
- ティッシュ
- チョコミント
** 好きな作家
- 村上龍
** 好きな芸能人
- 伊集院光
** 好きな歌手
- ミスチル
- 大槻ケンヂ
** 余暇の過ごし方
- コード読み書き
- 環境改善([[id:1ad8c3d5-97ba-4905-be11-e6f2626127ad][Emacs]]、[[id:49971784-7850-4d24-92f2-9c6f29bd332e][system]])
- 映画鑑賞
- game
* 持ち出しリスト
- 耳栓
- アイマスク
* Best Goods
** _
買って最高だったもの。
何らかの理由で失ったときに元の環境へ戻せるために書く。
** Realforce * 2
2台置いて、片手ずつで使っている。肩こりがない。
** 4K モバイルディスプレイ + グラボ
15.6型の4Kモバイルディスプレイ。特定のメーカーが良いというのはない。

フォントの綺麗さを最優先している。 4Kでスケーリング2倍は最高に綺麗(作業領域はHDと変わらなくなる)。同じ解像度だと画面が小さいほどピクセルは小さくなるので、美しくなる。

4K表示はそれなりにマシンパワーを使うようで、ある程度のグラフィックボードがないと動きが遅くなる。
** ノイズキャンセリングヘッドホン
SONY WH-1000XM3 を使っている。

ノイズキャンセリングモードをオンにしたときの静寂がすごい。
部屋ってこんなにうるさかったんだ、とわかる。マシンのファンの回る音、エアコンの音、隣のビルのドアを占める音、夜になると聞こえる謎の重低音、冷蔵庫の音…が消えた。静寂を楽しむために音楽を何も流さずにヘッドホンつけるレベル。

大学から一人暮らしを初めて以降、音に対して神経質な問題が常にあり、いくつかの策を試したがうまくいっていなかった。このノイズキャンセリングヘッドホンにより問題は完全に解決した。間違いなく人生を変えた買い物。

⚠重要なこと: いくつかの挙動はスマートフォンアプリを通じて設定できる。初期設定ではBluetoothに接続してないと5分で電源が切れる挙動は変えられる。これを知らず接続だけして音楽は流さない、という使い方を半年くらいしていた。接続しなくても電源を切らないように設定できる。
** 耳栓
寝るときは耳栓してると安眠できる。最初はいろんなタイプの耳栓が1セットずつ入っているパックがあるのでそれを買ってよさそうなものを試した。サイズや柔らかさが合っているかによって長くつけやすさが変わる。

[[https://www.amazon.co.jp/-/en/gp/product/B00L0507PW/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1][Amazon.co.jp: MOLDEX Disposable Ear Plugs without Cord, : Health & Personal Care]]
** アイマスク
暗くしたいというより、目の疲れが取れやすい。起きたときに目が乾いているのを防げる。特に冬。
** Apple Magic Trackpad
スクロールのために使用。
これでないとパソコンで長時間の読書ができない。
読書中ずっと触るものであるので、自然な姿勢で使えるようにする必要がある。
微調整がかなり効き、大量のスクロールも可能。手触りが良い。

いくつも試してきたが、最終的にApple Magic Trackpadに落ち着いた。
互換性を心配したが、[[id:7a81eb7c-8e2b-400a-b01a-8fa597ea527a][Linux]]でも問題なく使える。
- マウスのホイール
  - 指が痛くなる
  - 微調整が効かない
- ボリュームノブ
  - 使いにくい。横方向の回転は自然な動きでない
  - 微調整が効かない
- ワイヤレス片手マウス
  - 結局ホイールで指が痛い
  - 手を机に置かなくていいので姿勢の自由度が高い
  - トリガーボタンをスクロールに割り当てられれば良さげ
- フットペダル
  - 全く微調整が効かない
  - 脚を常に置くのが面倒
  - 間違えて押す
- コントローラ
  - トリガーボタンをページ送りにして使用
  - 押し心地はかなりいい
  - 両手で持たないといけないのが致命的
PCでの読書のページ送りのために使っている。
マウスのスクロールは腱鞘炎になりやすく、スクロールの精度もあまりよくない。何百ページもあるときつい。

トラックパッドだと微細な操作と大きな操作が両方できるので、読書に向く。さらに操作の自由度が高いので腱鞘炎になりにくい。
** 加湿器
冬に目が乾くのを防ぐために使う。
** LAN切替器
集中したいときに良い。
* ローカル環境でのマルチプレイ
ローカル環境でPCマルチプレイゲームをするとき(年末とか)毎回困るのでメモ。
一番良いのは、人数分のマシンを用意して、オンライン対戦にすること。多くの種類のゲームが楽しめる。

準備。
Steamクライアントを準備しておく。
ゲームもダウンロードしておく。
時間がかかるので、前もって準備する。
コントローラを用意しておく(画面分割できる類のゲームのときは)。キーボード1つでできるのもあるが、多くない。
年末など親戚があつまるときに、同年代の人とやることがなくて困る。ゲーム機とかはないので、毎回パソコンでなにかやろうとするのだが、パソコンのゲームにはローカルでできるものが意外となくて困る。
* 部屋の条件
+ 静音性
  - 大きな道路に面していない
  - 付近に線路・駅がない
  - 付近に店がない
  - 部屋の中に引き戸がない(ドアがない)
  - 3階以上(騒音＋水害)
  - 鉄筋コンクリート造
  - 最上階
  - 角部屋(できれば通路の一番奥側)
  - 単身者の広さ
  - 学校が近くにない
+ 便利さ
  - 弁当屋が近い
+ 優先しない項目
  - 交通の便
  - 日当たり
* Tasks
* Reference
* Archives
