:PROPERTIES:
:ID:       a9fab970-2057-48ce-95ee-19964d639a38
:END:
#+title: Project

* Project
よい個人プロジェクトとは。

- ワクワクすること
- 1ヶ月以内で終わること
- 何か形として残ること
- テストしやすいこと
- 新しく学ぶことが絞られていること
- 成功か失敗かわかりやすいこと
- 他人からのフィードバックが得られること

がある。新鮮な気分でテーマを掘り下げられる。
* Memo
** ゲームの問題点
ゲームの問題点。遊ぶ人が自分だけであること。
ゼロからやるのは楽しいが、結局大きすぎて途中で飽きる。
* Tasks
** CLOSE テキストベースのゲーム
CLOSED: [2021-08-31 Tue 23:20]
[[id:70f249a8-f8c8-4a7e-978c-8ff04ffd09c0][digger]]で行った。
- テストしやすいためテキスト主体。
- ローグライク
- アドベンチャーゲーム
** TODO DBゲーム
話がデカすぎてやる気が持続するとは思わないが。

自動生成操作をするプログラムをユーザに見立てて、dbアプリを作成する。出来ていくデータを眺める。とにかく重要なのは、生身のユーザを必要としないことだ。
基本的に眺める楽しさ。

viewは一切開発せず、直にパブリックメソッドを実行するbotを仮想ユーザとして考える。何かイベントを与えると必要なことを行おうとする。経営のダッシュボードだけ可視化できるようにして、あとはルールとして実装する。あとで変更しやすいように、テキストで全管理できるDBにしたいな。
- 株
- 病院
- レンタルビデオ
- 人間関係ネットワーク。お互いに影響を与え合う様子。

パワポケのペナントモードという考え方もできる。チームという入力を入れると、試合データが出てくる。試合やチームによって、所属する選手は変化していく。それってシミュレーションゲーム。値を自由に入れることができないシミュレーション。
うむむ、DBを使う必要はあるんだろうか。
** TODO SimutransのCUI版
** TODO 倉庫番
でかいのに取り組むより、これくらいがよい。
- 空間の実装方法が理解できる。
** TODO プログラムゲーム
最低限の世界のルールを定めておいて、それをプログラムで解決するゲーム。
世界のルール: 物体は質量を持つ、移動には費用がかかる、その枠の中で自由にプログラムできる、というもの。本質的には、ルールセットを記述して戦うロボット的なゲームに似ている。でもそうやって具体的なひとつのケースを見るのではなくて、全体を見るところが違う。
** TODO サウンドノベル・web
- markdownを拡張してサウンドノベル用の文法を作る。
- webでmdを読み込んで表示できるようにする。
** TODO バッジ出力ツール
たとえばカバレッジ出力などは乱立している。
** TODO パッケージ作る
これが現実的か。
- 小さくていい。
- 他のを見て参考にできる。
- 一度理解すれば横展開がやりやすい。どこかにPR出せばスターがつきやすいのもいい。確実に需要がある。
** TODO 経済ゲーム
Practical Ruby Projectsに書いてあったやつ。経済シミュレーター。
[[id:b4f27aef-22ec-45c0-be50-810f3a0cf9bc][Money]]の知識と絡められないか。
* Archive
*** CLOSE Textlint Web
CLOSED: [2021-09-10 Fri 17:52]
- もうすでにある。
