:PROPERTIES:
:ID:       7c01d791-1479-4727-b076-280034ab6a40
:END:
#+title: Simutrans
* 概要
Simutransはフリーの交通シミュレーション[[id:8b79aef9-1073-4788-9e81-68cc63e4f997][game]]である。
シミュレーションの中で、現実の輸送の効率性について考えることができる。
* Memo
** マイ設定ファイル
[[https://japanese.simutrans.com/index.php?%C0%DF%C4%EA%A5%D5%A5%A1%A5%A4%A5%EB%2F%B9%E2%C5%D9%A4%CA%C0%DF%C4%EA][設定ファイル/高度な設定 - Simutrans日本語化･解説]]

- starting_money
  - スタート時の所持金。すぐに足りなくなるので100倍ほど増やす
- crossconnect_factories = 1
  - すべての産業施設を関連づける
- factory_maximum_intransit_percentage = 0
  - 輸送中の貨物量による制限をしない
- industry_increase_every = 5000
  - 産業チェーンを追加する都市の人口、倍々で8回まで有効。2000だと早く増えすぎなので5000に上げる
- tourist_percentage = 50
  - 旅客が観光地を目的とする割合。面白いので上げる
- passenger_multiplier=80
- goods_multiplier=80
- growthfactor_villages=200
- growthfactor_cities=100
- growthfactor_capitals=50
- station_coverage = 2
  - 駅の範囲を増やして楽にする
- maintenance_building = 20
- cost_multiply_station = 60
- max_rail_convoi_length = 250
- max_road_convoi_length = 250
- max_ship_convoi_length = 250
- max_air_convoi_length = 250
** 学び方
毎回奥ゆきのないマップになってしまう、という悩み。どうしたら、すごい人が作るような、見るだけでワクワクするようなマップを再現できるのだろう。
ヒントは現実世界にある。現実世界では物理的制約を抱えているために、すべてに理由がある。線路にカーブがあるのは、歴史的、地形上の理由があるためだ。そういうものが積み重なって、風景に奥行きがあるように見える[fn:1]。

[fn:1]現実だから奥行きがあるのは当然とも言えるが、郊外のショッピングセンターのように現実でも無感動な印象を与える風景はある。

ケースで考えるとよさそう。たとえば、東京の御茶ノ水駅あたりは興味深い。

- 渓谷のようになった神田川ぎりぎりにある
- 道路やほかの建物より低い位置にある
- 美しい聖橋のほぼ真下にある
- 3線が立体交差する

わかりやすく謎要素が多いので気づきやすい。調べると歴史的理由があって、興味深い。
奥行きとはこういうことなのだと教えてくれる。ゲームでも同様で、こういった「設定」を与えることができれば、奥行きが生まれるだろう。
** シミュレーションゲームを楽しむコツ
現実の事象について深く知っていてロールプレイ(妄想)できると、シミュレーションを100％味わうことができる。
実際の鉄道や路線、交通、都市について知らないと、ゲームのやり方やルールを学んでもあまりピンとこない。
ゲーム的にはたくさん旅客を集めてお金を稼げばいいわけだが、しばらくすると毎回ピンとこない感じになる。

同じ例。
シムシティの退屈な街並み。碁盤の目で整然とした道路に、同じ形をした高層ビルが何本も立っている。実際にこういう都市は存在しない。魅力がなく、何回プレイしても同じような都市になるので、次第に飽きる。
Minecraftでの、豆腐建築。建物が単に同じ素材で作られた立方体になっている。こういった建築物は存在しない。やはり魅力や印象はなく、建築は単なる作業になる。

自由度の高いゲームでは、何が現実らしく見せているかを知っているとより楽しめる。
鉄道においては…。
- どのような事業会社があるか
- どのように路線が形成されているか
- どのような運行形態があるか
とか。

路線は最初に国鉄を考える。国鉄は利益というより要地を結ぶことを目的にする公共事業である。
路線は長大で、区間によって乗車率は大きく異なる。都市近郊では乗車率が高いが都市の中間では過疎地域もある。そこで限られた駅にしか停車しない急行や特急運行の概念が生まれる。都市圏内では各駅停車、定員の多い通勤用車両を使用し、都市間では高速な急行車両を使用する。

国鉄のカバーした路線を元に、各社私鉄が国鉄の路線から派生したり、より高速に結ぶ路線を作る。会社は沿線の不動産開発していたり、元は貨物輸送だったり、多様なバックグラウンドがある。旅客需要が多くなるにつれ、貨物線を旅客に転用したりもする。より大きな旅客を誘引するため、会社間で直通運転をするようになる。さらに発展すると、距離のある都市内交通の需要が高まり、かつ地上への建設困難なため地下鉄を建設する。

会社ごとのバックグラウンドを考えることで鉄道だけでなくて、別の交通についても考えることができるだろう。
効率的に捌くことだけを考えていると、出来上がるものは現実とは似つかないものになる。複雑度のない、表面的なものはうすっぺらくて魅力もない。

Minecraftも同様に考えてみよう。
多くの美しい建築物を知っていればよさそうだが、それだけでない。
↓といった背景を考えることで、街や建物の形が決まってくる。
- 住んでいる人
- 文化
- 気候。距離は近くても高度や海との距離によって異なる
- 産業。産業が有利だった点
- 歴史。なぜ人が集まったか、発展したか
- 交通
- 資源。どういう資源が比較的安く手に入るか
- 食文化。何を食べているか、飲水はどこで入手しているか
- 境界。類似な文化圏はどこまでか、何によって阻まれているか
- プレイヤー。政府、商人、軍事、農民。

背景を無視した、形だけ真似たようなものは、現実にもよくある。
日本中どこにでもある幹線道路沿いのロードサイド店が醜く見えるのは、背景がなく、だだっ広い場所にただ存在するからだ。
* Tasks
* Reference
** [[https://arx.neorail.jp/][A列車で理数探究：DATT-A9D【PS4・Windows両対応】]]
なんだかすごいサイト。
研究的視点から、シミュレーターとしてA列車を用いる。
* Archives
