:PROPERTIES:
:ID:       7c01d791-1479-4727-b076-280034ab6a40
:END:
#+title: Simutrans
* 概要
Simutransはフリーの交通シミュレーションゲームである。
シミュレーションの中で、現実の輸送の効率性について考えることができる。
* Memo
** シミュレーションゲームを楽しむコツ
現実の事象について深く知っていてロールプレイ(妄想)できると、シミュレーションを100％味わうことができる。
実際の鉄道や路線、交通、都市について知らないと、ゲームのやり方やルールを学んでもあまりピンとこない。
ゲーム的にはたくさん旅客を集めてお金を稼げばいいわけだが、しばらくすると毎回ピンとこない感じになる。

同じ例。
シムシティの退屈な街並み。碁盤の目で整然とした道路に、同じ形をした高層ビルが何本も立っている。実際にこういう都市は存在しない。魅力がなく、何回プレイしても同じような都市になるので、次第に飽きる。
Minecraftでの、豆腐建築。建物が単に同じ素材で作られた立方体になっている。こういった建築物は存在しない。やはり魅力や印象はなく、建築は単なる作業になる。

自由度の高いゲームでは、何が現実らしく見せているかを知っているとより楽しめる。
鉄道においては、どのように路線が形成されているか、どのような運行形態があるか、など。
路線は最初に国鉄を考える。国鉄は利益というより要地を結ぶことを目的にする公共事業である。
路線は長大で、区間によって乗車率は大きく異なる。都市近郊では乗車率が高いが都市の中間では過疎地域もある。そこで限られた駅にしか停車しない急行や特急運行の概念が生まれる。都市圏内では各駅停車、定員の多い通勤用車両を使用し、都市間では高速な急行車両を使用する。
国鉄のカバーした路線を元に、各社私鉄が国鉄の路線から派生したり、より高速に結ぶ路線を作る。
会社は沿線の不動産開発していたり、元は貨物輸送だったり、多様なバックグラウンドがある。
旅客需要が多くなるにつれ、貨物線を旅客に転用したりもする。
より大きな旅客を誘引するため、会社間で直通運転をするようになる。
* Tasks
* Reference
** [[https://arx.neorail.jp/][A列車で理数探究：DATT-A9D【PS4・Windows両対応】]]
なんだかすごいサイト。
研究的視点から、シミュレーターとしてA列車を用いる。
* Archives
