:PROPERTIES:
:ID:       fad0d446-fe06-4614-af63-a0c5ecc11c9c
:END:
#+title: workflow
#+filetags: :Habit:
* 概要
[[id:1ad8c3d5-97ba-4905-be11-e6f2626127ad][Emacs]]の[[id:7e85e3f3-a6b9-447e-9826-307a3618dac8][org-mode]]を使ってタスク管理している。

流れをまとめる。

- 今週やることを決めて、org-effortで時間目標を設定する
  - あまりでかすぎるものはチェックリストで分ける
- 朝、org-agenda(~C-c a~)を見てeffortの中から選ぶ
- 取り組む

今日できる、小さな目標を立てることが重要そう。がんばろうとなり、達成感を得られる。時間をかけることが目標になりにくい。短い時間でやろうと思える。そしてあとどれくらい残っているか、どの位置にいるかを把握せず長期間何かやることはむずかしい。

自分がどれだけの分量をこなせるかを知っていれば、パフォーマンスの指標にできる。何か変えてみるときにも、本当によい変更かわかりやすくなる。
* RepeatTasks

定期タスク。書いただけでは忘れるので、具体的な時刻を書いて通知させる。

** TODO Workout
SCHEDULED: <2024-04-13 Sat 14:00 +3d>
:PROPERTIES:
:STYLE:    habit
:LAST_REPEAT: [2024-04-14 Sun 11:40]
:END:
- State "DONE"       from "TODO"       [2024-04-14 Sun 11:40]
- State "DONE"       from "TODO"       [2024-04-07 Sun 19:11]
- State "DONE"       from "TODO"       [2024-04-04 Thu 00:32]
- State "DONE"       from "TODO"       [2024-04-01 Mon 20:07]
- State "DONE"       from "TODO"       [2024-04-01 Mon 20:06]
- State "DONE"       from "TODO"       [2024-04-01 Mon 20:06]
- State "DONE"       from "TODO"       [2024-03-24 Sun 00:06]
- State "DONE"       from "TODO"       [2024-03-24 Sun 00:06]
- State "DONE"       from "TODO"       [2024-03-24 Sun 00:06]
- State "DONE"       from "TODO"       [2024-03-24 Sun 00:06]
- State "DONE"       from "TODO"       [2024-03-24 Sun 00:06]
- State "DONE"       from "TODO"       [2024-03-24 Sun 00:06]
- State "DONE"       from "TODO"       [2024-03-24 Sun 00:05]
- State "DONE"       from "TODO"       [2024-03-04 Mon 19:19]
- State "DONE"       from "TODO"       [2024-02-28 Wed 00:16]
- State "DONE"       from "TODO"       [2024-02-28 Wed 00:16]
- State "DONE"       from "TODO"       [2024-02-28 Wed 00:16]
- State "DONE"       from "TODO"       [2024-02-19 Mon 19:23]
- State "DONE"       from "TODO"       [2024-02-19 Mon 19:23]
- State "DONE"       from "TODO"       [2024-02-19 Mon 19:23]
- State "DONE"       from "TODO"       [2024-02-11 Sun 00:41]
- State "DONE"       from "TODO"       [2024-02-08 Thu 09:02]
- State "DONE"       from "TODO"       [2024-02-05 Mon 22:29]
- State "DONE"       from "TODO"       [2024-02-05 Mon 22:29]
- State "DONE"       from "TODO"       [2024-02-01 Thu 22:11]
- State "DONE"       from "TODO"       [2024-01-28 Sun 23:03]
- State "DONE"       from "TODO"       [2024-01-25 Thu 00:17]
- State "DONE"       from "TODO"       [2024-01-21 Sun 23:23]
- State "DONE"       from "TODO"       [2024-01-18 Thu 00:12]
- State "DONE"       from "TODO"       [2024-01-14 Sun 20:13]
- State "DONE"       from "TODO"       [2024-01-13 Sat 19:45]
- State "DONE"       from "TODO"       [2024-01-10 Wed 21:10]
- State "DONE"       from "TODO"       [2024-01-05 Fri 17:04]
- State "DONE"       from "TODO"       [2024-01-02 Tue 21:58]
- State "DONE"       from "TODO"       [2024-01-01 Mon 19:24]
- State "DONE"       from "TODO"       [2023-12-27 Wed 00:25]
- State "DONE"       from "TODO"       [2023-12-24 Sun 00:22]
- State "DONE"       from "TODO"       [2023-12-24 Sun 00:22]
- State "DONE"       from "TODO"       [2023-12-18 Mon 22:08]
- State "DONE"       from "TODO"       [2023-12-18 Mon 22:08]
- State "DONE"       from "TODO"       [2023-12-18 Mon 22:08]
- State "DONE"       from "TODO"       [2023-12-10 Sun 15:00]
- State "DONE"       from "TODO"       [2023-12-10 Sun 15:00]
- State "DONE"       from "TODO"       [2023-12-04 Mon 20:46]
- State "DONE"       from "TODO"       [2023-12-04 Mon 20:46]
- State "DONE"       from "TODO"       [2023-12-04 Mon 20:46]
- State "DONE"       from "TODO"       [2023-11-25 Sat 12:14]
- State "DONE"       from "TODO"       [2023-11-25 Sat 12:14]
- State "DONE"       from "TODO"       [2023-11-18 Sat 15:17]
- State "DONE"       from "TODO"       [2023-11-17 Fri 00:23]
- State "DONE"       from "TODO"       [2023-11-12 Sun 16:14]
- State "DONE"       from "TODO"       [2023-11-11 Sat 23:12]
- State "DONE"       from "TODO"       [2023-11-06 Mon 20:30]
- State "DONE"       from "TODO"       [2023-11-03 Fri 21:47]
- State "DONE"       from "TODO"       [2023-11-01 Wed 22:00]

運動する。

** TODO Move entry
SCHEDULED: <2024-04-21 Sun 11:00 +1w>
:PROPERTIES:
:STYLE:    habit
:LAST_REPEAT: [2024-04-14 Sun 11:40]
:END:
- State "DONE"       from "TODO"       [2024-04-14 Sun 11:40]
- State "DONE"       from "TODO"       [2024-04-07 Sun 19:11]
- State "DONE"       from "TODO"       [2024-04-01 Mon 20:06]
- State "DONE"       from "TODO"       [2024-03-24 Sun 00:06]
- State "DONE"       from "TODO"       [2024-03-24 Sun 00:05]
- State "DONE"       from "TODO"       [2024-03-24 Sun 00:05]
- State "DONE"       from "TODO"       [2024-03-04 Mon 19:19]
- State "DONE"       from "TODO"       [2024-02-28 Wed 00:16]
- State "DONE"       from "TODO"       [2024-02-19 Mon 19:23]
- State "DONE"       from "TODO"       [2024-02-11 Sun 00:41]
- State "DONE"       from "TODO"       [2024-02-05 Mon 22:29]
- State "DONE"       from "TODO"       [2024-01-28 Sun 23:03]
- State "DONE"       from "TODO"       [2024-01-21 Sun 23:23]
- State "DONE"       from "TODO"       [2024-01-14 Sun 20:13]
- State "DONE"       from "TODO"       [2024-01-10 Wed 21:10]
- State "DONE"       from "TODO"       [2024-01-01 Mon 19:24]
- State "DONE"       from "TODO"       [2023-12-24 Sun 00:22]
- State "DONE"       from "TODO"       [2023-12-18 Mon 22:06]
- State "DONE"       from "TODO"       [2023-12-10 Sun 15:00]
- State "DONE"       from "TODO"       [2023-12-04 Mon 20:46]
- State "DONE"       from "TODO"       [2023-11-26 Sun 23:26]
- State "DONE"       from "TODO"       [2023-11-25 Sat 12:14]
:LOGBOOK:
CLOCK: [2023-11-25 Sat 12:05]--[2023-11-25 Sat 12:08] =>  0:03
:END:
- State "DONE"       from "TODO"       [2023-11-17 Fri 00:23]
- State "DONE"       from "TODO"       [2023-11-05 Sun 11:08]
- State "DONE"       from "TODO"       [2023-11-01 Wed 22:00]
- State "DONE"       from "TODO"       [2023-11-01 Wed 22:00]

取ったノートを適切な場所に分類する。

** TODO OSS contribute
SCHEDULED: <2024-05-01 Wed 10:00 +1m>
:PROPERTIES:
:LAST_REPEAT: [2024-04-01 Mon 20:07]
:END:
- State "DONE"       from "TODO"       [2024-04-01 Mon 20:07]
- State "DONE"       from "TODO"       [2024-03-01 Fri 12:58]
- State "DONE"       from "TODO"       [2024-02-01 Thu 22:11]
- State "DONE"       from "TODO"       [2024-01-01 Mon 19:24]
- State "DONE"       from "TODO"       [2023-12-10 Sun 15:00]
- State "DONE"       from "TODO"       [2023-11-02 Thu 08:35]
- State "DONE"       from "TODO"       [2023-10-01 Sun 14:31]
- State "DONE"       from "TODO"       [2023-09-02 Sat 11:52]
- State "DONE"       from "TODO"       [2023-06-01 Thu 23:29]
- State "DONE"       from "TODO"       [2023-06-01 Thu 19:32]
- State "DONE"       from "TODO"       [2023-06-01 Thu 19:32]
- State "DONE"       from "TODO"       [2023-05-01 Mon 00:32]
- State "DONE"       from "TODO"       [2023-04-01 Sat 10:17]
- State "DONE"       from "TODO"       [2023-03-01 Wed 12:04]

月に1回はコントリビュートする。

** TODO 片付け
SCHEDULED: <2024-04-21 Sun 14:00 +1w>
:PROPERTIES:
:STYLE:    habit
:LAST_REPEAT: [2024-04-14 Sun 11:40]
:END:
- State "DONE"       from "TODO"       [2024-04-14 Sun 11:40]
- State "DONE"       from "TODO"       [2024-04-07 Sun 19:11]
- State "DONE"       from "TODO"       [2024-04-01 Mon 20:06]
- State "DONE"       from "TODO"       [2024-03-24 Sun 00:06]
- State "DONE"       from "TODO"       [2024-03-24 Sun 00:06]
- State "DONE"       from "TODO"       [2024-03-24 Sun 00:05]
- State "DONE"       from "TODO"       [2024-03-04 Mon 19:19]
- State "DONE"       from "TODO"       [2024-02-28 Wed 00:16]
- State "DONE"       from "TODO"       [2024-02-19 Mon 19:23]
- State "DONE"       from "TODO"       [2024-02-11 Sun 00:41]
- State "DONE"       from "TODO"       [2024-02-11 Sun 00:41]
- State "DONE"       from "TODO"       [2024-01-28 Sun 23:03]
- State "DONE"       from "TODO"       [2024-01-21 Sun 23:23]
- State "DONE"       from "TODO"       [2024-01-14 Sun 20:13]
- State "DONE"       from "TODO"       [2024-01-10 Wed 21:10]
- State "DONE"       from "TODO"       [2024-01-01 Mon 19:24]
- State "DONE"       from "TODO"       [2023-12-24 Sun 00:22]
- State "DONE"       from "TODO"       [2023-12-18 Mon 22:08]
- State "DONE"       from "TODO"       [2023-12-10 Sun 15:00]
- State "DONE"       from "TODO"       [2023-12-04 Mon 20:46]
- State "DONE"       from "TODO"       [2023-11-26 Sun 23:26]
- State "DONE"       from "TODO"       [2023-11-19 Sun 10:42]
- State "DONE"       from "TODO"       [2023-11-12 Sun 16:14]
- State "DONE"       from "TODO"       [2023-11-05 Sun 23:35]
- State "DONE"       from "TODO"       [2023-11-01 Wed 22:00]
- State "DONE"       from "TODO"       [2023-10-22 Sun 19:02]

** TODO Write Entry                                                 :Train:
:LOGBOOK:
CLOCK: [2024-04-26 Fri 00:47]--[2024-04-26 Fri 01:12] =>  0:25
CLOCK: [2024-04-24 Wed 18:23]--[2024-04-24 Wed 18:48] =>  0:25
CLOCK: [2024-04-24 Wed 17:54]--[2024-04-24 Wed 18:19] =>  0:25
CLOCK: [2024-04-20 Sat 22:51]--[2024-04-20 Sat 23:16] =>  0:25
CLOCK: [2024-04-07 Sun 19:42]--[2024-04-07 Sun 20:07] =>  0:25
CLOCK: [2024-04-01 Mon 20:07]--[2024-04-01 Mon 20:32] =>  0:25
CLOCK: [2024-03-31 Sun 18:29]--[2024-03-31 Sun 18:54] =>  0:25
CLOCK: [2024-03-31 Sun 17:52]--[2024-03-31 Sun 18:17] =>  0:25
CLOCK: [2024-03-31 Sun 17:25]--[2024-03-31 Sun 17:50] =>  0:25
CLOCK: [2024-03-31 Sun 16:13]--[2024-03-31 Sun 16:38] =>  0:25
CLOCK: [2024-03-31 Sun 10:57]--[2024-03-31 Sun 11:22] =>  0:25
CLOCK: [2024-03-31 Sun 10:25]--[2024-03-31 Sun 10:50] =>  0:25
CLOCK: [2024-03-31 Sun 00:35]--[2024-03-31 Sun 01:00] =>  0:25
CLOCK: [2024-03-31 Sun 00:07]--[2024-03-31 Sun 00:32] =>  0:25
CLOCK: [2024-03-25 Mon 21:01]--[2024-03-25 Mon 21:26] =>  0:25
CLOCK: [2024-03-24 Sun 22:25]--[2024-03-24 Sun 22:50] =>  0:25
CLOCK: [2024-03-24 Sun 18:07]--[2024-03-24 Sun 18:32] =>  0:25
CLOCK: [2024-03-24 Sun 15:02]--[2024-03-24 Sun 15:27] =>  0:25
CLOCK: [2024-03-24 Sun 13:59]--[2024-03-24 Sun 14:24] =>  0:25
CLOCK: [2024-03-24 Sun 13:28]--[2024-03-24 Sun 13:53] =>  0:25
CLOCK: [2024-03-24 Sun 13:01]--[2024-03-24 Sun 13:26] =>  0:25
CLOCK: [2024-03-24 Sun 12:35]--[2024-03-24 Sun 13:00] =>  0:25
CLOCK: [2024-03-17 Sun 19:12]--[2024-03-17 Sun 19:37] =>  0:25
CLOCK: [2024-03-15 Fri 23:14]--[2024-03-15 Fri 23:39] =>  0:25
CLOCK: [2024-03-14 Thu 21:11]--[2024-03-14 Thu 21:36] =>  0:25
CLOCK: [2024-03-13 Wed 21:57]--[2024-03-13 Wed 22:22] =>  0:25
CLOCK: [2024-03-13 Wed 20:21]--[2024-03-13 Wed 20:46] =>  0:25
CLOCK: [2024-03-02 Sat 15:44]--[2024-03-02 Sat 16:10] =>  0:26
CLOCK: [2024-03-02 Sat 11:20]--[2024-03-02 Sat 11:45] =>  0:25
CLOCK: [2024-03-02 Sat 10:54]--[2024-03-02 Sat 11:19] =>  0:25
CLOCK: [2024-02-29 Thu 00:52]--[2024-02-29 Thu 01:17] =>  0:25
CLOCK: [2024-02-28 Wed 21:08]--[2024-02-28 Wed 21:33] =>  0:25
CLOCK: [2024-02-28 Wed 20:18]--[2024-02-28 Wed 20:43] =>  0:25
CLOCK: [2024-02-26 Mon 19:05]--[2024-02-26 Mon 19:30] =>  0:25
CLOCK: [2024-02-25 Sun 22:31]--[2024-02-25 Sun 22:56] =>  0:25
CLOCK: [2024-02-25 Sun 21:44]--[2024-02-25 Sun 22:09] =>  0:25
CLOCK: [2024-02-25 Sun 19:47]--[2024-02-25 Sun 20:12] =>  0:25
CLOCK: [2024-02-24 Sat 23:28]--[2024-02-24 Sat 23:53] =>  0:25
CLOCK: [2024-02-24 Sat 21:59]--[2024-02-24 Sat 22:24] =>  0:25
CLOCK: [2024-02-24 Sat 17:26]--[2024-02-24 Sat 17:51] =>  0:25
CLOCK: [2024-02-24 Sat 16:22]--[2024-02-24 Sat 16:47] =>  0:25
CLOCK: [2024-02-24 Sat 15:57]--[2024-02-24 Sat 16:22] =>  0:25
CLOCK: [2024-02-24 Sat 14:23]--[2024-02-24 Sat 14:48] =>  0:25
CLOCK: [2024-02-21 Wed 21:07]--[2024-02-21 Wed 21:32] =>  0:25
CLOCK: [2024-02-18 Sun 14:47]--[2024-02-18 Sun 15:12] =>  0:25
CLOCK: [2024-02-17 Sat 19:46]--[2024-02-17 Sat 20:11] =>  0:25
CLOCK: [2024-02-16 Fri 23:28]--[2024-02-16 Fri 23:53] =>  0:25
CLOCK: [2024-02-16 Fri 22:53]--[2024-02-16 Fri 23:18] =>  0:25
CLOCK: [2024-02-16 Fri 22:18]--[2024-02-16 Fri 22:43] =>  0:25
CLOCK: [2024-02-16 Fri 21:44]--[2024-02-16 Fri 22:09] =>  0:25
CLOCK: [2024-02-15 Thu 22:19]--[2024-02-15 Thu 22:44] =>  0:25
CLOCK: [2024-02-15 Thu 21:54]--[2024-02-15 Thu 22:19] =>  0:25
CLOCK: [2024-02-15 Thu 18:43]--[2024-02-15 Thu 19:08] =>  0:25
CLOCK: [2024-02-15 Thu 00:54]--[2024-02-15 Thu 01:19] =>  0:25
CLOCK: [2024-02-14 Wed 22:43]--[2024-02-14 Wed 23:08] =>  0:25
CLOCK: [2024-02-13 Tue 23:49]--[2024-02-14 Wed 00:14] =>  0:25
CLOCK: [2024-02-12 Mon 11:04]--[2024-02-12 Mon 11:29] =>  0:25
CLOCK: [2024-02-10 Sat 21:52]--[2024-02-10 Sat 22:17] =>  0:25
CLOCK: [2024-02-10 Sat 19:56]--[2024-02-10 Sat 20:21] =>  0:25
CLOCK: [2024-02-10 Sat 17:01]--[2024-02-10 Sat 17:26] =>  0:25
CLOCK: [2024-02-10 Sat 15:08]--[2024-02-10 Sat 15:34] =>  0:26
CLOCK: [2024-02-10 Sat 14:33]--[2024-02-10 Sat 14:58] =>  0:25
CLOCK: [2024-02-10 Sat 14:07]--[2024-02-10 Sat 14:32] =>  0:25
CLOCK: [2024-02-10 Sat 13:42]--[2024-02-10 Sat 14:07] =>  0:25
CLOCK: [2024-02-10 Sat 13:06]--[2024-02-10 Sat 13:31] =>  0:25
CLOCK: [2024-02-08 Thu 22:40]--[2024-02-08 Thu 23:05] =>  0:25
CLOCK: [2024-02-08 Thu 22:15]--[2024-02-08 Thu 22:40] =>  0:25
CLOCK: [2024-02-08 Thu 21:15]--[2024-02-08 Thu 21:40] =>  0:25
CLOCK: [2024-02-07 Wed 09:35]--[2024-02-07 Wed 10:00] =>  0:25
CLOCK: [2024-02-06 Tue 00:48]--[2024-02-06 Tue 01:13] =>  0:25
CLOCK: [2024-02-04 Sun 23:08]--[2024-02-04 Sun 23:33] =>  0:25
CLOCK: [2024-02-04 Sun 11:13]--[2024-02-04 Sun 11:38] =>  0:25
CLOCK: [2024-02-04 Sun 10:48]--[2024-02-04 Sun 11:13] =>  0:25
CLOCK: [2024-02-03 Sat 22:18]--[2024-02-03 Sat 22:43] =>  0:25
CLOCK: [2024-02-03 Sat 19:54]--[2024-02-03 Sat 20:19] =>  0:25
CLOCK: [2024-02-03 Sat 19:02]--[2024-02-03 Sat 19:27] =>  0:25
CLOCK: [2024-02-03 Sat 18:37]--[2024-02-03 Sat 19:02] =>  0:25
CLOCK: [2024-02-03 Sat 16:57]--[2024-02-03 Sat 17:22] =>  0:25
CLOCK: [2024-02-03 Sat 16:03]--[2024-02-03 Sat 16:28] =>  0:25
CLOCK: [2024-02-03 Sat 15:38]--[2024-02-03 Sat 16:03] =>  0:25
CLOCK: [2024-02-03 Sat 15:13]--[2024-02-03 Sat 15:38] =>  0:25
CLOCK: [2024-02-03 Sat 13:30]--[2024-02-03 Sat 13:55] =>  0:25
CLOCK: [2024-02-03 Sat 13:04]--[2024-02-03 Sat 13:29] =>  0:25
CLOCK: [2024-02-03 Sat 12:39]--[2024-02-03 Sat 13:04] =>  0:25
CLOCK: [2024-02-03 Sat 12:00]--[2024-02-03 Sat 12:25] =>  0:25
CLOCK: [2024-02-03 Sat 10:59]--[2024-02-03 Sat 11:24] =>  0:25
CLOCK: [2024-02-03 Sat 10:34]--[2024-02-03 Sat 10:59] =>  0:25
CLOCK: [2023-11-19 Sun 11:43]--[2023-11-19 Sun 12:08] =>  0:25
CLOCK: [2023-11-19 Sun 11:11]--[2023-11-19 Sun 11:36] =>  0:25
CLOCK: [2023-11-12 Sun 22:59]--[2023-11-12 Sun 23:24] =>  0:25
CLOCK: [2023-11-12 Sun 17:58]--[2023-11-12 Sun 18:23] =>  0:25
CLOCK: [2023-11-04 Sat 15:33]--[2023-11-04 Sat 15:58] =>  0:25
CLOCK: [2023-11-04 Sat 12:26]--[2023-11-04 Sat 12:51] =>  0:25
CLOCK: [2023-11-04 Sat 11:51]--[2023-11-04 Sat 12:16] =>  0:25
CLOCK: [2023-11-04 Sat 11:11]--[2023-11-04 Sat 11:36] =>  0:25
CLOCK: [2023-11-04 Sat 10:27]--[2023-11-04 Sat 10:52] =>  0:25
CLOCK: [2023-11-04 Sat 10:01]--[2023-11-04 Sat 10:26] =>  0:25
CLOCK: [2023-11-04 Sat 09:29]--[2023-11-04 Sat 09:54] =>  0:25
CLOCK: [2023-11-03 Fri 23:24]--[2023-11-03 Fri 23:49] =>  0:25
CLOCK: [2023-11-03 Fri 22:49]--[2023-11-03 Fri 23:14] =>  0:25
CLOCK: [2023-11-03 Fri 22:24]--[2023-11-03 Fri 22:49] =>  0:25
CLOCK: [2023-11-02 Thu 00:23]--[2023-11-02 Thu 00:48] =>  0:25
CLOCK: [2023-10-23 Mon 20:45]--[2023-10-23 Mon 21:10] =>  0:25
CLOCK: [2023-10-15 Sun 16:37]--[2023-10-15 Sun 17:02] =>  0:25
CLOCK: [2023-10-15 Sun 12:07]--[2023-10-15 Sun 12:32] =>  0:25
CLOCK: [2023-10-14 Sat 23:10]--[2023-10-14 Sat 23:35] =>  0:25
CLOCK: [2023-10-14 Sat 22:44]--[2023-10-14 Sat 23:09] =>  0:25
CLOCK: [2023-10-13 Fri 00:41]--[2023-10-13 Fri 01:06] =>  0:25
CLOCK: [2023-10-11 Wed 00:35]--[2023-10-11 Wed 01:00] =>  0:25
CLOCK: [2023-10-10 Tue 23:47]--[2023-10-11 Wed 00:12] =>  0:25
CLOCK: [2023-10-10 Tue 23:14]--[2023-10-10 Tue 23:39] =>  0:25
CLOCK: [2023-10-09 Mon 17:29]--[2023-10-09 Mon 17:54] =>  0:25
CLOCK: [2023-10-09 Mon 16:25]--[2023-10-09 Mon 16:50] =>  0:25
CLOCK: [2023-10-09 Mon 15:49]--[2023-10-09 Mon 16:14] =>  0:25
CLOCK: [2023-10-09 Mon 14:01]--[2023-10-09 Mon 14:26] =>  0:25
CLOCK: [2023-10-08 Sun 18:35]--[2023-10-08 Sun 19:00] =>  0:25
CLOCK: [2023-10-08 Sun 17:50]--[2023-10-08 Sun 18:15] =>  0:25
CLOCK: [2023-10-08 Sun 17:08]--[2023-10-08 Sun 17:33] =>  0:25
CLOCK: [2023-10-08 Sun 16:42]--[2023-10-08 Sun 17:07] =>  0:25
CLOCK: [2023-10-08 Sun 15:29]--[2023-10-08 Sun 15:54] =>  0:25
CLOCK: [2023-10-08 Sun 12:00]--[2023-10-08 Sun 12:25] =>  0:25
CLOCK: [2023-10-08 Sun 11:17]--[2023-10-08 Sun 11:42] =>  0:25
CLOCK: [2023-10-08 Sun 10:47]--[2023-10-08 Sun 11:12] =>  0:25
CLOCK: [2023-10-08 Sun 10:21]--[2023-10-08 Sun 10:46] =>  0:25
:END:

記事を書く。

** TODO Read Code                                                   :Train:
:LOGBOOK:
CLOCK: [2024-03-01 Fri 22:19]--[2024-03-01 Fri 22:44] =>  0:25
CLOCK: [2024-02-29 Thu 21:39]--[2024-02-29 Thu 22:04] =>  0:25
CLOCK: [2024-02-29 Thu 20:59]--[2024-02-29 Thu 21:24] =>  0:25
CLOCK: [2024-02-29 Thu 20:34]--[2024-02-29 Thu 20:59] =>  0:25
CLOCK: [2024-02-09 Fri 00:40]--[2024-02-09 Fri 01:05] =>  0:25
CLOCK: [2024-02-08 Thu 09:29]--[2024-02-08 Thu 09:54] =>  0:25
CLOCK: [2024-02-08 Thu 09:03]--[2024-02-08 Thu 09:28] =>  0:25
CLOCK: [2024-02-08 Thu 01:00]--[2024-02-08 Thu 01:25] =>  0:25
CLOCK: [2024-02-08 Thu 00:30]--[2024-02-08 Thu 00:55] =>  0:25
CLOCK: [2023-07-20 Thu 22:31]--[2023-07-20 Thu 22:56] =>  0:25
CLOCK: [2023-07-19 Wed 23:19]--[2023-07-19 Wed 23:44] =>  0:25
CLOCK: [2023-07-19 Wed 22:46]--[2023-07-19 Wed 23:11] =>  0:25
CLOCK: [2023-07-19 Wed 22:20]--[2023-07-19 Wed 22:45] =>  0:25
CLOCK: [2023-07-17 Mon 22:09]--[2023-07-17 Mon 22:34] =>  0:25
CLOCK: [2023-07-17 Mon 21:41]--[2023-07-17 Mon 22:06] =>  0:25
CLOCK: [2023-07-17 Mon 21:07]--[2023-07-17 Mon 21:32] =>  0:25
CLOCK: [2023-07-17 Mon 20:39]--[2023-07-17 Mon 21:04] =>  0:25
CLOCK: [2023-07-17 Mon 20:01]--[2023-07-17 Mon 20:26] =>  0:25
CLOCK: [2023-07-17 Mon 19:32]--[2023-07-17 Mon 19:57] =>  0:25
CLOCK: [2023-06-30 Fri 22:00]--[2023-06-30 Fri 22:25] =>  0:25
CLOCK: [2023-06-30 Fri 21:09]--[2023-06-30 Fri 21:34] =>  0:25
CLOCK: [2023-06-29 Thu 00:51]--[2023-06-29 Thu 01:16] =>  0:25
CLOCK: [2023-06-29 Thu 00:22]--[2023-06-29 Thu 00:47] =>  0:25
CLOCK: [2023-06-28 Wed 23:34]--[2023-06-28 Wed 23:59] =>  0:25
CLOCK: [2023-06-28 Wed 22:55]--[2023-06-28 Wed 23:20] =>  0:25
CLOCK: [2023-06-28 Wed 22:27]--[2023-06-28 Wed 22:52] =>  0:25
CLOCK: [2023-06-28 Wed 21:58]--[2023-06-28 Wed 22:23] =>  0:25
CLOCK: [2023-06-22 Thu 22:07]--[2023-06-22 Thu 22:32] =>  0:25
CLOCK: [2023-06-21 Wed 00:54]--[2023-06-21 Wed 01:19] =>  0:25
CLOCK: [2023-06-20 Tue 22:32]--[2023-06-20 Tue 22:57] =>  0:25
CLOCK: [2023-01-22 Sun 12:27]--[2023-01-22 Sun 12:52] =>  0:25
CLOCK: [2023-01-14 Sat 16:20]--[2023-01-14 Sat 16:45] =>  0:25
CLOCK: [2023-01-14 Sat 14:33]--[2023-01-14 Sat 14:58] =>  0:25
CLOCK: [2022-12-28 Wed 07:38]--[2022-12-28 Wed 08:03] =>  0:25
CLOCK: [2022-12-24 Sat 23:31]--[2022-12-24 Sat 23:56] =>  0:25
CLOCK: [2022-12-24 Sat 23:06]--[2022-12-24 Sat 23:31] =>  0:25
CLOCK: [2022-12-24 Sat 20:38]--[2022-12-24 Sat 21:03] =>  0:25
CLOCK: [2022-12-24 Sat 20:13]--[2022-12-24 Sat 20:38] =>  0:25
CLOCK: [2022-12-24 Sat 19:48]--[2022-12-24 Sat 20:13] =>  0:25
CLOCK: [2022-11-12 Sat 17:01]--[2022-11-12 Sat 17:26] =>  0:25
CLOCK: [2022-11-12 Sat 16:27]--[2022-11-12 Sat 16:52] =>  0:25
CLOCK: [2022-10-26 Wed 08:54]--[2022-10-26 Wed 09:19] =>  0:25
CLOCK: [2022-10-26 Wed 08:29]--[2022-10-26 Wed 08:54] =>  0:25
CLOCK: [2022-10-26 Wed 00:07]--[2022-10-26 Wed 00:32] =>  0:25
CLOCK: [2022-08-05 Fri 16:24]--[2022-08-05 Fri 16:49] =>  0:25
CLOCK: [2022-08-01 Mon 23:04]--[2022-08-01 Mon 23:29] =>  0:25
CLOCK: [2022-07-31 Sun 21:58]--[2022-07-31 Sun 22:23] =>  0:25
CLOCK: [2022-07-31 Sun 16:21]--[2022-07-31 Sun 16:46] =>  0:25
CLOCK: [2022-07-31 Sun 14:59]--[2022-07-31 Sun 15:24] =>  0:25
CLOCK: [2022-07-31 Sun 12:36]--[2022-07-31 Sun 13:01] =>  0:25
CLOCK: [2022-07-31 Sun 12:11]--[2022-07-31 Sun 12:36] =>  0:25
:END:
** TODO Read Feed                                                   :Train:
:LOGBOOK:
CLOCK: [2024-03-23 Sat 21:05]--[2024-03-23 Sat 21:30] =>  0:25
CLOCK: [2024-03-20 Wed 21:12]--[2024-03-20 Wed 21:37] =>  0:25
CLOCK: [2024-03-17 Sun 20:45]--[2024-03-17 Sun 21:10] =>  0:25
CLOCK: [2024-03-17 Sun 11:23]--[2024-03-17 Sun 11:48] =>  0:25
CLOCK: [2024-03-17 Sun 10:02]--[2024-03-17 Sun 10:27] =>  0:25
CLOCK: [2024-03-14 Thu 00:19]--[2024-03-14 Thu 00:44] =>  0:25
CLOCK: [2024-03-13 Wed 21:30]--[2024-03-13 Wed 21:55] =>  0:25
CLOCK: [2024-03-13 Wed 20:58]--[2024-03-13 Wed 21:23] =>  0:25
CLOCK: [2024-03-12 Tue 21:30]--[2024-03-12 Tue 21:55] =>  0:25
CLOCK: [2024-03-04 Mon 19:54]--[2024-03-04 Mon 20:19] =>  0:25
CLOCK: [2024-03-04 Mon 19:19]--[2024-03-04 Mon 19:44] =>  0:25
CLOCK: [2024-02-28 Wed 19:33]--[2024-02-28 Wed 19:58] =>  0:25
CLOCK: [2024-02-28 Wed 19:08]--[2024-02-28 Wed 19:33] =>  0:25
CLOCK: [2024-02-28 Wed 00:22]--[2024-02-28 Wed 00:47] =>  0:25
CLOCK: [2024-02-26 Mon 22:16]--[2024-02-26 Mon 22:41] =>  0:25
CLOCK: [2024-02-26 Mon 21:48]--[2024-02-26 Mon 22:13] =>  0:25
CLOCK: [2024-02-26 Mon 18:40]--[2024-02-26 Mon 19:05] =>  0:25
CLOCK: [2024-02-24 Sat 01:36]--[2024-02-24 Sat 02:01] =>  0:25
CLOCK: [2024-02-12 Mon 23:33]--[2024-02-12 Mon 23:58] =>  0:25
CLOCK: [2024-02-04 Sun 18:02]--[2024-02-04 Sun 18:27] =>  0:25
CLOCK: [2024-02-03 Sat 11:24]--[2024-02-03 Sat 11:50] =>  0:26
CLOCK: [2024-02-03 Sat 10:09]--[2024-02-03 Sat 10:34] =>  0:25
CLOCK: [2024-01-29 Mon 23:35]--[2024-01-30 Tue 00:00] =>  0:25
CLOCK: [2024-01-29 Mon 22:19]--[2024-01-29 Mon 22:44] =>  0:25
CLOCK: [2024-01-29 Mon 21:37]--[2024-01-29 Mon 22:02] =>  0:25
CLOCK: [2024-01-29 Mon 20:39]--[2024-01-29 Mon 21:04] =>  0:25
CLOCK: [2024-01-29 Mon 00:47]--[2024-01-29 Mon 01:12] =>  0:25
CLOCK: [2024-01-28 Sun 23:29]--[2024-01-28 Sun 23:54] =>  0:25
CLOCK: [2024-01-28 Sun 23:03]--[2024-01-28 Sun 23:28] =>  0:25
CLOCK: [2024-01-28 Sun 17:00]--[2024-01-28 Sun 17:25] =>  0:25
CLOCK: [2024-01-28 Sun 16:33]--[2024-01-28 Sun 16:58] =>  0:25
CLOCK: [2024-01-18 Thu 00:12]--[2024-01-18 Thu 00:37] =>  0:25
CLOCK: [2024-01-13 Sat 19:50]--[2024-01-13 Sat 20:15] =>  0:25
CLOCK: [2024-01-13 Sat 19:20]--[2024-01-13 Sat 19:45] =>  0:25
CLOCK: [2024-01-13 Sat 14:22]--[2024-01-13 Sat 14:47] =>  0:25
CLOCK: [2024-01-13 Sat 13:18]--[2024-01-13 Sat 13:43] =>  0:25
CLOCK: [2023-11-20 Mon 21:45]--[2023-11-20 Mon 22:10] =>  0:25
CLOCK: [2023-11-15 Wed 22:09]--[2023-11-15 Wed 22:34] =>  0:25
CLOCK: [2023-11-12 Sun 21:46]--[2023-11-12 Sun 22:11] =>  0:25
CLOCK: [2023-11-12 Sun 21:09]--[2023-11-12 Sun 21:34] =>  0:25
CLOCK: [2023-11-12 Sun 20:33]--[2023-11-12 Sun 20:58] =>  0:25
CLOCK: [2023-11-12 Sun 16:57]--[2023-11-12 Sun 17:22] =>  0:25
CLOCK: [2023-11-12 Sun 16:16]--[2023-11-12 Sun 16:41] =>  0:25
CLOCK: [2023-11-03 Fri 21:57]--[2023-11-03 Fri 22:22] =>  0:25
CLOCK: [2023-11-03 Fri 19:55]--[2023-11-03 Fri 20:20] =>  0:25
CLOCK: [2023-11-03 Fri 17:39]--[2023-11-03 Fri 18:04] =>  0:25
CLOCK: [2023-11-03 Fri 17:14]--[2023-11-03 Fri 17:39] =>  0:25
CLOCK: [2023-11-03 Fri 16:49]--[2023-11-03 Fri 17:14] =>  0:25
CLOCK: [2023-11-03 Fri 15:21]--[2023-11-03 Fri 15:46] =>  0:25
CLOCK: [2023-11-03 Fri 11:55]--[2023-11-03 Fri 12:20] =>  0:25
CLOCK: [2023-11-03 Fri 11:25]--[2023-11-03 Fri 11:50] =>  0:25
CLOCK: [2023-11-03 Fri 10:55]--[2023-11-03 Fri 11:20] =>  0:25
CLOCK: [2023-11-03 Fri 10:27]--[2023-11-03 Fri 10:52] =>  0:25
CLOCK: [2023-11-02 Thu 08:36]--[2023-11-02 Thu 09:01] =>  0:25
CLOCK: [2023-11-01 Wed 22:00]--[2023-11-01 Wed 22:25] =>  0:25
CLOCK: [2023-10-23 Mon 21:10]--[2023-10-23 Mon 21:35] =>  0:25
CLOCK: [2023-10-23 Mon 20:14]--[2023-10-23 Mon 20:39] =>  0:25
CLOCK: [2023-10-22 Sun 18:26]--[2023-10-22 Sun 18:51] =>  0:25
CLOCK: [2023-10-22 Sun 17:41]--[2023-10-22 Sun 18:06] =>  0:25
CLOCK: [2023-09-27 Wed 23:47]--[2023-09-28 Thu 00:12] =>  0:25
CLOCK: [2023-09-27 Wed 21:28]--[2023-09-27 Wed 21:53] =>  0:25
CLOCK: [2023-09-27 Wed 09:11]--[2023-09-27 Wed 09:36] =>  0:25
CLOCK: [2023-09-16 Sat 10:31]--[2023-09-16 Sat 10:56] =>  0:25
CLOCK: [2023-09-12 Tue 22:07]--[2023-09-12 Tue 22:32] =>  0:25
CLOCK: [2023-09-09 Sat 11:12]--[2023-09-09 Sat 11:37] =>  0:25
CLOCK: [2023-09-09 Sat 10:43]--[2023-09-09 Sat 11:08] =>  0:25
CLOCK: [2023-09-08 Fri 00:15]--[2023-09-08 Fri 00:40] =>  0:25
CLOCK: [2023-09-07 Thu 23:16]--[2023-09-07 Thu 23:41] =>  0:25
CLOCK: [2023-09-02 Sat 15:53]--[2023-09-02 Sat 16:18] =>  0:25
CLOCK: [2023-08-31 Thu 22:41]--[2023-08-31 Thu 23:06] =>  0:25
CLOCK: [2023-08-31 Thu 22:01]--[2023-08-31 Thu 22:26] =>  0:25
CLOCK: [2023-08-22 Tue 17:16]--[2023-08-22 Tue 17:41] =>  0:25
CLOCK: [2023-08-22 Tue 16:51]--[2023-08-22 Tue 17:16] =>  0:25
CLOCK: [2023-07-31 Mon 20:28]--[2023-07-31 Mon 20:53] =>  0:25
CLOCK: [2023-07-30 Sun 22:08]--[2023-07-30 Sun 22:33] =>  0:25
CLOCK: [2023-07-29 Sat 17:35]--[2023-07-29 Sat 18:00] =>  0:25
CLOCK: [2023-07-29 Sat 17:10]--[2023-07-29 Sat 17:35] =>  0:25
CLOCK: [2023-07-25 Tue 23:30]--[2023-07-25 Tue 23:55] =>  0:25
CLOCK: [2023-07-25 Tue 23:05]--[2023-07-25 Tue 23:30] =>  0:25
CLOCK: [2023-07-25 Tue 22:26]--[2023-07-25 Tue 22:51] =>  0:25
CLOCK: [2023-07-25 Tue 21:59]--[2023-07-25 Tue 22:24] =>  0:25
CLOCK: [2023-07-25 Tue 21:34]--[2023-07-25 Tue 21:59] =>  0:25
CLOCK: [2023-07-25 Tue 21:04]--[2023-07-25 Tue 21:29] =>  0:25
CLOCK: [2023-07-22 Sat 17:19]--[2023-07-22 Sat 17:44] =>  0:25
CLOCK: [2023-07-22 Sat 16:52]--[2023-07-22 Sat 17:17] =>  0:25
CLOCK: [2023-07-22 Sat 16:06]--[2023-07-22 Sat 16:31] =>  0:25
CLOCK: [2023-07-20 Thu 21:58]--[2023-07-20 Thu 22:23] =>  0:25
CLOCK: [2023-07-20 Thu 21:25]--[2023-07-20 Thu 21:50] =>  0:25
CLOCK: [2023-07-15 Sat 23:25]--[2023-07-15 Sat 23:50] =>  0:25
CLOCK: [2023-07-15 Sat 21:20]--[2023-07-15 Sat 21:45] =>  0:25
CLOCK: [2023-07-15 Sat 20:44]--[2023-07-15 Sat 21:09] =>  0:25
CLOCK: [2023-07-11 Tue 22:32]--[2023-07-11 Tue 22:57] =>  0:25
CLOCK: [2023-07-09 Sun 18:01]--[2023-07-09 Sun 18:26] =>  0:25
CLOCK: [2023-07-09 Sun 17:28]--[2023-07-09 Sun 17:53] =>  0:25
CLOCK: [2023-07-09 Sun 17:00]--[2023-07-09 Sun 17:25] =>  0:25
CLOCK: [2023-07-08 Sat 23:07]--[2023-07-08 Sat 23:32] =>  0:25
CLOCK: [2023-07-08 Sat 22:41]--[2023-07-08 Sat 23:06] =>  0:25
CLOCK: [2023-07-08 Sat 22:14]--[2023-07-08 Sat 22:39] =>  0:25
CLOCK: [2023-07-08 Sat 21:44]--[2023-07-08 Sat 22:09] =>  0:25
CLOCK: [2023-07-08 Sat 18:09]--[2023-07-08 Sat 18:34] =>  0:25
CLOCK: [2023-07-08 Sat 16:52]--[2023-07-08 Sat 17:17] =>  0:25
CLOCK: [2023-07-08 Sat 16:19]--[2023-07-08 Sat 16:44] =>  0:25
CLOCK: [2023-07-08 Sat 15:38]--[2023-07-08 Sat 16:03] =>  0:25
CLOCK: [2023-07-08 Sat 14:38]--[2023-07-08 Sat 15:03] =>  0:25
CLOCK: [2023-07-08 Sat 13:15]--[2023-07-08 Sat 13:40] =>  0:25
CLOCK: [2023-07-08 Sat 12:50]--[2023-07-08 Sat 13:15] =>  0:25
CLOCK: [2023-07-08 Sat 12:24]--[2023-07-08 Sat 12:49] =>  0:25
CLOCK: [2023-07-07 Fri 21:08]--[2023-07-07 Fri 21:33] =>  0:25
CLOCK: [2023-07-05 Wed 00:38]--[2023-07-05 Wed 01:03] =>  0:25
CLOCK: [2023-07-05 Wed 00:11]--[2023-07-05 Wed 00:36] =>  0:25
CLOCK: [2023-07-04 Tue 23:30]--[2023-07-04 Tue 23:55] =>  0:25
CLOCK: [2023-07-04 Tue 22:44]--[2023-07-04 Tue 23:09] =>  0:25
CLOCK: [2023-07-04 Tue 21:07]--[2023-07-04 Tue 21:32] =>  0:25
CLOCK: [2023-07-04 Tue 20:41]--[2023-07-04 Tue 21:06] =>  0:25
CLOCK: [2023-07-02 Sun 09:56]--[2023-07-02 Sun 10:21] =>  0:25
CLOCK: [2023-07-02 Sun 09:31]--[2023-07-02 Sun 09:56] =>  0:25
CLOCK: [2023-06-29 Thu 22:49]--[2023-06-29 Thu 23:14] =>  0:25
CLOCK: [2023-06-25 Sun 11:45]--[2023-06-25 Sun 12:10] =>  0:25
CLOCK: [2023-06-24 Sat 14:38]--[2023-06-24 Sat 15:04] =>  0:26
CLOCK: [2023-06-23 Fri 23:30]--[2023-06-23 Fri 23:55] =>  0:25
CLOCK: [2023-06-23 Fri 22:20]--[2023-06-23 Fri 22:45] =>  0:25
CLOCK: [2023-06-22 Thu 22:50]--[2023-06-22 Thu 23:15] =>  0:25
CLOCK: [2023-06-22 Thu 21:08]--[2023-06-22 Thu 21:33] =>  0:25
CLOCK: [2023-06-22 Thu 20:29]--[2023-06-22 Thu 20:54] =>  0:25
CLOCK: [2023-06-22 Thu 00:15]--[2023-06-22 Thu 00:40] =>  0:25
CLOCK: [2023-06-21 Wed 23:32]--[2023-06-21 Wed 23:57] =>  0:25
CLOCK: [2023-06-20 Tue 21:27]--[2023-06-20 Tue 21:52] =>  0:25
CLOCK: [2023-06-20 Tue 21:01]--[2023-06-20 Tue 21:26] =>  0:25
CLOCK: [2023-06-20 Tue 00:52]--[2023-06-20 Tue 01:17] =>  0:25
:END:
* Memo
** 時間で決めず、今日やる分量を決める
〜時間やる、という目標の立て方はよくない。具体的でないからだ。なにかやるには、集中してないと意味ない。どんなにがんばっても時間が短くなるわけはないので、集中するインセンティブは生まれない。結果、だらだらやってあまり進んでない、あるいは進捗を把握してないので嫌な気分になる。長期的な予測もつけられないので、過大な目標を毎回立てて未達成になり、自信を失う。達成してない気分になり、気晴らしのときもリラックスできない。生活のバランスを失う。

今日やることを明確に決めておくと、集中するインセンティブが生まれ、細かく達成してモチベーションを得やすい。自分がどれくらいの量を処理できるのかがだいたい把握できてくる。長期的にもどれくらい進むか予測可能になり、達成できる可能性が高くなる。
** 集中するためにオフラインにする
ポールグレアムのエッセイで紹介されてたこと。
[[http://blog.livedoor.jp/lionfan/archives/52681996.html][らいおんの隠れ家 : ポール・グレアム「気晴らしを断ち切る」 - livedoor Blog（ブログ）]]

- インターネットがない時代のパソコンでは、集中力が保てた。今は違う。
- ネットにつながってればなんだってできる。

なので、仕事用のPCではオフラインへするようにしているという。
インターネットを使う必要があるときは、離れたところにあるもう1つのPCを使ってやる。

これを参考に、LANのスイッチを買ってやってみた(机が2つないので)。かなりいい。
ふとしたときにネット検索しようとして脱線したり音楽を聞いて集中力が削がれていることがよくわかる。
インターネットにつながってないことで、心が平穏になる。

ただ生産的で知る必要があることもわからなくなる↓。

- ソフトウェアのドキュメント
- よく検索するちょっとしたこと

これらは、ローカルにあらかじめ置いて参照できるようにしておくとよさそう。
* Tasks
* Archives
** DONE タスク状況をレポート化する
CLOSED: [2021-09-12 Sun 18:18]
:LOGBOOK:
CLOCK: [2021-09-12 Sun 15:32]--[2021-09-12 Sun 15:57] =>  0:25
CLOCK: [2021-09-12 Sun 14:47]--[2021-09-12 Sun 15:12] =>  0:25
CLOCK: [2021-09-12 Sun 13:51]--[2021-09-12 Sun 14:16] =>  0:25
:END:
週ごとで作成できると面白そう。
今週doneしたやつ、タスクでかかった時間の総計。
** DONE よく使うagenda viewを一発で開けるようにする
CLOSED: [2021-09-12 Sun 18:19]
- [[https://orgmode.org/manual/Exporting-Agenda-Views.html][Exporting Agenda Views (The Org Manual)]]

week, log-modeを自動的に選択してほしい。
** CLOSE チェックを忘れるとalertされなくなる
CLOSED: [2022-02-13 Sun 01:44]
何時間かはスヌーズ的にorg-alert通知してくれるが、しばらくすると出なくなる。
一応org-agendaには過ぎてるのも表示されるので放置するようなことはないが、不便。

org-agendaに期限切れが表示されるから、この問題は起きない。
