:PROPERTIES:
:ID:       90c6b715-9324-46ce-a354-63d09403b066
:END:
#+title: Git
* 概要
Gitはバージョン管理システムである。
* Memo
** ゴミファイルを削除する
gitignoreしたディレクトリで、いつの間にかゴミファイルがたまりがち。
#+caption: 削除されるファイルを確認してから、削除する
#+begin_src shell
  git clean -xdn # dry run
  git clean -xdf # 実行
#+end_src
** revertしたブランチを再開するとき
revertしたブランチの途中から再開すると、revertコミットのために差分が出ない。
なので、revertコミットをさらにrevertして、その上で作業を再開する。

#+begin_src shell
git revert -m 1 {revertしたコミットハッシュ}
#+end_src

https://stackoverflow.com/questions/2389361/undo-a-git-merge-that-hasnt-been-pushed-yet/6217372#6217372
** コミットハッシュ取得
タグをつけるときに便利。

#+begin_src shell
  LC=$(git rev-parse --short HEAD)
  echo ${LC}
#+end_src

#+RESULTS:
: 0f777f9

↓みたいな感じで。
#+begin_src shell
  docker build -t ghcr.io/kijimad/webapp:${LC} .
#+end_src
** certエラーが出るとき
依存パッケージインストール時、httpsでcloneできないことがある。証明書がないエラー。
#+begin_src shell
  git config --global http.sslVerify false
#+end_src

[[https://stackoverflow.com/questions/19045556/git-clone-https-ssl-error][git clone https/ssl error - Stack Overflow]]
** バイナリファイルの差分
ファイルによって戦略を変えることができる。
特定のバイナリファイル…Wordファイルだったらこうやって変換してから差分を取る、など。
テキストに変換して、比較できる。

- [[http://git-scm.com/book/ja/v2/Git-%E3%81%AE%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%9E%E3%82%A4%E3%82%BA-Git-%E3%81%AE%E5%B1%9E%E6%80%A7][Git - Git の属性]]
** Git軽量化
しばらく使っていると不要なブランチが溜まってきて重くなるので、定期的に不要なものを削除する。
#+begin_src shell
  git gc && git fetch --prune
#+end_src
** Gitクライアント
直にGitコマンドを打つほかに、クライアントを使って操作する方法がある。
プログラミングと密接に関係しているので、エディタに付属したものを使うと、同じインターフェイスで扱えて便利。
例えば[[id:1ad8c3d5-97ba-4905-be11-e6f2626127ad][Emacs]]では[[https://github.com/magit/magit][Magit]]パッケージが人気。
* Tasks
** TODO [[http://git-scm.com/book/ja/v2][Git - Book]]
日本語で無料公開されている本。
Gitの仕組みの章がとても面白い。
実際のGitが内部で行っていることを、原始的なコマンドを使ってやってみるというもの。
** TODO [[https://github.blog/jp/2021-01-06-commits-are-snapshots-not-diffs/][コミットはスナップショットであり差分ではない - GitHubブログ]]
* Reference
** [[http://git-scm.com/book/ja/v2/Git%E3%81%AE%E5%86%85%E5%81%B4-%E9%85%8D%E7%AE%A1%EF%BC%88Plumbing%EF%BC%89%E3%81%A8%E7%A3%81%E5%99%A8%EF%BC%88Porcelain%EF%BC%89][Git - 配管（Plumbing）と磁器（Porcelain）]]
基本的な仕組みの解説。
** [[https://www.youtube.com/watch?v=W71BTkUbdqE][Why Google Stores Billions of Lines of Code in a Single Repository - YouTube]]
なぜGoogleはモノレポで管理しているか。
** TODO [[https://codeinthehole.com/tips/a-useful-template-for-commit-messages/][A useful template for commit messages — David Winterbottom]]
git commitテンプレート。
** TODO [[https://chris.beams.io/posts/git-commit/][How to Write a Git Commit Message]]
* Archive
** DONE Rebase on Magit
CLOSED: [2021-09-14 Tue 22:06]
:LOGBOOK:
CLOCK: [2021-09-14 Tue 21:15]--[2021-09-14 Tue 21:40] =>  0:25
:END:
わかりやすく解説している。
- [[https://www.youtube.com/watch?v=zM7K1y4h6UQ&list=PLEoMzSkcN8oMc34dTjyFmTUWbXTKrNfZA&index=3][Fix Your Git Commits Like a Rebase Expert with Magit - YouTube]]

今までコミットの修正したことなかったな。
