:PROPERTIES:
:ID:       49971784-7850-4d24-92f2-9c6f29bd332e
:END:
#+title: system
* 概要
Linuxマシンでいろんな設定をしている。
別のマシンへ移るときに再現できるよう、システムに関する情報をまとめる。
* Memo
** input関係の設定を.bash_profile等でしてはいけない理由
[[https://wiki.archlinux.jp/index.php/Fcitx#.E6.97.A5.E6.9C.AC.E8.AA.9E][Fcitx - ArchWiki]]

#+begin_quote
上記の設定を .bashrc でしないでください。.bashrc はインタラクティブな bash セッションを初期化するときに使われます。インタラクティブでないセッションや X セッションの初期化では用いられません。さらに、.bashrc で環境変数を設定すると、コマンドラインから実行した診断ツールに誤解を与えて、X セッションでは環境変数が使われていないのに正しく設定されているかのように表示されることがあります。
#+end_quote
* ビルド手順
すべてクリーンな状況の想定。
** 基本コマンドインストール
syncthingはディレクトリ同期ツール。
[[id:90c6b715-9324-46ce-a354-63d09403b066][Git]]はあとで[[id:32295609-a416-4227-9aa9-47aefc42eefc][dotfiles]]を[[id:6b889822-21f1-4a3e-9755-e3ca52fa0bc4][GitHub]]からクローンしてくるときに使う。

#+caption: aptからインストールする
#+begin_src shell
  sudo apt-get install syncthing git
#+end_src

ssh鍵を生成する。それから適切な権限を付与する。
#+caption: 権限を付与する
#+begin_src shell
  sudo chmod 600 .ssh/id_rsa
#+end_src
** package manager として[[id:d694ecaa-6a8b-4669-a95c-f76de6dcbd2c][GNU Guix]]インストール
ほかのディストリビューションの上にpackage managerとしてインストールする場合。
参考: [[https://systemcrafters.cc/craft-your-system-with-guix/installing-the-package-manager/][Installing the GNU Guix Package Manager - System Crafters]]

#+begin_src shell
  cd /tmp
  wget https://git.savannah.gnu.org/cgit/guix.git/plain/etc/guix-install.sh
  chmod +x guix-install.sh
  sudo ./guix-install.sh
#+end_src
** [[id:32295609-a416-4227-9aa9-47aefc42eefc][dotfiles]] 実行
#+caption: ホームディレクトリで実行する
#+begin_src shell
  git clone git@github.com:kijimaD/dotfiles.git
#+end_src

#+caption: makeタスク実行
#+begin_src shell
  make batch
#+end_src

- 必要パッケージの一括ダウンロード
- メモ用リポジトリのclone
- Emacsの設定
- stowによるdotfilesの配置

をやってくれる。
** その他インストール
いくつか手動でやる必要がある。

- Google Chrome
- org-protocolを設定する
- Zoom
- DBeaver
** TODO その他guix
ag, ripgrep をguixでインストールできそう。
* Tasks
* Reference
* Archives
