:PROPERTIES:
:ID:       815a2c31-7ddb-40ad-bae0-f84e1cfd8de1
:END:
#+title: Org-roam

* 概要
Org-roamはRoam Research[fn:1]の[[id:1ad8c3d5-97ba-4905-be11-e6f2626127ad][Emacs]]版。

org-modeをベースに、目的ファイルへのアクセスしやすさ、文書リンク、グラフ化の機能を強化する。

- GitHubリポジトリ :: https://github.com/org-roam/org-roam
- 公式サイト :: https://www.orgroam.com/
- マニュアル :: https://www.orgroam.com/manual.html
* Tasks
** 記法ルールを決める
適当なので、構造のルールとか決めてたほうがよい。

- 階層を3階層以上作らない。あとから変更するとき大変なので。浅く広く広げていく。継承をあまりせずミックスインして拡張していく、みたいな。
* References
** [[https://www.orgroam.com/manual.html][Org-roam User Manual]]
マニュアル。
** [[https://www.youtube.com/watch?v=AyhPmypHDEw][Getting Started with Org Roam - Build a Second Brain in Emacs - YouTube]]
[[id:fa497359-ae3f-494a-b24a-9822eefe67ad][System Crafters]]のOrg Roam紹介。
** [[https://www.mhatta.org/wp/2021/02/20/org-mode-101-9/#org125e180][Org mode 教室 その9: org-roam でアイデアをひねり出す]]
** https://blog.jethro.dev/posts/introducing_org_roam/
作者サイトのマニュアル。
** https://blog.jethro.dev/posts/org_mode_workflow_preview/
org-modeのワークフロー。
* Archives
** CLOSE Unify workflow management with roam
CLOSED: [2021-09-04 Sat 12:42]
https://d12frosted.io/posts/2021-01-16-task-management-with-roam-vol5.html
** CLOSE CI, sqliteを入れて試してみる
CLOSED: [2021-09-04 Sat 12:07]
- search emacsql
Default install sqlite on ubuntu, so does not matter.
** DONE 基本的キーバインド
CLOSED: [2021-08-29 Sun 21:18]
 - find(C-c n f)
 - バックリンク(C-c n l)
 - Roamリンク挿入(C-c n i)補完を有効にすることであまり使わなくなる。
** DONE idリンクをpublishできない問題
CLOSED: [2021-08-29 Sun 19:53]
roamのidがhtmlに変換できないよう。
#+begin_quote
Unable to resolve link
#+end_quote
になる。

#+begin_src emacs-lisp
  (setq org-hugo-base-dir ".")
  (setq org-export-with-broken-links t)
#+end_src
するとできるが、idリンクを辿れない。
ほかのサイトではidがあってもできてるように見える。
https://hugocisneros.com/blog/my-org-roam-notes-workflow/
orgのバージョンを最新にしたが変わらず。

公式で言及。
https://github.com/org-roam/org-roam/wiki/Hitchhiker's-Rough-Guide-to-Org-roam-V2#export

#+begin_src emacs-lisp
(setq org-id-link-to-org-use-id t)
(setq org-id-extra-files (org-roam--list-files org-roam-directory))
#+end_src
↓で設定していた。これを設定すると成功した。
https://hugocisneros.com/org-config/#configuration

https://gist.github.com/hugcis/1f2d2ad4b98b07ee543f10232ba1b025
#+begin_src emacs-lisp
  (require 'find-lisp)
  (defun hugcis/publish-note (file)
    "Publish a note in FILE."
    (interactive)
    (with-current-buffer (find-file-noselect file)
      (projectile-mode -1)
      (setq org-hugo-section "notes"
            org-hugo-base-dir "."
            citeproc-org-org-bib-header "* Bibliography\n<ol class=\"biblio-list\">"
            citeproc-org-org-bib-footer "</ol>")
      (let ((org-id-extra-files (find-lisp-find-files org-roam-directory "\.org$")))
          (org-hugo-export-wim-to-md))))
#+end_src

#+begin_src shell
  find . -name '*.org' | emacs --batch -l ./publish1.el --funcall kd/publish
#+end_src
** DONE 初期設定
CLOSED: [2021-08-29 Sun 21:17]
⚠バージョンが上がって設定が変わった。この内容は古い。
roamのデフォルトディレクトリを作成して、そこでファイルが作成されたり、検索対象になる。

#+begin_src emacs-lisp
  (require 'org-roam)
  (add-hook 'after-init-hook 'org-roam-mode)
  (make-directory "~/roam" t)
  (setq org-roam-directory "~/roam")
#+end_src

#+begin_src emacs-lisp
  (setq org-roam-completion-everywhere t)
  (define-key org-mode-map (kbd "C-M-i") 'completion-at-point)
#+end_src
リンク補完が有効になります。非常に便利。

#+begin_src emacs-lisp
  (define-key org-roam-mode-map (kbd "C-c n l") 'org-roam)
  (define-key org-roam-mode-map (kbd "C-c n f") 'org-roam-find-file)
  (define-key org-roam-mode-map (kbd "C-c n g") 'org-roam-graph)
  (define-key org-mode-map (kbd "C-c n i") 'org-roam-insert)
  (define-key org-mode-map (kbd "C-c n I") 'org-roam-insert-immediate)
#+end_src
** DONE 外部リンクをグラフに表示したくない
CLOSED: [2021-09-02 Thu 10:30]

~org-roam-graph~ でファイルリンクだけのつながりを表示したい。
v1ではファイルリンクだけで、外部リンクは出てなくてわかりやすかった。

[[https://github.com/org-roam/org-roam-ui][org-roam-ui]]を使ってみた。めちゃかっこいい。

org-roam-graph-link-hidden-types でhttp, httpsを指定すると消せた。
これでCIでも出力できるはず。
#+begin_src emacs-lisp
(setq org-roam-graph-link-hidden-types '("https" "http" "file"))
#+end_src
* 脚注
[fn:1] https://roamresearch.com/ Webでのアウトラインツール。
