:PROPERTIES:
:ID:       a6c9c9ad-d9b1-4e13-8992-75d8590e464c
:END:
#+title: Python
* 概要
Pythonは科学方面に強みを持った[[id:868ac56a-2d42-48d7-ab7f-7047c85a8f39][Programming Language]]。
機械学習、グラフ描画、に大きなエコシステムを持っている。
* Memo
** tkinterがインストールできないとき
#+caption: インストールしようとする
#+begin_src shell
pip3 install tkinter
#+end_src

すると、よくわからないエラー。

#+caption: バージョンかディストリビューションの問題か
#+begin_quote
ERROR: Could not find a version that satisfies the requirement tkinter (from versions: none)
ERROR: No matching distribution found for tkinter
#+end_quote

- https://stackoverflow.com/questions/39928710/why-is-there-no-tkinter-distribution-found

#+caption: aptでインストールする
#+begin_src shell
  apt-get install python3-tk
#+end_src

** AttributeError: 'module' object has no attribute 'randint'
random.pyという名前のファイルで、randomをインポートすると発生する。ファイル名と同じパッケージをインポートはできない。どちらかの名前を変える。
** requirements.txt
requirements.txtはライブラリ管理のために書くファイル。
書いたものがインストールされる。バージョン指定も可能。このように書いておくことで、簡単にライブラリ状況を再現できる。

#+caption: requirements.txt
#+begin_src
scipy
networkx
#+end_src

#+caption: 書いたものをインストール
#+begin_src python
pip3 install -r requirements.txt
#+end_src
** pipをインストール
#+begin_src python
  pyenv install --list
  pyenv install 3.5.4
  pyenv global 3.5.4

  pip install pandas sqlalchemy psycopg2
#+end_src
** 開発用webサーバ
webサーバ立ち上げ。デフォルトで入っている＋コマンドが短いので試すのに便利。
#+begin_src python
python -m http.server 8000
#+end_src
* Tasks
** TODO [[https://www.amazon.co.jp/Python%E3%81%A7%E3%81%A4%E3%81%8F%E3%82%8B-%E3%82%B2%E3%83%BC%E3%83%A0%E9%96%8B%E7%99%BA-%E5%85%A5%E9%96%80%E8%AC%9B%E5%BA%A7-%E5%BB%A3%E7%80%AC-%E8%B1%AA-ebook/dp/B07VD7BTRN/ref=tmm_kin_swatch_0?_encoding=UTF8&qid=&sr=][Amazon.co.jp: Pythonでつくる ゲーム開発 入門講座 eBook : 廣瀬 豪: 本]]
:LOGBOOK:
CLOCK: [2022-10-20 Thu 23:33]--[2022-10-20 Thu 23:58] =>  0:25
CLOCK: [2022-10-20 Thu 23:06]--[2022-10-20 Thu 23:31] =>  0:25
CLOCK: [2022-10-20 Thu 22:22]--[2022-10-20 Thu 22:47] =>  0:25
CLOCK: [2022-10-20 Thu 21:57]--[2022-10-20 Thu 22:22] =>  0:25
CLOCK: [2022-10-20 Thu 21:31]--[2022-10-20 Thu 21:56] =>  0:25
CLOCK: [2022-10-20 Thu 19:46]--[2022-10-20 Thu 20:11] =>  0:25
CLOCK: [2022-10-20 Thu 19:06]--[2022-10-20 Thu 19:31] =>  0:25
:END:
pythonによるゲーム開発入門。
** [[https://rogueliketutorials.com/][Welcome to the Roguelike Tutorial Revised | Roguelike Tutorials]]
Pythonによるroguelikeチュートリアル。
* References
