:PROPERTIES:
:ID:       7a81eb7c-8e2b-400a-b01a-8fa597ea527a
:END:
#+title: Linux
* 概要
GNU LinuxはオープンソースのOS。
最も成功した[[id:bb71747d-8599-4aee-b747-13cb44c05773][OSS]]プロジェクトの1つで、世界中の開発者によって開発が進められている。
* Memo
** lsのソースコード
#+caption: getoptで引数を取り出し、switchで処理する
#+begin_src git-permalink
https://github.com/kd-collective/NetBSD/blob/89341ae2e1875e7f91cefa9b1dcc0e4549edcde0/bin/ls/ls.c#L154-L169
#+end_src

#+RESULTS:
#+begin_example
	while ((ch = getopt(argc, argv, "1AaBbCcdFfghikLlMmnOoPpqRrSsTtuWwXx"))
	    != -1) {
		switch (ch) {
		/*
		 ,* The -1, -C, -l, -m and -x options all override each other so
		 ,* shell aliasing works correctly.
		 ,*/
		case '1':
			f_singlecol = 1;
			f_column = f_columnacross = f_longform = f_stream = 0;
			break;
		case 'C':
			f_column = 1;
			f_columnacross = f_longform = f_singlecol = f_stream =
			    0;
			break;
#+end_example

** cdのソースコード
#+begin_src git-permalink
https://github.com/kd-collective/NetBSD/blob/89341ae2e1875e7f91cefa9b1dcc0e4549edcde0/bin/sh/cd.c#L52-L54
#+end_src

#+RESULTS:
: /*
:  * The cd and pwd commands.
:  */

** echoのソースコード
#+caption: netBSDのechoのソースコード。本質的にprintf
#+begin_src git-permalink
https://github.com/kd-collective/NetBSD/blob/89341ae2e1875e7f91cefa9b1dcc0e4549edcde0/bin/echo/echo.c#L1
#+end_src

#+RESULTS:
: /* $NetBSD: echo.c,v 1.23 2021/11/16 21:38:29 rillig Exp $	*/

#+caption: nflagには0か1が入る
#+begin_src git-permalink
https://github.com/kd-collective/NetBSD/blob/89341ae2e1875e7f91cefa9b1dcc0e4549edcde0/bin/echo/echo.c#L60
#+end_src

#+RESULTS:
: 	nflag = *++argv != NULL && strcmp(*argv, "-n") == 0;

- getopt関数を使っていない
** ctrl+shiftが機能しない
インプットメソッドによって、入力方法の変更ショートカットが奪われる。
https://superuser.com/questions/358749/how-to-disable-ctrlshiftu

fcitxを使っている場合、 ~fcitx-configtool~ で設定できる。
全体の設定 → 入力メソッドの切り替えで、別のキーボードの組み合わせを選択する。
** ディスプレイマネージャーを再起動
壊れたときにシステム再起動よりはやく復帰できる。
#+begin_src shell
  systemctl restart display-manager
#+end_src
** linux mintでsnapをインストールする
#+begin_src shell
  sudo rm /etc/apt/preferences.d/nosnap.pref
#+end_src
** bluetoothが動かないとき
新しくクリーンインストールしたところ、Bluetooth接続ができなかった。
インストール前はできていたから、ハードウェアに問題はない。

前はデフォルトでできてたはずだが、bluetooth周辺ライブラリをインストールしてサービスを再起動する。
どれが効いたのかはさだかではないが、接続できるようになった。

#+begin_src shell
  sudo apt-get install bluetooth bluez bluez-tools rfkill blueman

  # 強制的に全てのブロックを解除
  sudo rfkill unblock all
  # Bluetoothを再起動
  sudo systemctl restart bluetooth.service
#+end_src

[[https://blog.hanhans.net/2019/03/18/ubuntu-enable-bluetooth/][強制的に全てのブロックを解除 1 $ sudo rfkill unblock all Bluetoothを再起動 1 $ sudo systemctl restart bluetooth.service]]
** caps_lockをコマンドで切り替える
Caps LockをControlに入れ替えていると、xmodmapをいじったときに大文字のまま元に戻せなくなることがある。
代替のキーはないので困る。コマンドでできる。
#+begin_src shell
sudo apt-get install xdotool
xdotool key Caps_Lock
#+end_src
* Tasks
** TODO [[https://linuxjf.osdn.jp/JFdocs/The-Linux-Kernel.html#toc14][The Linux Kernel]]
:LOGBOOK:
CLOCK: [2022-05-15 Sun 18:20]--[2022-05-15 Sun 18:45] =>  0:25
:END:
Linuxカーネルの解説。
** TODO [[https://0xax.gitbooks.io/linux-insides/content/][Introduction · Linux Inside]]
Linuxカーネルの解説。
** [[https://www.oreilly.co.jp/books/9784873113135/][O'Reilly Japan - 詳解 Linuxカーネル 第3版]]
:LOGBOOK:
CLOCK: [2022-06-01 Wed 00:42]--[2022-06-01 Wed 01:07] =>  0:25
:END:
- 15
カーネルのソースコードを読む本。
* Reference
** [[https://gihyo.jp/assets/files/event/2008/24svr/report/2-24svr-TechMTG-ito.pdf][Linuxカーネルの読み方]]
Linuxカーネルのソースコードを読むコツと参考文献がある。
** [[https://ja.wikipedia.org/wiki/Linux][Linux - Wikipedia]]
** [[https://www.geekpage.jp/blog/?id=2007/3/1][UNIX哲学の基本原則:Geekなぺーじ]]
UNIX哲学の一覧。
* Archives
