:PROPERTIES:
:ID:       7a81eb7c-8e2b-400a-b01a-8fa597ea527a
:header-args+: :wrap
:END:
#+title: Linux
* 概要
GNU LinuxはオープンソースのOS。
最も成功した[[id:bb71747d-8599-4aee-b747-13cb44c05773][OSS]]プロジェクトの1つで、世界中の開発者によって開発が進められている。
* Memo
** 特殊なディレクトリ
慣例的に使われる特別なディレクトリがある。

たとえば ~/etc/skel/~ は、ユーザが作成されたときのホームディレクトリのベースになる。前もってここに配置しておくと、ユーザが作られたあとホームディレクトリにコピーされ、ユーザが扱える。

~/etc/default/useradd~ に書いてあり、useraddを経由した変更もできる。

** インストールディスク作成

Linux環境でブータブルUSBを作成するとき、よくわからない要因によって失敗することが何度かあった。たいていはブートできないというもの。

- [[https://help.ubuntu.com/community/LiveCDCustomization][LiveCDCustomization - Community Help Wiki]]
  - ライブCDのカスタマイズ方法の詳しいドキュメント。GitHub Actionsでも実行できる

既存のベースとなるisoを持ってくる。isoを展開する。展開したシステムディレクトリをマウントする。この時点で、システムはiso内にあるものが使われ、変更もiso内に反映される。

- unetbootinを使う
  - [[https://unetbootin.github.io/linux_download.html][UNetbootin - Linux Downloads]]
- 焼く前に、USBドライブをext4でフォーマットする。それ以外だとbootに失敗することがある
- 仮想マシンで素早くテストできる
  - ~sudo apt install qemu-kvm~
  - ~qemu-system-x86_64 -boot d -cdrom ubuntu.iso -enable-kvm -m 4096~

** lsのソースコード
#+caption: getoptで引数を取り出し、switchで処理する
#+begin_src git-permalink
https://github.com/kd-collective/NetBSD/blob/89341ae2e1875e7f91cefa9b1dcc0e4549edcde0/bin/ls/ls.c#L154-L169
#+end_src

#+RESULTS:
#+begin_results
	while ((ch = getopt(argc, argv, "1AaBbCcdFfghikLlMmnOoPpqRrSsTtuWwXx"))
	    != -1) {
		switch (ch) {
		/*
		 * The -1, -C, -l, -m and -x options all override each other so
		 * shell aliasing works correctly.
		 */
		case '1':
			f_singlecol = 1;
			f_column = f_columnacross = f_longform = f_stream = 0;
			break;
		case 'C':
			f_column = 1;
			f_columnacross = f_longform = f_singlecol = f_stream =
			    0;
			break;
#+end_results

** cdのソースコード
#+begin_src git-permalink
https://github.com/kd-collective/NetBSD/blob/89341ae2e1875e7f91cefa9b1dcc0e4549edcde0/bin/sh/cd.c#L52-L54
#+end_src

#+RESULTS:
#+begin_results
/*
 * The cd and pwd commands.
 */
#+end_results

** echoのソースコード
#+caption: netBSDのechoのソースコード。本質的にprintf
#+begin_src git-permalink
https://github.com/kd-collective/NetBSD/blob/89341ae2e1875e7f91cefa9b1dcc0e4549edcde0/bin/echo/echo.c#L1
#+end_src

#+RESULTS:
#+begin_results
/* $NetBSD: echo.c,v 1.23 2021/11/16 21:38:29 rillig Exp $	*/
#+end_results

#+caption: nflagには0か1が入る
#+begin_src git-permalink
https://github.com/kd-collective/NetBSD/blob/89341ae2e1875e7f91cefa9b1dcc0e4549edcde0/bin/echo/echo.c#L60
#+end_src

#+RESULTS:
#+begin_results
	nflag = *++argv != NULL && strcmp(*argv, "-n") == 0;
#+end_results

- getopt関数を使っていない
** ctrl+shiftが機能しない
インプットメソッドによって、入力方法の変更ショートカットが奪われる。
https://superuser.com/questions/358749/how-to-disable-ctrlshiftu

fcitxを使っている場合、 ~fcitx-configtool~ で設定できる。
全体の設定 → 入力メソッドの切り替えで、別のキーボードの組み合わせを選択する。
** ディスプレイマネージャーを再起動
壊れたときにシステム再起動よりはやく復帰できる。
#+begin_src shell
  systemctl restart display-manager
#+end_src
** linux mintでsnapをインストールする
#+begin_src shell
  sudo rm /etc/apt/preferences.d/nosnap.pref
#+end_src
** TODO bluetoothが動かないとき
新しくクリーンインストールしたところ、Bluetooth接続ができなかった。
インストール前はできていたから、ハードウェアに問題はない。

前はデフォルトでできてたはずだが、bluetooth周辺ライブラリをインストールしてサービスを再起動する。
どれが効いたのかはさだかではないが、接続できるようになった。

#+begin_src shell
  sudo apt-get install bluetooth bluez bluez-tools rfkill blueman

  # 強制的に全てのブロックを解除
  sudo rfkill unblock all
  # Bluetoothを再起動
  sudo systemctl restart bluetooth.service3
#+end_src

[[https://blog.hanhans.net/2019/03/18/ubuntu-enable-bluetooth/][強制的に全てのブロックを解除 1 $ sudo rfkill unblock all Bluetoothを再起動 1 $ sudo systemctl restart bluetooth.service]]
** caps_lockをコマンドで切り替える
Caps LockをControlに入れ替えていると、xmodmapをいじったときに大文字のまま元に戻せなくなることがある。
代替のキーはないので困る。コマンドでできる。
#+begin_src shell
sudo apt-get install xdotool
xdotool key Caps_Lock
#+end_src
* Tasks
** TODO [[https://book.mynavi.jp/ec/products/detail/id=121220][ゼロからのOS自作入門 | マイナビブックス]]
:LOGBOOK:
CLOCK: [2022-11-19 Sat 09:48]--[2022-11-19 Sat 10:13] =>  0:25
:END:
ゼロからOSを自作する本。
** TODO [[https://www.shuwasystem.co.jp/book/9784798044781.html][ハロー“Hello, World” OSと標準ライブラリのシゴトとしくみ]]
printを実行するとき何が起こっているかの解説。
** TODO [[https://linuxjf.osdn.jp/JFdocs/The-Linux-Kernel.html#toc14][The Linux Kernel]]
:LOGBOOK:
CLOCK: [2022-05-15 Sun 18:20]--[2022-05-15 Sun 18:45] =>  0:25
:END:
Linuxカーネルの解説。
** TODO [[https://0xax.gitbooks.io/linux-insides/content/][Introduction · Linux Inside]]
Linuxカーネルの解説。
** [[https://www.oreilly.co.jp/books/9784873113135/][O'Reilly Japan - 詳解 Linuxカーネル 第3版]]
:LOGBOOK:
CLOCK: [2022-06-01 Wed 00:42]--[2022-06-01 Wed 01:07] =>  0:25
:END:
- 15
カーネルのソースコードを読む本。
* Reference
** [[https://qiita.com/stc1988/items/41d9da92ea02fc3d15a3][SquashFSをマウントするまで - Qiita]]
システムをファイルに圧縮するとき使う。
** [[https://www.express.nec.co.jp/linux/distributions/knowledge/system/useradd.html][新規ユーザ作成時のデフォルト値の設定]]
ユーザの設定方法。ここでデフォルトディレクトリに ~/etc/skel~ 指定している。
** [[https://tech.unifa-e.com/entry/2019/05/23/172424][sudo実行時のカレントディレクトリや環境変数などの挙動について - ユニファ開発者ブログ]]
sudoの解説。
** [[https://linuxjm.osdn.jp/html/sudo/man8/sudo.8.html][Man page of SUDO]]
sudoの解説。特にプロセスモデルに関する詳しい解説。
** [[https://www.amazon.co.jp/%E8%A9%B3%E8%A7%A3UNIX%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0-%E7%AC%AC3%E7%89%88-W-Richard-Stevens-ebook/dp/B00KRB9U8K/ref=pd_rhf_se_s_wsixn_v2_sccl_1_4/357-5123689-8619223?pd_rd_w=lYzom&content-id=amzn1.sym.64deb508-c4ba-451d-b1d7-cc84d2fa4a06&pf_rd_p=64deb508-c4ba-451d-b1d7-cc84d2fa4a06&pf_rd_r=BCZ6984RNNBKX9KACAMS&pd_rd_wg=MByiN&pd_rd_r=9434cf45-fc4f-4182-883d-59af9ed895f1&pd_rd_i=B00KRB9U8K&psc=1][詳解UNIXプログラミング 第3版 | W. Richard Stevens, Stephen A. Rago, 大木 敦雄 | 工学 | Kindleストア | Amazon]]
UNIX。
** [[https://gihyo.jp/assets/files/event/2008/24svr/report/2-24svr-TechMTG-ito.pdf][Linuxカーネルの読み方]]
Linuxカーネルのソースコードを読むコツと参考文献がある。
** [[https://ja.wikipedia.org/wiki/Linux][Linux - Wikipedia]]
** [[https://www.geekpage.jp/blog/?id=2007/3/1][UNIX哲学の基本原則:Geekなぺーじ]]
UNIX哲学の一覧。
* Archives
