:PROPERTIES:
:ID:       2d35ac9e-554a-4142-bba7-3c614cbfe4c4
:END:
#+title: GitHub Actions
* 概要
GitHub Actionsは[[id:6b889822-21f1-4a3e-9755-e3ca52fa0bc4][GitHub]]が提供する[[id:eaf6ed04-7927-4a16-ba94-fbb9f6e76166][CI]]/[[id:2c4cb3a7-7a8a-4a3b-88c2-2c5e69515764][CD]]環境。
コードやプロジェクトに対するタスクを実行できる。
* Memo
** cacheスコープ
- [[https://zenn.dev/mallowlabs/articles/github-actions-cache-scope#actions%2Fcache-%E3%81%AE%E3%82%B9%E3%82%B3%E3%83%BC%E3%83%97][GitHub Actions の cache アクションでキャッシュヒットしない時はスコープを確認してみる]]
- [[https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache][Caching dependencies to speed up workflows - GitHub Docs]]

pushトリガーのジョブで、こんな感じにキャッシュを使っているとする。
#+begin_src yaml
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
#+end_src

restore-keysはキャッシュ検索に使うkey。メインのkeyはgithub.shaによってすべてのコミットで別々にキャッシュ保存するので、完全一致でキャッシュ取得できることはない。ので、restore-keyが必要。キーが部分一致するので、後続のコミットで利用できる。

が、これだけではブランチが変わったとき、ブランチの最初ではキャッシュが利用されない。これがスコープ。スコープの探索は 同じブランチ → ベースブランチ → デフォルトブランチ のみで行われるので、ブランチの最初ではヒットしないということ。これを防ぐために、デフォルトブランチで定期的にpush保存を必要がある。

** reuseable actionにおけるsecretsの扱い方
#+caption: caller
#+begin_src yaml
  jobs:
    called:
      uses: user/repo/.github/workflows/called.yml@main
      with:
        text: ${{ github.event.inputs.text }}
        secrets: # ←←←
        DUMMY: ${{ secrets.DUMMY }} # ←←← caller側ではとくになにもせずともsecretsが使える
#+end_src

#+caption: called
#+begin_src yaml
  on:
    workflow_call:
      inputs:
        text:
          type: string
          required: true
      secrets: # ←←←
        DUMMY: # ←←←called側ではここで定義されていて、かつ呼び出し側のsecretsで定義されてないとsecretsは参照不可
          required: true

  jobs:
    called:
      runs-on: ubuntu-latest
      steps:
        - name: output secret
          run: |
            echo ${{ secrets.DUMMY }}
#+end_src
** Stale Bot
動きがないIssueやPRを自動的にマークしたりcloseするGitHub bot。
[[https://github.com/probot/stale][probot/stale: A GitHub App built with Probot that closes abandoned Issues and Pull Requests after a period of inactivity.]]

設定の例(rubocop)。
https://github.com/rubocop/rubocop/blob/master/.github/stale.yml
** PRの編集ファイルによって自動でラベルをつける
面倒なラベル付けを自動化する。

#+caption: actions https://github.com/upptime/uptime-monitor/blob/master/.github/workflows/labeler.yml
#+begin_src yaml
name: Pull Request Labeler
on:
  - pull_request
  - pull_request_review
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Label all PRs
        uses: actions/labeler@master
        with:
          repo-token: "${{ secrets.GH_PAT }}"
      - name: Label approved PRs
        uses: koj-co/label-approved-action@master
        with:
          labels: "merge"
        env:
          GITHUB_TOKEN: "${{ secrets.GH_PAT }}"
#+end_src

#+caption: labels.yml https://github.com/upptime/uptime-monitor/blob/master/.github/labeler.yml
#+begin_src yaml
config:
  - ./*
tooling:
  - tooling/**/*.*
assets:
  - static/**/*.*
tests:
  - any: ["src/**/*.spec.js", "cypress/**/*"]
package:
  - any: ["package.json", "package-lock.json"]
source:
  - src/**/*
#+end_src
** GitHub Actionsのトリガー
pathsで特定ファイルが含まれるときのみ実行するときの注意点。
pushは使わずに、pull_requestトリガーを使うべき。

#+caption: 良い。Dockerfileが含まれるPRではすべて実行される
#+begin_src yaml
on:
  pull_request:
    paths:
      - 'Dockerfile'
#+end_src

#+caption: 悪い。Dockerfileが含まれないコミットでは実行されない。漏れやすい
#+begin_src yaml
on:
  push:
    paths:
      - 'Dockerfile'
#+end_src

pushではpull_request全体の変更を追うことができないので、コミットが分かれているとジョブが走らず、あたかもパスしているように見えて危険。
* Tasks
** DONE [[https://note.com/tably/n/n46041458d6b3][GitHub Actions向け自作アクションの作り方｜Tably｜note]]
CLOSED: [2022-04-30 Sat 11:00]
:LOGBOOK:
CLOCK: [2022-04-30 Sat 10:40]--[2022-04-30 Sat 11:00] =>  0:20
:END:
作り方。
* Reference
** [[https://zenn.dev/hsaki/articles/github-actions-component][GitHub ActionsにおけるStep/Job/Workflow設計論]]
** [[https://zenn.dev/snowcait/articles/787e83640746e1][Composite Action Template を作りました GitHub Actions]]
自作アクションの作り方。ミニマルでわかりやすい。
[[https://github.com/snow-actions/git-config-user][snow-actions/git-config-user: Set git user name and email address]]
* Archives
