:PROPERTIES:
:ID:       d6696b59-7349-4c0a-9512-b72598a918eb
:END:
#+title: Web Browser
* 概要
ウェブブラウザは、パソコンやスマートフォン等でWebサーバに接続するためのソフトウェア。
* Memo
* Tasks
** TODO [[https://www.oreilly.co.jp/books/9784873119038/][O'Reilly Japan - Real World HTTP 第2版]]
:LOGBOOK:
CLOCK: [2023-05-04 Thu 19:30]--[2023-05-04 Thu 19:55] =>  0:25
CLOCK: [2023-05-04 Thu 18:52]--[2023-05-04 Thu 19:17] =>  0:25
CLOCK: [2023-05-04 Thu 18:25]--[2023-05-04 Thu 18:50] =>  0:25
CLOCK: [2023-05-04 Thu 13:37]--[2023-05-04 Thu 14:02] =>  0:25
CLOCK: [2023-05-04 Thu 13:07]--[2023-05-04 Thu 13:32] =>  0:25
CLOCK: [2023-05-04 Thu 12:23]--[2023-05-04 Thu 12:48] =>  0:25
CLOCK: [2023-05-04 Thu 11:53]--[2023-05-04 Thu 12:18] =>  0:25
CLOCK: [2023-05-04 Thu 11:28]--[2023-05-04 Thu 11:53] =>  0:25
CLOCK: [2023-05-04 Thu 11:03]--[2023-05-04 Thu 11:28] =>  0:25
CLOCK: [2023-05-03 Wed 22:33]--[2023-05-03 Wed 22:58] =>  0:25
CLOCK: [2023-05-03 Wed 22:07]--[2023-05-03 Wed 22:32] =>  0:25
CLOCK: [2023-05-03 Wed 21:40]--[2023-05-03 Wed 22:05] =>  0:25
CLOCK: [2023-05-03 Wed 21:12]--[2023-05-03 Wed 21:38] =>  0:26
CLOCK: [2023-05-03 Wed 18:43]--[2023-05-03 Wed 19:08] =>  0:25
CLOCK: [2023-05-03 Wed 17:57]--[2023-05-03 Wed 18:22] =>  0:25
CLOCK: [2023-05-03 Wed 17:32]--[2023-05-03 Wed 17:57] =>  0:25
CLOCK: [2023-05-03 Wed 17:03]--[2023-05-03 Wed 17:28] =>  0:25
CLOCK: [2023-05-03 Wed 16:33]--[2023-05-03 Wed 16:58] =>  0:25
CLOCK: [2023-05-03 Wed 13:07]--[2023-05-03 Wed 13:32] =>  0:25
CLOCK: [2023-05-03 Wed 12:01]--[2023-05-03 Wed 12:26] =>  0:25
CLOCK: [2023-05-03 Wed 11:32]--[2023-05-03 Wed 11:57] =>  0:25
CLOCK: [2023-05-03 Wed 11:01]--[2023-05-03 Wed 11:26] =>  0:25
CLOCK: [2023-05-03 Wed 10:31]--[2023-05-03 Wed 10:56] =>  0:25
CLOCK: [2023-05-03 Wed 10:06]--[2023-05-03 Wed 10:31] =>  0:25
CLOCK: [2023-05-03 Wed 09:40]--[2023-05-03 Wed 10:05] =>  0:25
CLOCK: [2023-05-03 Wed 09:15]--[2023-05-03 Wed 09:40] =>  0:25
CLOCK: [2023-05-03 Wed 00:38]--[2023-05-03 Wed 01:03] =>  0:25
:END:
HTTPの解説。

- 機能が追加されたり修正されるのには理由がある。最初のコンセプトはシンプルであることが多い。その流れを知れば、全体を理解しやすくなる
- RFCはRequest For Comment。仕様書なのにこの言葉が使われているのは、軍事用としてスタートしたため。公開するためには意見を募るためという名目が必要だった
- 初期バージョンのHTTPにはバージョン番号がなかった
- MIMEタイプはファイルの種類を区別するための文字列で、電子メールのために作られ、HTTPでも流用された。ヘッダー名はContent-Type。当初の仕様にはなく、ドキュメントを送ることしかできなかった
- 電子メールとHTTPは基本は同じ。ヘッダー + 本文がある。HTTPの通信は高速で電子メールが往復しているのと同じようなもの
- HTTPはファイルシステムのような思想で作られている
- ブラウザによってはリダイレクトを行ったときにメソッドが変更されるものがある。そのため、メソッドが対応してないエラーが表示されることがある
- URNは名前。URLは住所。URLは住所なので、移動するとアクセスできない。いっぽうURNは名前でしかないので、どこにあるかの情報は別に必要
- URIにはURNという名前の付け方のルールも含まれる
- URLの ~#~ はフラグメントで、ブラウザ内部でのみ利用されるので、サーバーに送信されるのはフラグメントより前の部分だけ
- <link rel="canonical" href="..."> によって、正規のURLをサーバに教えられる。これによって、たとえばURLパラメータにトラッキングIDがついたURLが検索エンジンに登録されるのを防げる
  - あるいは、ソーシャルブックマークで別のURLと認識されることを防げる
- クッキーはHTTPヘッダーをベースにして実装されている。 ~Set-Cookie: LAST_ACCESS=12:04~ とすると、サーバ側がクライアント(ブラウザ)に保存を指示する
  - クライアントは値を保存しておき、次回のアクセス時に ~Cookie: LAST_ACCESS=12:04~ の形式で送信する。サーバ側はこの設定を読み取ることでクライアントが最後にアクセスした時刻を知ることができる
- オリジン ... ブラウザはスキーム、ドメイン、ポートの3つの組が同じであれば同一のサイトと判断する
  - ほかのサイトにクッキーなどを使えたら、セキュリティが
- キャッシュしてほしいがされてない場合のチェック
  - GETとHEAD以外のべき等ではないメソッド
  - Cache-Controlヘッダーにprivateが設定されている
  - Cache-Controlヘッダーにno-storeが設定されている
  - Authorizationヘッダーがあるが、Cache-Controlヘッダーにpublicがない
- ETagは、キャッシュがフレッシュかを判断するのにファイルに関連するハッシュ値を使って比較する。これによって、動的な送信内容であってもキャッシュを利用できるか判断できる
- 同じURLでもクライアントに返す結果が異なることを示すヘッダーがVary
- referer はRFCに提案されたときのスペルミス
- 公開鍵 → 南京錠
- TLSの骨格になる、「サーバを認証し、鍵を交換して通信を行う」というフローはTLS1.0から1.3まで大きく変わらない。その一方で、鍵交換の方法、メッセージの暗号化、メッセージの署名方式などそれぞれの場面で使うアルゴリズムの組み合わせをリスト化して管理している。サーバ・クライアント間で共通に使えるものを選択する仕組みにすることで、新しいアルゴリズムを少しずつ導入したり、古いアルゴリズムを非推奨にするといったことを、バージョン間で行いやすくなっている。このアルゴリズムのセットを暗号スイートという
  - 暗号スイートの一覧を出す
  - ~$ openssl ciphers -v~
- ~data:application/json,{"message": "hello"}~ をブラウザのURLバーに入れるとそのまま表示できる
- ブラウザがファイルをどのように処理するのか決めているのは、拡張子ではなくサーバから送られたMIMEタイプ
  - Content-Dispositionヘッダーの内容によって、ブラウザはこの動作を変更する
  - 次のヘッダーがサーバから返ってくると、ブラウザはレスポンスは表示用のものではなく、ダウンロードしてローカルに保存するためのものであると認識する
  - ~Content-Disposition: attachment; filename=filename.xlsx~
- 自動ダウンロードの開始(はじまらない場合はクリック、みたいな)の実現方法
  - サーバは2つURLを提供する。ひとつは実際にファイルをダウンロードするページ。もうひとつはHTMLのページを返し、そこにはダウンロードありがとうメッセージと下記のヘッダーを含む
    - ~<meta http-equiv="refresh" content="0;URL=./download_file">~
  - ブラウザがページを表示するときにContent-Dispositionヘッダーがあると、ページの表示をリセットせずにダウンロードだけを行う。まず完了ページをユーザに見せる。ブラウザはコンテンツを表示するときにメタタグを見つけるので、そのページにジャンプしようとする
- ダウンロードの中断、再開は大きなファイルの指定範囲を切り出してダウンロード、という形で可能になっている
  - サーバ側が指定範囲ダウンロードをサポートしている場合には、Accept-Rangesヘッダーをレスポンスに付与する
** TODO [[https://blog.amedama.jp/entry/2016/01/03/115602][Xvfb を使って仮想ディスプレイを作る - CUBE SUGAR CONTAINER]]
ディスプレイがない環境で、ディスプレイなしにテストができる。
** TODO ブラウザがどうサーバと接続し、HTMLページを表示までやっているか :DontKnow:
* Reference
** [[https://ja.wikipedia.org/wiki/%E3%82%A6%E3%82%A7%E3%83%96%E3%83%96%E3%83%A9%E3%82%A6%E3%82%B6][ウェブブラウザ - Wikipedia]]
* Archives
