:properties:
:ID: 20231008T024111
:mtime:    20241102180227 20241028101410
:ctime:    20241028101410
:end:
#+title:      KDOC 31: イヤーカフ型イヤホンが良い
#+date:       [2023-10-08 Sun 02:41]
#+filetags:   :essay:
#+identifier: 20231008T024111

部屋の騒音を紛らわしたり一人暮らしでもの寂しいときにBGMとして音楽やラジオをかけている。特に音楽が好きではないので音質とかはどうでもいい。

湿性耳垢なので、耳の奥に入れるタイプは汚くなって嫌だ。奥に入れないタイプでも耳の骨が痛くなる。ヘッドホンは疲れる。耳掛け型は耳の付け根が痛くなる。首にかけるタイプは充電が面倒だ。スピーカーが一番理想的だが、苦情が来ないか心配で極小ボリュームになる[fn:1]。

雑な聞き方なので音質なんてどうでもいいから、とにかく楽なものがほしい、と考えていた。特定の機種というよりは、条件に合う方式を探していた。最近いい感じのものを見つけた。イヤーカフ型イヤホン、だ。

イヤーカフは耳のアクセサリの名前で、まさに同じ感じだ。オレの買ったやつはワイヤレスで、左右をつなぐ線はなく分かれている。左右それぞれの形は豆を2つつなげたような不思議な形をしていて、2つの豆で耳たぶの少し上あたりの、耳外側のひだに挟んで固定する。装飾品として名前がついているくらいなのでおしゃれな形をしている。機能的にも優れているように感じた。運動をしてもずれたり擦れたりが少ない。最初はこれをどうやってつけるか戸惑う。音が出る部分と耳の穴は離れていて密閉されていない。蒸れず、まわりの音も聞こえる。充電はワイヤレスのEarPodsで浸透した方式(おそらく)の、ケースに入れるだけで充電されるタイプだ。簡単だ。ワイヤレスイヤホンの充電が面倒、というのは過去の話になったのだろう。

現代のほかのイヤホンと比べて、技術的な目新しさはない。形が機能的に優れているというのが発明ポイントなのだろう。イヤホンは異常に種類がある品目の1つで、方式や形はもう出尽くしているように見えていたけど、じつはまだ余地があった。

ということで、イヤーカフ型イヤホンは作業BGMを流すのに最適だ。家事のながら作業、運動にも向いている。

[fn:1] 隣の重低音だけの音漏れがうるさい部屋に住んだことがあって、音量に気をつければいい、という話ではないと考えている。
