:properties:
:ID: 20240330T124355
:end:
#+title:      KDOC 133: ワーケーションで得た知見
#+date:       [2024-03-30 Sat 12:43]
#+filetags:   :draft:essay:
#+identifier: 20240330T124355

# (denote-rename-file-using-front-matter (buffer-file-name) 0)
# (save-excursion (while (re-search-backward ":draft" nil t) (replace-match "")))
# (flush-lines "^\\#\s.+?")

# ====ポリシー。
# 1ファイル1アイデア。
# 1ファイルで内容を完結させる。
# 常にほかのエントリとリンクする。
# 自分の言葉を使う。
# 参考文献を残しておく。
# 自分の考えを加える。
# 構造を気にしない。
# エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
# アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
# エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
# 恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。

* この文書のステータス
- 作成
  - [X] 2024-03-31 貴島
- レビュー
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))

# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。
* 概要
ワーケーションを思い立ち、1日だけ甲府で仕事した。が、全然仕事する気にならなかった。事前の準備が大切そうに見えたので、次回に備えておく。

#+begin_export html
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d10552.4321938283!2d138.56234615223227!3d35.66633983386785!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x601bf850977851a9%3A0xc276c11755ca7309!2sKofu%2C%20Yamanashi!5e0!3m2!1sen!2sjp!4v1711869303957!5m2!1sen!2sjp" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
#+end_export

問題点。

- まともな机と椅子がなかった

  ビジネスホテルに泊まったのだが、棚みたいな見かけ重視の机で、パソコンを操作できるものではなかった。椅子も見栄えだけのもの。泊まるための部屋で、仕事するのを想定してない。写真ではもうちょっとよさそうに見えたのだが。

- 結局やってるのは同じ仕事なので、場所を変えてもそんなに違う感じはしない

  狭い部屋が影響している可能性はある。しかし、場所が変わっただけでは大して気分転換にならなかった。外に出て知らない街を歩きたかった。

- 泊まった場所に風情がない

  典型的な地方のロードサイド沿いのホテルで、風景は最悪で部屋は狭かった。見飽きた風景で、騒がしく歩きにくい。

これらを次に生かした選択肢を考える。

まず、宿泊施設の決め方。1つは旅館に宿泊することだ。和室だと机と椅子を考えなくていい。あるいは、民泊でワーケーション用の部屋があるのでそこに泊まる。ホテルは普通の価格だと泊まるだけの部屋なので、避けたほうがよさそう。

次に宿泊施設の場所。狭い空間にいい作業スペースがある可能性は少ない。都市部を避けたほうが広さ・値段・気分転換の面で有利か。

あとは、前もって時短勤務としておくのも必要だろう。どうやっても旅先で8時間フルの仕事をやる気にはならない。午前や夜だけを勤務時間として、あとは好きに過ごす。

* 関連
なし。
