:properties:
:ID: 20240501T023710
:end:
#+title:      KDOC 148: ミンサガリマスターが最高のリマスターだった
#+date:       [2024-05-01 Wed 02:37]
#+filetags:   :draft:essay:
#+identifier: 20240501T023710

# (denote-rename-file-using-front-matter (buffer-file-name) 0)
# (save-excursion (while (re-search-backward ":draft" nil t) (replace-match "")))
# (flush-lines "^\\#\s.+?")

# ====ポリシー。
# 1ファイル1アイデア。
# 1ファイルで内容を完結させる。
# 常にほかのエントリとリンクする。
# 自分の言葉を使う。
# 参考文献を残しておく。
# 自分の考えを加える。
# 構造を気にしない。
# エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
# アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
# エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
# 恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。

* この文書のステータス
- 作成
  - [X] 2024-05-02 貴島
- レビュー
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))

# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。
* 概要
#+begin_export html
<iframe width="560" height="315" src="https://www.youtube.com/embed/DLKiGQ6wNCA?si=ujnmikDJegAwVjjj" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
#+end_export

「ロマンシング サガ -ミンストレルソング-」(ミンサガ)は、フリーシナリオのロールプレイングゲームである。PS2で出ていた。中学生くらいにプレイしてたゲームで、それまでRPGといえばドラクエしか知らなかった自分には衝撃で、ハマった。

最近リマスター版をやり、「リマスター」として完璧な仕事なことに驚いた。

- ゲームシステムの追加

  ニューゲームの持ち越しなどが追加されて、周回しやすくなった。仲間にできるキャラが増えた。

- 追加項目がオプショナルなこと

  ストーリー開始前に、原作との違いが示される。プレイヤーは原作版かリマスター版を適用するか選べる。

- 便利機能の追加

  戦闘や移動の倍速機能が本当に便利。原作は遅すぎた。当時も遅いなと考えていたくらいだから、最近のゲームのテンポよさに慣れるともう元の速度ではできない。

- ストーリーはそのまま収録。ちょっとどうかしてる迷場面(そこも魅力のひとつ)もそのまま

  ストーリーはもう完成しているのでいじる必要がなかったし、よくなったとしても「昔のほうがよかった」となっていただろう。リマスターに求めるのは懐かしさもあって、別のものを楽しみたいわけではない。

- いくつかのUIの改良

  わかりやすく、操作しやすくなった。

昨今リマスターされるゲームは多い。だいたい、そのまま移植しただけのものになるか、改悪になる印象がある。ミンサガリマスターでは見事に回避していた。完成されたストーリーや世界観はそのままに、より快適なゲーム体験が得られるようになった。

* 関連
なし。
