:properties:
:ID: 20240210T220912
:end:
#+title:      KDOC 87: なぜRFCの内容を理解できないのか
#+date:       [2024-02-10 Sat 22:09]
#+filetags:   :draft:essay:
#+identifier: 20240210T220912

# (denote-rename-file-using-front-matter (buffer-file-name) 0)
# (org-roam-tag-remove)
# (org-roam-tag-add)

# ====ポリシー。
# 1ファイル1アイデア。
# 1ファイルで内容を完結させる。
# 常にほかのエントリとリンクする。
# 自分の言葉を使う。
# 参考文献を残しておく。
# 自分の考えを加える。
# 構造を気にしない。
# エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
# アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
# エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
# 恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。

* この文書のステータス
:LOGBOOK:
CLOCK: [2024-02-11 Sun 15:03]
CLOCK: [2024-02-11 Sun 14:33]--[2024-02-11 Sun 14:58] =>  0:25
:END:
- 作成
  - [X] 2024-02-11 貴島
- レビュー
  - [ ] 2024-mm-dd <署名> (progn (kill-line 0) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))
# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。(org-roam-tag-remove)。
# すべてのコメントを削除した。
* 概要
IETFから新しい[[id:ec870135-b092-4635-8f8e-74a5411bb779][RFC]]エントリが出たときにさらっと読むのだが、8割方わからない。プロのプログラマ、Web開発者としてはチェックしたいと考えている。わからない理由を書く。
* わからない理由
ベースの知識がないから、これに尽きる。ネットワークに関する知識がない。プロトコルはHTTPを多少知っているだけだ。多くのエントリは既存のプロトコルの拡張や後継仕様についてだから、元のプロトコルを知らないと理解できない。RFCで初めて見た単語、というパターンはかなり多い。

新聞を読める人のプロセスと近そうに見える。新聞を読む人はすでに文脈ができあがっていて、各記事で受け取る情報量は過去記事の差分にすぎない。読まない人は情報量が多いので圧倒される。ただ新聞より専門的な内容なので、前提知識がないといけない。あるいは、関係ない分野はスルーでよさそう。
* 関連
- [[id:20221210T014600][KDOC 10: より理解する]]。理解つながり
