:properties:
:ID: 20240820T181738
:end:
#+title:      KDOC 222: TLSのバージョン制限を確認する
#+date:       [2024-08-20 Tue 18:17]
#+filetags:   :draft:code:
#+identifier: 20240820T181738

# (denote-rename-file-using-front-matter (buffer-file-name) 0)
# (save-excursion (while (re-search-backward ":draft" nil t) (replace-match "")))
# (flush-lines "^\\#\s.+?")

# ====ポリシー。
# 1ファイル1アイデア。
# 1ファイルで内容を完結させる。
# 常にほかのエントリとリンクする。
# 自分の言葉を使う。
# 参考文献を残しておく。
# 文献メモの場合は、感想と混ぜないこと。1つのアイデアに反する
# ツェッテルカステンの議論に寄与するか
# 頭のなかやツェッテルカステンにある問いとどのようにかかわっているか
# エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
# アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
# エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
# 恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。

# ====永久保存メモのルール。
# 自分の言葉で書く。
# 後から読み返して理解できる。
# 他のメモと関連付ける。
# ひとつのメモにひとつのことだけを書く。
# メモの内容は1枚で完結させる。
# 論文の中に組み込み、公表できるレベルである。

# ====価値があるか。
# その情報がどういった文脈で使えるか。
# どの程度重要な情報か。
# そのページのどこが本当に必要な部分なのか。

* この文書のステータス
- 作成
  - [X] 2024-08-22 貴島
- レビュー
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))

# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。
* 概要
セキュリティ上の理由で、サーバ側でTLSの古いバージョンのリクエストを受け付けなくすることがある。設定後、[[id:b11fb9a4-0a26-4354-bc60-6c755c256b21][curl]]で動作確認する方法をまとめる。

#+caption: TLSバージョン1.2を上限に設定する。TLS1.2を使用し、成功する
#+begin_src shell
  curl -v --tls-max 1.2 https://www.fsa.go.jp/ -I
#+end_src

#+caption: 実行結果
#+begin_src shell
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Host www.fsa.go.jp:443 was resolved.
  ,* IPv6: (none)
  ,* IPv4: 3.166.244.76, 3.166.244.80, 3.166.244.77, 3.166.244.84
  ,*   Trying 3.166.244.76:443...
  ,* Connected to www.fsa.go.jp (3.166.244.76) port 443
  ,* found 158 certificates in /home/orange/.guix-profile/etc/ssl/certs/ca-certificates.crt
  ,* found 474 certificates in /home/orange/.guix-profile/etc/ssl/certs
  ,* GnuTLS ciphers: NORMAL:-ARCFOUR-128:-CTYPE-ALL:+CTYPE-X509:-VERS-SSL3.0:-VERS-TLS-ALL:+VERS-TLS1.2:+VERS-TLS1.1:+VERS-TLS1.0
  ,* ALPN: curl offers h2,http/1.1
  ,* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
  ,*   server certificate verification OK
  ,*   server certificate status verification SKIPPED
  ,*   common name: www.fsa.go.jp (matched)
  ,*   server certificate expiration date OK
  ,*   server certificate activation date OK
  ,*   certificate public key: RSA
  ,*   certificate version: #3
  ,*   subject: C=JP,ST=Tokyo-to,L=Chiyoda-ku,O=Financial Services Agency,CN=www.fsa.go.jp
  ,*   start date: Wed, 05 Jun 2024 06:40:28 GMT
  ,*   expire date: Sat, 28 Jun 2025 14:59:59 GMT
  ,*   issuer: C=JP,O=SECOM Trust Systems CO.\,LTD.,CN=SECOM Passport for Web SR 3.0 CA
  ,* ALPN: server accepted h2
  ,* using HTTP/2
  ,* [HTTP/2] [1] OPENED stream for https://www.fsa.go.jp/
  ,* [HTTP/2] [1] [:method: HEAD]
  ,* [HTTP/2] [1] [:scheme: https]
  ,* [HTTP/2] [1] [:authority: www.fsa.go.jp]
  ,* [HTTP/2] [1] [:path: /]
  ,* [HTTP/2] [1] [user-agent: curl/8.5.0]
  ,* [HTTP/2] [1] [accept: */*]
  > HEAD / HTTP/2
  > Host: www.fsa.go.jp
  > User-Agent: curl/8.5.0
  > Accept: */*
  >
  < HTTP/2 200
  < content-type: text/html
  < content-length: 16891
  < date: Tue, 20 Aug 2024 09:21:14 GMT
  < server: Apache
  < last-modified: Mon, 29 Jul 2024 04:09:01 GMT
  < accept-ranges: bytes
  < x-frame-options: SAMEORIGIN
  < x-xss-protection: 1; mode=block
  < x-content-type-options: nosniff
  < vary: Accept-Encoding
  < x-cache: Hit from cloudfront
  < via: 1.1 f93e179d1b1a552c89c83ee369ac624a.cloudfront.net (CloudFront)
  < x-amz-cf-pop: NRT20-P6
  < x-amz-cf-id: YPb7msF24vcjjbBzuprNX6kKyClkEE0wj0Mk2QcZnOCPFB2HhbzWhg==
  < age: 107044
  <
  0 16891    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  ,* Connection #0 to host www.fsa.go.jp left intact
  [ Babel evaluation exited with code 0 ]
#+end_src

#+caption: TLSバージョン1.0を上限に設定する。TLS1.0を使用し、失敗する
#+begin_src shell
  curl -v --tls-max 1.0 https://www.fsa.go.jp/ -I
#+end_src

#+caption: 実行結果。Error in protocol versionを確認できる
#+begin_src shell
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Host www.fsa.go.jp:443 was resolved.
,* IPv6: (none)
,* IPv4: 3.166.244.80, 3.166.244.76, 3.166.244.77, 3.166.244.84
,*   Trying 3.166.244.80:443...
,* Connected to www.fsa.go.jp (3.166.244.80) port 443
,* found 158 certificates in /home/orange/.guix-profile/etc/ssl/certs/ca-certificates.crt
,* found 474 certificates in /home/orange/.guix-profile/etc/ssl/certs
,* GnuTLS ciphers: ,NORMAL:-ARCFOUR-128:-CTYPE-ALL:+CTYPE-X509:-VERS-SSL3.0:-VERS-TLS-ALL:+VERS-TLS1.0
,* ALPN: curl offers h2,http/1.1
,* gnutls_handshake() failed: Error in protocol version
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
,* Closing connection
curl: (35) gnutls_handshake() failed: Error in protocol version
[ Babel evaluation exited with code 35 ]
#+end_src

* 参考
- [[https://qiita.com/daji110728/items/ec400d0268c76cc1dc04][curlコマンドでTLSバージョンを指定する方法 #ALB - Qiita]]
* 関連
# 関連するエントリ。なぜ関連させたか理由を書く。意味のあるつながりを意識的につくる。
# この事実は自分のこのアイデアとどう整合するか。
# この現象はあの理論でどう説明できるか。
# ふたつのアイデアは互いに矛盾するか、互いを補っているか。
# いま聞いた内容は以前に聞いたことがなかったか。
# メモ y についてメモ x はどういう意味か。
なし。
