:properties:
:ID: 20240822T235059
:end:
#+title:      KDOC 224: 『親孝行プレイ』
#+date:       [2024-08-22 Thu 23:50]
#+filetags:   :draft:book:
#+identifier: 20240822T235059

# (denote-rename-file-using-front-matter (buffer-file-name) 0)
# (save-excursion (while (re-search-backward ":draft" nil t) (replace-match "")))
# (flush-lines "^\\#\s.+?")

# ====ポリシー。
# 1ファイル1アイデア。
# 1ファイルで内容を完結させる。
# 常にほかのエントリとリンクする。
# 自分の言葉を使う。
# 参考文献を残しておく。
# 文献メモの場合は、感想と混ぜないこと。1つのアイデアに反する
# ツェッテルカステンの議論に寄与するか
# 頭のなかやツェッテルカステンにある問いとどのようにかかわっているか
# エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
# アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
# エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
# 恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。

# ====永久保存メモのルール。
# 自分の言葉で書く。
# 後から読み返して理解できる。
# 他のメモと関連付ける。
# ひとつのメモにひとつのことだけを書く。
# メモの内容は1枚で完結させる。
# 論文の中に組み込み、公表できるレベルである。

# ====価値があるか。
# その情報がどういった文脈で使えるか。
# どの程度重要な情報か。
# そのページのどこが本当に必要な部分なのか。

* この文書のステータス
- 作成
  - [X] 2024-08-23 貴島
- レビュー
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))

# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。
* 概要
# 本文(タイトルをつける)。
[[https://amzn.to/3YTOgnK][『親孝行プレイ』]]は親孝行の正しいスタイルを提唱する本。
* メモ
- 心に行動が伴うのではなく、行動の後に心が伴うのが、現代の親孝行なのだ(位置38)
- 「子供は小さいころから、親や子供を喜ばせるプレイをしている」そう、「無邪気」とか「天真爛漫」という言葉だけで片付けられていた子供の言動は、すでに「プレイ」であったのだ。親孝行は心でするもの、親孝行に計算や打算はいらない、とする古びた固定観念は、この例から見ても明らかなように、今すぐ捨てなければならないのがわかるであろう(位置126)
- 私は、「えなりにはなれなかったけれど、えなりに学びつつ、たまにはえなりのように親孝行をする」スタンスを強く推奨したい。そして、それを実践する者をこのように命名したい。「エナリスト」と(位置161)
- 親孝行とは、親と自分が一緒に楽しむ、というものではない。親という客を喜ばせるためのプレイ、諸君はホスト、ホステス、ボーイ、支配人、S嬢、M嬢、掃除係のおばちゃんまで、「親孝行クラブ」従業員のすべての役割を担わなくてはならないのだ(位置208)
- ある程度の年齢になったとき、親がもっとも喜ぶトークとは「自分の子供はいかに頑張ってるか」なのだ。親孝行プレイは奉仕プレイ。諸君自身の恥ずかしさや照れはこの際、忘れなくてはならない(位置281)
- この「自分の自慢話」に続けて「子供の自慢話」をすることには、ひとつの大きな利点がある。「自分の子供はすごい」そして「自分の孫もすごい」ということを、諸君の口から聞くことができれば、親は言いたくてしょうがない結論を口にすることができるのだ。「蛙の子は蛙だな」初めての親孝行旅行で、親にこの言葉を言わせることができたら、諸君の親孝行道の未来は明るいと思っていい(位置306)
- 親孝行旅行に対する過度な期待を持ってもらわないためには、旅行後こそマメな電話や、とくに用事もないときの帰省といったものが重要になってくる。それによって、いわば「ガス抜き」をし、親孝行旅行は「日ごろおこなっている」親孝行の中でも特別なものであるということを、いつまでも思わせ続けなければならないのだ(位置362)
- 孫よりも子供の方が可愛い理由は、厳然とした事実としてあるのだ。お教えしよう。「孫にはすでに他人の血が入っている」孫にはすでに諸君の妻、すなわち他人の血が混入しており、純粋な肉親ではないのである。祖父母という種族が、孫が父親似か母親似かをどうしてあれほど気にするのか、その理由もここにある。彼らはどれだけ自分の血が濃く出ているのか、何パーセントが我が家のものなのか、を注視しているのである。要は「孫は私の子供にそっくり」ということだけを言いたいのだ(位置708)
- そのころは親孝行プレイにおける公費の使用が認められていなかったが、いまでは子供にそういったプレイをさせるとき、前払いのギャラ2000円、というのが認められているので、諸君にはぜひ実行していただきたいものである。かように、孫見せプレイは、イコールで血筋プレイであることを肝に命じておかねばならない(位置720)
- 実は親孝行プレイとは、「両親まとめて」やってはいけないのだ。それは、親孝行ポイントが半減するどころか、時にはマイナスにもなってしまう、親孝行初心者がもっとも陥りやすいミステイクなのだ(位置825)
- プレゼントというものは、相手にとって必要なものを贈る行為ではない。そのようなものは本人が自分の意志で購入すればいいのである。プレゼントとは本人では絶対に買わないもの、しかしもらうと意外に嬉しいものをチョイスするべきなのだ(位置954)
- 諸君も我が身を振り返ればわかるであろう。父親、いや男子というものは状況が変わらないと喋ることもおぼつかない人種なのだ(位置1017)
- よく考えていただきたい。有名人でなくとも、諸君が年長の者と話す機会をもったとき、実はその会話が盛り上がるか否かは「話が面白いか」がポイントではないのである。「その人の話だったらどんなにつまらない話でも聞ける」という感情がまず第一にあるはずなのだ(位置1067)
- とにかく「よし、オレはやるだけやったぞ」という達成感を得た者でなければ、永遠に親孝行への道は開かれない(位置1430)
- 死とはたぶん崖のようなもの。まだ、その崖が見えてない内はいくらでも「死にたいね」などと余裕があるが、だんだん見えてくるに従い、屁放り腰になる。親孝行とは、そんな屁放り腰な親をこちらに向かせ、少しでも崖の恐怖を和らげる行為だ(位置1535)
* 関連
# 関連するエントリ。なぜ関連させたか理由を書く。意味のあるつながりを意識的につくる。
# この事実は自分のこのアイデアとどう整合するか。
# この現象はあの理論でどう説明できるか。
# ふたつのアイデアは互いに矛盾するか、互いを補っているか。
# いま聞いた内容は以前に聞いたことがなかったか。
# メモ y についてメモ x はどういう意味か。
- [[id:20240822T234552][KDOC 223: 『いやげ物』]]。みうらじゅん著作つながり
