:properties:
:ID: 20240908T140226
:end:
#+title:      KDOC 237: 『マイ仏教』
#+date:       [2024-09-08 Sun 14:02]
#+filetags:   :draft:book:
#+identifier: 20240908T140226

# (denote-rename-file-using-front-matter (buffer-file-name) 0)
# (save-excursion (while (re-search-backward ":draft" nil t) (replace-match "")))
# (flush-lines "^\\#\s.+?")

# ====ポリシー。
# 1ファイル1アイデア。
# 1ファイルで内容を完結させる。
# 常にほかのエントリとリンクする。
# 自分の言葉を使う。
# 参考文献を残しておく。
# 文献メモの場合は、感想と混ぜないこと。1つのアイデアに反する
# ツェッテルカステンの議論に寄与するか
# 頭のなかやツェッテルカステンにある問いとどのようにかかわっているか
# エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
# アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
# エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
# 恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。

# ====永久保存メモのルール。
# 自分の言葉で書く。
# 後から読み返して理解できる。
# 他のメモと関連付ける。
# ひとつのメモにひとつのことだけを書く。
# メモの内容は1枚で完結させる。
# 論文の中に組み込み、公表できるレベルである。

# ====価値があるか。
# その情報がどういった文脈で使えるか。
# どの程度重要な情報か。
# そのページのどこが本当に必要な部分なのか。

* この文書のステータス
:LOGBOOK:
CLOCK: [2024-09-14 Sat 20:09]--[2024-09-14 Sat 20:34] =>  0:25
CLOCK: [2024-09-14 Sat 19:38]--[2024-09-14 Sat 20:03] =>  0:25
CLOCK: [2024-09-14 Sat 19:11]--[2024-09-14 Sat 19:36] =>  0:25
:END:
- 作成
  - [X] 2024-09-15 貴島
- レビュー
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))

# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。
* 概要
[[https://amzn.to/3B26qdc][『マイ仏教』]]は、[[id:f8030800-701c-44ed-b9f8-73df6a48ea53][みうらじゅん]]による仏教入門本。
* メモ
- 吉田拓郎は大ヒットした曲「結婚しようよ」それまでのフォーク・ファンから非難を受ける。それでも自分を貫き、単なる「フォーク・シンガー」から「吉田拓郎」となった(p40)
- 好きになっていく過程はどれも同じ、「好き=なりたい」だった、という。怪獣が好きだったときは円谷英二になりたかったし、仏像が好きだった頃はお坊さんになりたかった(p42)
- 人間はどうしても良いことを思いつくと、人に伝えたくなる。自分のことをわかってほしい、自分のことを褒めてほしいという執着が出てしまう。お釈迦さんが、それは煩悩であると一刀両断しているにもかかわらず、どうしても「自分」というものが出てきてしまう、「青春ノイローゼ」の時期だった、という(p43)
- 二人だけの「見仏」活動に飽き足らず、団体を作ろうということで始まったのが「大仏連」である。実質みうらじゅんと、いとうせいこうの二人だけなのだが、それでも団体っぽく見せる手法は、大乗仏教の手口にならったものである、という(p47)
- 地方の寺に行くと、ボロボロの仏像を見ることがよくある。仏教の教えを体現するはずの仏像もまた、諸行無常からは逃れられないということを、身をもって教えてくれていたのである、という(p56)
- 物を集めるというのは、空しさを知る「修行」である。コレクターとか趣味人とか呼ばれる人は、他人には「あの人は好き勝手やっていて、楽しそうでいいわね」なんて思われがちであるが、実際はかなり辛い修行生活をおくっているのである。しかしなかなか人にはそのことを理解されず、自業自得と言われ、二重の辛苦を背負っているものである、という(p59)
- フェノロサと言えば、岡倉天心とともに、法隆寺夢殿の扉を開け、長く秘仏として安置されていた救世観音を開張させた、「元祖・勝手に観光協会」の人物として有名である。来日して日本美術にグッときたフェノロサは、全国の社寺を回りその保存運動に尽力した。文化財保護というのは彼の「マイブーム」であったと考えている、という。お寺を存続させるという考え方自体、日本人ではなく外国人のセンスによって始まったのではないか、という(p60)
- 「自分探し」よりもむしろ、「自分なくし」の方が大事なのではないか、という。お釈迦さんの教えにならい、「自分探しの旅」ではなくて、「自分なくしの旅」を目指すべきである(p62)
- すぐに自分をなくせるかというと、大変むずかしい。方法は、誰かに「憧れ=なりたい」と考えることである、という。円谷英二しかりお寺の住職しかりボブ・ディランしかり。「その人になりたい」と考え、必死で真似をしているとき、自分はなくなっている。その人になりたいと考えて、できるだけ真似をする、つまり誰かを好きになって夢中になる、という癖をつければいい。それは自分をなくしていく技術を獲得することでもある(p62)
- 日本人は、宗教をタダだと考えている節がある、という。たった数十円のお賽銭を初詣のときだけ納め、数百円の絵馬を買うことで、「願い事」が叶うと考えている。これは「フグ・カニ・スッポン」を奢らない会社の上司と同じで、それで現世利益を得ようというのではあまりに虫が良すぎる(p83)
- 今の日本の仏教は、ほとんどがフリー・コンサートのようなものである。つまり仏教をタダだと考えている。だから、聞く耳を持たない。お金がすべてではないが、日本仏教の人気低下の理由のひとつに、このような意識が働いていることを挙げられるのではないか。その点、新興宗教はいろいろな形でお金を払っているから、信仰にも布教にも熱心である。あくどいシステムのもとで成り立っているなら論外だが、少なくともお金を払っているだけ彼らが自分の宗教に対して真面目なのは確かである(p84)
- かつては「男は黙ってサッポロビール」。三船敏郎が出演したコマーシャルのように、他にも「不器用ですから」の高倉健のように、自分から機嫌を取りにいかないほうが格好良い、とされる時代があった。それを世の男性は憧れ真似をするようになって、進んで「ご機嫌を取る」ことを考えなくなってしまったのではないか(p92)
- 「何でこの俺が」という言葉。それは「ご機嫌界」で一番の禁句である。「俺」に込められた意味が、大概の怒りの原因である(p92)
- 難しいのは、「機嫌を取る」ふりをしながら、ひそかにキックバックを求めてしまうこと。「相手のためにこれだけ尽くしたから、きっとこれだけの報酬を得られるはず」というもの(p96)
- 「自分をなくして、相手の機嫌を取る」行為、これまで「修行」と呼んでいたものを、「 *僕* 滅運動」と呼ぶことにした、という(p96)
- 飲み会の席で「いや、〜」とか「でも、〜」を言わない、というのも、ささやかながらも大切な「僕滅運動」だという。できるだけ「なるほど」とか「そうだね」と言って話を受けたほうが、圧倒的に感じがいいものである(p97)
- 「仏像ブーム」という言葉も、「ゆるキャラ」という言葉も、それまでその言葉が示すような現象や存在があったとしても、言葉を与えられなければなかなか実体化していかない。しかし不思議なもので、言葉として定着した瞬間、一気にその実体が目に見えるようになってくる、という(p113)
- 比較ができるからこそ人類は発展した可能性もあるが、比較こそが苦しむを生む原因な可能性もある。これを「比較三原則」と呼んでいる(p113)
- どんな辛いときでも、「そこがいいんじゃない」と考えるようにしている、という。「マイブーム」と呼んでいるものは、出会いの瞬間からそれが好きになってハマっているわけではない。「これは一体何なのか」という「問い」がまずあり、それについて考え抜くところからスタートしている。そのように考え続けて、ようやく出口近くにさしかかろうという瞬間に出てくるのが、「そこがいいんじゃない」というフレーズである。それは文字通り、その対象を好きになりかける瞬間でもある(p115)
- 不安というのは突然やってくる。その瞬間「不安タスクティック」と唱えれば、楽になる(p117)

* 関連
なし。
# 関連するエントリ。なぜ関連させたか理由を書く。意味のあるつながりを意識的につくる。
# この事実は自分のこのアイデアとどう整合するか。
# この現象はあの理論でどう説明できるか。
# ふたつのアイデアは互いに矛盾するか、互いを補っているか。
# いま聞いた内容は以前に聞いたことがなかったか。
# メモ y についてメモ x はどういう意味か。
