:properties:
:ID: 20240213T013922
:end:
#+title:      KDOC 92: 何も覚えてなくてショックを覚えた
#+date:       [2024-02-13 Tue 01:39]
#+filetags:   :draft:essay:
#+identifier: 20240213T013922

# (denote-rename-file-using-front-matter (buffer-file-name) 0)
# (org-roam-tag-remove)
# (org-roam-tag-add)

# ====ポリシー。
# 1ファイル1アイデア。
# 1ファイルで内容を完結させる。
# 常にほかのエントリとリンクする。
# 自分の言葉を使う。
# 参考文献を残しておく。
# 自分の考えを加える。
# 構造を気にしない。
# エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
# アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
# エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
# 恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。

* この文書のステータス
- 作成
  - [X] 2024-02-14 貴島
- レビュー
  - [ ] 2024-mm-dd <署名> (progn (kill-line 0) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))
# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。(org-roam-tag-remove)。
# すべてのコメントを削除した。
* 概要
『この世界の片隅に』および『この世界の（さらにいくつもの）片隅に』は『この世界の片隅に』は、太平洋戦争中の呉を舞台にした映画である。

#+begin_export html
<iframe width="560" height="315" src="https://www.youtube.com/embed/SSGOqeMhVk8?si=udchMZSizkVGLlUQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
#+end_export

* 何も覚えていなかった

4年ほど前、まだ学生だったころに『この世界の片隅に』を観ていて面白かった記憶がある。『この世界の（さらにいくつもの）片隅に』も面白いだろうと考えて最近観た。最後まで面白く、初めて見るストーリー、と認識して観たのだが、『この世界の（さらにいくつもの）片隅に』は単にカットを追加したバージョンにすぎないのを後で知って衝撃を受けた。

ストーリーを何も覚えてなかった。初見かと考えていた。面白かったというのは覚えている。自分の頭で何も考えずに観てるだけになってたのだろう。次の4年後は思い出せるだろうか。
