:properties:
:ID: 20241211T011547
:mtime:    20250118184721
:ctime:    20241211011548
:end:
#+title:      KDOC 323: ノベルゲームバンドルづくり
#+date:       [2024-12-11 Wed 01:15]
#+filetags:   :draft:project:
#+identifier: 20241211T011547

# (denote-rename-file-using-front-matter (buffer-file-name) 0)
# (save-excursion (while (re-search-backward ":draft" nil t) (replace-match "")))
# (flush-lines "^\\#\s.+?")

# ====ポリシー。
# 1ファイル1アイデア。
# 1ファイルで内容を完結させる。
# 常にほかのエントリとリンクする。
# 自分の言葉を使う。
# 参考文献を残しておく。
# 文献メモの場合は、感想と混ぜないこと。1つのアイデアに反する
# ツェッテルカステンの議論に寄与するか。それで本を書けと言われて書けるか
# 頭のなかやツェッテルカステンにある問いとどのようにかかわっているか
# エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
# アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
# エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
# 恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。
# 個人の感想・意思表明ではない。事実や書籍情報に基づいている

# ====永久保存メモのルール。
# 自分の言葉で書く。
# 後から読み返して理解できる。
# 他のメモと関連付ける。
# ひとつのメモにひとつのことだけを書く。
# メモの内容は1枚で完結させる。
# 論文の中に組み込み、公表できるレベルである。

# ====水準を満たす価値があるか。
# その情報がどういった文脈で使えるか。
# どの程度重要な情報か。
# そのページのどこが本当に必要な部分なのか。
# 公表できるレベルの洞察を得られるか

# ====フロー。
# 1. 「走り書きメモ」「文献メモ」を書く
# 2. 1日1回既存のメモを見て、自分自身の研究、思考、興味にどのように関係してくるかを見る
# 3. 追加すべきものだけ追加する

* この文書のステータス
- 作成
  - [X] 2024-12-15 貴島
- レビュー
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))

# チェックリスト ================
# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。
* WIP プロジェクトステータス

プロジェクトは進行中である。

* 概要
# 本文(見出しも設定する)
著作権の問題のない文章を、ノベルゲーム風にして名文を手軽に読めるようにする。
* なぜ作ったか

なぜ作ったか。

- 青空文庫などで、歴史的文学がただで大量に公開されている。しかし、それらがじゅうぶんに活用されているとはいえない。その面白さや奥深さに比して、読んだことのあるものは少ない。読もうと考えた機会はあったものの、すべて読み通せたものは多くない。個人的にもそうだし、体感的に、そもそも存在を知らない人も多い
- 著作権の切れた本はAmazon Kindleなどでも無料で販売されていて、端末にダウンロードはしていた。しかし読む気になれず、ずっと未読のままで眠っている

原因は、われわれがおかれた環境にあるように見える。娯楽は即効性を求めるようになっている。無限にあるコンテンツのなかで視聴にたるかどうかは、最初の数十秒〜数十分で判断する。本の世界を認識するための叙述…のどかな時代特有の長々とした序盤…を読み終える前に脱落することが多い。名作であるもののなかには、序盤が退屈に感じたり世界に入りこむのが大変なものもある。

そこで、ノベルゲームの表示スタイルで再生できるようにした。

- 少しづつ文字が表示されるので圧倒されない
- リズムがつきやすい
- 背景によって、場面のイメージがつきやすい

また、別の方向性として、明治〜昭和の時代背景であったり地理(特に東京)は、読むうえで必要な前提知識となっている。さらに、書いた人物の実在を感じる情報…住んだ家や生い立ち、家族構成、専門領域、好物…を知っているほど読みやすくなる。そのあたりを得るためのヒントを提供できればよいと考えている。

* 仕様の方針

- ノベルゲームエンジンの仕様に関する知見は持っていない。すでにデファクトとなっているエンジンやゲームの仕様を参考にし、仕様ぎめの労力をなくした
- ノベルゲームにありがちな、音楽/立ち絵/エフェクトといった機能は搭載しない。単純にそれらのメディアを作るリソースがない
- ただで配布するものなので、コストは極力かけない。作業者は自分しかいないので、テキストや背景の加工を極力自動でできるようにする
- 気軽に試せるように、ブラウザで実行できること
- 開発の勉強になること。読むことだけ考えれば、既存のノベルゲームエンジンに載せるのが一番はやい。しかしそれだと開発の勉強にならない。勉強の観点からいって、最低限の機能をもったライブラリを使うのが望ましい
- とりあえずたいした状態保持は必要ない。ローカルストレージやファイルで保持する

* 段階

- メモ化のためどうせ変数に入れるのだから、UI用の画像類はまとめて読み込んでいたほうがよい
- セーブ機能
  - タイトルとチャプター
- 既読機能
- 実績機能
- 自動文字送り機能
- 直前の文字表示機能
- リリース

* Tasks
** TODO シナリオを100個集める
:LOGBOOK:
CLOCK: [2025-01-18 Sat 09:55]--[2025-01-18 Sat 10:20] =>  0:25
CLOCK: [2025-01-12 Sun 09:23]--[2025-01-12 Sun 09:48] =>  0:25
CLOCK: [2024-12-14 Sat 16:38]--[2024-12-14 Sat 17:03] =>  0:25
CLOCK: [2024-12-14 Sat 11:20]--[2024-12-14 Sat 11:45] =>  0:25
CLOCK: [2024-12-14 Sat 10:40]--[2024-12-14 Sat 11:05] =>  0:25
:END:

地道に収集する。
** TODO UIをリファクタ
:LOGBOOK:
CLOCK: [2024-12-23 Mon 21:47]--[2024-12-23 Mon 22:12] =>  0:25
:END:
ボタンなどはそういう関数に、各自で指定してる色は変数にまとめる。
** TODO startラベルの先頭が常に実行される

#+begin_src
*start
[image source="black.png"]
『こころ』夏目漱石
#+end_src

ほかのラベルに飛んでも、黒画像の設定が実行される。もし文字を入れると、それが実行される。
** TODO シナリオジャンプごとに背景をリセットする
今は残り続ける。よくないことが多い。

チャプタージャンプ時にイベント通知すればよさそうか。
** TODO フェードアウト/イン
背景画像を変えるとき、パッと変わって見苦しい。場面転換のときは黒にフェードアウトするとかしたい。
** TODO 作品を読む
:LOGBOOK:
CLOCK: [2025-01-18 Sat 18:22]--[2025-01-18 Sat 18:47] =>  0:25
CLOCK: [2025-01-18 Sat 15:53]--[2025-01-18 Sat 16:18] =>  0:25
:END:

ひたすら読んで微調整する。
* Archives
** DONE セーブ機能
CLOSED: [2024-12-21 Sat 22:48]
:LOGBOOK:
CLOCK: [2024-12-21 Sat 22:11]--[2024-12-21 Sat 22:36] =>  0:25
CLOCK: [2024-12-21 Sat 21:15]--[2024-12-21 Sat 21:40] =>  0:25
CLOCK: [2024-12-21 Sat 20:50]--[2024-12-21 Sat 21:15] =>  0:25
CLOCK: [2024-12-21 Sat 20:24]--[2024-12-21 Sat 20:49] =>  0:25
CLOCK: [2024-12-21 Sat 19:36]--[2024-12-21 Sat 20:01] =>  0:25
CLOCK: [2024-12-21 Sat 19:00]--[2024-12-21 Sat 19:25] =>  0:25
CLOCK: [2024-12-21 Sat 18:31]--[2024-12-21 Sat 18:56] =>  0:25
CLOCK: [2024-12-21 Sat 18:05]--[2024-12-21 Sat 18:30] =>  0:25
CLOCK: [2024-12-21 Sat 17:40]--[2024-12-21 Sat 18:05] =>  0:25
CLOCK: [2024-12-21 Sat 14:46]--[2024-12-21 Sat 15:11] =>  0:25
CLOCK: [2024-12-21 Sat 12:11]--[2024-12-21 Sat 12:36] =>  0:25
CLOCK: [2024-12-21 Sat 11:26]--[2024-12-21 Sat 11:51] =>  0:25
CLOCK: [2024-12-21 Sat 10:56]--[2024-12-21 Sat 11:21] =>  0:25
CLOCK: [2024-12-21 Sat 10:31]--[2024-12-21 Sat 10:56] =>  0:25
CLOCK: [2024-12-21 Sat 09:42]--[2024-12-21 Sat 10:07] =>  0:25
:END:

セーブできるようにする。まずはオンメモリでやって、次に永続化・ロードできるようにする。

- シナリオに1つでいいだろう
- トップメニュー
  - こころ ch4 位置45
  - 明暗 ch5 位置23
- クリックすると、「読込」「削除」ができる
- ポーズ画面では保存ができる。スロットに保存ずみの情報が表示され、保存されたことが確認できる
- あとでファイル化しやすい形でないといけない
** DONE 収録冊数を表示する
CLOSED: [2024-12-25 Wed 21:46]
表示してわかるようにする。
** DONE 既読機能
CLOSED: [2025-01-17 Fri 23:06]

既読チェックを付けられるようにする。

* 関連
# 関連するエントリ。なぜ関連させたか理由を書く。意味のあるつながりを意識的につくる。
# この事実は自分のこのアイデアとどう整合するか。
# この現象はあの理論でどう説明できるか。
# ふたつのアイデアは互いに矛盾するか、互いを補っているか。
# いま聞いた内容は以前に聞いたことがなかったか。
# メモ y についてメモ x はどういう意味か。
なし。
