:properties:
:ID: 20241030T184511
:mtime:    20241104212739
:ctime:    20241101011859
:end:
#+title:      KDOC 256: DNSフィルタリングで断つ指針
#+date:       [2024-10-30 Wed 18:45]
#+filetags:   :essay:
#+identifier: 20241030T184511

* この文書のステータス
- 作成
  - [X] 2024-11-04 貴島
- レビュー
  - [X] 2024-11-07 貴島

* 概要

インターネット上のコンテンツ(ポルノ、ゲーム、ツイート…)はたやすく依存症を引き起こし、心身に有害をもたらす。ベーシックな療法はほかの依存症と同じく、「断つ」ことである。ほかの依存性のあるものと違って、インターネットコンテンツは無限にあり、少し指を運動するだけでアクセスできる。ハードルはとても低く、意志による克服はむずかしい。フィルタリングによって、有害コンテンツを完全に遮断する指針を示す。

* ポイント

断つポイントとしては2つある。

- すべての端末で遮断すること

  特定の端末だけ遮断、だとそこが抜け道となって破綻する。少しでも見てしまうと、抗うのは難しい。なのでPCやスマホ、持っているすべての端末で遮断する必要がある。

- 検索を防ぐこと

  URLで遮断するのは真っ先に行うべきことであるが、じゅうぶんではない。検索が抜け道となってしまう。代替のものを探し出し、破綻する。また、無限にあるURLを都度遮断設定してもきりがない。検索からも有害な内容を遮断できる必要がある。

* 方法

それぞれ、具体的にどうすればいいだろうか。

全端末での遮断、を行うためには各端末での遮断ではなくネットワーク側で遮断するとよい。ルータの機能や、DNSサーバによる遮断がある。

次に、検索を防ぐ。以下のようにして検索を防げる。

- セーフサーチを強制する
  - 強制モードではない場合、簡単にオフにできてしまう
  - DNSフィルタリングのアプリケーションに強制セーフサーチ機能があるものがある。例えば[[https://github.com/AdguardTeam/AdGuardHome][AdguardTeam/AdGuardHome]]
- 強化セーフサーチフィルタリングを設定する
  - Googleアカウントの設定から行える
  - 検索結果に含まれる有害コンテンツが排除される。テキストやサムネイルも非表示となる
- Chrome拡張で、キーワードで検索結果から排除する
  - セーフサーチだけではきわどいものは検索結果に出てしまうことがある
  - [[https://chromewebstore.google.com/detail/ublacklist/pncfbmialoiaghdehhbnbhkkgmjanfhe?hl=en][ublacklist]]を使うと、キーワードで非表示にできる

ということで、遮断の主たる役割を果たすのはDNSフィルタリングである。途中で名前を出したが、[[https://github.com/AdguardTeam/AdGuardHome][AdGuardHome]]が扱いやすい。家のルータに設定すれば、強力に遮断できる。

~docker compose~ で簡単に起動でき、設定を[[id:90c6b715-9324-46ce-a354-63d09403b066][Git]]管理できるのもよいところだ。設定は[[https://github.com/kijimaD/dotfiles/tree/main/adguard][dotfiles/adguard]]に上げた。

* 関連
- [[id:20240224T025714][KDOC 103: ゆるいインターネット断ちのやり方]]。以前の方法。甘かったため、じゅうぶんな効果がなかった
