:properties:
:ID: 20240226T192333
:end:
#+title:      KDOC 111: tarは Tape Archive の略
#+date:       [2024-02-26 Mon 19:23]
#+filetags:   :draft:essay:
#+identifier: 20240226T192333

# (denote-rename-file-using-front-matter (buffer-file-name) 0)
# (org-roam-tag-remove)
# (org-roam-tag-add)

# ====ポリシー。
# 1ファイル1アイデア。
# 1ファイルで内容を完結させる。
# 常にほかのエントリとリンクする。
# 自分の言葉を使う。
# 参考文献を残しておく。
# 自分の考えを加える。
# 構造を気にしない。
# エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
# アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
# エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
# 恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。

* この文書のステータス
- 作成
  - [X] 2024-02-26 貴島
- レビュー
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))

# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。
* 正式名称
Linuxコマンドのアーカイブ作成コマンド ~tar~ は、 Tape Archive の略[fn:1]である。つまりもともとは磁気テープ用のコマンドだった。出自がその時代で、頻度が少ないとはいえ今でも使われるツールなのは感動を感じる。

#+begin_quote
tarコマンドはTape ARchiveというその名の通り磁気テープの操作が念頭に置かれていた。fオプション[11]を省いた場合デフォルトで磁気テープデバイスを処理する。fオプションの指定によりファイルシステム上の任意の名前のファイルを処理できる。
#+end_quote

また、アーカイブ後のファイル種類をtarballということがあるが、これにもネタがある。

#+begin_quote
tarballという言葉の由来は「リーマスじいや（英語版）」の童話『タールの赤ん坊（英語版）』に由来し[12]、それに油塊（タールボール）を引っ掛けたジョーク的用語である。
#+end_quote

面白い。

* さまざまなtar
さまざまなtar方言があったという。それは複数のオプション形式に現れているように見える。

#+caption: tarのマニュアル
#+begin_src shell :results raw
  man tar | head -n 30
#+end_src

#+RESULTS:
#+begin_src
TAR(1)                          GNU TAR Manual                          TAR(1)

NAME
       tar - an archiving utility

SYNOPSIS
   Traditional usage
       tar {A|c|d|r|t|u|x}[GnSkUWOmpsMBiajJzZhPlRvwo] [ARG...]

   UNIX-style usage
       tar -A [OPTIONS] ARCHIVE ARCHIVE

       tar -c [-f ARCHIVE] [OPTIONS] [FILE...]

       tar -d [-f ARCHIVE] [OPTIONS] [FILE...]

       tar -t [-f ARCHIVE] [OPTIONS] [MEMBER...]

       tar -r [-f ARCHIVE] [OPTIONS] [FILE...]

       tar -u [-f ARCHIVE] [OPTIONS] [FILE...]

       tar -x [-f ARCHIVE] [OPTIONS] [MEMBER...]

   GNU-style usage
       tar {--catenate|--concatenate} [OPTIONS] ARCHIVE ARCHIVE

       tar --create [--file ARCHIVE] [OPTIONS] [FILE...]

       tar {--diff|--compare} [--file ARCHIVE] [OPTIONS] [FILE...]
#+end_src

- Traditional Usage
- Unix-style usage
- GNU-style usage

* まとめ
コンピュータまわりの言葉にはこういうネタが多くて面白い。

* 関連
- [[id:20240210T200104][KDOC 85: 元気に動くUnix on PDP-7を見て連綿と続く歴史を感じた]]。コンピュータの博物学つながり
* Footnotes
[fn:1] [[https://ja.wikipedia.org/wiki/Tar][tar - Wikipedia]]。
