:properties:
:ID: 20241109T134521
:mtime:    20241109152208
:ctime:    20241109134523
:end:
#+title:      KDOC 278: パイプの詰まりを再現する
#+date:       [2024-11-09 Sat 13:45]
#+filetags:   :draft:permanent:
#+identifier: 20241109T134521

# (denote-rename-file-using-front-matter (buffer-file-name) 0)
# (save-excursion (while (re-search-backward ":draft" nil t) (replace-match "")))
# (flush-lines "^\\#\s.+?")

# ====ポリシー。
# 1ファイル1アイデア。
# 1ファイルで内容を完結させる。
# 常にほかのエントリとリンクする。
# 自分の言葉を使う。
# 参考文献を残しておく。
# 文献メモの場合は、感想と混ぜないこと。1つのアイデアに反する
# ツェッテルカステンの議論に寄与するか。それで本を書けと言われて書けるか
# 頭のなかやツェッテルカステンにある問いとどのようにかかわっているか
# エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
# アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
# エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
# 恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。
# 個人の感想・意思表明ではない。事実や書籍情報に基づいている

# ====永久保存メモのルール。
# 自分の言葉で書く。
# 後から読み返して理解できる。
# 他のメモと関連付ける。
# ひとつのメモにひとつのことだけを書く。
# メモの内容は1枚で完結させる。
# 論文の中に組み込み、公表できるレベルである。

# ====水準を満たす価値があるか。
# その情報がどういった文脈で使えるか。
# どの程度重要な情報か。
# そのページのどこが本当に必要な部分なのか。
# 公表できるレベルの洞察を得られるか

# ====フロー。
# 1. 「走り書きメモ」「文献メモ」を書く
# 2. 1日1回既存のメモを見て、自分自身の研究、思考、興味にどのように関係してくるかを見る
# 3. 追加すべきものだけ追加する

* この文書のステータス
:LOGBOOK:
CLOCK: [2024-11-09 Sat 14:48]--[2024-11-09 Sat 15:13] =>  0:25
CLOCK: [2024-11-09 Sat 14:10]--[2024-11-09 Sat 14:35] =>  0:25
:END:
- 作成
  - [X] 2024-11-09 貴島
- レビュー
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))

# チェックリスト ================
# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。
* 再現する
# 本文(見出しも設定する)

パイプにはバッファサイズがあり、いっぱいになると処理をブロックする。これを確かめる。

#+caption: 10000バイトずつ転送する
#+begin_src shell
yes | pv -L 10000 | cat /dev/random > /dev/null
#+end_src

#+caption: 実行結果。7秒からは書き込み速度が0になっている
#+begin_src
9.77KiB 0:00:01 [9.02KiB/s]
19.5KiB 0:00:02 [9.84KiB/s]
29.3KiB 0:00:03 [9.84KiB/s]
39.1KiB 0:00:04 [9.84KiB/s]
48.8KiB 0:00:05 [9.84KiB/s]
56.6KiB 0:00:06 [7.87KiB/s]
56.6KiB 0:00:07 [0.00 B/s] # 👈 速度0
56.6KiB 0:00:08 [0.00 B/s]
56.6KiB 0:00:09 [0.00 B/s]
56.6KiB 0:00:10 [0.00 B/s]
#+end_src

また、straceをyesプロセスに使うとパイプのバッファに空きができ次第、書き込んでいる様子が確認できる。

#+caption: yesにstraceを仕込んでどのように動いているかを見る
#+begin_src shell
strace yes | pv -L 10000 | cat /dev/random > /dev/null
#+end_src

- yesプロセスとつながっているパイプは最初に一瞬でいっぱいになる。yesの書き込み速度は非常に早い
- pvが動き出してyesプロセスとつながっているパイプのバッファを読み出し空きができると、都度yesプロセスが実行開始、またパイプに追加される
- catコマンド側のパイプがいっぱいになると、pvもバッファを書き込めなくなるため停止する。結果、yesプロセスとpvプロセスがどちらもつながっているパイプの空き待ちのSleepになる

#+begin_src
write(1, "y\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\n"..., 8192) = 8192
(略...)
write(1, "y\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\n"..., 8192) = 8192
write(1, "y\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\n"..., 8192) = 8192
# 👆 pvが開始する前に、yesコマンドがyes側のパイプに大量に書き込みいっぱいになっている
write(1, "y\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\n"..., 8192
9.77KiB 0:00:01 [8.99KiB/s]
write(1, "y\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\n"..., 8192
19.5KiB 0:00:02 [9.84KiB/s]
write(1, "y\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\n"..., 8192
29.3KiB 0:00:03 [9.84KiB/s]
write(1, "y\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\n"..., 8192
39.1KiB 0:00:04 [9.84KiB/s]
write(1, "y\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\n"..., 8192) = 8192
write(1, "y\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\n"..., 8192
48.8KiB 0:00:05 [9.84KiB/s]
write(1, "y\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\n"..., 8192
56.6KiB 0:00:06 [7.87KiB/s]  56.6KiB 0:00:10 [0.00 B/s] # 👈 速度0
#+end_src

file:./images/20241109-pipe.drawio.svg

* メモ

- strace は発行システムコールを表示するコマンド
- pv はパイプのデータの流れを確認するコマンド。-Lで書き込み速度を制限できる。pvを使って制限しないと一瞬で終わってしまうため観察できない
- cat /dev/random > /dev/null は何もせず待ち受けるためのコマンド。要件:
  - 実行し続ける
  - パイプのバッファを消費しない
  - パイプを閉じない
  - 出力を一切しない

* 関連
# 関連するエントリ。なぜ関連させたか理由を書く。意味のあるつながりを意識的につくる。
# この事実は自分のこのアイデアとどう整合するか。
# この現象はあの理論でどう説明できるか。
# ふたつのアイデアは互いに矛盾するか、互いを補っているか。
# いま聞いた内容は以前に聞いたことがなかったか。
# メモ y についてメモ x はどういう意味か。
- [[id:20240225T174224][KDOC 109: 発行システムコールを調べる]]。straceで詳細に調べる方法
- [[id:20241017T190613][KDOC 254: ジョブプロセスがSleepしていた理由]]。調べたきっかけとなる事象
