:properties:
:ID: 20240219T225359
:end:
#+title:      KDOC 100: 細かいことを気にせず進める
#+date:       [2024-02-19 Mon 22:53]
#+filetags:   :draft:essay:
#+identifier: 20240219T225359

# (denote-rename-file-using-front-matter (buffer-file-name) 0)
# (org-roam-tag-remove)
# (org-roam-tag-add)

# ====ポリシー。
# 1ファイル1アイデア。
# 1ファイルで内容を完結させる。
# 常にほかのエントリとリンクする。
# 自分の言葉を使う。
# 参考文献を残しておく。
# 自分の考えを加える。
# 構造を気にしない。
# エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
# アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
# エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
# 恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。

* この文書のステータス
- 作成
  - [X] 2024-02-19 貴島
- レビュー
  - [ ] 2024-mm-dd <署名> (progn (kill-line 0) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))
# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。(org-roam-tag-remove)。
# すべてのコメントを削除した。
* 概要
細かいことを気にせず前へ進めることが、ものごとを続けるコツなのでは、と考えた。

以前[[id:20230301T234645][KDOC 21: 仕事のように集中する]]で、仕事は他者への責任意識や時間の制約があるから集中でき、プライベートではそれがないからなかなか進まないのではないか、と考えた。しかし最近思ったのは、無理やり進まされるのが良いのでは、ということだ。仕事ではどうしても解決できない問題があったとき、妥協して醜い解決法をとったりする。そうして強制的に進められる。しばらくしたあとにパッと解決できたりできなかったりする。常に何かしら進んでいて、新しい問題に取り組んでいる。完全に止まることはない。もし、仕事でうまくいかない1つの問題へ永遠に取り組まされたら、すぐ参ってしまうだろう。

一方でプライベートではどうだろう。何か1つ壁に突き当たったら、それで嫌になって途中でやめてしまう率が高い。完璧主義な傾向が強くなるようだ[fn:1]。

だから、とりあえず前に進めてあとから直そう、自分へ言い聞かせることにした。悪魔の囁きなときもあるが、何も進まないよりはマシだ。自信を持って未来の自分に託そう。途中でやめてしまうのが一番の損失だ。

* 関連
- [[id:20230301T234645][KDOC 21: 仕事のように集中する]]。ここでの意見を修正した

* Footnotes
[fn:1] 完全主義とはほど遠い生活を送っているにも関わらず。
