:properties:
:ID: 20240203T235748
:end:
#+title:      KDOC 70: 聖地巡礼したくなる要素
#+date:       [2024-02-03 Sat 23:57]
#+filetags:   :draft:essay:
#+identifier: 20240203T235748

* この文書のステータス
:LOGBOOK:
CLOCK: [2024-02-04 Sun 14:31]--[2024-02-04 Sun 14:56] =>  0:25
CLOCK: [2024-02-04 Sun 13:50]--[2024-02-04 Sun 14:15] =>  0:25
:END:
- 作成
  - [ ] <日付> <署名>
- レビュー
  - [ ] <日付> <署名>
# - 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)
# - 文脈なく読めるのを確認した
# - おばあちゃんに説明できる
# - いらない見出しを削除した
* 概要
アニメ『花咲くいろは』を見て、観光における物語について考えたことを書く。
* イントロ
『花咲くいろは』は東京育ちの女子高生が、金沢の旅館で仲居として働く話。旅館で働くことが物語のテーマになっている。美しい自然や町並み、伝統的な祭りが詳細に描写され、モデルとなる場所がたしかに存在することを確信できる。

このアニメは2011年公開で、だいぶ前と言えるのだが、古さを感じない。古いとわかるのはガラケーやメールの描写くらいだ。タイトルすら全然知らなかったので最近の作品なのかと考えていた。10年以上経った今でも現地の観光プロモーションに使われているという。実際行きたくなったから、プロモーションとしてとてつもない成功例に見える。

自分も舞台となった場所[fn:1]に対して非常に興味をかきたてられた。それはどこの観光地でもゴールとしていることに見えるが、なぜうまくいっているのか、について考える。
* なぜ行きたくなるのか
人は体験した時間の量によって、単純接触効果でその場所に親しみをもつようだ。地方から上京したとき最初住んだ沿線にその後も住む、ようなことはよくある話だが、それと似たような感じ[fn:2]。アニメの12時間分はその場所にいるようなものだから、親しみを持ちやすいだろう。

しかし、それだけではない。

次郎丸が海に飛び込んだ大岩、神社のある高台から見下ろす夕方風景、トコトコ走る1両の汽車(みんなちゃんと汽車と言っている)、学校前の看板がある道、あたりは印象的だ。単に美しいというだけでなく、印象的なシーンの風景であったり、舞台装置としての風景なのがポイントに見える。

アニメでそれらの背景にデフォルメが効いていたり、情報が取捨されているよい影響を与えている可能性も高い。実写だったらそこまで背景に意識を向けなかった可能性があるし、実写は詳細すぎる。田舎風景フィルターで、ありがちなものと見るような感じがする。何より実際に見るのと映像で違うので、行く意味がある。実写だと見に行っても代わり映えしない。

観光に限った話ではないが、全く知らなかったものに興味をもたせ、まして何百キロも旅をさせるのはとても難しい。しかしこうした成功例からなにか得られるものがあるのではないか、と考えた。
* Footnotes
[fn:1] 金沢市、湯涌温泉。
[fn:2] ただ完全にかけた時間の量かと言われるとそうでもない。何も物語を感じなければ、退屈さを感じる。ひどい場所のように感じる。多くの人が地元に退屈さを感じて東京に憧れるのは、そこに行けばなにか物語があると考えるから、に見える。テレビを見ているとフィクション・ノンフィクション問わず、ほとんどの話題は東京や関東についてである。上京してしまえば平凡で退屈な生活が待っているのだが、仕事とか経済の都合で東京を離れられなくなってそのまま居座ることになる。最初に感情的な親しみがあって、経済合理性とか利便性はその次にある。実際に住んでみないことには判断のしようがないのだから。すべての広告やプロモーションのゴールは、感情的な親しみを作り1度でも使ってもらうことだ。
