:properties:
:ID: 20240317T101828
:end:
#+title:      KDOC 125: /procのマニュアルを調べる
#+date:       [2024-03-17 Sun 10:18]
#+filetags:   :draft:code:
#+identifier: 20240317T101828

# (denote-rename-file-using-front-matter (buffer-file-name) 0)
# (org-roam-tag-remove)
# (org-roam-tag-add)

# ====ポリシー。
# 1ファイル1アイデア。
# 1ファイルで内容を完結させる。
# 常にほかのエントリとリンクする。
# 自分の言葉を使う。
# 参考文献を残しておく。
# 自分の考えを加える。
# 構造を気にしない。
# エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
# アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
# エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
# 恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。

* この文書のステータス
- 作成
  - [X] 2024-03-17 貴島
- レビュー
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))

# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。
* 概要
# 文書の短いまとめ。
[[id:7a81eb7c-8e2b-400a-b01a-8fa597ea527a][Linux]]などUnixライクなOSで使うディレクトリに ~/proc~ がある。CPU情報を見るときに呪文のように使ってきた。

#+caption: CPU情報を見る
#+begin_src shell :results raw
  cat /proc/cpuinfo | head
#+end_src

#+RESULTS:
#+begin_src
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 154
model name	: 12th Gen Intel(R) Core(TM) i7-1260P
stepping	: 3
microcode	: 0x429
cpu MHz		: 2500.000
cache size	: 18432 KB
physical id	: 0
#+end_src

これもOSの機能の1つであり、 ~procfs~ という。システム情報をファイルにマウントする機能。

#+caption: 調べる
#+begin_src shell :results raw
  man procfs | head -n 16
#+end_src

#+RESULTS:
#+begin_src
PROC(5)                    Linux Programmer's Manual                   PROC(5)

NAME
       proc - process information pseudo-filesystem

DESCRIPTION
       The  proc filesystem is a pseudo-filesystem which provides an interface
       to kernel data structures.  It is commonly  mounted  at  /proc.   Typi‐
       cally,  it  is  mounted automatically by the system, but it can also be
       mounted manually using a command such as:

           mount -t proc proc /proc

       Most of the files in the proc filesystem are read-only, but some  files
       are writable, allowing kernel variables to be changed.

#+end_src

psとかpgrepは、 ~/proc~ 下を情報源として検索し表示している。↓生のファイルを見てみると、 ~(cat)~ があり、これがプロセス名である。

#+caption: catプロセス自身の情報を見る
#+begin_src shell
cat /proc/self/stat
#+end_src

#+RESULTS:
#+begin_src
3394640 (cat) R 3394639 3394639 3394639 0 -1 4194304 95 0 0 0 0 0 0 0 20 0 1 0 159192456 9785344 249 18446744073709551615 94264123768832 94264123784246 140728130572832 0 0 0 0 0 0 0 0 0 17 4 0 0 0 0 0 94264123796192 94264123797608 94264147423232 140728130580548 140728130580568 140728130580568 140728130584555 0
#+end_src

* 関連
- [[id:20240314T212016][KDOC 122: Linuxカーネル知識の全体像を把握する]]。ちゃんとドキュメントと関連させていく
