:properties:
:ID: 20240605T205919
:end:
#+title:      KDOC 185: コンテナの中身をホストマシンにダンプする
#+date:       [2024-06-05 Wed 20:59]
#+filetags:   :draft:code:
#+identifier: 20240605T205919

# (denote-rename-file-using-front-matter (buffer-file-name) 0)
# (save-excursion (while (re-search-backward ":draft" nil t) (replace-match "")))
# (flush-lines "^\\#\s.+?")

# ====ポリシー。
# 1ファイル1アイデア。
# 1ファイルで内容を完結させる。
# 常にほかのエントリとリンクする。
# 自分の言葉を使う。
# 参考文献を残しておく。
# 文献メモの場合は、感想と混ぜないこと。1つのアイデアに反する
# ツェッテルカステンの議論に寄与するか
# 頭のなかやツェッテルカステンにある問いとどのようにかかわっているか
# エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
# アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
# エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
# 恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。

# ====永久保存メモのルール。
# 自分の言葉で書く。
# 後から読み返して理解できる。
# 他のメモと関連付ける。
# ひとつのメモにひとつのことだけを書く。
# メモの内容は1枚で完結させる。
# 論文の中に組み込み、公表できるレベルである。

# ====価値があるか。
# その情報がどういった文脈で使えるか。
# どの程度重要な情報か。
# そのページのどこが本当に必要な部分なのか。

* この文書のステータス
- 作成
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))
- レビュー
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))

# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。
* 概要
コンテナのルートファイルシステムを、ホストマシンのファイルシステムにダンプして中身を観察する。

#+begin_src shell :results raw
  mkdir -p bundle/rootfs
  docker pull centos:8
  docker run --rm --name tmp -d centos:8 sleep
  docker export tmp | tar -xC bundle/rootfs
  ls -al bundle/rootfs/
#+end_src

#+RESULTS:
#+begin_src
total 116
drwxrwxr-x 17 orange orange  4096 Jun  5 21:01 .
drwxrwxr-x  3 orange orange  4096 Jun  5 21:01 ..
lrwxrwxrwx  1 orange orange     7 Nov  4  2020 bin -> usr/bin
drwxr-xr-x  4 orange orange  4096 Jun  5 20:55 dev
-rwxr-xr-x  1 orange orange     0 Jun  5 20:55 .dockerenv
drwxr-xr-x 55 orange orange 24576 Jun  5 20:55 etc
drwxr-xr-x  2 orange orange  4096 Nov  4  2020 home
lrwxrwxrwx  1 orange orange     7 Nov  4  2020 lib -> usr/lib
lrwxrwxrwx  1 orange orange     9 Nov  4  2020 lib64 -> usr/lib64
drwx------  2 orange orange  4096 Sep 15  2021 lost+found
drwxr-xr-x  2 orange orange  4096 Nov  4  2020 media
drwxr-xr-x  2 orange orange  4096 Nov  4  2020 mnt
drwxr-xr-x  2 orange orange  4096 Nov  4  2020 opt
drwxr-xr-x  2 orange orange  4096 Sep 15  2021 proc
dr-xr-x---  2 orange orange  4096 Sep 15  2021 root
drwxr-xr-x 11 orange orange  4096 Sep 15  2021 run
lrwxrwxrwx  1 orange orange     8 Nov  4  2020 sbin -> usr/sbin
drwxr-xr-x  2 orange orange  4096 Nov  4  2020 srv
drwxr-xr-x  2 orange orange  4096 Sep 15  2021 sys
drwxrwxr-x  7 orange orange  4096 Sep 15  2021 tmp
drwxr-xr-x 12 orange orange  4096 Sep 15  2021 usr
drwxr-xr-x 20 orange orange  4096 Sep 15  2021 var
#+end_src

#+caption: 後片付け
#+begin_src shell
  docker stop tmp
#+end_src

* 関連
# 関連するエントリ。なぜ関連させたか理由を書く。意味のあるつながりを意識的につくる。
# この事実は自分のこのアイデアとどう整合するか。
# この現象はあの理論でどう説明できるか。
# ふたつのアイデアは互いに矛盾するか、互いを補っているか。
# いま聞いた内容は以前に聞いたことがなかったか。
# メモ y についてメモ x はどういう意味か。
- [[id:20240605T103458][KDOC 184: 『イラストでわかるDockerとKubernetes』]]で紹介されていた方法
