:properties:
:ID: 20240209T111023
:end:
#+title:      KDOC 83: CORSを確認する方法
#+date:       [2024-02-09 Fri 11:10]
#+filetags:   :draft:code:
#+identifier: 20240209T111023

# (denote-rename-file-using-front-matter (buffer-file-name) 0)

# ====ポリシー。
# 1ファイル1アイデア。
# 1ファイルで内容を完結させる。
# 常にほかのエントリとリンクする。
# 自分の言葉を使う。
# 参考文献を残しておく。
# 自分の考えを加える。
# 構造を気にしない。
# エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
# アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
# エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
# 恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。

* この文書のステータス
- 作成
  - [X] 2024-02-10 貴島
- レビュー
  - [ ] 2024-mm-dd <署名> (progn (kill-line 0) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。
* 概要
CORSを理解しにくかったりミスをしがちな原因は、動作確認のやり方が一見わかりにくいからに見える。[[id:b11fb9a4-0a26-4354-bc60-6c755c256b21][curl]]によるシンプルな動作確認方法を知っていれば、試行錯誤してすぐに理解できる。

* コマンド
サーバが設定してないとき(リソースを許可しない)、Access-Control-Allow-*がない。

#+caption: 設定できてない場合
#+begin_src shell :results raw
  curl -I -H "Origin: nandemoii.com" -H "Access-Control-Request-Method: GET" -X OPTIONS --verbose http://localhost
#+end_src

#+RESULTS:
#+begin_src
HTTP/1.1 200 OK
Date: Fri, 09 Feb 2024 02:21:43 GMT
Server: Apache
Allow: GET,HEAD,POST,OPTIONS,TRACE
Cache-Control: max-age=1
Expires: Fri, 09 Feb 2024 02:21:44 GMT
Content-Length: 0
Content-Type: httpd/unix-directory

#+end_src

設定できているとAccess-Control-Allow-*がある。

#+caption: 設定できている場合(全許可)
#+begin_src shell :results raw
  curl -I -H "Origin: nandemoii.com" -H "Access-Control-Request-Method: GET" -X OPTIONS --verbose http://localhost
#+end_src

#+RESULTS:
#+begin_src
HTTP/1.1 200 OK
Date: Fri, 09 Feb 2024 02:23:22 GMT
Server: Apache
Allow: GET,HEAD,POST,OPTIONS,TRACE
Cache-Control: max-age=1
Expires: Fri, 09 Feb 2024 02:23:23 GMT
Access-Control-Allow-Headers: Content-Type 👈
Access-Control-Allow-Origin: * 👈
Content-Length: 0
Content-Type: httpd/unix-directory

#+end_src

* 関連
- [[id:20240208T215527][KDOC 81: iframeの制約]]。でCORSのことを調べたのがきっかけ
- [[id:20240207T092747][KDOC 77: 検証する方法があると理解が進む]]。このパターン
