:properties:
:ID: 20251220T140427
:end:
#+title:      KDOC 511: 半蔵門ミュージアムを観察する
#+date:       [2025-12-20 Sat 14:04]
#+filetags:   :draft:essay:
#+identifier: 20251220T140427

#+begin_comment
(kd/denote-kdoc-rename)
(kd/denote-format)

====ポリシー。
1ファイル1アイデア。
1ファイルで内容を完結させる。
常にほかのエントリとリンクする。
自分の言葉を使う。
参考文献を残しておく。
文献メモの場合は、感想と混ぜないこと。1つのアイデアに反する
ツェッテルカステンの議論に寄与するか。それで本を書けと言われて書けるか
頭のなかやツェッテルカステンにある問いとどのようにかかわっているか
エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。
個人の感想・意思表明ではない。事実や書籍情報に基づいている

====永久保存メモのルール。
自分の言葉で書く。
後から読み返して理解できる。
他のメモと関連付ける。
ひとつのメモにひとつのことだけを書く。
メモの内容は1枚で完結させる。
論文の中に組み込み、公表できるレベルである。

====水準を満たす価値があるか。
その情報がどういった文脈で使えるか。
どの程度重要な情報か。
そのページのどこが本当に必要な部分なのか。
公表できるレベルの洞察を得られるか

====フロー。
1. 「走り書きメモ」「文献メモ」を書く
2. 1日1回既存のメモを見て、自分自身の研究、思考、興味にどのように関係してくるかを見る
3. 追加すべきものだけ追加する

#+end_comment

* この文書のステータス
- 作成
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))
- レビュー
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))

# チェックリスト ================
# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。
* 概要
# 本文(見出しも設定する)

半蔵門ミュージアムは、東京都千代田区にある歴史的な仏教美術品を展示する博物館である。

#+begin_export html
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d125215.87139745476!2d139.66005903906253!3d35.656440154172365!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x60188c6556d00001%3A0xcd6709c1ea4ad3e1!2sHanzomon%20Museum!5e1!3m2!1sen!2sjp!4v1766207040753!5m2!1sen!2sjp" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
#+end_export
* メモ

- 全体的に広々していて、豪勢なつくりになっている。特に地下は天井の高さが3フロアぶんくらいあって地下と感じないほど広々としている。間接照明で砂岩ふうの壁が照らされている。非常に静かで、厳かな雰囲気がする
- 面積の割に従業員が多い。受付に2人、エレベーターに1人、売店に2人、館内をスーツで巡回する人が数人いる。半蔵門という超絶スポットにある。それにも関わらず、入館料は無料である。明らかに公立の博物館よりコストがかかっているが、成り立っているのを不思議に感じた。宗教のバックグラウンドによるトリックがあるのだろうか
- 紀元付近につくられたというインドの本物の石彫刻は、ケースにも入っていなくて、間近に観察できる。キラキラしたものを含む岩石に掘られている。ケースの有無は全然違う。服装や顔の感じはギリシャふうの雰囲気である

* 感想

- 新興宗教を興す教祖になったつもりで見た。宗教グッズやストーリーにどういう「効果」があるかという観点で見る
- 昔の人も現代人と変わらない認識で、当時の人になりきって想像する
- 仏像は現代のフィギュアやアイドル文化みたいなもの。寺はテーマパークである
- まず仔細に実物を観察、考察して、それから解説を読んで楽しんだ。地下の解説は知らない登場人物が多すぎてわからなかったが、2階に易しい解説があった。わかりやすい
- 平安時代の造物が(過去数度の補修があったとしても)残っているのがすごいと感じる
- 仏教はグッズが多い感じがする。精巧で美しい、さまざまなタイプの仏像がある。恐ろしいもの、落ち着いたもの。こんな感じで等身大フィギュアに特色があれば、寺に行きたくなるのもわかる気がする
- 神社にはあまりないように見える。お守りとか販売用の小物はあるが、神社によってわかりやすく違う造作はないように見える
- 仏教は、壮大な原作とメディアミックス、同人誌の文化と解釈できるのではないか
- 彫刻のなかには、粘土ならギリできそうなくらいの出来のものもあった。単品で成立するわけでなく石塔についていたレリーフのようであった。このクオリティがあることに少し安心した。歴史的逸品はあまりにうますぎて人がつくったものであることが信じられない
- 今大人になって、時間をつくるのは大変であるが、当時の人たちも石の彫刻をほる時間をとるのは大変だっただろう。ヘタウマなところも含めて趣味の熱意を感じる

* 関連
# 関連するエントリ。書いているファイルから見て、なぜ関連させたか書く。意味のあるつながりを意識的につくる。
# [引用、整合性、どう説明できるか、矛盾、補っているか、以前聞いたこと、対立、修正、補足、付け加え、組み合わせ、疑問]
# また、現在はリンクが見つからなくてもこういった切り口で将来関連させられそうな項目を書いておく
# [類推、未解決、具体例、追加調査、理由、動機、検証]
# 横に類推するか、上に抽象化するか、下に具体化するか

- 類推: [[id:20241027T201315][KDOC 255: 『完全教祖マニュアル』]]。教祖としての宗教を解説する
