:properties:
:ID: 20251014T082131
:end:
#+title:      KDOC 473: 『Excelでできる不動産投資「収益計算」のすべて』
#+date:       [2025-10-14 Tue 08:21]
#+filetags:   :draft:book:
#+identifier: 20251014T082131

#+begin_comment
(kd/denote-kdoc-rename)
(kd/denote-format)

====ポリシー。
1ファイル1アイデア。
1ファイルで内容を完結させる。
常にほかのエントリとリンクする。
自分の言葉を使う。
参考文献を残しておく。
文献メモの場合は、感想と混ぜないこと。1つのアイデアに反する
ツェッテルカステンの議論に寄与するか。それで本を書けと言われて書けるか
頭のなかやツェッテルカステンにある問いとどのようにかかわっているか
エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。
個人の感想・意思表明ではない。事実や書籍情報に基づいている

====永久保存メモのルール。
自分の言葉で書く。
後から読み返して理解できる。
他のメモと関連付ける。
ひとつのメモにひとつのことだけを書く。
メモの内容は1枚で完結させる。
論文の中に組み込み、公表できるレベルである。

====水準を満たす価値があるか。
その情報がどういった文脈で使えるか。
どの程度重要な情報か。
そのページのどこが本当に必要な部分なのか。
公表できるレベルの洞察を得られるか

====フロー。
1. 「走り書きメモ」「文献メモ」を書く
2. 1日1回既存のメモを見て、自分自身の研究、思考、興味にどのように関係してくるかを見る
3. 追加すべきものだけ追加する

#+end_comment

* この文書のステータス
- 作成
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))
- レビュー
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))

# チェックリスト ================
# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。
* 概要
# 本文(見出しも設定する)
* メモ

- 金利の支払いは税務上の経費になるが、元本の返済は経費にならない。したがって税務上の経費が減るので税金の支払いが増えCFを圧迫する。純資産は順調に増えている(位置173)
- 賃料から得られるCFばかりにとらわれず、いかに純資産を増加させるかに着目するのが重要(位置183)
- 不動産投資における最大の経費は税金である。投資家が税金について熟知すべき理由は、税金を支払っても利益が出るか検証するためである。不動産業者や税理士に試算を依頼しても概算しか出てこない(位置225)
- 物件価格に変動がない場合の1年間の正味利益簡便計算法(位置358)
  - 不動産投資の1年間の賞味利益 = 賃貸NOI - 金利支払い - 税金支払い
  - 物件を保有することにより得られる正味利益(純資産の増加額)は、毎年の賃貸NOIの積み上げであり、物件を保有するために必要なコストは借り入れ金利と税金である
- 不動産投資における減価償却とは、今年の税金が安くなり、その分売却時の税金が高くなるという性質を持つ、会計上の経費である。したがって、買ってから売るまでの全体で見れば、減価償却による損益は相殺され、その有無が賞味利益に与える影響はほとんどない(位置358)
- 正味利益の計算では、借入金利の支払いだけが経費となり、元金の返済は経費として考えない。正味利益のうち、一部はCFとして現金を得て、元金返済部分はそれと同額の土地持分を購入したと考えているためである。不動産をローンで買うことには、ローン返済を通じて土地を少しづつ自分のものにしていくという意味合いがある。銀行に借金を返せば、その分だけ土地持分が増えていくと考える(位置381)
- 土地は売れば換金できる。換金性のあるものはすべて現金同等と考え、土地持分の取得も同じく、純資産が増加したと理解する。今すぐ得られるキャッシュフローに、売却時に現金化される土地の持分増加という「含み益」を足し合わせた額が保有期間中の正味利益と考えるべき(位置381)
- 保有期間中の賞味利益 = 税引後賃料キャッシュフロー + (今期に増加した含み益 - 売却時に支払うべき税金)
  - 「含み益」は土地の持分という形で蓄積されていく。将来にわたって土地価格が下落しない場所を選ぶことが重要である(位置398)
- 解散価値(NAV): 「いま不動産を売却して、売却益に対する税金を支払って投資を終了させた場合、結局いくら残るのか」
- 金融市場では、換金価値のある資産はすべて現金換算してリアルタイムで評価するのが慣例である。所有権が法律によって保証されていてすぐに買い手が見つかるのなら、どのような資産も解散価値(純資産)をいつでも現金化できる、現金と等価の資産であることに変わりない。不動産投資において、キャッシュフローばかりに気をとられず、純資産の増加に注力すべきなのはそのため(位置438)
- キャッシュフローだけを見ると物件を売却したとき、借入金の返済が終わった翌月から急激に利益が増えるように見えるが、実際にはそうではない。NAVの増加額は毎年ほぼ一定である。それをどのような形で受け取るか、賃料キャッシュフローとしていま現金を受け取るか、土地持分を将来現金化するか、その違いだけ。十分な純資産があれば、現金を作ることは難しくない。純資産には担保価値と換金性があるから(位置438)
- 日本の都市部で行われている不動産投資の収益の源泉は、高い賃料収入(NOI)と低金利の借り入れの広いスプレッド(差額)である。売却時に高く売れればキャピタルゲインも得られるが、日本でキャピタルゲインありきの不動産投資を考えている人は少数派である(位置(p473)
- 諸外国では借入金利が高く、賃料収入と借入金利のスプレッドは非常に狭い。借入した場合持てば持つほど赤字が積み重なり、それを相殺できるだけの大きな売却益が得られなければ利益は出ない。したがって海外ではキャピタルゲインに期待する投資であり、日本とは状況が異なる。世界の投資家から日本の不動産が注目されているのは相対的に高い利回りと低い借入金利による広いスプレッドが得られ、かつ価格の上昇が期待できるからである(p474)
- 物件を購入したら売却までを見据えて保有期間中にすべきことは賃料の値上げである。賃料を値上げすれば収入が増えるという当たり前の効果があるが、それ以上に重要なのは売却価格の上昇に対する寄与が高いためである(位置557)
- 投資の上級者は、「すべての投資は、将来キャッシュフローの割引現在価値である」という表現をする。投資とはキャッシュフローを得て資金を増やすための活動である。会計上の「含み益」(未実現益)を知る必要はあるが、結局「いつの時点で、いくらの現金を受け取れる」という「実現益」こそが投資のすべてである。すべての投資は金融商品や事業において将来発生するであろうキャッシュフローを得るためにいまいくらまで払えるかを判断することにほかならない(位置603)
- 割引現在価値: 早期に得られるキャッシュフローには再投資する利回り分だけ余計に価値がある。最低でも年率3%の利回りが確約されている市場環境であれば、いま100もらうのと1年後に103もらうのは同じ価値といえる(位置619)

* 関連
# 関連するエントリ。なぜ関連させたか理由を書く。意味のあるつながりを意識的につくる。
# - この事実は自分のこのアイデアとどう整合するか。
# - この現象はあの理論でどう説明できるか。
# - ふたつのアイデアは互いに矛盾するか、互いを補っているか。
# - いま聞いた内容は以前に聞いたことがなかったか。
# - メモ y についてメモ x はどういう意味か。
# - 対立する
# - 修正する
# - 補足する
# - 付け加えるもの
# - アイデア同士を組み合わせて新しいものを生み出せないか
# - どんな疑問が浮かんだか
なし。
