:properties:
:ID: 20251208T083954
:end:
#+title:      KDOC 500: Covering Indexを試す
#+date:       [2025-12-08 Mon 08:39]
#+filetags:   :draft:permanent:
#+identifier: 20251208T083954

#+begin_comment
(kd/denote-kdoc-rename)
(kd/denote-format)

====ポリシー。
1ファイル1アイデア。
1ファイルで内容を完結させる。
常にほかのエントリとリンクする。
自分の言葉を使う。
参考文献を残しておく。
文献メモの場合は、感想と混ぜないこと。1つのアイデアに反する
ツェッテルカステンの議論に寄与するか。それで本を書けと言われて書けるか
頭のなかやツェッテルカステンにある問いとどのようにかかわっているか
エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。
個人の感想・意思表明ではない。事実や書籍情報に基づいている

====永久保存メモのルール。
自分の言葉で書く。
後から読み返して理解できる。
他のメモと関連付ける。
ひとつのメモにひとつのことだけを書く。
メモの内容は1枚で完結させる。
論文の中に組み込み、公表できるレベルである。

====水準を満たす価値があるか。
その情報がどういった文脈で使えるか。
どの程度重要な情報か。
そのページのどこが本当に必要な部分なのか。
公表できるレベルの洞察を得られるか

====フロー。
1. 「走り書きメモ」「文献メモ」を書く
2. 1日1回既存のメモを見て、自分自身の研究、思考、興味にどのように関係してくるかを見る
3. 追加すべきものだけ追加する

#+end_comment

* この文書のステータス
- 作成
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))
- レビュー
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))

# チェックリスト ================
# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。
* 概要
:PROPERTIES:
  :header-args+: :results table
  :header-args+: :database postgres
  :header-args+: :dbhost localhost
  :header-args+: :dbport 15432
  :header-args+: :dbuser postgres
  :header-args+: :engine postgresql
:END:

[[https://syu-m-5151.hatenablog.com/entry/2025/11/25/135220][「Postgres で試した？」と聞き返せるようになるまでもしくはなぜ私は雰囲気で技術を語るのか？]]で、Covering Indexという見慣れない単語を見た。調べて、試す。

インデックスにINCLUDEオプションをつけることで、内容についてもキャッシュを追加できる。

#+begin_quote
オプションのINCLUDE句は非キー列としてインデックスに含める列のリストを指定します。 非キー列をインデックススキャンの検索条件に使うことはできません。また、インデックスで何であれ一意性制約や排他制約を強制する目的に対しても無視されます。 しかしながら、インデックスオンリースキャンは、インデックスエントリから値を直接得ることができるので、インデックスのテーブルを見に行く必要なく、非キー列の内容を返すことができます。 このように非キー列の追加は、そうでないとできないインデックスオンリースキャンを利用可能にします。
[[https://www.postgresql.jp/docs/13/sql-createindex.html][CREATE INDEX]]
#+end_quote

#+begin_src sql
  CREATE TABLE users (
      tel integer,
      name1 varchar(255),
      name2 varchar(255)
  );
  CREATE INDEX idx_users_name1 ON users(name1) INCLUDE (tel);
  CREATE INDEX idx_users_name2 ON users(name2);

  -- include付き
  explain
  select tel from users where name1 = 'a';

  -- includeなし
  explain
  select tel from users where name2 = 'a';
#+end_src

#+RESULTS:
#+begin_src
|                                                                                  |
|----------------------------------------------------------------------------------|
| > CREATE TABLE users (                                                           |
| >     tel integer,                                                               |
| >     name1 varchar(255),                                                        |
| >     name2 varchar(255)                                                         |
| > );                                                                             |
| CREATE TABLE                                                                     |
|                                                                                  |
| > CREATE INDEX idx_users_name1 ON users(name1) INCLUDE (tel);                    |
| CREATE INDEX                                                                     |
|                                                                                  |
| > CREATE INDEX idx_users_name2 ON users(name2);                                  |
| CREATE INDEX                                                                     |
|                                                                                  |
| > explain                                                                        |
| > select tel from users where name1 = 'a';                                       |
| QUERY PLAN                                                                       |
| Index Only Scan using idx_users_name1 on users  (cost=0.14..8.16 rows=1 width=4) |
| Index Cond: (name1 = 'a'::text)                                                  |
|                                                                                  |
| > explain                                                                        |
| > select tel from users where name2 = 'a';                                       |
| QUERY PLAN                                                                       |
| Index Scan using idx_users_name2 on users  (cost=0.14..8.16 rows=1 width=4)      |
| Index Cond: ((name2)::text = 'a'::text)                                          |
#+end_src

* 関連
# 関連するエントリ。なぜ関連させたか理由を書く。意味のあるつながりを意識的につくる。
# - この事実は自分のこのアイデアとどう整合するか。
# - この現象はあの理論でどう説明できるか。
# - ふたつのアイデアは互いに矛盾するか、互いを補っているか。
# - いま聞いた内容は以前に聞いたことがなかったか。
# - メモ y についてメモ x はどういう意味か。
# - 対立する
# - 修正する
# - 補足する
# - 付け加えるもの
# - アイデア同士を組み合わせて新しいものを生み出せないか
# - どんな疑問が浮かんだか

- [[id:20251207T091742][KDOC 497: 複合インデックスの使用条件を試す]]。インデックスつながり
