:properties:
:ID: 20251218T232745
:end:
#+title:      KDOC 508: 除算の実行速度を計測する
#+date:       [2025-12-18 Thu 23:27]
#+filetags:   :draft:permanent:
#+identifier: 20251218T232745

#+begin_comment
(kd/denote-kdoc-rename)
(kd/denote-format)

====ポリシー。
1ファイル1アイデア。
1ファイルで内容を完結させる。
常にほかのエントリとリンクする。
自分の言葉を使う。
参考文献を残しておく。
文献メモの場合は、感想と混ぜないこと。1つのアイデアに反する
ツェッテルカステンの議論に寄与するか。それで本を書けと言われて書けるか
頭のなかやツェッテルカステンにある問いとどのようにかかわっているか
エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。
個人の感想・意思表明ではない。事実や書籍情報に基づいている

====永久保存メモのルール。
自分の言葉で書く。
後から読み返して理解できる。
他のメモと関連付ける。
ひとつのメモにひとつのことだけを書く。
メモの内容は1枚で完結させる。
論文の中に組み込み、公表できるレベルである。

====水準を満たす価値があるか。
その情報がどういった文脈で使えるか。
どの程度重要な情報か。
そのページのどこが本当に必要な部分なのか。
公表できるレベルの洞察を得られるか

====フロー。
1. 「走り書きメモ」「文献メモ」を書く
2. 1日1回既存のメモを見て、自分自身の研究、思考、興味にどのように関係してくるかを見る
3. 追加すべきものだけ追加する

#+end_comment

* この文書のステータス
- 作成
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))
- レビュー
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))

# チェックリスト ================
# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。
* 概要
# 本文(見出しも設定する)

除算というのは負荷の大きな演算であり、加算などの演算に比べると、実行に要する時間がはるかに長い(p51)。

アセンブリを見てみると、除算は命令数が多いのを確認できる。単純に ~DIV~ 命令だけではない。

#+begin_export html
<iframe width="800px" height="200px" src="https://godbolt.org/e#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:go,selection:(endColumn:17,endLineNumber:7,positionColumn:17,positionLineNumber:7,selectionStartColumn:17,selectionStartLineNumber:7,startColumn:17,startLineNumber:7),source:'//+Type+your+code+here,+or+load+an+example.%0A//+Your+function+name+should+start+with+a+capital+letter.%0Apackage+main%0A%0Afunc+main()+%7B%0A++++_+%3D+add(1,+2)%0A++++_+%3D+div(1,+2)%0A%7D%0A%0Afunc+add(a,+b+int)+int+%7B%0A++++return+a+%2B+b%0A%7D%0A%0Afunc+div(a,+b+int)+int%7B%0A+++return+a+/+b%0A%7D'),l:'5',n:'0',o:'Go+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:gltip,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1',verboseDemangling:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:go,libs:!(),options:'',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+gc+(tip)+(Editor+%231)',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4"></iframe>
#+end_export

じっさいに計測してみる。

#+caption: ベンチマーク
#+begin_src shell :results output
  go install golang.org/x/perf/cmd/benchstat@latest

  tmpdir=$(mktemp -d)
  cd $tmpdir

  cat > $tmpdir/bench_test.go <<EOF
    package main

    import "testing"

    func BenchmarkAdd(b *testing.B) {
    	for i := 0; i < b.N; i++ {
    		_ = add(42)
    	}
    }

    func BenchmarkDiv(b *testing.B) {
    	for i := 0; i < b.N; i++ {
    		_ = div(42)
    	}
    }

    //go:noinline
    func add(a int) int {
    	return a + a
    }

    //go:noinline
    func div(a int) int {
    	return a / a
    }
  EOF

  go mod init bench
  go mod tidy
  go test -bench=. -benchmem -count=10 > exec.log

  benchstat exec.log 2>&1

  rm -rf $tmpdir
#+end_src

#+RESULTS:
#+begin_src
goos: linux
goarch: amd64
pkg: bench
cpu: AMD Ryzen 9 9900X 12-Core Processor
        │   exec.log   │
        │    sec/op    │
Add-24    0.9069n ± 1% 👈
Div-24     1.262n ± 4% 👈
geomean    1.070n

        │   exec.log   │
        │     B/op     │
Add-24    0.000 ± 0%
Div-24    0.000 ± 0%
geomean              ¹
¹ summaries must be >0 to compute geomean

        │   exec.log   │
        │  allocs/op   │
Add-24    0.000 ± 0%
Div-24    0.000 ± 0%
geomean              ¹
¹ summaries must be >0 to compute geomean
#+end_src

たしかに、除算は加算より時間がかかるのを確認できた。

* 関連
# 関連するエントリ。書いているファイルから見て、なぜ関連させたか書く。意味のあるつながりを意識的につくる。
# [引用、整合性、どう説明できるか、矛盾、補っているか、以前聞いたこと、対立、修正、補足、付け加え、組み合わせ、疑問]
# また、現在はリンクが見つからなくてもこういった切り口で将来関連させられそうな項目を書いておく
# [類推、未解決、具体例、追加調査、理由、動機、検証]
# 横に類推するか、上に抽象化するか、下に具体化するか

- 参照: [[id:20240810T122445][KDOC 217: 『基礎からきっちり覚える 機械語入門』]]から
