:properties:
:ID: 20250211T230035
:mtime:    20250212004925
:ctime:    20250211230036
:end:
#+title:      KDOC 338: 英語学習に向いていて興味のあるコンテンツ
#+date:       [2025-02-11 Tue 23:00]
#+filetags:   :draft:essay:
#+identifier: 20250211T230035

# (denote-rename-file-using-front-matter (buffer-file-name) 0)
# (save-excursion (while (re-search-backward ":draft" nil t) (replace-match "")))
# (flush-lines "^\\#\s.+?")

# ====ポリシー。
# 1ファイル1アイデア。
# 1ファイルで内容を完結させる。
# 常にほかのエントリとリンクする。
# 自分の言葉を使う。
# 参考文献を残しておく。
# 文献メモの場合は、感想と混ぜないこと。1つのアイデアに反する
# ツェッテルカステンの議論に寄与するか。それで本を書けと言われて書けるか
# 頭のなかやツェッテルカステンにある問いとどのようにかかわっているか
# エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
# アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
# エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
# 恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。
# 個人の感想・意思表明ではない。事実や書籍情報に基づいている

# ====永久保存メモのルール。
# 自分の言葉で書く。
# 後から読み返して理解できる。
# 他のメモと関連付ける。
# ひとつのメモにひとつのことだけを書く。
# メモの内容は1枚で完結させる。
# 論文の中に組み込み、公表できるレベルである。

# ====水準を満たす価値があるか。
# その情報がどういった文脈で使えるか。
# どの程度重要な情報か。
# そのページのどこが本当に必要な部分なのか。
# 公表できるレベルの洞察を得られるか

# ====フロー。
# 1. 「走り書きメモ」「文献メモ」を書く
# 2. 1日1回既存のメモを見て、自分自身の研究、思考、興味にどのように関係してくるかを見る
# 3. 追加すべきものだけ追加する

* この文書のステータス
- 作成
  - [X] 2025-02-11 貴島
- レビュー
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))

# チェックリスト ================
# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。
* 概要
# 本文(見出しも設定する)
英語でYouTubeを見るのにハマっている。英語だとよりディープでわかりやすいコンテンツがあって面白い。映画などと違って短いので、全然わからなくなることが少ない(ただ字幕の質は落ちる)。英語学習に向いていると感じる。そのなかでも自分が興味を持っていて面白かったコンテンツを列挙する。

- 異常なスケールのDIYシリーズ
  - ヘリコプター作ってみたとか
- 建築/機械/交通...の解説動画
  - 興味がある。面白い
- コンピュータサイエンス系の解説動画
  - 概念の話になるので、なかなか難しいことも多い
- バーチャルアイドルの配信
  - 単純にかわいい声の女の子が楽しそうにしゃべっているのは楽しい
  - チャットでウケているのを見ると理解しなければ、となる
  - 入り組んだ話はしておらず入りやすい
  - 日本のバーチャルアイドル事務所の海外向けの配信者だと、たまに日本語が出ることも多く、親しみを持ちやすい。コメントを見る限り日本人もよく視聴しているようだ
- ゲーム実況
  - 特にやったことのあるゲームや日本が舞台だと、起こっている状況や文脈把握がしやすい
  - 刺激があり、眠くなりにくい
  - ゲームや配信者によってはあまり話さなくて勉強になりにくいものもある
- ゲーム解説
  - アクションというより、シミュレーションゲームなど戦略性があるものの解説に興味がある。面白い
- 使っているライブラリのチュートリアル・リリース紹介
  - denoteの作者はみずから動画で解説動画を出すことが多い

内容というよりは、配信者やチャンネルに親しみを持つことが重要に見える。内容というより何度も観て親しみのある人が言っているほうが頭に入ってきやすい。

動画以外には、サウンドノベルなどもいい可能性がある。ひぐらしとか日本産の名作の翻訳だと、背景や雰囲気を掴みやすいだろう。

#+begin_export html
<iframe width="560" height="315" src="https://www.youtube.com/embed/J7XG48IGsvY?si=vWyJy5vMsVP1qLot" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
#+end_export

#+begin_export html
<iframe width="560" height="315" src="https://www.youtube.com/embed/5Z85EF4_8ME?si=xfnsQCsYA42-ilyS" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
#+end_export

#+begin_export html
<iframe width="560" height="315" src="https://www.youtube.com/embed/78XKGNmBmHw?si=ErQzeJyT89XPzRHG" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
#+end_export

#+begin_export html
<iframe width="560" height="315" src="https://www.youtube.com/embed/psjExhXfvbI?si=fGZ4eZpJ5tt5CfBe" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
#+end_export

#+begin_export html
<iframe width="560" height="315" src="https://www.youtube.com/embed/82sVzqkv-9o?si=fZfVDfRL_RNuOKGk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
#+end_export

#+begin_export html
<iframe width="560" height="315" src="https://www.youtube.com/embed/zzXcav0yb50?si=wkqqgEovVoCKPsMF" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
#+end_export

* 関連
# 関連するエントリ。なぜ関連させたか理由を書く。意味のあるつながりを意識的につくる。
# この事実は自分のこのアイデアとどう整合するか。
# この現象はあの理論でどう説明できるか。
# ふたつのアイデアは互いに矛盾するか、互いを補っているか。
# いま聞いた内容は以前に聞いたことがなかったか。
# メモ y についてメモ x はどういう意味か。
- [[id:20250211T222421][KDOC 337: 多読は難しいことを認識しなければならない]]。多読が困難なので、よりスモールステップを考えることにした
