:properties:
:ID: 20251103T231224
:end:
#+title:      KDOC 483: 『ROCK IN!』のコンセプトについて話す(訳)
#+date:       [2025-11-03 Mon 23:12]
#+filetags:   :draft:wiki:
#+identifier: 20251103T231224

#+begin_comment
(kd/denote-kdoc-rename)
(kd/denote-format)

====ポリシー。
1ファイル1アイデア。
1ファイルで内容を完結させる。
常にほかのエントリとリンクする。
自分の言葉を使う。
参考文献を残しておく。
文献メモの場合は、感想と混ぜないこと。1つのアイデアに反する
ツェッテルカステンの議論に寄与するか。それで本を書けと言われて書けるか
頭のなかやツェッテルカステンにある問いとどのようにかかわっているか
エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。
個人の感想・意思表明ではない。事実や書籍情報に基づいている

====永久保存メモのルール。
自分の言葉で書く。
後から読み返して理解できる。
他のメモと関連付ける。
ひとつのメモにひとつのことだけを書く。
メモの内容は1枚で完結させる。
論文の中に組み込み、公表できるレベルである。

====水準を満たす価値があるか。
その情報がどういった文脈で使えるか。
どの程度重要な情報か。
そのページのどこが本当に必要な部分なのか。
公表できるレベルの洞察を得られるか

====フロー。
1. 「走り書きメモ」「文献メモ」を書く
2. 1日1回既存のメモを見て、自分自身の研究、思考、興味にどのように関係してくるかを見る
3. 追加すべきものだけ追加する

#+end_comment

* この文書のステータス
- 作成
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))
- レビュー
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))

# チェックリスト ================
# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。
* 概要
# 本文(見出しも設定する)

Vtuberの Koseki Bijou が語った内容の日本語訳を見て感動した。原文を見る。

#+begin_quote
Let's talk about the concept of the song. Let's start with the whole concept of the song.

曲のコンセプトについて話そうと思う。曲全体のコンセプトについて。

So I wanted the song to be very like me. So like half brain rot, half not so serious, half like you know not very silly but also has a lot of meaning in me in it and I think it has equal parts of both like you can on the surface level it's very catchy danceable but if you look in the lyrics and you look at it deeper, its very me in terms of the story and the meaning of the lyrics to it.

私みたいな曲にしたかった。つまり半分は脳が腐ったような感じで、半分は深刻じゃなくて、すごく愚かなわけじゃないけど、私自身の意味もたくさん込めている。両方が均等にある。表面的に見ればキャッチーで踊りやすいけど、歌詞に入り込んで深く見ると、ストーリーや歌詞の意味という点において、まさに私なんだ。

Yeah, there's lots of I think the lyrics are very smart and they're very very personal to me.

歌詞はとても賢いと思う。それはすごく個人的なものだ。

So thinking of this song and when I was asked what do I want? I said I wanted something that could hype up a crowd on stage.

この曲を思い返すと、どうしたいか聞かれたとき、私はなにかステージの人たちを湧かすような何かがほしい、って言った。

I said that Prism No Maho, you know, was very cutey Biboo and like you know, soft Biboo beginnings, but I wanted this one to be the Biboo that is Biboo right now.

The high energy meme lord total personality Biboo high high energy sort of thing. So that's what we were going for and it this is also song that was developed for the stage as well.

So like imagine like something like a concert or fest and Biboo going like "Biboo Biboo!". I wanted the song to be very like high energy and something that, you know, we would all have fun singing along with and dancing along with on stage.

So that was the initial concept. And obviously I wanted it to be video game themed.

Because it was specifically for my live, right? So, I was making this song along side my 3D live which both had to do with video games. So, there's a general like gaming theme around it.

But if you look into the lyrics deeper than that, it's not specifically really exactly about video games. It's more personally the stubborn, determined unable to give up nature of Biboo is kind of the deeper meaing of it.

It which is how I approach life in general and video games and mostly everything I do which is I don't start out necessarily being the best at something.

In games in life in Hololive in really anything I do I don't start out being the best. I start out as knowing nothing. I start out as a little baby not knowing what to do. Lost little baby Biboo.

And then I keep going and going and going until I get good. And I think that reflects me overall like in everything, not only video games. It's very reflective of how I play video games too.

Like Dark Souls and specifically, but other video games as well, is where, you know, I'll there's a hard boss and it's hard, but not going to grind and grind and grind and grind and grind until I get good and then finally reach my goal.

But again, it's in all aspects of my life. Like singing, I'm not I started off, you know, not the best sinnger. Even starting off in Hololive, you know, my singing wasn't that strong. But even now I'm grinding over and over and overand over again to get good.

You know sometimes what was it? Sometimes I think like, man, how did I get here in Holive? Because I feel like, you know, I'm not particularly the most skilled in general like dancing, singing, performing, content creation, streaming even. I just came in, you know, I like video games.

I like video games. I play a lot of video games and I play a lot of video games for a long time. So I'm like, how did I get here? But now that I think about it, I like that I came into Hololive not particularly skilled at everything.

Like I kind of like that I came into Hololive not a great singer. Didn't know how to dance, was very new, you know, trying to find my footing and everything because then you could see the start of my journey and then you guys could watch me grow alongside me. Yeah, sort of that. Soft of that idea.
#+end_quote

#+begin_export html
<iframe width="560" height="315" src="https://www.youtube.com/embed/qb51ZfcpDx0?si=VCYU0TjtKJVdxQ_e&amp;start=1607" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
#+end_export

* 関連
# 関連するエントリ。なぜ関連させたか理由を書く。意味のあるつながりを意識的につくる。
# - この事実は自分のこのアイデアとどう整合するか。
# - この現象はあの理論でどう説明できるか。
# - ふたつのアイデアは互いに矛盾するか、互いを補っているか。
# - いま聞いた内容は以前に聞いたことがなかったか。
# - メモ y についてメモ x はどういう意味か。
# - 対立する
# - 修正する
# - 補足する
# - 付け加えるもの
# - アイデア同士を組み合わせて新しいものを生み出せないか
# - どんな疑問が浮かんだか
なし。
