:properties:
:ID: 20251222T090340
:end:
#+title:      KDOC 517: DNS階層をたどる様子を見る
#+date:       [2025-12-22 Mon 09:03]
#+filetags:   :draft:permanent:
#+identifier: 20251222T090340

#+begin_comment
(kd/denote-kdoc-rename)
(kd/denote-format)

====ポリシー。
1ファイル1アイデア。
1ファイルで内容を完結させる。
常にほかのエントリとリンクする。
自分の言葉を使う。
参考文献を残しておく。
文献メモの場合は、感想と混ぜないこと。1つのアイデアに反する
ツェッテルカステンの議論に寄与するか。それで本を書けと言われて書けるか
頭のなかやツェッテルカステンにある問いとどのようにかかわっているか
エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。
個人の感想・意思表明ではない。事実や書籍情報に基づいている

====永久保存メモのルール。
自分の言葉で書く。
後から読み返して理解できる。
他のメモと関連付ける。
ひとつのメモにひとつのことだけを書く。
メモの内容は1枚で完結させる。
論文の中に組み込み、公表できるレベルである。

====水準を満たす価値があるか。
その情報がどういった文脈で使えるか。
どの程度重要な情報か。
そのページのどこが本当に必要な部分なのか。
公表できるレベルの洞察を得られるか

====フロー。
1. 「走り書きメモ」「文献メモ」を書く
2. 1日1回既存のメモを見て、自分自身の研究、思考、興味にどのように関係してくるかを見る
3. 追加すべきものだけ追加する

#+end_comment

* この文書のステータス
- 作成
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))
- レビュー
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))

# チェックリスト ================
# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。
* 概要
# 本文(見出しも設定する)

#+begin_src shell
  dig +trace www.github.com
#+end_src

#+RESULTS:
#+begin_src

; <<>> DiG 9.18.30-0ubuntu0.24.04.1-Ubuntu <<>> +trace www.github.com
;; global options: +cmd
.			6976	IN	NS	a.root-servers.net.
.			6976	IN	NS	l.root-servers.net.
.			6976	IN	NS	e.root-servers.net.
.			6976	IN	NS	m.root-servers.net.
.			6976	IN	NS	h.root-servers.net.
.			6976	IN	NS	i.root-servers.net.
.			6976	IN	NS	d.root-servers.net.
.			6976	IN	NS	k.root-servers.net.
.			6976	IN	NS	g.root-servers.net.
.			6976	IN	NS	b.root-servers.net.
.			6976	IN	NS	c.root-servers.net.
.			6976	IN	NS	f.root-servers.net.
.			6976	IN	NS	j.root-servers.net.
;; Received 239 bytes from 127.0.0.53#53(127.0.0.53) in 0 ms

;; UDP setup with 2001:dc3::35#53(2001:dc3::35) for www.github.com failed: network unreachable.
;; no servers could be reached
;; UDP setup with 2001:dc3::35#53(2001:dc3::35) for www.github.com failed: network unreachable.
;; no servers could be reached
;; UDP setup with 2001:dc3::35#53(2001:dc3::35) for www.github.com failed: network unreachable.
;; UDP setup with 2001:503:c27::2:30#53(2001:503:c27::2:30) for www.github.com failed: network unreachable.
com.			172800	IN	NS	l.gtld-servers.net.
com.			172800	IN	NS	c.gtld-servers.net.
com.			172800	IN	NS	k.gtld-servers.net.
com.			172800	IN	NS	m.gtld-servers.net.
com.			172800	IN	NS	i.gtld-servers.net.
com.			172800	IN	NS	b.gtld-servers.net.
com.			172800	IN	NS	h.gtld-servers.net.
com.			172800	IN	NS	e.gtld-servers.net.
com.			172800	IN	NS	d.gtld-servers.net.
com.			172800	IN	NS	f.gtld-servers.net.
com.			172800	IN	NS	a.gtld-servers.net.
com.			172800	IN	NS	g.gtld-servers.net.
com.			172800	IN	NS	j.gtld-servers.net.
com.			86400	IN	DS	19718 13 2 8ACBB0CD28F41250A80A491389424D341522D946B0DA0C0291F2D3D7 71D7805A
com.			86400	IN	RRSIG	DS 8 1 86400 20260103170000 20251221160000 61809 . LyStNQm9+1ankIVATIyU/cW7QtLvLE7NfHzzVnKqTLu6ko4/slJmY1QU bmhcRd6Z3e+u1k04++RixtKc/5N7MQ5olnze3pZ9y9VX0AdyGqnLSINP Ui3hZr5NIu3mTgjTt2PttfIEe1V0qrgaC903fIaNSdL2nISm49u5zoG6 LJ4l7rrDVt2pNvR+KiZtbSWp7ULt4jJLvQWjsvpfADnq2UqgOSVqNIvk kDQ8fXYFoNXETBHkdZ1NEQbIl/e4cj2vk0I4q5eeJReuKKamWjIxY6Zb GLnvjDVh2mAjVQcbkjde5r7oxrcJiK8z3Tx6Yd0QFns0g92/0JMukcZY r7em8g==
;; Received 1205 bytes from 192.33.4.12#53(c.root-servers.net) in 2 ms

;; UDP setup with 2001:502:7094::30#53(2001:502:7094::30) for www.github.com failed: network unreachable.
;; UDP setup with 2001:503:a83e::2:30#53(2001:503:a83e::2:30) for www.github.com failed: network unreachable.
github.com.		172800	IN	NS	ns-520.awsdns-01.net.
github.com.		172800	IN	NS	ns-421.awsdns-52.com.
github.com.		172800	IN	NS	ns-1707.awsdns-21.co.uk.
github.com.		172800	IN	NS	ns-1283.awsdns-32.org.
github.com.		172800	IN	NS	dns1.p08.nsone.net.
github.com.		172800	IN	NS	dns2.p08.nsone.net.
github.com.		172800	IN	NS	dns3.p08.nsone.net.
github.com.		172800	IN	NS	dns4.p08.nsone.net.
CK0POJMG874LJREF7EFN8430QVIT8BSM.com. 900 IN NSEC3 1 1 0 - CK0Q3UDG8CEKKAE7RUKPGCT1DVSSH8LL NS SOA RRSIG DNSKEY NSEC3PARAM
CK0POJMG874LJREF7EFN8430QVIT8BSM.com. 900 IN RRSIG NSEC3 13 2 900 20251225002706 20251217231706 46539 com. gmHVJS+WmLxYXTQMDYmfFRMcTSDHtHHXgSTWPo3FbOjYVV6GmpBv4Rd3 q91lGtsv8vkur4/nrD7LolMHJ4gpqw==
4KB4M5P0V10KIBJ8HQ2VH9EMME8NV6MR.com. 900 IN NSEC3 1 1 0 - 4KB4V9IAMJL29MC1VBJ8NDO7E6SI2B8O NS DS RRSIG
4KB4M5P0V10KIBJ8HQ2VH9EMME8NV6MR.com. 900 IN RRSIG NSEC3 13 2 900 20251225021105 20251218010105 46539 com. 8mEzmw5hy48Fr2ps/fSxqKgLwBWLyLUV3RwXyj9cQshaoXLOhqhpIawj /fvfrbiMADGGEIjO7zwfrk338jhexg==
;; Received 639 bytes from 192.43.172.30#53(i.gtld-servers.net) in 112 ms

;; UDP setup with 2620:4d:4000:6259:7:8:0:3#53(2620:4d:4000:6259:7:8:0:3) for www.github.com failed: network unreachable.
www.github.com.		3600	IN	CNAME	github.com.
github.com.		60	IN	A	20.27.177.113
;; Received 73 bytes from 198.51.44.72#53(dns3.p08.nsone.net) in 113 ms

#+end_src

* 関連
# 関連するエントリ。書いているファイルから見て、なぜ関連させたか書く。意味のあるつながりを意識的につくる。
# [引用、整合性、どう説明できるか、矛盾、補っているか、以前聞いたこと、対立、修正、補足、付け加え、組み合わせ、疑問]
# また、現在はリンクが見つからなくてもこういった切り口で将来関連させられそうな項目を書いておく
# [類推、未解決、具体例、追加調査、理由、動機、検証]
# 横に類推するか、上に抽象化するか、下に具体化するか
なし。
