:properties:
:ID: 20250504T212651
:mtime:    20250518164108
:ctime:    20250504212652
:end:
#+title:      KDOC 370: 『人を選ぶ技術』
#+date:       [2025-05-04 Sun 21:26]
#+filetags:   :book:
#+identifier: 20250504T212651

* この文書のステータス
:LOGBOOK:
CLOCK: [2025-05-05 Mon 09:22]--[2025-05-05 Mon 09:47] =>  0:25
CLOCK: [2025-05-05 Mon 08:52]--[2025-05-05 Mon 09:17] =>  0:25
CLOCK: [2025-05-05 Mon 08:25]--[2025-05-05 Mon 08:50] =>  0:25
CLOCK: [2025-05-05 Mon 08:00]--[2025-05-05 Mon 08:25] =>  0:25
CLOCK: [2025-05-04 Sun 23:03]--[2025-05-04 Sun 23:28] =>  0:25
CLOCK: [2025-05-04 Sun 21:58]--[2025-05-04 Sun 22:23] =>  0:25
CLOCK: [2025-05-04 Sun 21:26]--[2025-05-04 Sun 21:51] =>  0:25
:END:
- 作成
  - [X] 2025-05-05 貴島
- レビュー
  - [X] 2025-05-18 貴島

* 概要

『人を選ぶ技術』は世界的な人材会社で働く著者が、企業の採用について解説した本。

* メモ

- 人の優劣を判断するとき、特定の評価軸でしか判断しないことが多い。何をもって優秀とするかは個人や会社によって異なり、「弁が立つ」「花がある」などがある。そうではないが、大きなことをなした人は経営者は多い。成功したスタートアップでものを言ったのは「粘り強さ」と「鈍感力」であり、優劣を見誤った、という(位置517)
- コンピテンシーとは、その人がどんなシチュエーションでどういうアクションを取りがちかという固有の行動パターン、だという(位置713)
- 相手の「意見」ではなく「取った行動」にフォーカスする。エピソードベースのインタビューにする。似たような場面でどんな行動を取りがちかを想像できる。意見は、汲み取って相手に合わせることができ、実際の傾向を判断できない(位置759)
- 人の器の大きさ、伸びしろは「好奇心」「洞察力」「共鳴力」「胆力」の4つの因子で測れる、という研究がある(位置822)

因子。

- 好奇心: ほかの因子に優性する。経験、知識、フィードバックを求めるエネルギーの強さ、学習と変化の開放性
- 洞察力: 新しい可能性を示唆する情報を収集し、理解するエネルギーの強さ
- 共鳴力: 感情と論理を使って想いやビジョンを伝え人々とつながろうとするエネルギーの強さ
- 胆力: 大きなチャレンジがある課題を好み、困難な目標に向かって戦うことに強いエネルギーを得て、逆境から素早く立ち直る力を持つ

ラッセル・アコフの、情報処理の5つの次元(位置914)。

1. 「データ」
2. 意味を持つ「情報」
3. つながりを示す「知識」
4. 離れたものの共通項を見出す「洞察」
5. 共通項が繋がる筋を見出す「叡智」

メモ。

- インタビュー者が3人以上だと圧迫面接になる(位置1145)
- タメ語風言葉の効果。自分がタメ語風言葉を交えて話すと相手もこういう言葉を使ってもOKな人だと緊張感が和らぐ(位置1292)
- 大事なのはエピソードを聞くこと。こちらの欲しい答えを意図的に打ち返せないから。エピソードで語られている内容の重心の置き方を分析することでその人が大事にしている価値観を把握できる。エピソードに対してさらに質問し深堀りしていくことでメッキをはがせる(位置1336)
- 人選びに必要なのは「意見」ではなく「ファクト」。意見はあくまでフィクションで意思表明である。その人の実態でも能力でもない(位置1369)
- 大事なのは行動特性である。状況で何をしていたかというファクトである。行動特性は再現度が高い(位置1386)
- 「志望動機を聞く」はダメな面接の典型的なパターン。熱量について聞いたところでいくらでも偽装できるし、雇う会社からしても念押ししているにすぎない。モチベーションはあって当たり前。大事なのは会社が求める能力を備えているかどうか(位置1472)
- カルチャーフィット採用を謳う会社ほど、じつはカルチャーについてわかってないことが多い。企業カルチャーとは結果的に自然と生まれてくるものであって、流動的なものであるはずである(位置1489)
- 人を見るうえで性格ほど曖昧で危険な概念はない。評価のアングルが異なるから(位置1505)
- ほとんどの日本企業において勇気を出して「未然」ながら「可能性がある」人を採用すること(「ワイルドな採用」)には大変な勇気が必要になっている(位置2017)

* 関連
なし。
