:properties:
:ID: 20251206T184941
:end:
#+title:      KDOC 495: 文芸的にDB動作を検証できるようにする
#+date:       [2025-12-06 Sat 18:49]
#+filetags:   :project:
#+identifier: 20251206T184941

* この文書のステータス
- 作成
  - [X] 2025-12-15 貴島
- レビュー
  - [X] 2025-12-15 貴島

* 概要

文芸的にDB動作を検証できるようにした。

* 背景

[[https://syu-m-5151.hatenablog.com/entry/2025/11/25/135220][「Postgres で試した？」と聞き返せるようになるまでもしくはなぜ私は雰囲気で技術を語るのか？]]を読んで、データベースの機能について知らないことが多いのを知った。

コンピュータのほかの事柄と同様に、じっさいに試して、挙動を仔細にみて背景にあるアイデアを理解し、自分なりのモデルを構築していくのが必要に見えた。REPLでいじるのではなく、記録しつつ試していけると、あとで見返すこともできよさそうである。

そういうことを気軽にできるようにした。

* 要件

- 少ない準備で気軽にデータベースを実行できる
- 文芸的プログラミングができる。入力と標準出力をテキストに残し、そのままドキュメント化できる
  - 入力クエリを出力にエコー表示できる
- 毎回クリーンな環境で、完全に再現できる
- org-mode org-babelの ~sql~ ブロックから直接使える
- 完全に同等の機能が使える。インデックス、EXPLAIN、トランザクション...が使える

* 使用例
:PROPERTIES:
  :header-args+: :results table
  :header-args+: :database postgres
  :header-args+: :dbhost localhost
  :header-args+: :dbport 15432
  :header-args+: :dbuser postgres
  :header-args+: :engine postgresql
:END:

リポジトリは[[https://github.com/kijimad/pgpg][kijimad/pgpg]]にある。

根本的なアイデアは、データベースのプロキシを実装し、フック処理を追加することである。プロキシで、実験に必要な処理(DB初期化と削除)を実行する。

#+caption: DBとプロキシを起動する
#+begin_src shell
  docker compose up -d
#+end_src

#+caption: org-modeの見出しやファイルヘッダに接続先情報を書く
#+begin_src org-mode
:PROPERTIES:
  :header-args+: :results table
  :header-args+: :database postgres
  :header-args+: :dbhost localhost
  :header-args+: :dbport 15432
  :header-args+: :dbuser postgres
  :header-args+: :engine postgresql
:END:
#+end_src

あとは、org-babelでSQLを実行して評価する。

#+begin_src sql
  select 1+1 as result;
#+end_src

#+RESULTS:
#+begin_src
|                         |
|-------------------------|
| > select 1+1 as result; |
| result                  |
| 2                       |
#+end_src

データベースは接続のたびにリセットされる。完全に再現可能で、あとで読みやすい。

#+caption: リセットされるので実行のたびに同じ結果が出る
#+begin_src sql
  CREATE TABLE users (
      name varchar(255),
      tel integer
  );
  INSERT INTO users (name, tel) VALUES ('きじま', 100);
  SELECT * FROM users;
#+end_src

#+RESULTS:
#+begin_src
|                                                         |     |
|---------------------------------------------------------+-----|
| > CREATE TABLE users (                                  |     |
| >     name varchar(255),                                |     |
| >     tel integer                                       |     |
| > );                                                    |     |
| CREATE TABLE                                            |     |
|                                                         |     |
| > INSERT INTO users (name, tel) VALUES ('きじま', 100); |     |
| INSERT 0 1                                              |     |
|                                                         |     |
| > SELECT * FROM users;                                  |     |
| name                                                    | tel |
| きじま                                                  | 100 |
#+end_src

* 関連

- 動機: [[id:20240207T092747][KDOC 77: 検証する方法があると理解が進む]]。に基づいて作った
