:properties:
:ID: 20251103T231224
:end:
#+title:      KDOC 483: 『ROCK IN!』のコンセプトを話す(訳)
#+date:       [2025-11-03 Mon 23:12]
#+filetags:   :draft:wiki:
#+identifier: 20251103T231224

#+begin_comment
(kd/denote-kdoc-rename)
(kd/denote-format)

====ポリシー。
1ファイル1アイデア。
1ファイルで内容を完結させる。
常にほかのエントリとリンクする。
自分の言葉を使う。
参考文献を残しておく。
文献メモの場合は、感想と混ぜないこと。1つのアイデアに反する
ツェッテルカステンの議論に寄与するか。それで本を書けと言われて書けるか
頭のなかやツェッテルカステンにある問いとどのようにかかわっているか
エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。
個人の感想・意思表明ではない。事実や書籍情報に基づいている

====永久保存メモのルール。
自分の言葉で書く。
後から読み返して理解できる。
他のメモと関連付ける。
ひとつのメモにひとつのことだけを書く。
メモの内容は1枚で完結させる。
論文の中に組み込み、公表できるレベルである。

====水準を満たす価値があるか。
その情報がどういった文脈で使えるか。
どの程度重要な情報か。
そのページのどこが本当に必要な部分なのか。
公表できるレベルの洞察を得られるか

====フロー。
1. 「走り書きメモ」「文献メモ」を書く
2. 1日1回既存のメモを見て、自分自身の研究、思考、興味にどのように関係してくるかを見る
3. 追加すべきものだけ追加する

#+end_comment

* この文書のステータス
- 作成
  - [X] 2025-11-23 貴島
- レビュー
  - [X] 2025-11-25 貴島

# チェックリスト ================
# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。
* 概要
# 本文(見出しも設定する)

Vtuberの Koseki Bijou が語った内容のクリップ動画を見て、自分も何か頑張ろうと考えた。原文を見る。

#+begin_quote
Let's talk about the concept of the song. Let's start with the whole concept of the song.

曲のコンセプトについて話そうと思う。曲全体のコンセプトについて。

So I wanted the song to be very like me. So like half brain rot, half not so serious, half like you know not very silly but also has a lot of meaning in me in it and I think it has equal parts of both like you can on the surface level it's very catchy danceable but if you look in the lyrics and you look at it deeper, its very me in terms of the story and the meaning of the lyrics to it.

私みたいな曲にしたかった。つまり半分は脳が腐ったような感じで、半分は深刻じゃなくて、すごく愚かなわけじゃないけど、私自身の意味もたくさん込めている。両方が均等にある。表面的に見ればキャッチーで踊りやすいけど、歌詞に入り込んで深く見ると、ストーリーや歌詞の意味という点において、まさに私なんだ。

Yeah, there's lots of I think the lyrics are very smart and they're very very personal to me.

歌詞はとても賢いと思う。そして私にとっては個人的なんだ。

So thinking of this song and when I was asked what do I want? I said I wanted something that could hype up a crowd on stage.

この曲を思い返すと、どうしたいか聞かれたとき、私はなにかステージの人たちを湧かすような何かがほしい、って言った。

I said that Prism No Maho, you know, was very cutey Biboo and like you know, soft Biboo beginnings, but I wanted this one to be the Biboo that is Biboo right now.

私はプリズムの魔法はビブー初期のキュートでソフトな感じだった、でもこの曲では、今のビブーらしいビブーにしたいと言った。

The high energy meme lord total personality Biboo high high energy sort of thing. So that's what we were going for and it this is also song that was developed for the stage as well.

高いエネルギーのミームの支配者、それが全体的なビブーの人格という感じ。だからそれが私達が目指す姿で、この曲もステージのために作られた。

So like imagine like something like a concert or fest and Biboo going like "Biboo Biboo!". I wanted the song to be very like high energy and something that, you know, we would all have fun singing along with and dancing along with on stage.

だから「ビブー!ビブー!」みたいな感じのコンサートやフェスを想像して。曲はそういうハイな感じのものであってほしかった。私たちがステージでいっしょに歌って踊っている間に楽しめるようなものだよ。

So that was the initial concept. And obviously I wanted it to be video game themed.

それが最初のコンセプトだった。そして、明らかにビデオゲームなテーマにしたかった。

Because it was specifically for my live, right? So, I was making this song along side my 3D live which both had to do with video games. So, there's a general like gaming theme around it.

なぜかって、それは私のライブ配信の特徴だから。そうでしょ? だから、3Dライブと平行で曲を作ったんだけど、どちらもビデオゲームに関連していたんだ。

But if you look into the lyrics deeper than that, it's not specifically really exactly about video games. It's more personally the stubborn, determined unable to give up nature of Biboo is kind of the deeper meaing of it.

でも歌詞を深く見ると、本当は厳密にはビデオゲームについてではないんだ。

It which is how I approach life in general and video games and mostly everything I do which is I don't start out necessarily being the best at something.

それは私が人生全般とビデオゲーム、ほぼすべてのことにアプローチする方法なんだ。私は必ずしも最初から得意な状態でスタートするわけじゃない。

In games in life in Hololive in really anything I do I don't start out being the best. I start out as knowing nothing. I start out as a little baby not knowing what to do. Lost little baby Biboo.

マジで、ゲーム、人生、ホロライブ ... 私がすることはすべて得意な状態で始まったわけじゃない。何も知らないところから始まった。何をするかもわからない小さな赤ん坊として始まった。迷子で赤ん坊のビブー。

And then I keep going and going and going until I get good. And I think that reflects me overall like in everything, not only video games. It's very reflective of how I play video games too.

そしてうまくやれるまでやり続ける。ビデオゲームだけじゃなくて、あらゆる面で私を反映していると思う。私がどのようにビデオゲームをプレイしているかも、よく反映してる。

Like Dark Souls and specifically, but other video games as well, is where, you know, I'll there's a hard boss and it's hard, but not going give up. I'm going to grind and grind and grind and grind and grind until I get good and then finally reach my goal.

とくにダークソウルみたいなゲームは、ほかのビデオゲームもそうだけど、そこにはハードなボスがいる。だけど諦めない。いい結果が出るまで地道に何回もやりつづける。そして最終的にゴールに到達するんだ。

But again, it's in all aspects of my life. Like singing, I'm not I started off, you know, not the best sinnger. Even starting off in Hololive, you know, my singing wasn't that strong. But even now I'm grinding over and over and over and over again to get good.

まただけど、それが私の人生すべての側面なんだ。歌にせよ、私は最高の歌手としてはじまったわけじゃないよね。ホロライブで始めるときですら、私の歌は強くなかった。でも今でも、私は何回も何回もやり続けて、よくなった。

You know sometimes what was it? Sometimes I think like, man, how did I get here in Holive? Because I feel like, you know, I'm not particularly the most skilled in general like dancing, singing, performing, content creation, streaming even. I just came in, you know, I like video games.

たまに、何だったのか?と思う。たまに私はどうやってホロライブにたどり着いたのだろう、というようなことを思う。私は特に最高のスキルを持っていない、ダンスとか歌、パフォーマンス、コンテンツ作成、配信だってそう。私はただ、ビデオゲームが好きだからっていう理由で来た。

I like video games. I play a lot of video games and I play a lot of video games for a long time. So I'm like, how did I get here? But now that I think about it, I like that I came into Hololive not particularly skilled at everything.

私はビデオゲームが好きだ。私は長時間、たくさんのビデオゲームをプレイする。それで、どうやってここにたどり着いたんだ? でも今思えば、何もスキルも持たずにホロライブに入ったことがよかったと思う。

Like I kind of like that I came into Hololive not a great singer. Didn't know how to dance, was very new, you know, trying to find my footing and everything because then you could see the start of my journey and then you guys could watch me grow alongside me. Yeah, sort of that. Soft of that idea.

私はとくに優れていない歌手としてホロライブに入った。ダンスのしかたも知らなくて、本当に初心者だった。自分の足場を探そうとしていた。そうすれば、君たちは旅の始まりを見られて、私が成長するのを一緒に見られるから。そういう感じ。そういうアイデアなんだ。

Because that's a very Biboo thing. And that's what the song is about. Is just, starting off not very new, not knowing much, and then just throwing yourself head first, not worried about making mistakes over and over and over and over again until you slowly but surely get better.

最初は新しくない、多くを知らないところから始める。ただ頭から飛び込む。ミスをすることを恐れずに、遅くとも、うまくなるまで何度も何度も。

And I hope that you can see that in the video. And also just me in general as a person cuz that's very me as a person. I think one of my strong suits as a person is I'm not afraid to make mistakes.

そういったことがビデオで伝わるのを願っている。そしてひとりの人間としてもね。なぜならそれが私だから。私の強みの一つは、失敗を恐れないことだ。

And I'm not afraid to mess up in front of you guys. I'm very like open with like you know if I make a mistake you see it. I don't hide it.

そして君たちの前で台無しにすることを恐れない。私はオープンだ。もしミスをしたら、君たちはそれを見るだろう。私は隠さない。

And I think it's that like no fear of like making oopsies that makes it easy for me to like go again and again and again and again and keep going forward until I get it done.

失敗をしでかすことに対する恐れがないのは、私に何度も挑戦して、達成するまで前に進み続けやすくする。

That was the basis of like envy. It's in the visuals. It's in the lyrics and it's inside people. And I think, you know, biboo not being perfect and, you know, starting off with nothing really maybe it helps you a little bit, too.

それは嫉妬の基礎のようなものだ。ビジュアルになってる。それが歌詞と人々の内側にある。ビブーは完璧ではないこと、何も持たずに始めることだって、少しは助けになるかもしれないと思うんだ。
#+end_quote

#+begin_export html
<iframe width="560" height="315" src="https://www.youtube.com/embed/qb51ZfcpDx0?si=VCYU0TjtKJVdxQ_e&amp;start=1607" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
#+end_export

* 関連
# 関連するエントリ。なぜ関連させたか理由を書く。意味のあるつながりを意識的につくる。
# - この事実は自分のこのアイデアとどう整合するか。
# - この現象はあの理論でどう説明できるか。
# - ふたつのアイデアは互いに矛盾するか、互いを補っているか。
# - いま聞いた内容は以前に聞いたことがなかったか。
# - メモ y についてメモ x はどういう意味か。
# - 対立する
# - 修正する
# - 補足する
# - 付け加えるもの
# - アイデア同士を組み合わせて新しいものを生み出せないか
# - どんな疑問が浮かんだか
なし。
