:properties:
:ID: 20251207T091742
:end:
#+title:      KDOC 497: 複合インデックスの使用条件を試す
#+date:       [2025-12-07 Sun 09:17]
#+filetags:   :draft:permanent:
#+identifier: 20251207T091742

#+begin_comment
(kd/denote-kdoc-rename)
(kd/denote-format)

====ポリシー。
1ファイル1アイデア。
1ファイルで内容を完結させる。
常にほかのエントリとリンクする。
自分の言葉を使う。
参考文献を残しておく。
文献メモの場合は、感想と混ぜないこと。1つのアイデアに反する
ツェッテルカステンの議論に寄与するか。それで本を書けと言われて書けるか
頭のなかやツェッテルカステンにある問いとどのようにかかわっているか
エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。
個人の感想・意思表明ではない。事実や書籍情報に基づいている

====永久保存メモのルール。
自分の言葉で書く。
後から読み返して理解できる。
他のメモと関連付ける。
ひとつのメモにひとつのことだけを書く。
メモの内容は1枚で完結させる。
論文の中に組み込み、公表できるレベルである。

====水準を満たす価値があるか。
その情報がどういった文脈で使えるか。
どの程度重要な情報か。
そのページのどこが本当に必要な部分なのか。
公表できるレベルの洞察を得られるか

====フロー。
1. 「走り書きメモ」「文献メモ」を書く
2. 1日1回既存のメモを見て、自分自身の研究、思考、興味にどのように関係してくるかを見る
3. 追加すべきものだけ追加する

#+end_comment

* この文書のステータス
- 作成
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))
- レビュー
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))

# チェックリスト ================
# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。
* 概要
:PROPERTIES:
  :header-args+: :results table
  :header-args+: :database postgres
  :header-args+: :dbhost localhost
  :header-args+: :dbport 15432
  :header-args+: :dbuser postgres
  :header-args+: :engine postgresql
:END:

条件を変えて、どのように使われるか試す。

#+caption: 複合インデックスを使う
#+begin_src sql
  CREATE TABLE users (
      id serial PRIMARY KEY,
      name varchar(255),
      tel integer,
      nonidx varchar(255)
  );
  CREATE INDEX idx_users_name ON users(name, tel);

  -- レコードが空だと、すべてインデックス使用になったため
  INSERT INTO users (name, tel)
  SELECT
      'Name' || (i % 1000),
      (i % 10000)
  FROM generate_series(1, 100000) i;

  -- 複合インデックスの両方の要素を使うと、インデックスが使われる
  explain
  select id from users where name = 'a' and tel = 1;

  -- 複合インデックスの最初の要素を使うと、インデックスが使われる
  explain
  select id from users where name = 'a';

  -- 複合インデックスの順番も入れ替えても、要素があっていればインデックスが使われる
  explain
  select id from users where tel = 1 and name = 'a';

  -- 複合インデックスの最初の要素 + インデックス外だとインデックスが使われる
  explain
  select id from users where name = 'a' and nonidx = 'a';

  -- 複合インデックスの2番めの要素を使うと、インデックスが使われない
  explain
  select id from users where tel = 1;
#+end_src

#+RESULTS:
#+begin_src
|                                                                            |   |             |
|----------------------------------------------------------------------------+---+-------------|
| > CREATE TABLE users (                                                     |   |             |
| >     id serial PRIMARY KEY,                                               |   |             |
| >     name varchar(255),                                                   |   |             |
| >     tel integer,                                                         |   |             |
| >     nonidx varchar(255)                                                  |   |             |
| > );                                                                       |   |             |
| CREATE TABLE                                                               |   |             |
|                                                                            |   |             |
| > CREATE INDEX idx_users_name ON users(name, tel);                         |   |             |
| CREATE INDEX                                                               |   |             |
|                                                                            |   |             |
| > INSERT INTO users (name, tel)                                            |   |             |
| > SELECT                                                                   |   |             |
| >     'Name'                                                               |   | (i % 1000), |
| >     (i % 10000)                                                          |   |             |
| > FROM generate_series(1, 100000) i;                                       |   |             |
| INSERT 0 100000                                                            |   |             |
|                                                                            |   |             |
| > explain                                                                  |   |             |
| > select id from users where name = 'a' and tel = 1;                       |   |             |
| QUERY PLAN                                                                 |   |             |
| Index Scan using idx_users_name on users  (cost=0.28..8.30 rows=1 width=4) |   |             |
| Index Cond: (((name)::text = 'a'::text) AND (tel = 1))                     |   |             |
|                                                                            |   |             |
| > explain                                                                  |   |             |
| > select id from users where name = 'a';                                   |   |             |
| QUERY PLAN                                                                 |   |             |
| Bitmap Heap Scan on users  (cost=4.43..69.98 rows=19 width=4)              |   |             |
| Recheck Cond: ((name)::text = 'a'::text)                                   |   |             |
| ->  Bitmap Index Scan on idx_users_name  (cost=0.00..4.42 rows=19 width=0) |   |             |
| Index Cond: ((name)::text = 'a'::text)                                     |   |             |
|                                                                            |   |             |
| > explain                                                                  |   |             |
| > select id from users where tel = 1 and name = 'a';                       |   |             |
| QUERY PLAN                                                                 |   |             |
| Index Scan using idx_users_name on users  (cost=0.28..8.30 rows=1 width=4) |   |             |
| Index Cond: (((name)::text = 'a'::text) AND (tel = 1))                     |   |             |
|                                                                            |   |             |
| > explain                                                                  |   |             |
| > select id from users where name = 'a' and nonidx = 'a';                  |   |             |
| QUERY PLAN                                                                 |   |             |
| Bitmap Heap Scan on users  (cost=4.42..70.03 rows=1 width=4)               |   |             |
| Recheck Cond: ((name)::text = 'a'::text)                                   |   |             |
| Filter: ((nonidx)::text = 'a'::text)                                       |   |             |
| ->  Bitmap Index Scan on idx_users_name  (cost=0.00..4.42 rows=19 width=0) |   |             |
| Index Cond: ((name)::text = 'a'::text)                                     |   |             |
|                                                                            |   |             |
| > explain                                                                  |   |             |
| > select id from users where tel = 1;                                      |   |             |
| QUERY PLAN                                                                 |   |             |
| Seq Scan on users  (cost=0.00..588.34 rows=19 width=4)                     |   |             |
| Filter: (tel = 1)                                                          |   |             |
#+end_src

見知らぬキーワードがある。

- Bitmap Index Scan
- Bitmap Heap Scan
- Recheck Cond
- Filter

* 関連
# 関連するエントリ。なぜ関連させたか理由を書く。意味のあるつながりを意識的につくる。
# - この事実は自分のこのアイデアとどう整合するか。
# - この現象はあの理論でどう説明できるか。
# - ふたつのアイデアは互いに矛盾するか、互いを補っているか。
# - いま聞いた内容は以前に聞いたことがなかったか。
# - メモ y についてメモ x はどういう意味か。
# - 対立する
# - 修正する
# - 補足する
# - 付け加えるもの
# - アイデア同士を組み合わせて新しいものを生み出せないか
# - どんな疑問が浮かんだか
なし。
