:properties:
:ID: 20251214T123530
:end:
#+title:      KDOC 505: 既存メモ側からどういった関連ができそうか考える
#+date:       [2025-12-14 Sun 12:35]
#+filetags:   :draft:essay:
#+identifier: 20251214T123530

#+begin_comment
(kd/denote-kdoc-rename)
(kd/denote-format)

====ポリシー。
1ファイル1アイデア。
1ファイルで内容を完結させる。
常にほかのエントリとリンクする。
自分の言葉を使う。
参考文献を残しておく。
文献メモの場合は、感想と混ぜないこと。1つのアイデアに反する
ツェッテルカステンの議論に寄与するか。それで本を書けと言われて書けるか
頭のなかやツェッテルカステンにある問いとどのようにかかわっているか
エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。
個人の感想・意思表明ではない。事実や書籍情報に基づいている

====永久保存メモのルール。
自分の言葉で書く。
後から読み返して理解できる。
他のメモと関連付ける。
ひとつのメモにひとつのことだけを書く。
メモの内容は1枚で完結させる。
論文の中に組み込み、公表できるレベルである。

====水準を満たす価値があるか。
その情報がどういった文脈で使えるか。
どの程度重要な情報か。
そのページのどこが本当に必要な部分なのか。
公表できるレベルの洞察を得られるか

====フロー。
1. 「走り書きメモ」「文献メモ」を書く
2. 1日1回既存のメモを見て、自分自身の研究、思考、興味にどのように関係してくるかを見る
3. 追加すべきものだけ追加する

#+end_comment

* この文書のステータス
- 作成
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))
- レビュー
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))

# チェックリスト ================
# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。
* 概要
# 本文(見出しも設定する)

ツェッテルカステンライクな方法でメモしている。

メモの関連が少なく、理解や思考を深められていないのを課題に感じてきた。単純に同じカテゴリの話題だから、という理由で関連させていることが多かったが、意味ないよな、と感じてきた。

既存メモ側にどういった関連ができそうかの想定を書いておくと関連させやすいことに気づいた。また、それだけだと忘れやすいので関連想定に対して類型をつけて抽象化しておくと、組み合わせて考えやすいのに気づいた。

#+caption: 例
#+begin_example
KDOC 37: トップダウンかボトムアップ、どちらで成し遂げるか?
- 具体例: トップダウンの主張も出す

KDOC 71: KDOCエントリの書き方を考える
- 補足: 結局テンプレートファイルに含めた項目以外は忘れ去っていた。仕組みにしなければならない

KDOC 3: 『ない仕事の作り方』
- 組み合わせ: 彼のスクラップ癖と知識獲得モデルは、メモのとりかたで説明できるのではないか
#+end_example

過去のメモを見返して、この関連となるメモを追加していくわけである。

いままでは作成時に膨大なメモから関連を考える必要があったが、この方法だと先に関連の補助線は引いてあるので、あとは書くだけである。関連を作れなかった理由は、複数の作業を同時にやるハードルが高かったからに見える。分解してやると、自然にできるようになる。

* 関連
# 関連するエントリ。なぜ関連させたか理由を書く。意味のあるつながりを意識的につくる。
# [引用、整合性、どう説明できるか、矛盾、補っているか、以前聞いたこと、対立、修正、補足、付け加え、組み合わせ、疑問]
#
# また、現在はリンクが見つからなくてもこういった切り口で将来関連させられそうな項目を書いておく
# [類推、未解決、具体例、追加調査、理由、動機]
# 横に類推するか、上に抽象化するか、下に具体化するか

- 動機: [[id:20240502T172812][KDOC 153: すでにあるメモから、関連させられないか考える]]。「時間を作る」だけでは改善しなかったので、対策を具体化した
