:properties:
:ID: 20250506T120102
:mtime:    20250612204856
:ctime:    20250506120122
:end:
#+title:      KDOC 377: 『一日で読めてわかるTCP/IPのエッセンス』
#+date:       [2025-05-06 Tue 12:01]
#+filetags:   :draft:book:
#+identifier: 20250506T120102

# (kd/denote-kdoc-rename)
# (denote-rename-file-using-front-matter (buffer-file-name) 0)
# (save-excursion (while (re-search-backward ":draft" nil t) (replace-match "")))
# (flush-lines "^\\#\s.+?")

# ====ポリシー。
# 1ファイル1アイデア。
# 1ファイルで内容を完結させる。
# 常にほかのエントリとリンクする。
# 自分の言葉を使う。
# 参考文献を残しておく。
# 文献メモの場合は、感想と混ぜないこと。1つのアイデアに反する
# ツェッテルカステンの議論に寄与するか。それで本を書けと言われて書けるか
# 頭のなかやツェッテルカステンにある問いとどのようにかかわっているか
# エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
# アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
# エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
# 恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。
# 個人の感想・意思表明ではない。事実や書籍情報に基づいている

# ====永久保存メモのルール。
# 自分の言葉で書く。
# 後から読み返して理解できる。
# 他のメモと関連付ける。
# ひとつのメモにひとつのことだけを書く。
# メモの内容は1枚で完結させる。
# 論文の中に組み込み、公表できるレベルである。

# ====水準を満たす価値があるか。
# その情報がどういった文脈で使えるか。
# どの程度重要な情報か。
# そのページのどこが本当に必要な部分なのか。
# 公表できるレベルの洞察を得られるか

# ====フロー。
# 1. 「走り書きメモ」「文献メモ」を書く
# 2. 1日1回既存のメモを見て、自分自身の研究、思考、興味にどのように関係してくるかを見る
# 3. 追加すべきものだけ追加する

* この文書のステータス
:LOGBOOK:
CLOCK: [2025-05-11 Sun 16:17]--[2025-05-11 Sun 16:42] =>  0:25
CLOCK: [2025-05-11 Sun 15:52]--[2025-05-11 Sun 16:17] =>  0:25
CLOCK: [2025-05-11 Sun 15:26]--[2025-05-11 Sun 15:51] =>  0:25
CLOCK: [2025-05-08 Thu 22:08]--[2025-05-08 Thu 22:33] =>  0:25
CLOCK: [2025-05-08 Thu 20:52]--[2025-05-08 Thu 21:17] =>  0:25
:END:
- 作成
  - [X] 2025-05-11 貴島
- レビュー
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))

# チェックリスト ================
# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。
* 概要
:LOGBOOK:
CLOCK: [2025-05-07 Wed 23:14]--[2025-05-07 Wed 23:39] =>  0:25
CLOCK: [2025-05-07 Wed 21:49]--[2025-05-07 Wed 22:14] =>  0:25
CLOCK: [2025-05-07 Wed 18:41]--[2025-05-07 Wed 19:06] =>  0:25
:END:
# 本文(見出しも設定する)

[[https://www.amazon.co.jp/1%E6%97%A5%E3%81%A7%E8%AA%AD%E3%82%81%E3%81%A6%E3%82%8F%E3%81%8B%E3%82%8BTCP-IP%E3%81%AE%E3%82%A8%E3%83%83%E3%82%BB%E3%83%B3%E3%82%B9-NextPublishing-%E6%A6%8A-%E6%AD%A3%E6%86%B2-ebook/dp/B00IZ76TGE][1日で読めてわかるTCP/IPのエッセンス]]はTCP/IPを易しく解説する本。

* メモ

- TCP/IPは実際に通信するネットワーク方式を定めていない。TCP/IPは特定のネットワーク方式に依存するプロトコルではない。ネットワーク方式に依存する要素はプロトコルに含まれていない(位置84)
- TCP/IPは使用するアプリケーションの動作を定めない。アプリケーションやサービスを自由に実装するための基盤となる(位置84)
- TCP/IPはイーサネットなどの実際のネットワークシステムとネットワークを使うアプリケーションの間に位置する。アプリケーションとネットワークはどウェアの間を取り持ち、汎用的な通信サービスを提供する(位置106)
  - アプリケーション → TCP/IP → ネットワークデバイスのデバイスドライバ → ネットワークハードウェア → ネットワーク
- TCP/IPは複数のプロトコルから構成されるプロトコルスイート。IP, UDP, TCPを中心としていくつかの関連プロトコルを含む(位置106)
- IPの役割は複雑に接続されたインターネット(ネットワークが相互に接続されたもの)において、接続されている個々の機器が任意の相手にデータを送れるようにすること。イーサネットや無線LANは1つのネットワーク内での通信を行えるが、そのままでは多数のネットワークを相互に接続できない(位置119)
- ルーターは接続しているネットワークの間でデータの中継を行う機器。ルータを使ったインターネットでのデータ転送をサポートするプロトコルがIP。IPを使うことでイーサネットなどで構成されたネットワークどうしをルータで接続しデータを中継できる(位置119)
- IPアドレスにはその機器が接続されているネットワークを識別する情報と機器そのものを識別する情報が含まれる。インターネットではIPアドレスを使って通信の相手を指定する(位置138)
- UDPはプログラム間でデータをやり取りするためにデータにポート番号を付加するプロトコル(位置151)
- TCPはポート番号を使って機器上のプログラムを識別する。そして2つのプログラムの間でデータを相互にやり取りする通信路を提供する。最初に通信相手を指定して明示的に接続処理し、以後はその相手とのみデータをやり取りする。明示的な接続関係のことをコネクションという。コネクションによって相手と自分の状態を共有し通信のエラー検出や対処をする(位置168)
- ネットワークシステムは何段階にも機能を分け、組み合わせた形で構築されている。実際のネットワーク方式、伝送の制御、アプリケーション...。このようにすることでネットワーク方式やアプリケーションの自由度が高くなる(位置206)
- OSIの7階層モデルは、TCP/IPを使うインターネットのネットワーク構成にはうまくあてはまらない。層の役割がアプリケーションの構造に対応しないため。TCP/IP階層モデルと呼ばれるモデルもある(位置223)
- ネットワーク方式ごとのフレーム中のデータサイズの上限値をMTUという(位置333)
- IPアドレスはインターネットに接続された個々のノードを識別するための一意な32ビットの情報。表記がピリオドつなぎというだけ(位置400)
- TCP/IPの特徴の1つに、1つのIPアドレスでネットワークとノードをまとめて表すという点がある(位置400)
- アドレスの上位の、ネットワークを示す部分をネットワーク部、下位の、ノードを示す部分をホスト部という。IPアドレスのネットワーク部とホスト部を示すため、サブネットマスクという情報が使われる。ネットワーク部とマスク部の配分は自由なので必要である。ビットが1の部分がネットワーク部、0の部分がホスト部を表す(位置419)
- ネットワーク部が異なるノードは別ネットワークに接続していると判断され、ルーターを介して通信する(位置435)
- ホスト部のビットがすべて0のIPアドレスは、特定のノードを識別するためのアドレスではなく、ネットワークを識別するアドレスとして使われる(位置476)
- 論理アドレスであるIPアドレスと、物理アドレスであるMACアドレス(位置569)
- イーサネットでTCP/IPを使う場合、IPのレベルではIPアドレスで宛先や送信元を指定する。実際の通信はイーサネットを使うので、MACアドレスでノードを指定しなければならない。そのため通信を行うにはIPアドレスから対応するMACアドレスを求める作業が必要になる。そこでARP(アドレス解決プロトコル)を使いネットワークを使ってIPアドレスとMACアドレスの対応付けを行っている(位置587)
- ARPキャッシュはどこに保存されるのだろうか
- ネットワークの基本的な診断を行うpingコマンドはICMPエコー要求/応答要求機能を使っている(位置660)
- CIDRはIPアドレスのネットワーク部のビット配分を階層的に扱い、多数のネットワーク宛のルーティングエントリを少数のエントリで代表して扱うというもの。電話番号の国番号や市外局番のように階層化されているようなもの(位置810)
- IPアドレスはノードを識別するだけで、目的のプログラムを示せない(位置854)
- UDPとTCPでは、UDPヘッダ、TCPヘッダの中にポート番号という情報が収められており、そのポート番号でコンピュータのプログラムを識別する(位置854)
- 単純なデータ要求に対し、短い応答が返されて終わりというやり取りの場合、UDPのほうが効率的である。たとえばDNSによる名前解決にはUDPが多用されている(位置854)
- UDPはTCPと異なり、特定の接続相手を定めない。一度に複数の宛先に伝送する場合はUDPを使う。UDPでデータを転送する場合、データグラムの送信ごとに宛先を指定する(位置854)
- UDPはデータグラムに送信元ポート番号と宛先ポート番号を付加するプロトコルといえる(位置995)
- TCPは常に特定の2つのプログラム間でのやりとりとなる(位置1058)
- TCPの伝送では順序情報をやりとりすることでデータの順序や欠落の有無を確認する(位置1072)
- あるサーバープログラムが複数のクライアントや同一クライアントの複数のプログラムに同時にサービスを提供する場合、サーバー側のIPアドレスとポート番号は同一である。が、クライアント側のIPアドレスとポート番号は異なるため、それぞれのコネクションを別のものとして区別できる(位置1103)
- 2つのプログラム間で通信を行う際には伝送するデータの量を加減する処理が求められる。受信側が処理しきれないペースでデータを送ってしまうと受信側のバッファが溢れてデータが失われる。TCPはスロースタートという方法で輻輳の発生を抑えている(位置1252)

* 関連
# 関連するエントリ。なぜ関連させたか理由を書く。意味のあるつながりを意識的につくる。
# - この事実は自分のこのアイデアとどう整合するか。
# - この現象はあの理論でどう説明できるか。
# - ふたつのアイデアは互いに矛盾するか、互いを補っているか。
# - いま聞いた内容は以前に聞いたことがなかったか。
# - メモ y についてメモ x はどういう意味か。
# - 対立する
# - 修正する
# - 補足する
# - 付け加えるもの
# - アイデア同士を組み合わせて新しいものを生み出せないか
# - どんな疑問が浮かんだか
なし。
