:properties:
:ID: 20251020T112602
:end:
#+title:      KDOC 476: AWSネットワーク入門
#+date:       [2025-10-20 Mon 11:26]
#+filetags:   :draft:book:
#+identifier: 20251020T112602

#+begin_comment
(kd/denote-kdoc-rename)
(kd/denote-format)

====ポリシー。
1ファイル1アイデア。
1ファイルで内容を完結させる。
常にほかのエントリとリンクする。
自分の言葉を使う。
参考文献を残しておく。
文献メモの場合は、感想と混ぜないこと。1つのアイデアに反する
ツェッテルカステンの議論に寄与するか。それで本を書けと言われて書けるか
頭のなかやツェッテルカステンにある問いとどのようにかかわっているか
エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。
個人の感想・意思表明ではない。事実や書籍情報に基づいている

====永久保存メモのルール。
自分の言葉で書く。
後から読み返して理解できる。
他のメモと関連付ける。
ひとつのメモにひとつのことだけを書く。
メモの内容は1枚で完結させる。
論文の中に組み込み、公表できるレベルである。

====水準を満たす価値があるか。
その情報がどういった文脈で使えるか。
どの程度重要な情報か。
そのページのどこが本当に必要な部分なのか。
公表できるレベルの洞察を得られるか

====フロー。
1. 「走り書きメモ」「文献メモ」を書く
2. 1日1回既存のメモを見て、自分自身の研究、思考、興味にどのように関係してくるかを見る
3. 追加すべきものだけ追加する

#+end_comment

* この文書のステータス
- 作成
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))
- レビュー
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))

# チェックリスト ================
# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。
* 概要
# 本文(見出しも設定する)
* メモ

- サービスの種類によって、グローバル、リージョン、アベイラビリティゾーンのどの範囲で提供されるのか異なる(p20)
  - グローバルサービス: IAM, CDN, Route53...
  - リージョンサービス: VPC, S3, ...
  - アベイラビリティゾーンサービス: EC2, ...
- 非VPCサービスとVPCサービスがある(p22)
  - グローバルネットワークを利用する非VPCサービス: CloudFront, Route53, S3, ...
  - プライベートネットワークを利用するVPCサービス: EC2, RDS, ...
- VPCにプライベートIPアドレスを割り当てて運用する(p22)
- セキュリティグループはEC2インスタンスとネットワークの間にあり、パケットフィルタリング型ファイアウォールを提供する。ENIに対して設定する(p24)
- セキュリティグループはインスタンスを対象とし、ネットワークACLはサブネットを対象としている(p26)
- ルーターを設置する操作をしなくても、VPCには必ず1つルーターが暗黙に置かれる。サブネットが増えたとき、暗黙的な1つのルーターを経由して互いにつながる(p26)
- VPCはリージョン全体をまたぐが、サブネットはそれぞれのアベイラビリティゾーンに属する。サブネットがアベイラビリティゾーンをまたぐことはない(p30)
- VPCに割り当てるIPアドレス範囲は、プライベートIPアドレスのネットワーク範囲のなかから任意のものを指定する(p31)
- VPCをインターネットに接続するときは、インターネットゲートウェイという一種のNATを構成することで、「プライベートIPアドレスに加えてパブリックIPアドレスを追加で割り当てる」という構成にする(p32)
- VPCのIPアドレス範囲は変更できない(p32)
- CIDER。数万台の端末は1つのネットワークに接続した運用はパフォーマンス・メンテナンス的に望ましくないので、普通はネットワークを小さい単位に分割する。なのでたとえば ~10.0.0.0/16~ より ~10.0.0.0/24~ のほうが一般的。 ~/24~ の場合は256個のサブネット、256個のIPアドレスになる(p34)
- それぞれのリージョンには契約者ごとにVPCが1つ作られている。この用意されているVPCはデフォルトのVPCと呼ばれていて、他のVPCと少し構成が異なる。デフォルトのVPCはすぐにインターネットに接続できるようにする目的に作られた特別なVPCである(p36)
- VPC > アベイラビリティゾーン > サブネット
- AWSのサブネット上ではDHCPサーバ機能が動作している。そのためサブネットにEC2インスタンスを設置して起動すると、そのDHCPサーバからENIに対してサブネットで利用可能なプライベートIPアドレスが動的に割り当てられる(p48)
- AWSにおけるパブリックIPアドレスは、NATによる運用がなされている。パブリックIPアドレスを割り当てたとしても、EC2インスタンスにはプライベートIPアドレスしか割り当てられない。そのかわりにNATでプライベートIPアドレスとパブリックIPアドレスを相互変換している(p78)
- メインのルートテーブルの初期状態は 送信先: ~10.0.0.0/16~ ターゲット: ~local~ である。なので、VPCで用いているネットワーク範囲のものはlocal(このネットワーク内)で処理されるが、それ以外はルートの登録がないのですべて破棄される。つまりインターネットに出ていけない。インターネットにつなぐにはルートテーブルを作成し、インターネットゲートウェイをデフォルトゲートウェイとする必要がある(p90)
- ルートテーブルで送信先: 0.0.0.0/0 ターゲット: インターネットゲートウェイとすることで、ほかのルート情報でターゲットの定まらないパケットは破棄されずにインターネットゲートウェイにルーティングされる。0.0.0.0は「すべての宛先」を表す特別なルート(p93)
- EC2のパブリックIPアドレスに対してpingコマンドを実行しても応答はない。デフォルトのセキュリティグループでICMP通信を遮断する設定になっているため(p96)
- AWSネットワーク上には ~169.254.169.254~ というIPアドレスが付けられた特別なサーバがある。アクセスしたEC2インスタンスに関するさまざまな情報を返すメタデータサーバである(p102)
- インスタンスにElastic IPアドレスを割り当てても、OSから見えるのはプライベートIPアドレスだけなのは変わらない(p112)
- ENIとセキュリティグループは多対多の関係である(p120)
- プライベートサブネットからインターネットに接続したいとき(p145)
  - NATゲートウェイをパブリックサブネットに配置する
  - プライベートサブネットのデフォルトゲートウェイをNATゲートウェイに向けるようにルートテーブルを編集する
- ポートフォワードの利点は、SSHの鍵を踏み台のサーバに置く必要がないので、鍵が盗まれるおそれがない点(p168)
- IPアドレスとホスト名を関連付けるには、ゾーンを作成してAレコードとして登録する。ELBなど、DNS名が登録されているものへの別名を設定するにはエイリアスとして設定する(p243)
- S3はパブリックIPで提供されているサービスなので、プライベートIP環境からは利用できない。パブリックIPが割り当てられていないとVPC外に出られないから(p265)

* 関連
# 関連するエントリ。なぜ関連させたか理由を書く。意味のあるつながりを意識的につくる。
# - この事実は自分のこのアイデアとどう整合するか。
# - この現象はあの理論でどう説明できるか。
# - ふたつのアイデアは互いに矛盾するか、互いを補っているか。
# - いま聞いた内容は以前に聞いたことがなかったか。
# - メモ y についてメモ x はどういう意味か。
# - 対立する
# - 修正する
# - 補足する
# - 付け加えるもの
# - アイデア同士を組み合わせて新しいものを生み出せないか
# - どんな疑問が浮かんだか
なし。
