:properties:
:ID: 20251206T184941
:end:
#+title:      KDOC 495: 文芸的にDB動作を検証できるようにする
#+date:       [2025-12-06 Sat 18:49]
#+filetags:   :draft:project:
#+identifier: 20251206T184941

#+begin_comment
(kd/denote-kdoc-rename)
(kd/denote-format)

====ポリシー。
1ファイル1アイデア。
1ファイルで内容を完結させる。
常にほかのエントリとリンクする。
自分の言葉を使う。
参考文献を残しておく。
文献メモの場合は、感想と混ぜないこと。1つのアイデアに反する
ツェッテルカステンの議論に寄与するか。それで本を書けと言われて書けるか
頭のなかやツェッテルカステンにある問いとどのようにかかわっているか
エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。
個人の感想・意思表明ではない。事実や書籍情報に基づいている

====永久保存メモのルール。
自分の言葉で書く。
後から読み返して理解できる。
他のメモと関連付ける。
ひとつのメモにひとつのことだけを書く。
メモの内容は1枚で完結させる。
論文の中に組み込み、公表できるレベルである。

====水準を満たす価値があるか。
その情報がどういった文脈で使えるか。
どの程度重要な情報か。
そのページのどこが本当に必要な部分なのか。
公表できるレベルの洞察を得られるか

====フロー。
1. 「走り書きメモ」「文献メモ」を書く
2. 1日1回既存のメモを見て、自分自身の研究、思考、興味にどのように関係してくるかを見る
3. 追加すべきものだけ追加する

#+end_comment

* この文書のステータス
- 作成
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))
- レビュー
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))

# チェックリスト ================
# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。

* 概要

文芸的にDB動作を検証できるようにした。

* 背景

[[https://syu-m-5151.hatenablog.com/entry/2025/11/25/135220][「Postgres で試した？」と聞き返せるようになるまでもしくはなぜ私は雰囲気で技術を語るのか？]]を読んで、データベースの機能について知らないことが多いのを知った。

コンピュータのほかの事柄と同様に、じっさいに試して、挙動を仔細にみて背景にあるアイデアを理解し、自分なりのモデルを構築していくのが必要に見えた。REPLでいじるだけでなく、体系立てて記録しつつ試していけるとよさそうである。

そういうことを気軽にできるようにした。

* 要件

- 少ない準備で気軽にデータベースを実行できる
- 文芸的プログラミングができる。入力と標準出力をテキストに残し、そのままドキュメント化できる
  - 入力クエリを出力にエコー表示できる
- 毎回クリーンな環境で、完全に再現できる
- org-mode org-babelの ~sql~ ブロックから直接使える
- 完全に同等の機能が使える。インデックス、EXPLAIN、トランザクション...が使える

* 使用例
:PROPERTIES:
  :header-args+: :results table
  :header-args+: :database postgres
  :header-args+: :dbhost localhost
  :header-args+: :dbport 15432
  :header-args+: :dbuser postgres
  :header-args+: :engine postgresql
:END:

リポジトリは[[https://github.com/kijimad/pgpg][kijimad/pgpg]]にある。

根本的なアイデアは、データベースのプロキシを実装し、フック処理を追加することである。プロキシで、実験に必要な処理(DB初期化と削除)を実行する。

#+caption: DBとプロキシを起動する
#+begin_src shell
  docker compose up -d
#+end_src

#+caption: org-modeの見出しやファイルヘッダに接続先情報を書く
#+begin_src org-mode
:PROPERTIES:
  :header-args+: :results table
  :header-args+: :database postgres
  :header-args+: :dbhost localhost
  :header-args+: :dbport 15432
  :header-args+: :dbuser postgres
  :header-args+: :engine postgresql
:END:
#+end_src

あとは、org-babelでSQLを実行して評価する。

#+begin_src sql
  select 1+1 as result;
#+end_src

#+RESULTS:
#+begin_src
|                         |
|-------------------------|
| > select 1+1 as result; |
| result                  |
| 2                       |
#+end_src

データベースは接続のたびにリセットされる。完全に再現可能で、あとで読みやすい。

#+caption: リセットされるので実行のたびに同じ結果が出る
#+begin_src sql
  CREATE TABLE users (
      name varchar(255),
      tel integer
  );
  INSERT INTO users (name, tel) VALUES ('きじま', 100);
  SELECT * FROM users;
#+end_src

#+RESULTS:
#+begin_src
|                                                         |     |
|---------------------------------------------------------+-----|
| > CREATE TABLE users (                                  |     |
| >     name varchar(255),                                |     |
| >     tel integer                                       |     |
| > );                                                    |     |
| CREATE TABLE                                            |     |
|                                                         |     |
| > INSERT INTO users (name, tel) VALUES ('きじま', 100); |     |
| INSERT 0 1                                              |     |
|                                                         |     |
| > SELECT * FROM users;                                  |     |
| name                                                    | tel |
| きじま                                                  | 100 |
#+end_src

* 関連
# 関連するエントリ。なぜ関連させたか理由を書く。意味のあるつながりを意識的につくる。
# - この事実は自分のこのアイデアとどう整合するか。
# - この現象はあの理論でどう説明できるか。
# - ふたつのアイデアは互いに矛盾するか、互いを補っているか。
# - いま聞いた内容は以前に聞いたことがなかったか。
# - メモ y についてメモ x はどういう意味か。
# - 対立する
# - 修正する
# - 補足する
# - 付け加えるもの
# - アイデア同士を組み合わせて新しいものを生み出せないか
# - どんな疑問が浮かんだか

- 動機: [[id:20240207T092747][KDOC 77: 検証する方法があると理解が進む]]。に基づいて作った
