:properties:
:ID: 20251129T082342
:end:
#+title:      KDOC 491: 『マイクロサービスアーキテクチャ』
#+date:       [2025-11-29 Sat 08:23]
#+filetags:   :draft:book:
#+identifier: 20251129T082342

#+begin_comment
(kd/denote-kdoc-rename)
(kd/denote-format)

====ポリシー。
1ファイル1アイデア。
1ファイルで内容を完結させる。
常にほかのエントリとリンクする。
自分の言葉を使う。
参考文献を残しておく。
文献メモの場合は、感想と混ぜないこと。1つのアイデアに反する
ツェッテルカステンの議論に寄与するか。それで本を書けと言われて書けるか
頭のなかやツェッテルカステンにある問いとどのようにかかわっているか
エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。
個人の感想・意思表明ではない。事実や書籍情報に基づいている

====永久保存メモのルール。
自分の言葉で書く。
後から読み返して理解できる。
他のメモと関連付ける。
ひとつのメモにひとつのことだけを書く。
メモの内容は1枚で完結させる。
論文の中に組み込み、公表できるレベルである。

====水準を満たす価値があるか。
その情報がどういった文脈で使えるか。
どの程度重要な情報か。
そのページのどこが本当に必要な部分なのか。
公表できるレベルの洞察を得られるか

====フロー。
1. 「走り書きメモ」「文献メモ」を書く
2. 1日1回既存のメモを見て、自分自身の研究、思考、興味にどのように関係してくるかを見る
3. 追加すべきものだけ追加する

#+end_comment

* この文書のステータス
:LOGBOOK:
CLOCK: [2025-12-21 Sun 09:43]--[2025-12-21 Sun 10:08] =>  0:25
CLOCK: [2025-11-29 Sat 15:52]--[2025-11-29 Sat 16:17] =>  0:25
:END:
- 作成
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))
- レビュー
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))

129ページで止まっている。[[https://mypdfs.a9ne.com/?file=20251129T003032--%E3%83%9E%E3%82%A4%E3%82%AF%E3%83%AD%E3%82%B5%E3%83%BC%E3%83%93%E3%82%B9%E3%82%A2%E3%83%BC%E3%82%AD%E3%83%86%E3%82%AF%E3%83%81%E3%83%A3.pdf&page=129&half=top][マイクロサービスアーキテクチャ - Theater]]。

# チェックリスト ================
# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。
* 概要
# 本文(見出しも設定する)
* メモ
- マイクロサービスはサービス指向アーキテクチャ(SOA)の一種である。サービス境界の引き方については意見が分かれるが、独立してデプロイできるのが重要である(p3)
- 独立デプロイ可能性を実現したい場合、データベースの共有は最悪なことの1つである(p9)
- システムのすべての機能をまとめてデプロイしなければならない場合、モノリス、だという(p15)
- モジュラモノリス: 各モジュールで独立して作業できるが、デプロイするにはすべてを結合する必要がある。多くの組織で優れた選択肢で、マイクロサービスアーキテクチャの課題を回避しながら高度な並列作業ができる(p17)
  - 課題の1つとして、コードレベルで行われるような分解が、データベースにおいては行われない傾向がある(p17)
  - モジュラごとに分解したデータベースを使うモジュラモノリスもある
- 人々はモノリスを避けるべきもの、本質的に問題があるもの、と考えるようになっている。モノリシックアーキテクチャは1つの選択肢であり有効である(p19)
- 100万行のモノリシックアプリケーションのうち1行を変更したら、その変更をリリースするためにアプリケーション全体をデプロイする必要があるようなデプロイは、影響が大きく危険性の高いものになる可能性がある(p26)
- 分散システムでは複数プロセスが異なるデータベースで状態を管理する。データ一貫性の観点で課題が発生する可能性がある(p33)
- 安定したサービス境界を定義することの重要性を考えると、マイクロサービスアーキテクチャは新製品やスタートアップにとって向いてないことが多い。開発するにつれて、作業するドメインが大きく変更されるのが一般的である。ドメインモデルがじゅうぶん安定するまで待ってからサービス境界を定義するほうが適切である(p33)
- 凝集を説明する簡潔な定義: 一緒に変更され、一緒に存在するコード(p40)
- 状態が正しく変更されるようにする1つの方法は有限状態機械を作成することだが、複数のマイクロサービスが状態機械を管理する責任を共有していると問題になる。単一のマイクロサービスが状態を管理するとよい(p51)
- データベースのCRUD操作の軽量ラッパーのようなマイクロサービスは低凝集、密結合の兆候である。そのサービスにあるべきデータを管理するロジックがシステムの別の場所に分散している(p51)
- マイクロサービス境界を探すためのメカニズムはドメイン自体を中心としたものであり、ドメイン駆動設計を利用してドメインモデルを作成する(p55)
  - (感想)ドメイン駆動設計がマイクロサービスのためのものなのを知った
  - ユビキタス言語: ユーザが使っているのと同じ用語をコード内でも使うように努めるべきであるという考え方。実世界のドメインのモデル化がより簡単になり、コミュニケーションも改善する、という考え方(55)
- アグリゲートの意味がわからない(p62)
  - アグリゲートはより幅広いシステムとの明確に定義されたインターフェースを備えた、凝集ユニットとなる。アグリゲートはシステム内の単一のドメイン概念に焦点を当てた自己完結型の状態機械である
- システムに実装する変更は多くの場合、ビジネス側がシステムの振る舞いに関して行いたい変更に関するものである。顧客に公開している機能を変更する(p65)
- ドメインの理解があいまいなままマイクロサービスを作成するのは危険である。最初からマイクロサービスを目指すよりも、マイクロサービスに分解したい既存のコードがあるほうがかんたんである(p78)
- 多くの企業が、バックエンド機能を分割する利点にだけ目を向け、過度にサイロ化したアーキテクチャ再構築を行っている(p80)

* 関連
# 関連するエントリ。なぜ関連させたか理由を書く。意味のあるつながりを意識的につくる。
# - この事実は自分のこのアイデアとどう整合するか。
# - この現象はあの理論でどう説明できるか。
# - ふたつのアイデアは互いに矛盾するか、互いを補っているか。
# - いま聞いた内容は以前に聞いたことがなかったか。
# - メモ y についてメモ x はどういう意味か。
# - 対立する
# - 修正する
# - 補足する
# - 付け加えるもの
# - アイデア同士を組み合わせて新しいものを生み出せないか
# - どんな疑問が浮かんだか
なし。
