:properties:
:ID: 20260114T085151
:end:
#+title:      KDOC 529: 状態を示すComponentはどう表現するのがよいか
#+date:       [2026-01-14 Wed 08:51]
#+filetags:   :draft:permanent:
#+identifier: 20260114T085151

#+begin_comment
(kd/denote-kdoc-rename)
(kd/denote-format)

====ポリシー。
1ファイル1アイデア。
1ファイルで内容を完結させる。
常にほかのエントリとリンクする。
自分の言葉を使う。
参考文献を残しておく。
文献メモの場合は、感想と混ぜないこと。1つのアイデアに反する
ツェッテルカステンの議論に寄与するか。それで本を書けと言われて書けるか
頭のなかやツェッテルカステンにある問いとどのようにかかわっているか
エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。
個人の感想・意思表明ではない。事実や書籍情報に基づいている

====永久保存メモのルール。
自分の言葉で書く。
後から読み返して理解できる。
他のメモと関連付ける。
ひとつのメモにひとつのことだけを書く。
メモの内容は1枚で完結させる。
論文の中に組み込み、公表できるレベルである。

====水準を満たす価値があるか。
その情報がどういった文脈で使えるか。
どの程度重要な情報か。
そのページのどこが本当に必要な部分なのか。
公表できるレベルの洞察を得られるか

====フロー。
1. 「走り書きメモ」「文献メモ」を書く
2. 1日1回既存のメモを見て、自分自身の研究、思考、興味にどのように関係してくるかを見る
3. 追加すべきものだけ追加する

#+end_comment

* この文書のステータス
- 作成
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))
- レビュー
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))

# チェックリスト ================
# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。
* 概要
# 本文(見出しも設定する)

ECS(Entity Component System)において、状態を示すコンポーネントをどのように設計するかを考える。

まず、その状態ごとにコンポーネントとするパターン。

#+begin_src go
  type Components struct {
  	ItemLocationInBackpack *ecs.Component
  	ItemLocationEquipped   *ecs.Component
  	ItemLocationOnField    *ecs.Component
  }
#+end_src

- バックパックのアイテム一覧を取得したいときは多くある。コンポーネントで直接クエリできるとわかりやすく、早い
- 必ずいずれか1つの状態になるケースで、不整合が起きる可能性がある。誤って矛盾した状態を付与してしまわないように、ヘルパーを通して変更するなどのルール化が必要になる

つぎに、1コンポーネントにいずれかの状態をするパターン。

#+begin_src go
  type Components struct {
  	ItemLocationType *ecs.Component
  }
#+end_src

- 状態遷移が明確で矛盾がない
- 状態でのクエリができない
- セーブ・ロードが複雑化する

つまりおおまかにいって、状態ごとにコンポーネントを作る方式は読み込みに有利で、いずれかの状態で1コンポーネントにする方式は書き込みに有利だといえる。アイテムの状態遷移はわりと頻繁にあるといっても、コードでは読み込みのほうがはるかに多いので、読み込みを重視したほうがいいように見える。

-----

結局セーブ・ロードがうまくできなかったので状態ごとにコンポーネントを作る方式にした。運用して考えていく。

* 関連
# 関連するエントリ。書いているファイルから見て、なぜ関連させたか書く。意味のあるつながりを意識的につくる。
# [引用、整合性、どう説明できるか、矛盾、補っているか、以前聞いたこと、対立、修正、補足、付け加え、組み合わせ、疑問]
# また、現在はリンクが見つからなくてもこういった切り口で将来関連させられそうな項目を書いておく
# [類推、未解決、具体例、追加調査、理由、動機、検証]
# 横に類推するか、上に抽象化するか、下に具体化するか

- 動機: [[id:20231128T074518][KDOC 59: ECSを使ってRPGを作る]]。で考えた
