:properties:
:ID: 20260505T151949
:end:
#+title:      KDOC 577: 『ナニワ金融道』
#+date:       [2026-05-05 Tue 15:19]
#+filetags:   :draft:book:
#+identifier: 20260505T151949

#+begin_comment
(kd/denote-kdoc-rename)
(kd/denote-format)

====ポリシー。
1ファイル1アイデア。
1ファイルで内容を完結させる。
常にほかのエントリとリンクする。
自分の言葉を使う。
参考文献を残しておく。
文献メモの場合は、感想と混ぜないこと。1つのアイデアに反する
ツェッテルカステンの議論に寄与するか。それで本を書けと言われて書けるか
頭のなかやツェッテルカステンにある問いとどのようにかかわっているか
エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。
個人の感想・意思表明ではない。事実や書籍情報に基づいている

====永久保存メモのルール。
自分の言葉で書く。
後から読み返して理解できる。
他のメモと関連付ける。
ひとつのメモにひとつのことだけを書く。
メモの内容は1枚で完結させる。
論文の中に組み込み、公表できるレベルである。

====水準を満たす価値があるか。
その情報がどういった文脈で使えるか。
どの程度重要な情報か。
そのページのどこが本当に必要な部分なのか。
公表できるレベルの洞察を得られるか

====フロー。
1. 「走り書きメモ」「文献メモ」を書く
2. 1日1回既存のメモを見て、自分自身の研究、思考、興味にどのように関係してくるかを見る
3. 追加すべきものだけ追加する

#+end_comment

* DONE この文書のステータス
CLOSED: [2026-05-09 Sat 23:28]
:LOGBOOK:
CLOCK: [2026-05-09 Sat 19:59]--[2026-05-09 Sat 20:24] =>  0:25
CLOCK: [2026-05-09 Sat 18:13]--[2026-05-09 Sat 18:38] =>  0:25
CLOCK: [2026-05-09 Sat 17:37]--[2026-05-09 Sat 18:02] =>  0:25
CLOCK: [2026-05-09 Sat 16:27]--[2026-05-09 Sat 16:52] =>  0:25
CLOCK: [2026-05-09 Sat 16:00]--[2026-05-09 Sat 16:25] =>  0:25
CLOCK: [2026-05-09 Sat 15:24]--[2026-05-09 Sat 15:49] =>  0:25
CLOCK: [2026-05-09 Sat 14:58]--[2026-05-09 Sat 15:23] =>  0:25
CLOCK: [2026-05-09 Sat 13:48]--[2026-05-09 Sat 14:13] =>  0:25
CLOCK: [2026-05-09 Sat 13:20]--[2026-05-09 Sat 13:45] =>  0:25
CLOCK: [2026-05-09 Sat 12:50]--[2026-05-09 Sat 13:15] =>  0:25
CLOCK: [2026-05-07 Thu 23:39]--[2026-05-08 Fri 00:04] =>  0:25
CLOCK: [2026-05-07 Thu 22:40]--[2026-05-07 Thu 23:05] =>  0:25
CLOCK: [2026-05-07 Thu 21:31]--[2026-05-07 Thu 21:56] =>  0:25
CLOCK: [2026-05-06 Wed 23:34]--[2026-05-06 Wed 23:59] =>  0:25
CLOCK: [2026-05-06 Wed 22:37]--[2026-05-06 Wed 23:02] =>  0:25
CLOCK: [2026-05-06 Wed 22:11]--[2026-05-06 Wed 22:36] =>  0:25
CLOCK: [2026-05-06 Wed 21:38]--[2026-05-06 Wed 22:03] =>  0:25
CLOCK: [2026-05-06 Wed 17:36]--[2026-05-06 Wed 18:01] =>  0:25
CLOCK: [2026-05-06 Wed 16:53]--[2026-05-06 Wed 17:18] =>  0:25
CLOCK: [2026-05-06 Wed 16:26]--[2026-05-06 Wed 16:51] =>  0:25
CLOCK: [2026-05-06 Wed 11:04]--[2026-05-06 Wed 11:29] =>  0:25
CLOCK: [2026-05-06 Wed 10:38]--[2026-05-06 Wed 11:03] =>  0:25
:END:
- 作成
  - [X] 2026-05-09 貴島
- レビュー
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))

# チェックリスト ================
# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。
* 概要
# 本文(見出しも設定する)

『ナニワ金融道』は、消費者金融会社を描いた漫画である。リアルな例で、お金について知らなければ危険だということがよくわかる。

* メモ

- 金融は良心を売って金を儲ける商売
- 市議
  - 公共工事で土建屋のキックバックして儲ける
  - 役所の人事に介入する
  - 公立学校の校長人事に介入する
- 票を金で買うために、地域のボスに現金を渡して末端に行き渡らせる
- 府会議員より市会議員のほうが儲かる。報酬や社会的地位は府会議員のほうが上だが、市会議員のほうが介入できるものが多い
- 便宜を図った業者を後援会にして会費をとる
- 病院を建てればその周辺は風俗営業禁止になる。また、ベッド1つでも病院になる
- 所有権、貸借権、抵当権
- 紹介もなく知らない人の懐に入り込むには家の前を掃除するのがいちばん
- 儲かっている話に対する返し -- 去年の税金はどれくらい払いましたか
- 官名と職名

* 関連
# 関連するエントリ。書いているファイルから見て、なぜ関連させたか書く。意味のあるつながりを意識的につくる。
# [引用、整合性、どう説明できるか、矛盾、補っているか、以前聞いたこと、対立、修正、補足、付け加え、組み合わせ、疑問]
# また、現在はリンクが見つからなくてもこういった切り口で将来関連させられそうな項目を書いておく
# [類推、未解決、具体例、追加調査、理由、動機、検証]
# 横に類推するか、上に抽象化するか、下に具体化するか

- 類推: [[id:20260426T102149][KDOC 573: 『ハイパーインフレーション』]]と[[id:20250427T175852][KDOC 350: 『正直不動産』]]。攻撃側からみた手口を物語形式で紹介することで、その分野についての興味を深めることができるシリーズ。自分で勉強して自衛していこうというモチベーションになる
