:properties:
:ID: 20260124T095842
:end:
#+title:      KDOC 536: なぜJavaScriptが難しく感じるか
#+date:       [2026-01-24 Sat 09:58]
#+filetags:   :draft:essay:
#+identifier: 20260124T095842

#+begin_comment
(kd/denote-kdoc-rename)
(kd/denote-format)

====ポリシー。
1ファイル1アイデア。
1ファイルで内容を完結させる。
常にほかのエントリとリンクする。
自分の言葉を使う。
参考文献を残しておく。
文献メモの場合は、感想と混ぜないこと。1つのアイデアに反する
ツェッテルカステンの議論に寄与するか。それで本を書けと言われて書けるか
頭のなかやツェッテルカステンにある問いとどのようにかかわっているか
エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。
個人の感想・意思表明ではない。事実や書籍情報に基づいている

====永久保存メモのルール。
自分の言葉で書く。
後から読み返して理解できる。
他のメモと関連付ける。
ひとつのメモにひとつのことだけを書く。
メモの内容は1枚で完結させる。
論文の中に組み込み、公表できるレベルである。

====水準を満たす価値があるか。
その情報がどういった文脈で使えるか。
どの程度重要な情報か。
そのページのどこが本当に必要な部分なのか。
公表できるレベルの洞察を得られるか

====フロー。
1. 「走り書きメモ」「文献メモ」を書く
2. 1日1回既存のメモを見て、自分自身の研究、思考、興味にどのように関係してくるかを見る
3. 追加すべきものだけ追加する

#+end_comment

* この文書のステータス
- 作成
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))
- レビュー
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))

# チェックリスト ================
# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。
* 概要
# 本文(見出しも設定する)

これは向き合って学ぶ前の感想である。未来この気持ちがわからなくなると信じたい。

何が妨げているか明らかにすれば対応もできると考えている。さまざまな感覚の集合からくる「難しい」であって、「難易度が高い」とは異なる可能性もある。ほとんど印象のケースに見える。難易度が高い、にかかるほど熟達はしていない。

プロ登山家が「山登りは難しい」というのと、山に登ったことのない人が「山登りは難しい」というのは全然違う。プロは特定のケースや具体的な知識を思い浮かべているが、そうでない人は漠然とした知識のなさから「難しい」といっている。あまりに知らないことが多いと、難しい、と雑に判断するようになっているようである。

職業人生のなかで、常に2割くらいはJavaScriptを触れてきた。プライベートでもJavaScriptを使っていくつか作ったことがある。の割には親しみのない感覚がある。わからずにそのまま使ってきた感覚が強い。

- 使うまでの設定、エコシステムが多い。拡張文法、モジュールシステム、トランスパイルターゲット、...。他言語だと選択する機会のないものも、多く選択肢がある。目に入るたびに圧倒されて、「難しい」と感じる
- 関数型

ほかの物事と同じく、背後にある概念をつかめば、一気に理解や親しみが増えると信じている。

* 関連
# 関連するエントリ。書いているファイルから見て、なぜ関連させたか書く。意味のあるつながりを意識的につくる。
# [引用、整合性、どう説明できるか、矛盾、補っているか、以前聞いたこと、対立、修正、補足、付け加え、組み合わせ、疑問]
# また、現在はリンクが見つからなくてもこういった切り口で将来関連させられそうな項目を書いておく
# [類推、未解決、具体例、追加調査、理由、動機、検証]
# 横に類推するか、上に抽象化するか、下に具体化するか

なし。
