:properties:
:ID: 20260121T094643
:end:
#+title:      KDOC 534: 『不動産投資1年目の教科書』
#+date:       [2026-01-21 Wed 09:46]
#+filetags:   :draft:book:
#+identifier: 20260121T094643

#+begin_comment
(kd/denote-kdoc-rename)
(kd/denote-format)

====ポリシー。
1ファイル1アイデア。
1ファイルで内容を完結させる。
常にほかのエントリとリンクする。
自分の言葉を使う。
参考文献を残しておく。
文献メモの場合は、感想と混ぜないこと。1つのアイデアに反する
ツェッテルカステンの議論に寄与するか。それで本を書けと言われて書けるか
頭のなかやツェッテルカステンにある問いとどのようにかかわっているか
エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。
個人の感想・意思表明ではない。事実や書籍情報に基づいている

====永久保存メモのルール。
自分の言葉で書く。
後から読み返して理解できる。
他のメモと関連付ける。
ひとつのメモにひとつのことだけを書く。
メモの内容は1枚で完結させる。
論文の中に組み込み、公表できるレベルである。

====水準を満たす価値があるか。
その情報がどういった文脈で使えるか。
どの程度重要な情報か。
そのページのどこが本当に必要な部分なのか。
公表できるレベルの洞察を得られるか

====フロー。
1. 「走り書きメモ」「文献メモ」を書く
2. 1日1回既存のメモを見て、自分自身の研究、思考、興味にどのように関係してくるかを見る
3. 追加すべきものだけ追加する

#+end_comment

* この文書のステータス
- 作成
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))
- レビュー
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))

# チェックリスト ================
# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。
* 概要
# 本文(見出しも設定する)

『不動産投資1年目の教科書』は、不動産投資についてQ&A形式で説明する本。
* メモ

- 期待で上昇して事実で売られる株式とは違い、不動産は事実確定後にはじめて価格上昇に転じるという特徴がある。タイムラグがある(位置510)
- 不動産価格は人口動態やGDP、賃貸需要など実需的な指標に連動していない。たとえば80年代のバブル、00年代のITバブル、2007年のファンドバブルのとき、人口は増えておらず、賃貸需要も物件価格の急上昇を説明できるほど増えていない。不動産価格の動きにもっとも寄与率の高い指標は世界経済の大波、金融機関の融資姿勢である(位置630)
- 不動産ファンドが投資を考えるときには次のように投資対象を分類する(位置728)
  - コア型投資 :: 賃貸収入を主な目的とする不動産投資。低利回りだが一等地で安定しており低リスク
  - コアプラス型投資 :: 賃貸収入と値上がり益の両方をバランスよく狙う。都心だが2等地
  - バリューアデッド型投資 :: 割安物件に付加価値をつけて賃貸や転売する
  - オポチュニスティック型投資 :: 競売などの訳あり物件
- 景気のいい時期には売却を想定する戦略の不動産投資において、勝負は「何を買うか」よりも「いつ買うか」で決まる(位置798)
- 高松市は地方のなかでも特殊な街で、不動産市場も珍しい価格形成がされているため価格が読めない。無制限にどの場所にも建物が建てられる(位置895)
- 高利回りの地方物件は理想どおりに運用できれば都心の物件よりも収益率は高いものの、入居率が修繕費用、売却価格が予測しにくいため収益の振れ幅が大きいといえる。それをコントロールするのはオーナーの経営能力、運である(位置945)
- 売却時の融資付けができない物件は価格を下げても売れない(位置1014)
- リスクの高い地方物件に高額なローンがつくことがある。根拠となっているのは固定資産税評価額をもとにした積算評価という評価システムである。時価とは大幅に乖離した評価方法であり、実態を反映していない(位置1014)
- 最初に区分を買うやつは最後まで区分(位置1067)
- 規模を拡大していきたい人は、土地が広い/固定資産税評価額が高い/築年が古すぎない/場所がよいなど、銀行評価の高いスタンダードな物件を買い進めていくべき(位置1091)
- 小粒な物件を賃貸目的で保有するのは固定費がかさみ、いいことがない(位置1208)
- なぜアルバイトでなく社員に営業電話をかけさせるのかというと、残業代が出ないため時給換算するとアルバイトよりも安価であるため。また、雇用助成金がもらえることもある(位置1232)
  - (感想)残業代が出ないというのはどういうことか。保険料とか差し引いても安いんだろうか
- 不動産投資はある程度の規模がないと収支の振れ幅が大きくなる。「小さな物件からとりあえず」という方法はじつは大型物件よりもリスク(収支のぶれ)が大きく、投資規模は大きいほうが安定している(位置1254)
- 木造には減価償却が早くとれる、固定資産税が安い、という税務上のメリットがある。RCと木造を同じ築20年、同じ床面積で比較すると、RCは木造よりも約4倍ほど建物にかかる税額が高い。しかし都心では建物評価額3に対して土地評価額7の割合が基本であり、投資全体から見ればそれほど大きなウェイトを占めるわけではない(位置1276)
- 建売では、土地の真ん中に位置指定道路という4メートル道路を新たにつくって、それに接道するように戸建てを建てる。建売業者は有効宅地といってじっさいに家が建てられる面積しか金を払わない(位置1377)
- どんなに印象が悪い物件でも安く手に入れば優良物件である。現場を見に行ったなら採算ラインを考えて指値はしてみるべき(位置1402)
- お金をかければ解決できる問題とそれ以外に切り分けることは重要である。お金では解決できない例: 近隣の雰囲気が悪い、間取りや賃料が地域の需要とあっていない、設計図面や検査証がない、違法建築(位置1402)
- 境界確定はお金に換算できる問題なので、境界確定をしてない物件は買わないほうがいい理由はない(位置1451)
- 不動産投資をする最大唯一の理由は金融機関からの融資が受けられること。他人から低利で借りた資金で賃料利回りを得られ、借りてしまえば返済を迫られることもない。キャッシュで不動産を買っても利益は出ない(位置1802)
- 固定金利による借入では、早期返済に違約金が発生するのが一般的である。そのため9割以上の投資家は変動金利を選択しており、固定金利への変更を検討している人は少ない(位置1924)
- 現実的には資金を増やす唯一のタイミングは高値売却による利益確定のときだけ(位置2000)
- 中途半端な規模で場所を分散して地方物件を購入すると東京の金融機関では保有物件の調査不可となり、それ以上のローンが出ないことがある(位置2076)
- 不動産投資の経費でもっとも多くかかるのは税金。なので必ず税引き後で試算しなければならない(位置2238)
- ファンドの人たちは投資対象を見るときはIRRという統一指標を用いて収益を判断する。IRRの最大のメリットはさまざまな投資対象を同一の尺度で比較して優劣を判断すること(位置2296)
- 推奨する損益分岐点の考え方: 買ってから売るまでのキャッシュフロー総額がゼロになる売却価格こそが損益分岐点。つまりキャッシュフロー+売却価格=0(位置2444)
- 売却時は保有期間中に使った減価償却額の総額を購入価格から差し引いた額を取得原価とみなす。つまり減価償却で取得原価が高くなる。つまり売却益が高くなり、税金もそのぶん高くなる(位置2466)
- 江戸の昔から4公6民の分配は変わっていない(位置2560)
- 「不動産の節税効果」は誇大広告に近いセールストークである。購入すると税金の総額は確実に増える(位置2625)
- 世界の要人たちは、自分の子どもには「借金をしたら貿易黒字と増税で返せ」といいながら、自分たちは紙幣を印刷して金融政策で借金を返済している(位置2701)
- 高成長の国はインフレ率も金利も高い。低成長の国でもインフレ率を下回る収益率低下と通貨価値の下落がない限り、将来的に少子化やGDP低下で国力が弱まっても、賃料収入を頼りにした生活の水準は変わらない可能性が高い。本業の給与も、リストラされない限り、生活必需品の価格下落よりも自分の給料の下落幅が大きくない限り、生活実感は変わらない(位置2805)
- 地震保険の制度趣旨は、損壊した建物の再調達資金を確保するためではなく、生活再建のために当面必要となる資金を確保することである(位置2934)

* 関連
# 関連するエントリ。書いているファイルから見て、なぜ関連させたか書く。意味のあるつながりを意識的につくる。
# [引用、整合性、どう説明できるか、矛盾、補っているか、以前聞いたこと、対立、修正、補足、付け加え、組み合わせ、疑問]
# また、現在はリンクが見つからなくてもこういった切り口で将来関連させられそうな項目を書いておく
# [類推、未解決、具体例、追加調査、理由、動機、検証]
# 横に類推するか、上に抽象化するか、下に具体化するか

なし。
