:properties:
:ID: 20260517T014342
:end:
#+title:      KDOC 586: 『ミナミの帝王』
#+date:       [2026-05-17 Sun 01:43]
#+filetags:   :draft:book:
#+identifier: 20260517T014342

#+begin_comment
(kd/denote-kdoc-rename)
(kd/denote-format)

====ポリシー。
1ファイル1アイデア。
1ファイルで内容を完結させる。
常にほかのエントリとリンクする。
自分の言葉を使う。
参考文献を残しておく。
文献メモの場合は、感想と混ぜないこと。1つのアイデアに反する
ツェッテルカステンの議論に寄与するか。それで本を書けと言われて書けるか
頭のなかやツェッテルカステンにある問いとどのようにかかわっているか
エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。
個人の感想・意思表明ではない。事実や書籍情報に基づいている

====永久保存メモのルール。
自分の言葉で書く。
後から読み返して理解できる。
他のメモと関連付ける。
ひとつのメモにひとつのことだけを書く。
メモの内容は1枚で完結させる。
論文の中に組み込み、公表できるレベルである。

====水準を満たす価値があるか。
その情報がどういった文脈で使えるか。
どの程度重要な情報か。
そのページのどこが本当に必要な部分なのか。
公表できるレベルの洞察を得られるか

====フロー。
1. 「走り書きメモ」「文献メモ」を書く
2. 1日1回既存のメモを見て、自分自身の研究、思考、興味にどのように関係してくるかを見る
3. 追加すべきものだけ追加する

#+end_comment

* TODO この文書のステータス
:LOGBOOK:
CLOCK: [2026-05-28 Thu 00:32]--[2026-05-28 Thu 00:57] =>  0:25
CLOCK: [2026-05-24 Sun 00:07]--[2026-05-24 Sun 00:32] =>  0:25
CLOCK: [2026-05-23 Sat 23:11]--[2026-05-23 Sat 23:36] =>  0:25
CLOCK: [2026-05-21 Thu 23:33]--[2026-05-21 Thu 23:58] =>  0:25
CLOCK: [2026-05-20 Wed 22:36]--[2026-05-20 Wed 23:02] =>  0:26
CLOCK: [2026-05-20 Wed 22:06]--[2026-05-20 Wed 22:31] =>  0:25
CLOCK: [2026-05-20 Wed 00:31]--[2026-05-20 Wed 00:56] =>  0:25
CLOCK: [2026-05-19 Tue 22:46]--[2026-05-19 Tue 23:11] =>  0:25
CLOCK: [2026-05-19 Tue 22:15]--[2026-05-19 Tue 22:40] =>  0:25
CLOCK: [2026-05-18 Mon 21:28]--[2026-05-18 Mon 21:53] =>  0:25
CLOCK: [2026-05-18 Mon 20:58]--[2026-05-18 Mon 21:23] =>  0:25
CLOCK: [2026-05-17 Sun 23:05]--[2026-05-17 Sun 23:30] =>  0:25
CLOCK: [2026-05-17 Sun 22:11]--[2026-05-17 Sun 22:36] =>  0:25
CLOCK: [2026-05-17 Sun 21:43]--[2026-05-17 Sun 22:08] =>  0:25
CLOCK: [2026-05-17 Sun 20:38]--[2026-05-17 Sun 21:03] =>  0:25
CLOCK: [2026-05-17 Sun 18:56]--[2026-05-17 Sun 19:21] =>  0:25
CLOCK: [2026-05-17 Sun 18:31]--[2026-05-17 Sun 18:56] =>  0:25
CLOCK: [2026-05-17 Sun 16:48]--[2026-05-17 Sun 17:13] =>  0:25
CLOCK: [2026-05-17 Sun 15:56]--[2026-05-17 Sun 16:21] =>  0:25
CLOCK: [2026-05-17 Sun 01:43]--[2026-05-17 Sun 02:08] =>  0:25
:END:
- 作成
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))
- レビュー
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))

# チェックリスト ================
# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。
* 概要
:LOGBOOK:
CLOCK: [2026-05-26 Tue 20:56]--[2026-05-26 Tue 21:21] =>  0:25
CLOCK: [2026-05-26 Tue 09:40]--[2026-05-26 Tue 10:05] =>  0:25
CLOCK: [2026-05-26 Tue 00:22]--[2026-05-26 Tue 00:47] =>  0:25
CLOCK: [2026-05-25 Mon 23:56]--[2026-05-26 Tue 00:21] =>  0:25
CLOCK: [2026-05-25 Mon 22:27]--[2026-05-25 Mon 22:52] =>  0:25
CLOCK: [2026-05-25 Mon 21:38]--[2026-05-25 Mon 22:03] =>  0:25
CLOCK: [2026-05-25 Mon 09:21]--[2026-05-25 Mon 09:46] =>  0:25
CLOCK: [2026-05-24 Sun 23:32]--[2026-05-24 Sun 23:57] =>  0:25
CLOCK: [2026-05-24 Sun 21:27]--[2026-05-24 Sun 21:52] =>  0:25
CLOCK: [2026-05-24 Sun 20:42]--[2026-05-24 Sun 21:07] =>  0:25
CLOCK: [2026-05-24 Sun 18:42]--[2026-05-24 Sun 19:07] =>  0:25
CLOCK: [2026-05-24 Sun 16:36]--[2026-05-24 Sun 17:01] =>  0:25
CLOCK: [2026-05-24 Sun 10:00]--[2026-05-24 Sun 10:25] =>  0:25
CLOCK: [2026-05-24 Sun 09:28]--[2026-05-24 Sun 09:53] =>  0:25
:END:
# 本文(見出しも設定する)

『ミナミの帝王』は、高金利の金融業を描いた漫画である。

* メモ

- 捨て印を押すというのは白紙に印鑑を押すというのと同じことで、あとから何を書かれても文句は言われない
- 銀行は必ずしも土地の評価に合った金額を抵当権として設定するとは限らない。二束三文の土地であっても、取引する会社に信用があれば貸す
- 返済期限を定めてない借金は貸した側がいつでも返済を請求できる
- 契約を白紙に戻せるかは契約書の内容による。「仮」とついていても白紙に戻せない
- 窃盗罪かを問う場合には所有権が誰にあるかはあまり関係ない。窃盗罪は「他人の占有」を奪うことにある
- 遺産の「放棄」も「限定承認」も3ヶ月以内にしないと「自然承認」となる。遺産も負債も引き継ぐ
- 不動産屋のイロハ
  1. 悪い物件を見せる
  2. 最悪の物件を見せる
  3. 普通の物件を見せる -> 普通の物件でもよく見える
- バブルでバンバン貸したのは担保の土地の値段が上がっていたから
- 生命保険会社の店舗が利便性の低い3階にあるのは、客に会社に来てほしくないから。自分から生命保険に入りたいと訪ねてくる客には魂胆があると考える。店頭では生命保険の加入は断っているところもある
  - 必要のなさそうな人に売るのが生命保険セールスレディの仕事
- 生保レディの、本来対象ではない人にもハックで売って成績を上げる方法
- 会社名と肩書きが入っていれば会社名義となる。会社の場合は民法ではなく商法が適用される。商法は民法に優先して適用される
  - 会社の借金の保証人は借り主に返済を求めないでいきなり保証人に借金の返済を請求してきたときでも応じなければならない
  - 借り主にじゅうぶんな財産があるのに貸し主がいきなり保証人の財産を差し押さえてもいっさい文句はいえない
- スーパーで20円や30円の値段の差には敏感なのに買い物が何千万という金額になるととたんに思考能力が低下する
- 消費者の保護よりも営業の自由を優先するのがこの国の方針
- 日本は民主国家であって、大衆が1番強い。建前でなく、大衆が動かないだけ。数を集めて公的機関やマスコミに駆け込んで声を大きくする。声が大きくなれば事件化して警察が動く
- 銀行用語でリスケジュール、リスケという
- 本店を移転している場合、商業登記簿は何も教えてくれない。前の登記地で行ってきた資本金の増減や役員などすべての記録が抹消されるから
- 自分の名で稼いだ金は自分のものであり、生活費として家庭に入れた時点でその金は夫婦の共有財産となる

* 関連
# 関連するエントリ。書いているファイルから見て、なぜ関連させたか書く。意味のあるつながりを意識的につくる。
# [引用、整合性、どう説明できるか、矛盾、補っているか、以前聞いたこと、対立、修正、補足、付け加え、組み合わせ、疑問]
# また、現在はリンクが見つからなくてもこういった切り口で将来関連させられそうな項目を書いておく
# [類推、未解決、具体例、追加調査、理由、動機、検証]
# 横に類推するか、上に抽象化するか、下に具体化するか

なし。
