:properties:
:ID: 20260110T194239
:end:
#+title:      KDOC 523: PTRレコードを見る
#+date:       [2026-01-10 Sat 19:42]
#+filetags:   :draft:permanent:
#+identifier: 20260110T194239

#+begin_comment
(kd/denote-kdoc-rename)
(kd/denote-format)

====ポリシー。
1ファイル1アイデア。
1ファイルで内容を完結させる。
常にほかのエントリとリンクする。
自分の言葉を使う。
参考文献を残しておく。
文献メモの場合は、感想と混ぜないこと。1つのアイデアに反する
ツェッテルカステンの議論に寄与するか。それで本を書けと言われて書けるか
頭のなかやツェッテルカステンにある問いとどのようにかかわっているか
エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。
個人の感想・意思表明ではない。事実や書籍情報に基づいている

====永久保存メモのルール。
自分の言葉で書く。
後から読み返して理解できる。
他のメモと関連付ける。
ひとつのメモにひとつのことだけを書く。
メモの内容は1枚で完結させる。
論文の中に組み込み、公表できるレベルである。

====水準を満たす価値があるか。
その情報がどういった文脈で使えるか。
どの程度重要な情報か。
そのページのどこが本当に必要な部分なのか。
公表できるレベルの洞察を得られるか

====フロー。
1. 「走り書きメモ」「文献メモ」を書く
2. 1日1回既存のメモを見て、自分自身の研究、思考、興味にどのように関係してくるかを見る
3. 追加すべきものだけ追加する

#+end_comment

* この文書のステータス
- 作成
  - [X] 2026-01-10 貴島
- レビュー
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))

# チェックリスト ================
# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。
* 概要
# 本文(見出しも設定する)

DNSのPTRレコードはIPアドレスからドメイン名の逆引きに使う。逆引きすることでメールの送信元が正当かを判断したりするのだという。

#+begin_quote
DNSのAレコードは与えられたドメイン名の下に格納されますが、DNSのPTRレコードはIPアドレスの下に格納されます — 反転して、「.in-addr.arpa」が追加されます。たとえば、IPアドレス192.0.2.255のPTRレコードは、「255.2.0.192.in-addr.arpa」の下に格納されます。

[[https://www.cloudflare.com/ja-jp/learning/dns/dns-records/dns-ptr-record/][DNS PTRレコードとは？ | Cloudflare]]
#+end_quote

#+caption: -x は逆引き形式に変換する
#+begin_src shell
dig -x 8.8.8.8
#+end_src

#+RESULTS:
#+begin_src

; <<>> DiG 9.18.30-0ubuntu0.24.04.1-Ubuntu <<>> -x 8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 60423
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;8.8.8.8.in-addr.arpa.		IN	PTR

;; ANSWER SECTION:
8.8.8.8.in-addr.arpa.	5273	IN	PTR	dns.google. 👈

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Sat Jan 10 20:14:24 JST 2026
;; MSG SIZE  rcvd: 73

#+end_src

#+caption: オプションの説明
#+begin_src shell
  dig -h | grep "\-x"
#+end_src

#+RESULTS:
#+begin_src
                 -x dot-notation     (shortcut for reverse lookups)
                 -x dot-notation     (shortcut for reverse lookups)
                 +[no]identify       (ID responders in short answers)
                 +[no]short          (Display nothing except short
#+end_src

#+caption: -x オプションを使わずに同じ意味で書く
#+begin_src shell
  dig PTR 8.8.8.8.in-addr.arpa.
#+end_src

#+RESULTS:
#+begin_src

; <<>> DiG 9.18.30-0ubuntu0.24.04.1-Ubuntu <<>> PTR 8.8.8.8.in-addr.arpa.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24668
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;8.8.8.8.in-addr.arpa.		IN	PTR

;; ANSWER SECTION:
8.8.8.8.in-addr.arpa.	6739	IN	PTR	dns.google. 👈

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Sat Jan 10 19:49:58 JST 2026
;; MSG SIZE  rcvd: 73

#+end_src

* 関連
# 関連するエントリ。書いているファイルから見て、なぜ関連させたか書く。意味のあるつながりを意識的につくる。
# [引用、整合性、どう説明できるか、矛盾、補っているか、以前聞いたこと、対立、修正、補足、付け加え、組み合わせ、疑問]
# また、現在はリンクが見つからなくてもこういった切り口で将来関連させられそうな項目を書いておく
# [類推、未解決、具体例、追加調査、理由、動機、検証]
# 横に類推するか、上に抽象化するか、下に具体化するか

- 追加調査: PTRレコードはどうやって追加するのか
- 追加調査: IPアドレスの所有はどうやって決まっているのか
- 追加調査: in-addr.arpaはどうなっているのか。通常のドメインとは違うのか
