:properties:
:ID: 20260505T111446
:end:
#+title:      KDOC 576: 『ザ・ゴール』
#+date:       [2026-05-05 Tue 11:14]
#+filetags:   :draft:book:
#+identifier: 20260505T111446

#+begin_comment
(kd/denote-kdoc-rename)
(kd/denote-format)

====ポリシー。
1ファイル1アイデア。
1ファイルで内容を完結させる。
常にほかのエントリとリンクする。
自分の言葉を使う。
参考文献を残しておく。
文献メモの場合は、感想と混ぜないこと。1つのアイデアに反する
ツェッテルカステンの議論に寄与するか。それで本を書けと言われて書けるか
頭のなかやツェッテルカステンにある問いとどのようにかかわっているか
エントリ間の接続を発見したら、接続エントリを追加する。カード間にあるリンクの関係を説明するカード。
アイデアがまとまったらアウトラインエントリを作成する。リンクをまとめたエントリ。
エントリを削除しない。古いカードのどこが悪いかを説明する新しいカードへのリンクを追加する。
恐れずにカードを追加する。無意味の可能性があっても追加しておくことが重要。
個人の感想・意思表明ではない。事実や書籍情報に基づいている

====永久保存メモのルール。
自分の言葉で書く。
後から読み返して理解できる。
他のメモと関連付ける。
ひとつのメモにひとつのことだけを書く。
メモの内容は1枚で完結させる。
論文の中に組み込み、公表できるレベルである。

====水準を満たす価値があるか。
その情報がどういった文脈で使えるか。
どの程度重要な情報か。
そのページのどこが本当に必要な部分なのか。
公表できるレベルの洞察を得られるか

====フロー。
1. 「走り書きメモ」「文献メモ」を書く
2. 1日1回既存のメモを見て、自分自身の研究、思考、興味にどのように関係してくるかを見る
3. 追加すべきものだけ追加する

#+end_comment

* DONE この文書のステータス
CLOSED: [2026-05-09 Sat 23:27]
:LOGBOOK:
CLOCK: [2026-05-09 Sat 20:34]--[2026-05-09 Sat 20:59] =>  0:25
CLOCK: [2026-05-05 Tue 20:34]--[2026-05-05 Tue 20:59] =>  0:25
CLOCK: [2026-05-05 Tue 19:29]--[2026-05-05 Tue 19:54] =>  0:25
CLOCK: [2026-05-05 Tue 18:40]--[2026-05-05 Tue 19:05] =>  0:25
CLOCK: [2026-05-05 Tue 17:51]--[2026-05-05 Tue 18:16] =>  0:25
CLOCK: [2026-05-05 Tue 17:20]--[2026-05-05 Tue 17:45] =>  0:25
CLOCK: [2026-05-05 Tue 16:49]--[2026-05-05 Tue 17:14] =>  0:25
CLOCK: [2026-05-05 Tue 16:22]--[2026-05-05 Tue 16:47] =>  0:25
CLOCK: [2026-05-05 Tue 14:11]--[2026-05-05 Tue 14:36] =>  0:25
CLOCK: [2026-05-05 Tue 13:42]--[2026-05-05 Tue 14:08] =>  0:26
CLOCK: [2026-05-05 Tue 13:17]--[2026-05-05 Tue 13:42] =>  0:25
CLOCK: [2026-05-05 Tue 12:52]--[2026-05-05 Tue 13:17] =>  0:25
CLOCK: [2026-05-05 Tue 12:26]--[2026-05-05 Tue 12:51] =>  0:25
CLOCK: [2026-05-05 Tue 11:14]--[2026-05-05 Tue 11:39] =>  0:25
:END:
- 作成
  - [X] 2026-05-09 貴島
- レビュー
  - [ ] <署名>
# (progn (kill-line -1) (insert (format "  - [X] %s 貴島" (format-time-string "%Y-%m-%d"))))

# チェックリスト ================
# 関連をつけた。
# タイトルがフォーマット通りにつけられている。
# 内容をブラウザに表示して読んだ(作成とレビューのチェックは同時にしない)。
# 文脈なく読めるのを確認した。
# おばあちゃんに説明できる。
# いらない見出しを削除した。
# タグを適切にした。
# すべてのコメントを削除した。
* 概要
# 本文(見出しも設定する)

『ザ・ゴール』は、工場の生産管理の手法について、物語形式で説明する本である。

* メモ

- 生産的であるということは、自己の目標と照らし合わせて何かを達成したということである(p58)
  - 感想: ビジネスの目的は利益を得ることであるから、間違ったものを作ったら生産的ではない
- 生産性は目標がはっきりわかっていなければまったく意味をもたない(p58)
- 純利益、投資収益率、キャッシュフローの3つを同時に増やすことで金を儲ける(p85)
- スループットとは、販売を通じてお金を作り出す割合のこと(p102)
- 在庫とは、販売しようとするモノを購入するために投入したすべてのお金のこととする。会計の意味とは異なる(p103)
- 業務費用とは、在庫をスループットに変えるために費やすお金のこと(p103)
- 失ったお金はすべて業務費用で、売れる投資はすべて在庫になる(p126)
- バランスをとらないといけないのは生産能力ではなくフロー(p233)
- ボトルネックを通過するフローを市場からの需要に合わせる(p233)
- ボトルネックがある場合、工場の能力はボトルネックの能力に等しい。だからボトルネックで1時間無駄にすると工場全体で1時間無駄になる(p264)
- すぐに売れる見込みのないものを作って在庫を溜め込むことは、将来入ってくるお金のためにいまあるお金を犠牲にしていることになる(p266)
- 非ボトルネックを単純に最大限まで働かせることは愚の骨頂である。工場内のすべてのリソースの能力を個別に最大化してはならない。個別の最大化は全体的にはまったく最適なシステムではない(p345)
- 資材が工場を通過する時間は4つに分けられる(p377)
  - セットアップ
  - プロセスタイム
  - キュータイム
  - ウエイトタイム
- 何も考えずに習慣どおりにしかできない人を説得するのに、答えをただ教えても非効率である(p435)
- 科学のアプローチ。最初にあまりデータの収集はせず、ランダムに事実を取り上げる。それか仮説を立てる。「もし〜ならば、〜になる」という考え方をする。物語の関連性を考える、がすべての基本である(p517)
- 目先の状況の改善策だけで満足するだけでなく、何をすべきか慎重に選んで、それに努力を集中させなければならない(p536)
- マネージャーとして求められる3つの能力(p549)
  - 何を変える
  - 何に変える
  - どうやって変える
- 従来の会計システムは、工場全体の生産量がボトルネックの生産能力以上にできないということを想定してない(p579)

* 関連
# 関連するエントリ。書いているファイルから見て、なぜ関連させたか書く。意味のあるつながりを意識的につくる。
# [引用、整合性、どう説明できるか、矛盾、補っているか、以前聞いたこと、対立、修正、補足、付け加え、組み合わせ、疑問]
# また、現在はリンクが見つからなくてもこういった切り口で将来関連させられそうな項目を書いておく
# [類推、未解決、具体例、追加調査、理由、動機、検証]
# 横に類推するか、上に抽象化するか、下に具体化するか

- 類推: 工場以外にもこの考え方は適用できるか
- 追加調査: 従来の会計システムの正しさの根拠はどこにあるか。会計が第一義とすることは何か。逆に向いてない分野はあるか
- 類推: Factorioなどの、工場系ゲームの副読本として役に立つだろう
