version: '3.7'

services:
  build:
    image: ghcr.io/kijimad/roam:40837b0a
    build:
      context: .
      target: build
    volumes:
      - .:/roam
  dev:
    build:
      context: .
      target: dev
    volumes:
      - .:/roam
