version: '3.7'

services:
  build:
    image: ghcr.io/kijimad/roam:397cbf75
    build:
      context: .
      target: build
    volumes:
      - .:/roam
  lint:
    build:
      context: .
      target: lint
    volumes:
      - .:/roam
      - /roam/node_modules
