version: '3.7'

services:
  build:
    image: ghcr.io/kijimad/roam:3b14be0
    build:
      context: .
      target: build
    volumes:
      - .:/roam
  # dev:
  #   build:
  #     context: .
  #     target: dev
  #   volumes:
  #     - .:/roam
