services:
  roam-server:
    image: docker.io/nginx:1.27
    container_name: roam-server
    volumes:
      - ./public:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
    ports:
      - "8005:80"
    restart: always
    labels:
      description: "メモ"
