#+title:      仕事場
#+date:       [2022-10-27 Thu 23:48]
#+filetags:   :essay:
#+identifier: 20221027T234844

成した仕事の大きさと、仕事場は無関係なようだ。

最近YouTubeでRedHatの開発者のPCまわりを紹介している動画を見た。多くの開発者は質素なものだった。乱雑な人、片付いている人は半々くらい。1枚のディスプレイを使う開発者が半分で、残りは複数のディスプレイを使う。自分の観測できる範囲のすごい開発者も、ノートパソコン1台で開発するという人はけっこういる。使用マシンもそう高性能ではなかったり、年式の経ったもの[fn:1]が多いのは意外だった。

以前読んだ本で、偉大な作品を残した芸術家や作家の特徴となる習慣を探る、というのがあった。仕事をする場所(ソファやベッド、冷蔵庫の上で仕事する作家もいた)や、昼型/夜型、乱雑/整然について調査していた。結局人によってバラバラで、「成功要因」みたいなものはない、という結論だったことを覚えている。開発者についても、同じ結論がいえるように見えた。

逆に、二流三流ほど要因や方法にこだわりたがり、そっちが主な関心になるんじゃないかって、自分と重ねて感じている。PC周りを紹介しているブロガーやプログラマーはネットに多くいるので彼らを何人か観察してみる。自分の仕事環境に自信を持っていて、紹介しているように見える。それぞれのこだわりのグッズや家具があって、画像を多く含んだレビューを入れている。

- HHKB
- 複数のディスプレイ
- 高級チェア
- Mac
- ディスプレイライト

は、驚くほど出てくる。

掲載している記事の内容や種類から、彼らは自分と同じように職業人として大した特徴のない平凡な人々に見える。デスク周りへのこだわりはプログラマとしての能力と逆相関に見える。本当は好きじゃないから少しでも快適にすることでなんとかしようとしているんじゃないか。だから、もし机周りを買い換えて *生産性* を上げよう、とよく考えるなら注意したほうがいい。コンピュータやソフトウェアそのものに興味がないってことを示している可能性がある。

[fn:1] 動画の撮られた年代を考慮していなかった。撮られた当時では最新だった可能性がある。ただ動画内で相対的に違いがあるように見えた。
