#+title:      workspace
#+date:       [2022-10-27 Thu 23:48]
#+filetags:   :essay:
#+identifier: 20221027T234844

* 仕事場へのこだわりは能力と逆相関である可能性
:LOGBOOK:
CLOCK: [2022-10-26 Wed 01:37]--[2022-10-26 Wed 02:02] =>  0:25
CLOCK: [2022-10-26 Wed 01:05]--[2022-10-26 Wed 01:30] =>  0:25
CLOCK: [2022-10-25 Tue 22:50]--[2022-10-25 Tue 23:15] =>  0:25
:END:

成した仕事の大きさと、仕事場は無関係だ。

最近RedHatの開発者のPCまわりを紹介している動画を見た。多くの開発者は質素なものだった。乱雑な人、片付いている人は半々くらい。片付いているいっても普通の生活のレベルでいう「片付いている」で、モデルルームのようではない。1枚のディスプレイを使う開発者が半分で、残り半分は複数のディスプレイを使う。自分の観測できる範囲のすごい開発者も、ノートパソコン1台という人はけっこういる。使用マシンもそう高性能ではない、年式の経ったものが多い。

以前読んだ本で、偉大な作品を残した芸術家や作家の特徴となる習慣を探る、というのがあった。仕事をする場所(ソファやベッド、冷蔵庫の上で仕事する作家もいた)や、昼型/夜型、乱雑/整然について調査していた。結局人によってバラバラで、「成功要因」みたいなものはない、ということだった。開発者についても、同じ結論がいえるように見えた。

逆に、二流三流ほど要因や方法にこだわりたがるんじゃないかって、自分と重ねて感じている。PC周りを紹介しているブロガーやプログラマーはネットに多くいるので彼らを何人か観察してみる。自分の仕事環境に自信を持っていて、紹介しているように見える。それぞれのこだわりのグッズや家具があって、画像を多く含んだレビューを入れている。彼らは自分と同じように、職業人として大した特徴のない平凡な人々に見える。

- HHKB
- 複数のディスプレイ
- 高級チェア
- Mac
- ディスプレイライト

は、驚くほど出てくる。[fn:1]

デスク周りへのこだわりはプログラマとしての能力と逆相関に見える。本当は好きじゃないから少しでも快適にすることでなんとかしようとしているんじゃないか。だから、もし机周りを買い換えて *生産性* を上げよう、とよく考えるなら注意したほうがいい。コンピュータやソフトウェアそのものに興味がないってことを示している可能性がある。

[fn:1] 単にみんながいいっていう理由で選ばれているように見える。
