#+title:      理解を試す基準
#+date:       [2022-12-13 Tue 00:51]
#+filetags:   :essay:
#+identifier: 20221213T005128

より高度なことを理解するには、理解を試す基準が重要に見える。

今の職場には、アカデミックな背景をもった驚くほど知的な人たちが多くいる。そのうちの何人かは、1人の際立って優れた人のリファラルによるものだ。彼らの接点は、技術系のチャットグループだったという。そのサーバには技術オタクたちが集まっていた。同じ職場で働く彼らを見るに、数学やコンピュータに関する学問的素養があって、非常に高度な集団だったようだ。実装や理論レベルで詳しく、Web系に多くいる動けばいい人々(オレもそうだ...)とは一線を画する。

彼らは、年齢に少し差があるのだが、みんなタメ口だ。フランクに議論を交わす。単純に高度なオタク友達という感じ。現実にあるような年齢や立場による上下関係、敬語さえない。高尚なことはなく、楽しみたいという感じ。よく見るコミュニティ活動という感じではない。普通の友達みたいな感じ。ただ、高い知能や強い興味という共通点がある違い。

彼らを見ていて、数学とか技術とか抽象的なテーマについて人と話せること、興味を持つことが、より深い知識をもたらしているように見えた。議論には時間制限があり、目の前の相手に理解させるというインセンティブがある。読み/書き出し速度の速さと正確さが要求される。そうやって、彼らはさらに磨きをかけていったように見える。

オレはそういったことをしてこなかった。プログラミング言語やテキストエディタは好きだが、黙って1人でいじってるだけで、交流しようとしてこなかった。自分さえわかればよかったし、人に共有する価値のあるものを発見したこともない。これは単に「好き」の範疇におさまっているように見える。もっと好きでたまらなかったら、人に教えたり教えてもらったりして、学ぼうとするだろう。すごい人々を見るに、オレは技術そのものというより、それでできるものに興味があるようだ。より優れたものを見るというよりは、今あるもので何かをつくることに関心があった。より熱意のある人々を見て、自覚した。

具体的な仕様や挙動について興味や疑問を持つことが、第一歩のようだ。そうでないと、オタクと会話はできない。質問だって出てこない。
