#+title:      2022年のまとめ
#+date:       [2023-01-01 Sun 17:57]
#+filetags:   :essay:
#+identifier: 20230101T175751

2022年は社会人2年目だった。8月の退職、10月の引っ越し、11月の入社と、後半の印象が強い。

* 技術的
:LOGBOOK:
CLOCK: [2023-01-04 Wed 17:02]--[2023-01-04 Wed 17:27] =>  0:25
:END:
1年で新しく学んだこと。

- [[id:1658782a-d331-464b-9fd7-1f8233b8b7f8][Docker]] を使えるようになった。完全にLinuxで開発するようになった。開発環境の整備から、コンテナの本番運用など
- [[id:2d35ac9e-554a-4142-bba7-3c614cbfe4c4][GitHub Actions]] に詳しくなった。自作アクションを作ってみたりもした
- [[id:ddc21510-6693-4c1e-9070-db0dd2a8160b][Rust]] 言語を学んでみた。ゲームを途中まで作ってみた
- [[id:7cacbaa3-3995-41cf-8b72-58d6e07468b1][Go]] 言語を学んで業務で使うのと、いくつかのツール作成。そこまで熟達してない
- [[id:1ad8c3d5-97ba-4905-be11-e6f2626127ad][Emacs]]の設定ファイルの文芸化

* イベント
** 退職
約2年働いた会社を退職した。
** ECS移行(仕事)
仕事の、前半のハイライト。
** 姉の婚約
身近な人ではじめて結婚するケースだった。今まで家族は最初から存在しているものだったが、どこかの時点で作られるものという認識に改めた。
** 徒歩で山手線一周
7時ぐらいに品川駅を出発して、夜9時ごろにゴールする過酷な一周をした。街の距離感、それぞれの街に対する印象が生まれた。多くの街に興味が湧いた。
** 高千穂
夏に帰省したとき行った。自然も驚くほど素晴らしかったが、町並みもまた好きな感じだった。
** 引っ越し
馬喰町から高円寺に引っ越した。高円寺にしたのはみうらじゅんや村上龍が住んだというのを知っていたため。そしてなんだかイケてそうな雰囲気だった。

馬喰町まわりは交通の便は最高なのだが、オフィス街で飲食店は少なく、スーパーもないのが不便だった。人通りが比較的少なく、駅も空いているのはよかった。
** 転職
ギークが集まっている会社に転職した。とても刺激を受ける。
* 変わったこと
以前よりも外に出るようになった。上京してから、全く外に出てなかった分が、今来た感じ。

** 飲食店に行くように
出社が復活したとき、ランチをいろいろ連れて行ってもらって楽しかった。それで色々遊びへいくようになった。
** よくぶらつくように
原宿の町並みや雰囲気が面白かったので、ぶらぶらするのが好きになった。金も余裕ができたので、映画を見たり外食することのハードルが低くなった。
