name: called

on:
  workflow_call:
    inputs:
      text:
        type: string
        required: true
    secrets:
      DUMMY:
        required: true

jobs:
  called:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: output called
        run: |
          echo ${{ inputs.text }}

      - name: output secret
        run: |
          echo ${{ secrets.DUMMY }}
          pwd
