name: caller

on:
  workflow_dispatch:
    inputs:
      text:
        type: choice
        description: 'caller text'
        required: true
        options:
          - production
          - sandbox
          - staging

jobs:
  called:
    runs-on: ubuntu-latest

    steps:
      - uses: kijimaD/roam/.github/workflows/called.yml@main
        with:
          text: ${{ github.event.inputs.text }}
