name: called

on:
  workflow_call:
    inputs:
      text:
        type: string
        required: true

jobs:
  called:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: output called
        run: |
          echo ${{ inputs.text }}
