name: caller

on:
  workflow_dispatch:
    inputs:
      text:
        type: choice
        description: 'caller text'
        required: true
        options:
          - production
          - sandbox
          - staging

jobs:
  called:
    uses: ./.github/workflows/called.yml
    with:
      text: ${{ github.event.inputs.text }}
    secrets:
      DUMMY: ${{ secrets.DUMMY }}
