name: caller

on:
  workflow_dispatch:
    inputs:
      text:
        type: choice
        description: 'caller text'
        required: true
        options:
          - production
          - sandbox
          - staging

jobs:
  called:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/called@main
        with:
          text: ${{ github.event.inputs.text }}
