name: Docker build

on:
  push:
    branches:
      - main
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

        # for using git hash to tag
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/yoshinorin/docker-cahsper

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.WRITE_PACKAGE }}

        # build + push
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          # Dokcerfileのパス
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
