name: Textlint

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
      with:
        node-version: '18.x'

    - name: linting org files
      run: make textlint
