name: Textlint

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # setup Node.js
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
      with:
        node-version: '14.x'

    # Run scripts
    - name: Install dependencies
      run: npm install
    - name: linting org files
      run: make textlint
