name: Merge any branch
on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: 'target branch'
        required: true
        options:
          - sandbox
          - staging

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Merge current branch -> target
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: ${{ github.event.inputs.target }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "Merge branch by GitHub Actions ${{ github.ref }}"
