name: Build PDF

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Build
        run: |
          ./scripts/pandoc.sh

      - name: Check
        run: |
          ls -al ./pdf
          ls | wc -l
          ls ./pdf | wc -l
