name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      git-tag: ${{ steps.git-tag.outputs.git-tag }}

    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.WRITE_PACKAGE }}

      - name: Get git tag(short)
        id: git-tag
        run: |
          GIT_TAG=$(git rev-parse --short HEAD)
          echo "::set-output name=git-tag::$GIT_TAG"

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build release image
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          target: release
          push: true
          tags: ghcr.io/kijimad/roam_release:${{ steps.git-tag.outputs.git-tag }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: copy
        run: |
          docker run --detach --name release ghcr.io/kijimad/roam_release:${{ needs.build.outputs.git-tag }} && \
          docker cp release:/roam/public ./public && \
          sudo chown -R $USER:$USER ./public

      - name: check
        run: ls -al ./public

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: public
