name: Publish

on:
  workflow_dispatch:
  push:

jobs:
  org-roam-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Apps token
        id: generate
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ steps.generate.outputs.token }}
          repository: kijimaD/roam-ui
          event-type: commit

  tag:
    runs-on: ubuntu-latest
    outputs:
      git-tag: ${{ steps.git-tag.outputs.git-tag }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Get git tag(short)
        id: git-tag
        run: |
          GIT_TAG=$(git rev-parse --short HEAD)
          echo "::set-output name=git-tag::$GIT_TAG"

  release_image:
    if: github.ref == 'refs/heads/main'
    needs: tag
    uses: ./.github/workflows/build.yml
    with:
      image: ghcr.io/kijimad/roam_release:${{ needs.tag.outputs.git-tag }},ghcr.io/kijimad/roam_release:latest
      target: release
    secrets:
      WRITE_PACKAGE: ${{ secrets.WRITE_PACKAGE }}

  staging_image:
    needs: tag
    uses: ./.github/workflows/build.yml
    with:
      image: ghcr.io/kijimad/roam_staging:${{ needs.tag.outputs.git-tag }},ghcr.io/kijimad/roam_staging:latest
      target: staging
    secrets:
      WRITE_PACKAGE: ${{ secrets.WRITE_PACKAGE }}

  build_image:
    needs: tag
    uses: ./.github/workflows/build.yml
    with:
      image: ghcr.io/kijimad/roam_build:${{ needs.tag.outputs.git-tag }},ghcr.io/kijimad/roam_build:latest
      target: build
    secrets:
      WRITE_PACKAGE: ${{ secrets.WRITE_PACKAGE }}

  publish:
    needs:
      - tag
      - release_image
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4 # publish actions require git

      - name: copy
        run: |
          docker run --detach --name release ghcr.io/kijimad/roam_release:${{ needs.tag.outputs.git-tag }} sleep infinity && \
          docker cp release:/roam/public . && \
          sudo chown -R $USER:$USER ./public

      - name: check
        run: |
          ls -al ./public
          ls -al ./public/pdfs

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.7.1
        with:
          branch: gh-pages
          folder: public
