name: Publish to GitHub Pages

on:
  push:
    branches:
      - main
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Build the graph
        uses: kamiazya/setup-graphviz@v1

      - name: Install Emacs
        uses: purcell/setup-emacs@master
        with:
          version: 27.2

      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 2.7

      - name: Install Ruby dependency
        run: bundle install

      - name: Install gnuplot
        run: sudo apt-get install gnuplot

      - name: Build git file graph
        run: make file-graph

      - name: Build git line graph
        run: make line-graph

      - name: Create count table
        run: make gen-file-table

      - name: Update index.org
        run: make update-index

      - name: Build the pages
        run: make build

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Build node graph
        run: make node-graph

      - name: check
        run: ls -al ./public

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: public
