name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      git-tag: ${{ steps.git-tag.outputs.git-tag }}
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Get git tag(short)
        id: git-tag
        run: |
          GIT_TAG=$(git rev-parse --short HEAD)
          echo "::set-output name=git-tag::$GIT_TAG"

  build:
    needs: tag
    uses: ./.github/workflows/build.yml
    with:
      image: ghcr.io/kijimad/roam_release:${{ needs.tag.outputs.git-tag }}
      target: release
    secrets:
      WRITE_PACKAGE: ${{ secrets.WRITE_PACKAGE }}

  publish:
    needs:
      - tag
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3 # publish actions require git

      - name: copy
        run: |
          docker run --detach --name release ghcr.io/kijimad/roam_release:${{ needs.tag.outputs.git-tag }} && \
          docker cp release:/roam/public ./public && \
          sudo chown -R $USER:$USER ./public

      - name: check
        run: ls -al ./public

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: public
