name: Publish

on:
  push:
    branches:
      - main
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1 # MEMO: Use v1 for .git analysis

      - name: build
        run: make deploy

      - name: user
        run: sudo chown -R $USER:$USER .

      - name: check
        run: ls -al ./public

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: public
