name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 22
      - name: Install dependencies
        run: yarn global add semantic-release@24.1.2
      - name: Releaser
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: semantic-release
