name: Staging

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: deploy staging
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        run: |
          heroku container:login
          docker tag ghcr.io/kijimad/roam_release:latest registry.heroku.com/roam-staging/web
          docker push registry.heroku.com/roam-staging/web
          heroku container:release web --app=roam-staging
