name: StaleFile

on:
  schedule:
    - cron: "0 0 1 * *" # 月初
  workflow_dispatch:
    inputs:
      label:
        required: false
      file_extension:
        required: false
      include:
        required: false
      exclude:
        required: false
      days_until_stale:
        required: false
      issue_comment:
        required: false

jobs:
  stale_file:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    steps:
      - uses: kijimaD/StaleFile@v0.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          file_extension: '*.org'
