name: My Textlint

on:
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      git-tag: ${{ steps.git-tag.outputs.git-tag }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Get git tag(short)
        id: git-tag
        run: |
          GIT_TAG=$(git rev-parse --short HEAD)
          echo "::set-output name=git-tag::$GIT_TAG"

  release_image:
    needs: tag
    uses: ./.github/workflows/build.yml
    with:
      image: ghcr.io/kijimad/roam_textlint:${{ needs.tag.outputs.git-tag }},ghcr.io/kijimad/roam_textlint:latest
      target: textlint
    secrets:
      WRITE_PACKAGE: ${{ secrets.WRITE_PACKAGE }}
